### ISSUE TITLE
Will this plug in fix the issue with scenes and power command?

### ISSUE THREAD

**Issue by Cloudore** [tavicu/homebridge-samsung-tizen#1]
Basically, in every other plug in, if the TV is already on and I set my "Movie Time Scene" (which of course turns the TV switch on), it would see that the TV was already on yet STILL send the command, turning the TV off.

Will this plug in address this issue?

Appreciate it!

**Comment by tavicu** [comment]
Hi,

This plugin is under development! But yes, it will fix it :)

**Comment by tavicu** [comment]
sudo npm install -g --unsafe-perm git://github.com/tavicu/homebridge-samsung-tv.git

Then in config.json, replace IP and MAC address.

    "accessories": [
        {
            "accessory": "SamsungTV",
            "name": "Living Room TV",
            "ip": "192.168.1.1", // TV IP
            "mac": "00:00:00:00:00:00" // TV MAC
        }
    ]

**Comment by Cloudore** [comment]
>     Right now i have implemented only the option to power on and off the tv.

Thats all I need, Thank you!

**Comment by tavicu** [comment]
Hi @Cloudore, I have released the final version of the plugin.

To use it now you make the following steps:
1. `sudo npm uninstall -g homebridge-samsung-tv`
2. `sudo npm install -g --unsafe-perm homebridge-samsung-tizen`
3. Update your config file. You need to remove the TV from accessories and add it to platforms like this:
```
"platforms": [
    {
        "platform": "SamsungTizen",
        "devices": [
            {
                "name": "Bedroom TV",
                "ip": "10.20.30.40",
                "mac": "A0:B1:C2:D3:E4:F5"
            }
        ]
    }
]
```
4. Restart Homebridge and enjoy :)

Also read the description of the package! I've added some new features that you will probably like.
I'm using a custom switch to set the TV on sleep and volume on 3 when i'm going to bed.
`{"name": "Sleep", "sleep": 60, "command": ["KEY_VOLDOWN*25", "KEY_VOLUP*3"]}`

**Comment by Cloudore** [comment]
Thank you @tavicu!

Is there a way I could limit functionality to an "on-off" switch? that is all I need as to not clog up my home app

**Comment by tavicu** [comment]
@Cloudore Just add the code without switches :), like the code i've posted in the previous comment.

**Comment by Cloudore** [comment]
Appreciate it!
