### ISSUE TITLE
The new Apple TV App[BUG] 

### ISSUE THREAD

**Issue by JordanPatterson** [tavicu/homebridge-samsung-tizen#100]
Ok I am back again. Now that I have the code for the new apple tv app I configured it as an input just like Netflix, YouTube, and Prime. The Apple TV app does not open when selected.

**Comment by tavicu** [comment]
From what i understand you can only have the Apple TV app if your tv is compatible with HomeKit! So why using this plugin at all? :) 

And unfortunately i can't help you since i have a 2017 TV and can't install the Apple TV app.

**Comment by JordanPatterson** [comment]
Right now Samsung has an exclusive on the Apple TV app with the other manufacturers coming later in the year. Samsung is not doing HomeKit on their TVs only airplay and the Apple TV app. Is there a log or any info I could provide to help understand why it will not launch?

**Comment by tavicu** [comment]
It will help me if you start the homebridge in debug mode and with tizen-apps (`DEBUG=* homebridge -D tizen-apps`) and tell me what does the server responds when the apps appear. It should be an object `{...}`

Then, still on the same instance with debug mode try to switch the input to the app and check if you have anything in the console related to the plugin.

**Comment by discostur** [comment]
@tavicu having the same problem - started homebridge like you said, here is the output if i want to start the appleTV app:


```
  Accessory [Fernseher] Processing characteristic set: [{"aid":1,"iid":11,"value":3}] +1ms
  Accessory [Fernseher] Setting Characteristic "Active Identifier" to value 3 +0ms
[2019-7-7 9:40:47 PM] [Fernseher] [DEBUG] { method: 'ms.channel.emit',
  params:
   { to: 'host',
     event: 'ed.apps.launch',
     data: { action_type: 'NATIVE_LAUNCH', appId: '3201807016597' } } }
  EventedHTTPServer [::ffff:192.168.0.189] Muting event '1.11' notification for this connection since it originated here. +5ms
  EventedHTTPServer [::ffff:192.168.0.189] HTTP Response is finished +0ms
[2019-7-7 9:40:47 PM] [Fernseher] [DEBUG] { data: 200, event: 'ed.apps.launch', from: 'host' }
  thing:miio:259647378 -> (5) {"method":"get_status","params":[],"id":10} +30s
  miio:packet -> <Buffer 21 31 00 50 00 00 00 00 0f 79 e7 92 5d 22 4a c1 e9 b3 41 f8 9f 0a 89 75 2e 3f 21 25 7a e8 62 f3> +30s
  thing:miio:259647378 -> (5) {"method":"get_consumable","params":[],"id":11} +0ms
  miio:packet -> <Buffer 21 31 00 50 00 00 00 00 0f 79 e7 92 5d 22 4a c1 b9 b7 66 db 30 2f 44 75 e0 b2 df 99 5a e0 cd c4> +1ms
  miio:packet <- <Buffer 21 31 01 10 00 00 00 00 0f 79 e7 92 5d 22 4a c2 ed 5e 9a d2 81 cc ca ea 0e e6 88 2a 1f dc 29 4b> +10ms
  miio:packet <- <Buffer 21 31 01 10 00 00 00 00 0f 79 e7 92 5d 22 4a c2 ed 5e 9a d2 81 cc ca ea 0e e6 88 2a 1f dc 29 4b> +0ms
  thing:miio:259647378 <- Message: `{"result":[{"msg_ver":2,"msg_seq":35,"state":8,"battery":100,"clean_time":0,"clean_area":0,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":1,"fan_power":60,"dnd_enabled":0}],"id":10}` +11ms
  miio:packet <- <Buffer 21 31 00 b0 00 00 00 00 0f 79 e7 92 5d 22 4a c2 b0 3f 92 99 04 00 5a 2f b2 c2 ae 25 6f dd c2 17> +1ms
  miio:packet <- <Buffer 21 31 00 b0 00 00 00 00 0f 79 e7 92 5d 22 4a c2 b0 3f 92 99 04 00 5a 2f b2 c2 ae 25 6f dd c2 17> +0ms
  thing:miio:259647378 <- Message: `{"result":[{"main_brush_work_time":52316,"side_brush_work_time":52316,"filter_work_time":52316,"sensor_dirty_time":52311}],"id":11}` +1ms
```

**Comment by apexad** [comment]
Having the same problem, but not just with the Apple TV app.
Both of these show up when `homebridge tizen-apps' is run:
3201710015067 - Universal Guide
3201807016597 - Apple TV

Neither work as inputs.  Maybe because they are 'built in apps'?  Perhaps they have an id because they can be updated but really internally there is some different id like the browser?

**Comment by apexad** [comment]
@tavicu Any idea? Perhaps you can try to duplicate it with the Universal Guide app.
