### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by runeix** [tavicu/homebridge-samsung-tizen#104]
Is the maximum number of inputs a choice of this plugin or a base characteristic of home kit?
I can only get 6 to show up out of the 9 options that i'd like to display.

I've tried to add 3 x HDMI, Live TV then Netflix, Amazon and 3 local Australian streaming services (ABC, SBS and Stan) via their app ID.

They are configured properly, because they bump each other off the list if more than 6 and all show up if only 6 are listed at a time. 

Alternately would it be possible to add the same TV twice or have separate switches for apps to get around this limitation?

**Comment by tavicu** [comment]
I don't know! I only use 4 :) 

And just because you can, i don't recommend adding a lot of inputs because for every input as `app` type it's make a request to check the state!
