### ISSUE TITLE
Polling

### ISSUE THREAD

**Issue by backfisch88** [tavicu/homebridge-samsung-tizen#106]
Hi!

First. Great Plugin! Love it!

Is there any way to set the polling interval smaller?
When i Switch the tv off with the normal remote there is a delay like 30 Seconds :/

Thank you!

**Comment by tavicu** [comment]
The default interval for checking the TV status in 10 seconds.
Then there is a sleep state for the TV. When you turn it off the tv still responds and acts like it's on for 15 seconds.

So with the right timing you get a delay of ~25 seconds when turning off from remote.

The only thing you can do it's to lower the interval of checking the TV. The minimum in 500ms. But you will still have the 15 seconds delay.

Unfortunately this can't be fixed!

**Comment by backfisch88** [comment]
Thank you for answearing!

Where can i set the checking Status?

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/issues/82#issuecomment-480174668

**Comment by backfisch88** [comment]
Thank! It works! Great Plugin
