### ISSUE TITLE
[BUG] youtube id

### ISSUE THREAD

**Issue by curla92** [tavicu/homebridge-samsung-tizen#107]
Youtube id doen't work. i tried to search new id but homebridge tizen-apps doen't work. i also tried to set tv to developer mode. Can you help me? thanks.

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen#other

**Comment by curla92** [comment]
> https://github.com/tavicu/homebridge-samsung-tizen#other

i tried but doesn't work.

**Comment by tavicu** [comment]
Without debug i can't help you. Don't know how you installed the homebridge but you need to run it in debug mode so we can see why it's "not working".

**Comment by curla92** [comment]
i have installed homebridge on raspberry with ios app. i run in debug mode but there is not any error.
