### ISSUE TITLE
v4.0.2 kills homebridge-alexa

### ISSUE THREAD

**Issue by adamstamper** [tavicu/homebridge-samsung-tizen#109]
The latest version of homebridge-samsung-tizen (4.0.2) - kills the `homebridge-alexa` plugin 0.4.17 with the error `Cannot read property 'Manufacturer' of undefined` which then crashes the whole of homebridge.

**Comment by tavicu** [comment]
More informations please. Post all the error with paths and everything

**Comment by adamstamper** [comment]
Sure thing, see below - this only occurs when I have a TV in my configuration:
```
TypeError: Cannot read property 'Manufacturer' of undefined
    at new Service (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Service.js:40:89)
    at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Accessory.js:34:23)
    at Array.forEach (<anonymous>)
    at new Accessory (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Accessory.js:26:20)
    at Homebridge.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Homebridge.js:24:21)
    at Array.forEach (<anonymous>)
    at new Homebridge (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Homebridge.js:23:35)
    at Homebridges.<anonymous> (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Homebridges.js:17:22)
    at Array.forEach (<anonymous>)
    at new Homebridges (/usr/local/lib/node_modules/homebridge-alexa/lib/parse/Homebridges.js:16:11)

```

**Comment by tavicu** [comment]
That error has nothing to do with my plugion. All the files are from homebridge-alexa.

Try removing my plugin and see what happens!

**Comment by adamstamper** [comment]
Yep, that fixes it. As said - it's only when I include a `homebridge-samsung-tizen` TV in my config that the crash happens.

**Comment by tavicu** [comment]
With the latest version we are using external accessories. Maybe homebridge-alexa was not updated to support this!

**Comment by tavicu** [comment]
I don't have an alexa but i'm trying to install the plugin locally so i can reproduce :) 

Can you show me your config please?

Do i have to link homebridge-alexa to my plugin somehow?

**Comment by tavicu** [comment]
Had to open in insecure mode :D

**Comment by adamstamper** [comment]
Nope, once installed `homebridge-alexa` is just added as a platform, like `homebridge-samsung-tizen` - here's the relevant part of my config:

```
    "platforms": [
    {
        "platform": "Alexa",
        "name": "Alexa",
        "username": "za0",
        "pin": "039-45-150",
        "password": "wugpom-tojkuj-1ceDhu",
        "refresh": 15
     },
     {
        "platform": "SamsungTizen",
        "inputs": [
            {"name": "BBC iPlayer", "type": "app", "value": "3201601007670"},
            {"name": "Netflix", "type": "app", "value": "11101200001"}
        ],
        "devices": [{
            "name": "TV",
            "ip": "192.168.0.99",
            "mac": "E4:7D:BD:7E:0A:08",
            "switches": [
                {"name": "Mute", "mute": true}
            ]
        }]
    }
   ]
```

**Comment by adamstamper** [comment]
Looks like it has also been flagged to the `homebridge-alexa` project: https://github.com/NorthernMan54/homebridge-alexa/issues/223

**Comment by tavicu** [comment]
I have seen. Let's continue the discussion over there.

**Comment by NorthernMan54** [comment]
@tavicu Agreed, close this

And if I see a problem with your plugin I will raise it as a new issue so we can discuss
