### ISSUE TITLE
No input available

### ISSUE THREAD

**Issue by maisun** [tavicu/homebridge-samsung-tizen#110]
Hi,
Thank you for the great work!
I installed the plugin and it works great except that I do not see any input source for selection. Am I doing something wrong or it’s the limitation of Tizen API? Thank you in advance!

**Comment by tavicu** [comment]
Hei! Sometimes it needs to close and reopen the Home app.

Does the inputs show when you open the accessory settings?

![IMG_0291](https://user-images.githubusercontent.com/172068/58377842-3bfe8700-7f92-11e9-8e0b-29c9a15be3fb.jpeg)

**Comment by mafyata** [comment]
Did you enter inputs that you want in config file ?

**Comment by maisun** [comment]
Hi,
Sorry I missed that part - I thought inputs can be detected automatically. Now I have added the following section in config file for inputs:
 "inputs": [
                        {
                            "name": "HDMI",
                            "type": "command",
                            "value": [
                                "KEY_SOURCE",
                                "KEY_ENTER"
                            ]
                        },
                        {
                            "name": "YouTube",
                            "type": "app",
                            "value": "111299001912"
                        },
                        {
                            "name": "Netflix",
                            "type": "app",
                            "value": "11101200001"
                        }
                    ]
However for some reason they are created as 3 independent switches and the TV still doesn't have any input. Any suggestion?

**Comment by tavicu** [comment]
Restart the home app

**Comment by maisun** [comment]
Hi Tavicu,

Thank you! Restart didn’t seem to help so I remove the accessory and try to add it again. However after removing the TV I can’t seem to add it back, HomeKit does’t detect it even though I can see the bonjour service. Remember I had similar problem before with camera, I had to change the Id and listen port of HB, is there a way to change that for external accessory?
Thanks

**Comment by tavicu** [comment]
Interesting! It should appear!

In the last instance you can remove ‘persist’ folder from Homebridge! But this means you will also have to add all accessories and bridge again!

I can’t look right now. But if you will wait i will come back with an answer asap!

**Comment by mafyata** [comment]
I try this and it is working

 {
                            "name": "VivaCom",
                            "type": "command",
                            "value": "KEY_HDMI"
                        }

**Comment by maisun** [comment]
> Interesting! It should appear!
> 
> In the last instance you can remove ‘persist’ folder from Homebridge! But this means you will also have to add all accessories and bridge again!
> 
> I can’t look right now. But if you will wait i will come back with an answer asap!
I tried to remove the file generated by he plugin in persist folder, also anything related to the plugin in accessories folder without help.
I think it is a common issue with HB and HK, somehow HK doesn't allow to add an bridge that has been deleted previously.

**Comment by maisun** [comment]
A complete reinstall of HB solves the issue, all good now! Thanks all for the help!
BTW, KEY_HDMI doesn’t work for me.

**Comment by tavicu** [comment]
I checked right now and even if i remove the accessory from Home app i am able to read it without a problem!
