### ISSUE TITLE
which command to map context menu in HDMI CEC device

### ISSUE THREAD

**Issue by maisun** [tavicu/homebridge-samsung-tizen#112]
Hi,
Check the list of available commands (https://github.com/tavicu/homebridge-samsung-tizen/wiki/Commands) and tried a few but couldn't find one that can trigger menu action on my TV box (controlled via HDMI CEC and TV remote). There is no button on the TV remote that can trigger the action though, any suggestion?
Thank you in advance!

**Comment by tavicu** [comment]
Samsung api accepts only keys that are found on a physical remote.

**Comment by maisun** [comment]
Ah, ok thanks for your reply!
