### ISSUE TITLE
TV unstable

### ISSUE THREAD

**Issue by monsterciattolo** [tavicu/homebridge-samsung-tizen#116]
Hi, I have a Samsung Q8F 55’ with firmware revision 1270 (the last available)
Since i’ve installed the plugin on homebridge, TV becomes slow the unstable. I have to reset to factory default to fix it.
Do you know if plugin do something on the tv like saturated the logs,buffer....? 
Thanks

**Comment by tavicu** [comment]
Hi! The only overload for tv is if you have a lot of custom switches with [apps](https://github.com/tavicu/homebridge-samsung-tizen/wiki/Switches#application)! Other than that, no!
