### ISSUE TITLE
Unable to add in HomeKit

### ISSUE THREAD

**Issue by mactwin** [tavicu/homebridge-samsung-tizen#117]
Hi, I describe the problem:
I installed the plug-in the first time and everything went well, I opened homekit and added the TV (is a Samsung Q9F), it turned on and off.
The remote control (interface with arrows, info ... etc) only in part, and I couldn't find a way to change channels.
I then deleted the accessory from homekit, and unplugged from homebridge.
Then I found the instructions on how to insert the commands in the configuration file, so I proceeded to reinstall everything and prepare the json file.
Homebrige has left and the television has asked me again the combination.
The problem is that I can no longer insert the object in homekit, it does not appear by default and does not even appear in the list for manual entry.
I tried to change the name in the json file, nothing, I can't make it appear.

**Comment by tavicu** [comment]
Hei! I have pushed a new version where you can change the uuid. I don't know why sometimes after you remove the accessory you can't add it again. I have tested on my home and i can read it :)

Anyway, now you have the option to change the uuid of device.
```
{
    "name": "Bedroom TV",
    "ip": "10.20.30.40",
    "mac": "A0:B1:C2:D3:E4:F5",
    "uuid": "A1"
}
```

**Comment by mactwin** [comment]
Just added the row
    "uuid": "A1"

then I try after a Homebridge restart, nothing.

I tried to change with 
    "uuid": "A3"
....restart, again tried with manual add....nothing :(

**Comment by tavicu** [comment]
Did you update the plugin to v4.0.4?

**Comment by mactwin** [comment]
I reinstalled the plug in today, I don't know which version it is but I imagined the last one

**Comment by mafyata** [comment]
npm list -g —depth 0
This will show you the version of the plugin

**Comment by tavicu** [comment]
> I reinstalled the plug in today, I don't know which version it is but I imagined the last one

The new version i pushed 20 minutes ago when i left the comment! That's why i asked you to update to the latest version! It's a fix i pushed for your problem

**Comment by mactwin** [comment]
Ok great!! Just reinstalled and now it works!! great!
just a question, if I add some command in json I have to add manually or the new switch appear in default?

**Comment by mactwin** [comment]
Ok seen, just restart Homebridge and mod appears.
Great Works! Thanks a lot
