### ISSUE TITLE
[More of a feature] Can you add a Debugging option

### ISSUE THREAD

**Issue by James712346** [tavicu/homebridge-samsung-tizen#120]
Can you add a debugging option which prints out everything that the plugin is doing. for example printing out the Background refreshes, input changes, changes in status and commands.
:)

**Comment by tavicu** [comment]
Hi @James712346 
There is already debug logs for important things that will help me understand when someone have problems!

I will check and see if something can be improved :)

**Comment by tavicu** [comment]
I have added some new debugs and now you can see every response from TV
