### ISSUE TITLE
Support for H Series (none Tizen)

### ISSUE THREAD

**Issue by Spoocs** [tavicu/homebridge-samsung-tizen#121]
Hello, do you think it might be possible to add pairing for H series as it’s implemented in homebridge-homesung module. The homesung plugin has issues with power on due to missing WOL. Additionally there are issues with multiple devices due to uuid generation. This is why I would appreciate to add pairing support for H series to your plugin.

**Comment by tavicu** [comment]
Hi,

I'm sorry but i am not planning to extend the plugin to support older TV's.
