### ISSUE TITLE
TV turning on randomly

### ISSUE THREAD

**Issue by kopa11** [tavicu/homebridge-samsung-tizen#122]
Hi, I experience an issue with my tv that is randomly turning on during the day since I installed and configured your plugin.

I tried to turn on debug mode, you can see the logs from time that it happend last time - today at ca. 04:48.

Tue, 16 Jul 2019 04:44:48 GMT EventedHTTPServer [::ffff:192.168.11.32] Sending HTTP event 'keepalive' with data: {"characteristics":[]}
Tue, 16 Jul 2019 04:44:48 GMT EventedHTTPServer [::ffff:192.168.11.218] Sending HTTP event 'keepalive' with data: {"characteristics":[]}
Tue, 16 Jul 2019 04:48:03 GMT EventedHTTPServer [::ffff:192.168.11.31] Sending HTTP event '1.10' with data: {"characteristics":[{"aid":1,"iid":10,"value":1}]}
Tue, 16 Jul 2019 04:48:03 GMT EventedHTTPServer [::ffff:192.168.11.32] Sending HTTP event '1.10' with data: {"characteristics":[{"aid":1,"iid":10,"value":1}]}
Tue, 16 Jul 2019 04:49:51 GMT EventedHTTPServer [::ffff:192.168.11.231] New connection from client
Tue, 16 Jul 2019 04:49:51 GMT EventedHTTPServer [::ffff:192.168.11.231] HTTP server listening on port 38714
Tue, 16 Jul 2019 04:49:51 GMT EventedHTTPServer [::ffff:192.168.11.231] HTTP request: /pair-verify
Tue, 16 Jul 2019 04:49:51 GMT HAPServer [FB:F0:00:9D:F3:E2] HAP Request: POST /pair-verify
Tue, 16 Jul 2019 04:49:51 GMT HAPServer [FB:F0:00:9D:F3:E2] Pair verify step 1/2
Tue, 16 Jul 2019 04:49:51 GMT EventedHTTPServer [::ffff:192.168.11.231] HTTP Response is finished
Tue, 16 Jul 2019 04:49:52 GMT EventedHTTPServer [::ffff:192.168.11.231] HTTP request: /pair-verify
Tue, 16 Jul 2019 04:49:52 GMT HAPServer [FB:F0:00:9D:F3:E2] HAP Request: POST /pair-verify
Tue, 16 Jul 2019 04:49:52 GMT HAPServer [FB:F0:00:9D:F3:E2] Pair verify step 2/2
Tue, 16 Jul 2019 04:49:52 GMT HAPServer [FB:F0:00:9D:F3:E2] Client 2309868B-E0B6-4B08-8036-9A52BF9A18EC verification complete
Tue, 16 Jul 2019 04:49:52 GMT EventedHTTPServer [::ffff:192.168.11.231] HTTP Response is finished
Tue, 16 Jul 2019 04:49:52 GMT EventedHTTPServer [::ffff:192.168.11.231] HTTP request: /accessories
Tue, 16 Jul 2019 04:49:52 GMT HAPServer [FB:F0:00:9D:F3:E2] HAP Request: GET /accessories
Tue, 16 Jul 2019 04:49:52 GMT EventedHTTPServer [::ffff:192.168.11.231] HTTP Response is finished
Tue, 16 Jul 2019 04:49:52 GMT EventedHTTPServer [::ffff:192.168.11.231] HTTP request: /characteristics
Tue, 16 Jul 2019 04:49:52 GMT HAPServer [FB:F0:00:9D:F3:E2] HAP Request: PUT /characteristics
Tue, 16 Jul 2019 04:49:52 GMT Accessory [TV] Processing characteristic set: [{"aid":1,"iid":12,"ev":true},{"aid":1,"iid":22,"ev":true},{"aid":1,"iid":30,"ev":true}]
Tue, 16 Jul 2019 04:49:52 GMT Accessory [TV] Registering Characteristic "Configured Name" for events
Tue, 16 Jul 2019 04:49:52 GMT Accessory [TV] Registering Characteristic "Configured Name" for events
Tue, 16 Jul 2019 04:49:52 GMT Accessory [TV] Registering Characteristic "Configured Name" for events
Tue, 16 Jul 2019 04:49:52 GMT EventedHTTPServer [::ffff:192.168.11.231] HTTP Response is finished

Thank you for your help.

**Comment by tavicu** [comment]
Hi.

It is possible that your homebridge server to restart and trying to pair with the TV?

But even like that ... if the TV is not on it will not try to pair or send any command.

**Comment by kopa11** [comment]
Finally found the reason, not caused by this plugin, I have to disable HDMI CEC on TV.
