### ISSUE TITLE
Is there a list of compatible tv’s?

### ISSUE THREAD

**Issue by zabaya** [tavicu/homebridge-samsung-tizen#124]
I want to buy a new tv soon, but don’t want to buy something i can’t connect.

**Comment by mafyata** [comment]
Mine is ue50mu6102

**Comment by tavicu** [comment]
Hi.

Can't tell you for sure since i'm not familiar with all the Samsung products :D 
But a Smart TV from 2017 and up should work.

Mine is 2017 model.
