### ISSUE TITLE
Refresh makes automation impossible

### ISSUE THREAD

**Issue by denzel1994** [tavicu/homebridge-samsung-tizen#126]
Hey,

I got the following setup:
Samsung 2018 Smart TV paired with the plugin. Controls work just finde.
LED-Lightstrip behind the TV also in HomeKit.

Now when I turn on the TV I want the LEDs to turn on as well and turn off when the TV turns off. Even if I turn on the TV just with the remote. Managed this by two simple automations in HomeKit.

However the status of the TV get's refreshed every 10 seconds and the switch in HomeKit turns on and off.... on and off and so on. The TV itself stays on the entire time, but the switch status in HomeKit changes all the time, which causes the LEDs to turn on and off all the time as well.

I tried different settings for `"refresh": `, but the only setting that works is setting main or main and switch to "false". But this results in the Homebridge not recognising if the TV is on or off if controlled by the TV's remote.

Oh and the TV is connected via Wifi not LAN. Might that be the problem?

**Comment by jeffwhalen** [comment]
Make sure your IP address is correct. I had the same problem with the home app resetting the tv status and it was because my IP address had changed.

**Comment by Echistas** [comment]
im having a similar issue -- where did you see the option to modify the refresh settings? I'm not seeing this anywhere in my config
