### ISSUE TITLE
Sending KEYS as a Switch does not work

### ISSUE THREAD

**Issue by Vants5150** [tavicu/homebridge-samsung-tizen#127]
Hi thanks for the great plugin.
I have one problem with Switches. 
 if I put {"name": "Menu", "type": "command", "value": "KEY_MENU"} in the Switches section I can see the switch but it does not work. If I put same command in the Inputs section it Works. 
No problems with “App” or mute command. Just I can’t remote buttons Keys. 

Any clue?
Thanks

**Comment by tavicu** [comment]
Hi,

Different format for switches.

https://github.com/tavicu/homebridge-samsung-tizen/wiki/Switches#command
