### ISSUE TITLE
Can’t add TV to HomeKit 

### ISSUE THREAD

**Issue by Olived-fr** [tavicu/homebridge-samsung-tizen#129]
Hi, I can’t manage to add the TV to the HomeKit app and I can’t find why.
The TV does show up on the add accessory page and I can enter the PIN but afterwards it just load indefinitely.
I am currently on iOS 13 beta, maybe it is related?

**Comment by kravtsovguy** [comment]
the same trouble (iOS 13)

**Comment by fighterzg6** [comment]
The Same Problem on iOS 13

**Comment by fighterzg6** [comment]
Is there a solution for this Problem?

**Comment by tavicu** [comment]
Hi.

Tried right now on the latest beta and it's working! I can add the TV without problems.

**Comment by fighterzg6** [comment]
Sorry it‘s works not! In the Homebridge config ui x it works. In the HomeKit App from Apple i can‘t add the tv! It is a ue55mu6199

**Comment by tavicu** [comment]
make sure you are on latest beta. And try adding uuid, https://github.com/tavicu/homebridge-samsung-tizen/issues/117#issuecomment-502435485

**Comment by fighterzg6** [comment]
Ok thanks the uuid A1 works
