### ISSUE TITLE
IOS remote control e.g. FireTV via HDMI-CEC

### ISSUE THREAD

**Issue by Hochiss** [tavicu/homebridge-samsung-tizen#131]
firstly thanks to this great plugin ! .... and @tavicu happy honeymoon there ~~ :-)

![image](https://user-images.githubusercontent.com/36304198/63208876-4b492880-c0da-11e9-867b-a22419980ca9.png)

currently the IOS remote can navigate if input is e.g. Youtube, but not for HDMI input.

For instance, I have FireTV plugged in AVR then output via HDMI to Samsung TV(due to better audio decoding). We know Samsung remote can physically navigate within FireTV's interface by means of the [HDMI-CEC](https://en.wikipedia.org/wiki/Consumer_Electronics_Control) protocol,  e.g. power-off TV also does power-off AVR(via HDMI), but HDMI-CEC has more, e.g. with arrows navigate, confirm and back etc. I don't know if it is possible or already in development, so I miss the setting in config.json, I read [this](https://github.com/tavicu/homebridge-samsung-tizen/issues/88) cannot find.

On the other side, beside the navigate screen shown above, how to bring up [this](https://cdn.macrumors.com/article-new/2019/02/tvremotenewinterface-800x780.jpg) screen
https://cdn.macrumors.com/article-new/2019/02/tvremotenewinterface-800x780.jpg

as TV is the center of entertainment devices , so this expansion would be very useful, right? 

thanks!

**Comment by mafyata** [comment]
I can navigate my stb given from my ip tv provider. You make something wrong. I can change input between hdmi , youtube , hbo go and can navigate my stb connected to hdmi, change volume , change channels and more.

**Comment by Hochiss** [comment]
@mafyata switching inputs for me no problem at Home/TV, volume can also adjust via IOS remote using iPhone side button(volume up/down), only FireTV not able to navigate. 
what could be wrong ... Could you share your setting? thanks!
Hereby my config.json section for Samsung (homebridge-samsung-tizen v4.0.5) :

`        {
            "platform": "SamsungTizen",
            "keys": {
                "INFORMATION": "KEY_ENTER",
                "REWIND": [
                    "KEY_ENTER",
                    "KEY_ENTER"
                ]
            },
            "inputs": [
                {
                    "name": "Netflix",
                    "type": "app",
                    "value": "11101200001"
                },
                {
                    "name": "Prime Video",
                    "type": "app",
                    "value": "3201512006785"
                },
                {
                    "name": "YouTube",
                    "type": "app",
                    "value": "111299001912"
                },
                {
                    "name": "HDMI",
                    "type": "command",
                    "value": [
                        "KEY_HDMI"
                    ]
                }
            ],
            "devices": [
                {
                    "name": "Samsung TV",
                    "ip": "xxx",
                    "mac": "xxx",
                    "switches": [
                        {
                            "name": "Mute",
                            "mute": true
                        },
                        {
                            "name": "Sleep in 60s",
                            "sleep": 60
                        },
                        {
                            "name": "Channel 13",
                            "channel": 13
                        },
                        {
                            "name": "Volume +",
                            "command": "KEY_VOLUP"
                        },
                        {
                            "name": "Volume -",
                            "command": [
                                "KEY_VOLDOWN"
                            ]
                        }
                    ]
                }
            ]
        },`

**Comment by mafyata** [comment]
{
            "platform": "SamsungTizen",
            "devices": [
                {
                    "name": "Samsung TV",
                    "ip": "10.0.1.102",
                    "mac": "28:39:5E:1D:12:D7",
                    "inputs": [
                        {
                            "name": "YouTube",
                            "type": "app",
                            "value": "111299001912"
                        },
                        {
                            "name": "HBO GO",
                            "type": "app",
                            "value": "3201706012478"
                        },
                        {
                            "name": "VivaCom",
                            "type": "command",
                            "value": "KEY_HDMI"
                        }
                    ]
                }
            ]
        }

**Comment by Hochiss** [comment]
@mafyata thanks!

For unknown reason, It works now for controlling FireTV without my change the config settings. Maybe because I recently update the Samsung TV Firmware (yet still some keys/buttons not as it  defined conventionally, e.g. I cannot navigate to change subtitle with e.g. option button)

But by now it is already quite nice.
so case closed.

**Comment by mafyata** [comment]
You control it by hdmi-cec, like from tv remote.
