### ISSUE TITLE
iOS 13 grouped accessories issue

### ISSUE THREAD

**Issue by apexad** [tavicu/homebridge-samsung-tizen#133]
iOS 13 (currently in beta_ now groups accessories in the Apple Home app.  Seems like it is probably if it is the same Serial Number.
This breaks the 'Main TV' tile if you add any switches. It will include these switches and then not correctly display the current App.

The solution here would be to make it so that switches no longer use the same serial number, but rather a unique uuid or perhaps <ip address>_<switch index/number>.

**Comment by tavicu** [comment]
Hi! I've seen the problem since the first beta but i was hoping it's just a bug that needs to be fixed in Home App.

Apparently not. I will take a look and see how i can separate the switches from TV!

**Comment by tavicu** [comment]
I have made a new branch and i will test it until release.

If anyone want's to play with it, edit `package.json` to this:
`"homebridge-samsung-tizen": "git://github.com/tavicu/homebridge-samsung-tizen.git#prepare-new-release"`

**Comment by flobernd** [comment]
@tavicu 
Hi there, iOS13 has been released now. Are you going to merge the updated branch anytime soon? 😸

**Comment by tavicu** [comment]
Hei! On monday! I forgot my laptop at work and can’t push new version to packagist :(

**Comment by flobernd** [comment]
Perfect. No hurries :)

**Comment by tavicu** [comment]
I have pushed the new version :)

**Comment by mauricelumiere** [comment]
@tavicu in 13.2 its possible to decide to group or ungroup one devices sensors and keys individually 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tavicu** [comment]
> @tavicu in 13.2 its possible to decide to group or ungroup one devices sensors and keys individually

Yup! I've seen and i consider to make it how it was before since you will be able to choose :)

Waiting for 13.2 release then i will test it and if everything is ok, i will "revert" how it was

**Comment by apexad** [comment]
In my opinion, I do not think you should revert. There is no reason switches should be grouped with the TV, even if Apple does allow them to be separated.

**Comment by tavicu** [comment]
In iOS 13.2 you will have the option to select how you want it to be!

Like it is roght now, you wont be able :)

**Comment by flobernd** [comment]
> In iOS 13.2 you will have the option to select how you want it to be!

At least up to some degree ... You can either chose to have all services grouped - or not. Does not seem like you can ungroup just specific services.

**Comment by apexad** [comment]
@tavicu So, the thing is though, I see almost no reason that switches should be grouped with the TV object.  It even seems like having this happen actually breaks the functionality of the TV tile.  So, on that note, I would say it's probably not worth your time or effort to 'revert' this change you made to be iOS 13 compliant.  Of course, it's your plugin and it is completely up to you!

**Comment by tavicu** [comment]
@apexad I know, but it doesn't take a lot of time to add it. There are other users that will want to keep it grouped :)

I'm also on your side and i will keep them separated :)
