### ISSUE TITLE
Set menu button in the iOS control center remote

### ISSUE THREAD

**Issue by Staphylococcus** [tavicu/homebridge-samsung-tizen#134]
Hi, first of all I gotta say that this is an amazing plugin, I love not having to worry about where the remote is and just always be able to control the tv from my phone. One thing I was wondering is whether it’s possible to have the menu button in the control center remote? I’ve tried to look for some sort of reference of available commands that remote supports and what kind of key presses can be issued by the plugin, but couldn’t find enough info to figure out how to do what I’m aiming for. Would appreciate any suggestions!

Upd. Found the supported commands, are control center commands in the default config the only ones that it can handle or can one add a menu button in there?

**Comment by Staphylococcus** [comment]
![IMG_0358](https://user-images.githubusercontent.com/7261268/64904795-9d7c6a00-d6d7-11e9-8e4f-e29311905aa3.PNG)
Right, so I've figured out that the buttons I'm looking for are in the default config, they just aren't showing in the remote control. Does anyone have any pointers as to why that might happen?

**Comment by tavicu** [comment]
Unfortunately Apple decides what buttons are displayed in Control Center. We can only map them.

Maybe in the future we will be able to choose what buttons to show!

[Here](https://github.com/tavicu/homebridge-samsung-tizen/wiki/Keys) you can find more info how to map the current buttons.

**Comment by Staphylococcus** [comment]
Thanks, I’ve ended up remapping the Information button to act as “KEY_HOME”, that should do the trick until Apple decides to open up customization. Thanks again for creating and maintaining this plugin.
