### ISSUE TITLE
after the update my device was not found

### ISSUE THREAD

**Issue by fighterzg6** [tavicu/homebridge-samsung-tizen#138]
Hi,
after the update my device was not found!
the furnished transmitter still work but the device itself I can not switch on / off!
even after uninstalling the plugin and re-setup the TV is not found!

**Comment by fighterzg6** [comment]
ok, I've taken uuid now a3 and everything set up again!

but why is everything now displayed individually!
 in the past, the transmitters were all stored in the television button. now everything individually?

**Comment by cilianospina** [comment]
Same problem, now all button is individually:(

**Comment by tavicu** [comment]
Hei. Not a problem! That’s how it should work.

**Comment by cilianospina** [comment]
Well, I want everything integrated as before Hahaha

**Comment by tavicu** [comment]
If apple will redesign the Home app to display the name for every switch and make the interface more user friendly, i will reconsider it! But right now with the current interface, having a few custom switches and it's getting frustrating not knowing what it does.
