### ISSUE TITLE
Samsung Frame TV - Power Off

### ISSUE THREAD

**Issue by finch6** [tavicu/homebridge-samsung-tizen#14]
Hi,

I have the Samsung Frame TV. This plug-in works perfectly for what I want it fo (turning on and off).

However, the Frame TV doubles as a picture frame. So if you press the power button when the TV is on, the TV will go into "frame mode". To turn the TV off, you have to hold the power button for 2 seconds.

I have looked through the code (I'm VERY new to this) and couldn't find anything about how long the script sends the power off command for.

Please can you assist where I can add the code to support this function?

Thank you in advance!

**Comment by tavicu** [comment]
Hey.

The api only know to send an receive a command. It doesn't have an option to simulate "hold" unfortunately.

I don't think you will be able to do this with any plugin.

**Comment by arnowillig** [comment]
Hi, I got a similar problem with "The Frame". (It is a UE55LS003 Samsung TV from 2017)

The problem is, that the power detection of the plugin does not work with this TV. For example, when the TV is on "Off"-Mode (Art-Mode), the URL http://x.x.x.x:8001/api/v2/ is still reachable.
It would be ideal if the plugin would mark the TV as "Off" in this mode. Maybe there is another API call to detect this mode?

I noticed the "FrameTVSupport": "true" in the /api/v2/ output (see below), this seems to advertise the TV to be a "Frame" with art-mode support.

Thank you!


```
curl http://x.x.x.x:8001/api/v2/

{
  "device": {
    "FrameTVSupport": "true",
    "GamePadSupport": "true",
    "ImeSyncedSupport": "true",
    "OS": "Tizen",
    "TokenAuthSupport": "true",
    "VoiceSupport": "true",
    "countryCode": "DE",
    "description": "Samsung DTV RCR",
    "developerIP": "0.0.0.0",
    "developerMode": "0",
    "duid": "uuid:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "firmwareVersion": "Unknown",
    "id": "uuid:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "ip": "x.x.x.x",
    "model": "17_KANTM_UHD",
    "modelName": "UE55LS003",
    "name": "[TV]The Frame",
    "networkType": "wireless",
    "resolution": "3840x2160",
    "smartHubAgreement": "true",
    "ssid": "xx:xx:xx:xx:xx:xx",
    "type": "Samsung SmartTV",
    "udn": "uuid:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "wifiMac": "xx:xx:xx:xx:xx:xx"
  },
  "id": "uuid:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "isSupport": "{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"true\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n",
  "name": "[TV]The Frame",
  "remote": "1.0",
  "type": "Samsung SmartTV",
  "uri": "http://x.x.x.x:8001/api/v2/",
  "version": "2.0.25"
}

```
