### ISSUE TITLE
TV state randomly reports 'on' while the device is switched off

### ISSUE THREAD

**Issue by flobernd** [tavicu/homebridge-samsung-tizen#141]
Hi there,

my TV is randomly shown as powered on in HomeKit for some seconds while the device is off. That’s kinda annoying because I am using the TV power state as a trigger for an automation. 

Is there anything we can do to improve the check?

Best regards

**Comment by flobernd** [comment]
I think there are some different problems:

- While turning on/off the power-state gets changed immediately, but with low refresh rates (1000ms for me) the port check happens before the TV is completely switched on/off which causes the state to jump back to the previous value until one of the succeeding port checks returns the correct value
- It seems like the TV wakes up in certain intervalls for a very short time to perform some kind of background tasks (maybe the on/off detection should perform a full http request to the info API or a short threshold time until the state gets changed - which sadly would be bad as well for time critical automizations)

**Comment by flobernd** [comment]
Another way to reproduce:

- Open the universal remote control and click on a button of your choice (e.g. "back")
- The TV device immediately becomes "active" in the Home app (but does not actually switch on)

**Comment by tavicu** [comment]
That's because the TV enter in a "sleep" state where it respond to every request and ping like it's ON.
There is no option to know if it's in the sleep state or not.

But when you turn it off there is already a check that for 15 seconds after you turn it off (from the home app, not from the remote) it will display the tv like off. after 15 seconds the tv will actually turn off and it will not respond to requests.

I will check to see if the feature is working as it should.

**Comment by flobernd** [comment]
> That's because the TV enter in a "sleep" state where it respond to every request and ping like it's ON.
There is no option to know if it's in the sleep state or not.

Maybe there is a way to detect if the TV is in sleep state or actually turned on by the API? I saw there is a way to query what app is currently active on the TV ... just a random idea. At the moment it's completely impossible to use automations based on the TVs power state, as it enters sleep mode several times per hour.

> But when you turn it off there is already a check that for 15 seconds after you turn it off (from the home app, not from the remote) it will display the tv like off. after 15 seconds the tv will actually turn off and it will not respond to requests.

I saw that in code and can only guess that the timeout might not be long enough for my TV. A configurable threshold (one for On, one for Off) could be a possible solution. For me it's like this:
- TV is on -> click "Off" in Home app -> TV tile turns off immediately -> after the 15 seconds it turns back on -> after another 2-5 seconds it turns off

I'm using a 1000ms (tested with 500ms as well) refresh rate.

**Comment by flobernd** [comment]
Ok as for the random power-on events there must be a bug in either your plugin, homebridge or even HomeKit.

I wrote a small tool which periodically (every 500ms) sends a GET request to the `api/v2` endpoint from my workstation computer.

While the tool always run into a connection timeout (configured to 1000ms) the device in HomeKit on the other hand was powered on for some split-seconds and triggered my automation.

**Comment by lukyer** [comment]
Same problem with my Samsung Tizen 7 TV. Probably relying just on api/v2 response is not realiable. Hopefully some API will provide us more reliable off/on status info.

In the meantime I think we can create two switches, one for turning ON and second for turning OFF (if you don't actually need TV power status itself - my automation is just to turn off TV when leaving home regardless it is on or off)

**Comment by mafyata** [comment]
I don’t have such a problem. Everything is perfect. My tv is UE50MU6102

**Comment by flobernd** [comment]
@mafyata Do you actually run an automation based on the TVs power-state? You won't notice the problem otherwise.

@tavicu We could try to log the return values of your `getActive()` function. If we really see "On" values while my custom script is not able to connect, then it must be a problem with the plugin. If we don't see "On" values in your plugin log, but my automation still gets triggeted, it must be a problem with Homebridge or Homekit.

**Comment by tavicu** [comment]
The plugin does not check if tv is online requesting the /api/v2 endpoint. It pings the IP. If it answers, then it's ON.

**Comment by flobernd** [comment]
> The plugin does not check if tv is online requesting the /api/v2 endpoint. It pings the IP. If it answers, then it's ON.

Well ... the library you are using is actually opening a (TCP) socket. No ping. Sending a real HTTP request to the api might even be the better and more reliable solution.

**Comment by tavicu** [comment]
This is the only option right now! Trust me when i’m telling i tried everything!

Sending a request to the api will block the TV. After some time the TV will stop responding to everything and you need to hard restart it.

**Comment by flobernd** [comment]
Ok but what about using the socket/ping method if the TV is On and the api request method if the TV is off. If it's really off it can't block the traffic after some time and as we would stop using requests as soon as the plugin gets the first response, we should be fine.

**Comment by mafyata** [comment]
> @mafyata Do you actually run an automation based on the TVs power-state? You won't notice the problem otherwise.

I have automation I work great. Manually turn on/off work great.

**Comment by codyc1515** [comment]
I have a similar issue. The TV appears in the Home app to be turning on & off (when in fact it is not).

**Comment by benjaminsehl** [comment]
I have the Samsung Frame, which is weird because it has art mode which is off? And then on? But in the home app on=art mode, off=fully on

**Comment by flobernd** [comment]
> I have a similar issue. The TV appears in the Home app to be turning on & off (when in fact it is not).

Yeah that behavior makes it impossible to use any kind of automation based on the power-state. I will have some spare time next week where I will probably going to fork this plugin and fix it myself.

**Comment by tavicu** [comment]
> Yeah that behavior makes it impossible to use any kind of automation based on the power-state. I will have some spare time next week where I will probably going to fork this plugin and fix it myself.

Good luck doing that :) As i already told, since the last update of TV, samsung implemented something that will start the TV in the sleep mode to do some checks (i didn't have time to check if can be disabled). Since the TV is in sleep mode it will answer to the requests like is ON, making the accessory switch to ON since it responds to the check.

Someone told that requesting the endpoint `api/v2/` doesn't answer when is in sleep. I didn't check but this method is not valid, why? You will see when you will try to fix it yourself.

Ahhh ... ok, i'll tell you since i already tried this method. Making to much requests to the endpoint will block the TV and it will stop answer to any request! It doesn't matter if you turn it ON/OFF, it will stop working! Only solution to get back is by hard restarting the TV or plug it off from the power!

I will try to see if there is another option or something but right now I have a lot of work and can't check!

It will be awesome if samsung made an endpoint to check the status of TV ... but unfortunately ... 

And other thing i discovered since the last update, if you try to connect to socket while the TV is off, it will turn it on (like ON ON, not sleep ON)!

**Comment by flobernd** [comment]
> Someone told that requesting the endpoint api/v2/ doesn't answer when is in sleep. I didn't check but this method is not valid, why? You will see when you will try to fix it yourself.

Yeah, that's what I observed while running a custom script on my workstation machine for some time. Not a single response while the TV appeared to be On in HomeKit several times. At least my TV did not block traffic - even after some hours. How could it anyways, if it's off? As I said .. we could just use the socket method while the TV state was initially detected as beeing On. After the internal power-state is Off, we switch to the request method. There is no way for the TV to even notice our requests while beeing off.

> And other thing i discovered since the last update, if you try to connect to socket while the TV is off, it will turn it on (like ON ON, not sleep ON)!

Well, that did not happen for my TV as well 😆 I will check thater again tho.

> It will be awesome if samsung made an endpoint to check the status of TV ... but unfortunately ...

Yeah Samsung should just provide a proper public API interface. But yeah ... it's Samsung.

**Comment by tavicu** [comment]
Next week i will have some more free time and will see what combination of checks i can do to get a more accurate response.

**Comment by mauricelumiere** [comment]
@tavicu @flobernd can you please be aware of the artmode_status for the frame TVs or ambientmode_status for OLED TVs ? Because here you have the ability to keep the TV on showing a Picture or simulation of the wall behind. @tavicu already made a branch but has not responded. I can help, if you tell me what you need.

Thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JonMR** [comment]
I noticed this same issue today. 

I setup an automation to turn on my receiver via a Harmony Hub when the TV is on, and another to turn the receiver off when the TV is off. Everything works great, until I heard my receiver randomly turning on and off throughout the day.

Any progress on this? Maybe I can try to spam my TV with API requests to see if I can recreate the lockup that @tavicu mentioned.

**Comment by JonMR** [comment]
@tavicu how long did it take for the tv to lockup by hitting the HTTP API?

I have two separate Samsung TVs and I have curl requesting their API endpoints once every second. I’m planning to leave that running and see if I can reproduce the lockup. If I can’t reproduce it, maybe we could make an option to use the API endpoint for status?

I have not experienced the TV turning on by requesting the API endpoint

**Comment by tavicu** [comment]
The problem is that depends on the TV! It may not lockup on yours, but do on others!

I had that implementation one time and issues started to appear! I didn't have that problem, but others do!

I have an ideea of how to fix it but i need some time and that will be starting with next year :)

**Comment by JonMR** [comment]
Would you like help? I’ve got the next week and some off of work. If you tell me what you’re thinking I might be able to get a PR together.

**Comment by tavicu** [comment]
I want to make some changes that when the TV responds that is ON, to also check if the HTTP responds. But only once every 5 minutes or something! Not every time!

Also i want to move the power on/off logic to other controller to help me with the implementation for the Frame TV.

Sorry but i think it will take more to explain to you than making it :P 
Thanks for the help!

**Comment by luixiuno** [comment]
My tv model is a Samsung tizen UN55J6300 And it is not working

**Comment by lengyimester** [comment]
Same issue in 2020 :) we wait the best solve

**Comment by town3r** [comment]
Any update on this front?

**Comment by ItayZviCohen** [comment]
Any updates?

**Comment by JonMR** [comment]
I'm back again a year and two days later with yet another free holiday on my hands. I don't intend to guilt you as a maintainer with that statement, but only communicate my motivation to help resolve this.

Rather than hacking something I decided to see if maybe the device's power state has been added to the API. To my delight, I think it has? But possibly it hasn't been back ported to all devices? 😢 I have two devices a 2019 Q90R and a 2016 KS8000.

On my Q90R, when I run `curl http://my-tv:8001/api/v2/` under `device` I see `"PowerState": "standby"` when the API is available and the TV is off. When the TV is on I see `"PowerState": "on"`. 🍠 

My KS8000 has no such `PowerState` property. ☹️

Here's my proposal: 

1. We leave the ping in place.
2. If the ping fails, the TV is off.
3. If the ping is successful, we query the API for `PowerState`. 
4. If the API query fails, the TV is off. 
5. If the API responds and `PowerState` isn't present, the TV is on.
6. Else, the TV is only on if `PowerState` has a value of `on`. 

That would at least fix this issue for TVs that have `PowerState` available and slightly improve results for those that don't. If you want a to limit API queries to every 5 seconds or something, please let me know. I would hope that Samsung has fixed whatever memory leak it is that you hit previously. 🤞

**Comment by JonMR** [comment]
I made a really simple attempt at the above. If more complication is needed to throttle API requests, then I'd be happy to attempt that. You obviously have way more context on this project and the devices than I do.

I won't open a PR until I get some general direction. In the meantime, I'm going to run my branch for a bit and see if my devices lock up as you mentioned.

**Comment by Final-Hawk** [comment]
Any update on this?

**Comment by JonMR** [comment]
I haven’t heard back so I went ahead and opened a PR. https://github.com/tavicu/homebridge-samsung-tizen/pull/304

It’s working well for my use case. I haven’t had either of my Samsung TVs lock up as described in this issue, but I only have two devices to test with. It’s been running stable for over a month now on my homebridge.

**Comment by tavicu** [comment]
> I haven’t heard back so I went ahead and opened a PR. #304
> 
> It’s working well for my use case. I haven’t had either of my Samsung TVs lock up as described in this issue, but I only have two devices to test with. It’s been running stable for over a month now on my homebridge.

Hi @JonMR ! Thank you for contribution but unfortunately i will not merge that method.
That's how it was implemented before and there where problems with most of TVs. 
After a few requests (especially for users that change refresh interval) the TV stops responding to the API and need to be force rebooted.

You probably have a newer TV which maybe have better processing power. But the plugin is used on a lot of older TVs and also a lot of people change the refresh interval.

So this is not an option where all we are happy :)

We need a hibrid between these two methods ...

**Comment by JonMR** [comment]
Sure thing. How about this. We use the API to determine if the TV is on. Then use the socket check thereafter to determine if the TV is off.

That’ll be a little slower to report off for TVs that go into standby before the API stops responding.

We could get a little fancier and solely use the API if PowerState is present. Assuming that only newer TVs report that property and are therefore hopefully immune to the lockup issue. Feels like a fairly safe bet to me.

Let me know what you think. It seems like a good mix of the two approaches. Additionally it would avoid the complexity of a 5 minute timer and allow the plugin to report the device as off quicker.

**Comment by Final-Hawk** [comment]
Not sure if this helps, but in [this](https://github.com/ollo69/ha-samsungtv-smart) repo they solve this by seeing if the tv is muted
`Use volume mute status to detect fake power ON
(default = True)
When enabled try to detect fake power on based on the Volume mute state, based on the assumption that when the TV is powered on the volume is always unmuted.`

**Comment by CGDaveMac** [comment]
> > I haven’t heard back so I went ahead and opened a PR. #304
> > It’s working well for my use case. I haven’t had either of my Samsung TVs lock up as described in this issue, but I only have two devices to test with. It’s been running stable for over a month now on my homebridge.
> 
> Hi @JonMR ! Thank you for contribution but unfortunately i will not merge that method.
> That's how it was implemented before and there where problems with most of TVs.
> After a few requests (especially for users that change refresh interval) the TV stops responding to the API and need to be force rebooted.
> 
> You probably have a newer TV which maybe have better processing power. But the plugin is used on a lot of older TVs and also a lot of people change the refresh interval.
> 
> So this is not an option where all will are happy :)
> 
> We need a hibrid between these two methods ...

Is there a way to change the methods based on user settings, which could include model of the TV. Or possibly a toggle with a warning that it may not work on some TVs?

**Comment by tavicu** [comment]
i will try to make some scripts and see if our hibrid solution is the right one.

if it is and TV is not responding to `/api/v2/` while it does its magic i will implement it then test if for a few days.

I will keep you posted

**Comment by tavicu** [comment]
Ok, i made a small script to ping every two seconds and if ping responds to also check the http api `/api/v2`.
Unfortunately when the TV is doing is magic thing (without turning on) it also starts to respond to http request. The voodoo magic takes about 3 seconds.
So this will not be useful for TVs which don't have the `PowerState` key, like my TV :(

I will implement the method but the problem will remain for older TVs which don't send the PowerState. i tried multiple methods and unfortunately there is no way of knowing if TV is sleeping or actually it's on :(
it responds to ping, http and websocket request while doing it's things!

```
---- Thu, 04 Mar 2021 19:31:02 GMT ----
status - ping false
status false

---- Thu, 04 Mar 2021 19:31:04 GMT ----
status - ping true
status - http true
status true

...

---- Thu, 04 Mar 2021 19:33:52 GMT ----
status - ping true
status - http true
status true

---- Thu, 04 Mar 2021 19:33:54 GMT ----
status - ping false
status false
```

**Comment by JonMR** [comment]
That makes sense. Thank you for testing. I thought the API wouldn’t respond at all on older TVs in that magic “on” state and I didn’t catch it in my testing I guess.

Let me know if you’d like me to adapt my PR. 

One thing I had to do in my PR that might not be obvious was add a retry when checking the API. The request was sometimes timing out. Everything is on a wired network. I suspect the TV API is the culprit. In my use case, I’m tying the TV’s power status to my AV receiver’s power status, when the API would time out, the receiver would turn off then turn back on in a subsequent check. Adding a few retries before deciding the TV has powered off solved that.

**Comment by tavicu** [comment]
Ok, 7 hours later i had pushed the changes but did not released a new version yet. I want to test it and make sure everything it's ok before releasing it to public.

If anyone want's to try it you can install the master branch like this: `npm install -g https://github.com/tavicu/homebridge-samsung-tizen#master`

**Comment by CGDaveMac** [comment]
> Ok, 7 hours later i had pushed the changes but did not released a new version yet. I want to test it and make sure everything it's ok before releasing it to public.
> 
> If anyone want's to try it you can install the master branch like this: `npm install -g https://github.com/tavicu/homebridge-samsung-tizen#master`

I just tried this version and now my Samsung Frame doesn't respond at all. Also, home bridge asked to re-add to the Home App.

**Comment by tavicu** [comment]
Homebridge will always tell you to add it to Home app when you start the instance.

I have just updated my main instance to the master and everything it's working fine for my TVs.

I will not offer support on how to install a testing version of the plugin. Sorry for that!
If you don't know what you are doing, don't do it :)

And if you find a problem, provide more info, not "not responding".
Don't even know what is not responding, what did you do, what have you tried, anything in logs, etc.

I will ignore posts like that :)

**Comment by CGDaveMac** [comment]
My apologies, I was not looking for support. It sounded like you were waiting to release this version pending any bugs and I wanted to provide feedback that updating the plugin breaks my existing setup. In my experience I have not had to re-add a device when updating plugins, so was surprised to see the following log as the TV was still showing in the Home app:

```
[3/7/2021, 1:41:52 PM] Homebridge v1.3.2 (HomeBridge4) is running on port 51831.
Preparing Advertiser for 'Living Room TV BD08' using bonjour-hap backend!
Starting to advertise 'Living Room TV BD08' using bonjour-hap backend!
[3/7/2021, 1:41:52 PM] Living Room TV BD08 is running on port 62803.
[3/7/2021, 1:41:52 PM] Please add [Living Room TV BD08] manually in Home app. Setup Code:
```
Changing the power state provided nothing in the logs. So I deleted and re-added the TV, then saw the following:

`[3/7/2021, 1:56:36 PM] [Living Room TV] Powering on is in progress ` 
...but nothing else happened. The device was not showing as non-responsive in the Home app. But the TV itself was non-responsive. 

I deleted and re-paired the TV once again and this appeared in the log:
`[3/7/2021, 1:59:24 PM] [Living Room TV] Failed to pair! Make sure TV is online and you click "Allow" on the popup`

I reverted the version to 4.3.6 and it works without changing any settings. If you want me to test anything and provide feedback, I am willing to help. Otherwise I will stick to 4.3.6 for now.

**Comment by tavicu** [comment]
Hi. Thank you for the informations.

As i said, the `Please add ...` appears every time you start the homebridge instance. Maybe you missed it until now :)

For the not communicating part, i will take a look but it's interesting cause i didn't change anything over there ...

**Comment by tavicu** [comment]
Hei. I have pushed the new version.

Take note that you **DON'T have to remove the TV from home app** or something. Just update the plugin :)

**Comment by tavicu** [comment]
Hei @CGDaveMac , from what i understand you have a Frame TV, could you please send me the response from this endpoint `http://TV_IP:8001/api/v2/` when your TV is in art mode?

I am working on Frame method and i want to see what the PowerState value is when it's in Art Mode

**Comment by CGDaveMac** [comment]
> Hei @CGDaveMac , from what i understand you have a Frame TV, could you please send me the response from this endpoint `http://TV_IP:8001/api/v2/` when your TV is in art mode?
> 
> I am working on Frame method and i want to see what the PowerState value is when it's in Art Mode

Sure. I updated the plugin and it seems to be working erratically or perhaps backwards. As discussed in the other [Implement Frame TV thread](https://github.com/tavicu/homebridge-samsung-tizen/issues/318), PowerState is ON when in Art Mode.

**Comment by tavicu** [comment]
> > Hei @CGDaveMac , from what i understand you have a Frame TV, could you please send me the response from this endpoint `http://TV_IP:8001/api/v2/` when your TV is in art mode?
> > I am working on Frame method and i want to see what the PowerState value is when it's in Art Mode
> 
> Sure. I updated the plugin and it seems to be working erratically or perhaps backwards. As discussed in the other [Implement Frame TV thread](https://github.com/tavicu/homebridge-samsung-tizen/issues/318), PowerState is ON when in Art Mode.

Yeah, unfortunately for Frame TVs it will work just like it worked before ... it will always be ON as long as the TV is in art mode.

But the first step of the Frame TV implementation should be ready in a few days and will fix it :)

**Comment by flobernd** [comment]
Hi there,

things improved over time, but now it seems like the latest version has the same problem but reversed.

Randomly the TV reports "off" for some seconds and instantly turns "on" again. Sadly this makes it impossible to use automations :-/

Could you probably give us configurable "threshold/timeout" values after which the device is shown as "off". E.g. show it as "off" if there was no response in the last 10,30,60 seconds.

Best

**Comment by JonMR** [comment]
Ditto what @flobernd said.

I've been running my fork successfully since 2021 without the issue they're reporting. Today I tried to switch back to mainline and had the same experience as @flobernd.

The difference is that my fork retried HTTP 3 times when transitioning from on to off. See https://github.com/JonMR/homebridge-samsung-tizen/blob/debugging/lib/remote.js#L56-L63.

**Comment by uncom-es** [comment]
Hi everyone.
please help, I need to turn off the TV ( UE55AU9005KXXC) or put it into sleep mode from the command line.
type: curl -X POST -i ‘http://192.168.110.50:8001/api/v2/applications/111299001912’
I do not know how to do it
I could only run YouTube and other applications.

needs curl -X POST -i ‘http://192.168.110.50:8001/xxxxx/(POWEROFF)
Thanks
