### ISSUE TITLE
Strange remote (no keys)

### ISSUE THREAD

**Issue by flobernd** [tavicu/homebridge-samsung-tizen#142]
Hi there,

my remote looks strange and does not have any keys. I can't control my TV with it either (iOS 13.1 Beta)

![image](https://user-images.githubusercontent.com/8585557/65585637-10f96380-df83-11e9-9053-f62ccea839c6.jpeg)

Is there anything I can try?

Best regards

**Comment by mauricelumiere** [comment]
@flobernd you have to configure your installation. In default there are no keys and inputs configured only the on/off switch. You can follow the Configuration Page and e.x add Keys following this page:

https://github.com/tavicu/homebridge-samsung-tizen/wiki/Keys


Best,
Maurice

**Comment by flobernd** [comment]
Oh I see, so only the custom switches are showing up there. I expected to see the universal remote control app to be integrated at this place. 

So the TV should show up in the Remote app just like an normal AppleTv?

**Comment by tavicu** [comment]
Hei. Did you read the wiki? https://github.com/tavicu/homebridge-samsung-tizen/wiki
I have spend a lot of time making it and trying to be as briefly as possible.

On the main tv you will see only the ON/OFF and Inputs. Inputs needs to be configured.
Custom switches will appear as separate accessory once you configure them.

Also, the TV is shown in Remote Control by default (here you can see a GIF, https://github.com/tavicu/homebridge-samsung-tizen/wiki/Keys). In Remote App will not shown since Apple doesn't allow that (yet i hope).

**Comment by flobernd** [comment]
Yeah I read that, sorry for not beeing precise. Seems like I‘m still half asleep 😝 I meant the input switches, not the custom ones.

Oh I did not know that the Remote App and the Remote Control are actually two different things.

Thank you anyways!

**Comment by flobernd** [comment]
Sorry to bother you again, but .. on my iPad it’s working like a charm, but on my phone I just see this:

![8569C42A-5587-40E0-B4B3-161E05025FF5](https://user-images.githubusercontent.com/8585557/65683755-63f41900-e05e-11e9-8177-f41cbf18486a.png)
![BB56AB98-40AD-4614-8216-5BDECDF6AEC3](https://user-images.githubusercontent.com/8585557/65683756-63f41900-e05e-11e9-98bc-e786ffd9b1ee.png)

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/wiki/Common-Issues#--inputs-are-appearing-like-separate-accessories

**Comment by flobernd** [comment]
I read that and already restarted the Home app and my phone (this was yesterday in the evening). Well, not a big issue and might be related to me using iOS 13.1 beta.

**Comment by tavicu** [comment]
Restart Home App or even the phone.

**Comment by flobernd** [comment]
> Restart Home App or even the phone.

> I read that and already restarted the Home app and my phone (this was yesterday in the evening).

But as I said ... not a big deal. I will test it on another device with 13.0 later.
