### ISSUE TITLE
Switche with the same name

### ISSUE THREAD

**Issue by Tontonpat** [tavicu/homebridge-samsung-tizen#143]
Hello, sorry for my english because i’m french.
Since i update to the latest version, all the switches got the same name (TV).
So it is difficult to choose vol-up or Channel-up or else.
Can you help me?

**Comment by tavicu** [comment]
Hi,

Strange why it happened. Switches name are composed of switch name + tv name.

You can rename the switches from the Home App.

**Comment by Tontonpat** [comment]
Thanks, but the name of all the switche is only TV

**Comment by tavicu** [comment]
Try removing `accessories/cachedAccessories` folder then restart Homebridge.

**Comment by Tontonpat** [comment]
It don’t work. The same name on each switche.
Maybe, i have to remove all, and re install it?

**Comment by tavicu** [comment]
Remove all switches from config then restart the Homebridge server.

Then add them back and restart the server again. See what happens :)

**Comment by Tontonpat** [comment]
It works fine on my iMac, but don't on my iPhone (ios13.1)
![IMG_7F0891E50D02-1](https://user-images.githubusercontent.com/49283285/65601365-3fd30200-dfa2-11e9-8b40-e6d4fa9c91a4.jpeg)

**Comment by Tontonpat** [comment]
So, i erase all, and re install. It's ok, but the name of the switches don't have to contain + or / or - or a space, so that the name of the switches will be : switche on iMac or "TV name" only on iPhone with iOS 13.1.

I hope you will understand all :-)
Thank you very much for your help and sorry for my bad english
