### ISSUE TITLE
"No response" when not on the local network

### ISSUE THREAD

**Issue by codyc1515** [tavicu/homebridge-samsung-tizen#145]
Since updating to iOS 13 when I am _not_ on my local network I receive the message "No response". This happens on the TV only. All of my other accessories are working.

Any ideas? I wonder if this is because it is a bridged accessory.

**Comment by JonoHaysom** [comment]
works for me. I do have a weird issue where my HomePods wont control the TV (on/off) but the other Siri devices and the Home app will/

**Comment by JonoHaysom** [comment]
hey @tavicu is there a way to do debugging so I can better see what/where the issue is? its so odd that only the HomePods wont trigger it but the iPhone, iPad will.

The

**Comment by codyc1515** [comment]
Could be a glitch using iOS 13 whereas the HomePods are still on iOS 12.3 (I think it is). Reminds me of the Reminders app on macOS which STILL is not updated as yet.

**Comment by mauricelumiere** [comment]
@JonoHaysom which device do you use as HomeKit Control Device for external access? Apple TV or this HomePod or iPad?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mauricelumiere** [comment]
@JonoHaysom what does the HomePod says if you would like to control the TV? Or do you use a shortcut?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JonoHaysom** [comment]
> Could be a glitch using iOS 13 whereas the HomePods are still on iOS 12.3 (I think it is). Reminds me of the Reminders app on macOS which STILL is not updated as yet.

Yup could be this, all my other devices will respond and activate it via Siri commands. "hey Siri, turn the tv on" works with everything but my homepods.

@mauricelumiere it says "Done" but nothing happens to the TV :/

**Comment by tavicu** [comment]
If it works from other devices, it has nothing to do with the Homebridge server! Probably because you did not update. 

Did you try restarting the homepod?

**Comment by mauricelumiere** [comment]
@JonoHaysom try to restart the HomePod or even reset it through the Home App. Apple has made various changes to HomeKit in iOS 13 and the HomePod still is on 12.4

Another thing you can try is to rename the accessory in the home app.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JonoHaysom** [comment]
> If it works from other devices, it has nothing to do with the Homebridge server! Probably because you did not update.
> 
> Did you try restarting the homepod?

@mauricelumiere Ive tried restarting the HomePod. didn't help. there is no iOS 13 update for the homepods yet. do you have one? is it working?

@tavicu its weird as it used to work from the HomePod on 12.4 and as well on my iOS 13 devices before the update.. but the remote look and feel in the iOS app was the old version until you updated the plugin. maybe something was deprecated when you updated?

**Comment by tavicu** [comment]
The main accessory was not touched! Only the custom switches

**Comment by JonoHaysom** [comment]
Even weirder.. hrrmm..

Wonder what it could be!

**Comment by mauricelumiere** [comment]
@JonoHaysom no there is no update yet. Try to reset the HomePod to factory. There are sometimes Siri problems and it helped me some days ago.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mauricelumiere** [comment]
@JonoHaysom if you say Siri says “Done”. Do you use a Siri Shortcut made in the Shortcuts App? It sounds so.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mauricelumiere** [comment]
@JonoHaysom Siri Shortcuts are not well supported on the HomePod with the hab between 12.4 and 13.1

Please try to remove the shortcuts and rename the TV with just like “TV Livingroom” put it in the Room “Livingroom” and say “Siri turn on/off TV Livingroom”

My Siri doesn’t answer and just do the job. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JonoHaysom** [comment]
No, natively asking her to do it. I don’t use shortcuts. The TV is called “TV”.

Best,

Jonathan

**Comment by codyc1515** [comment]
Restarting my HomePod didn't work, so I tried turning off my HomePod and using my iPad Pro (running iOS 13) as the main hub. Voila! It works. Shame that Apple has gone and broken something like this and we still have no confirmed date for iOS 13 to come out on the HomePod's.
