### ISSUE TITLE
Other Home App

### ISSUE THREAD

**Issue by yclai1229** [tavicu/homebridge-samsung-tizen#147]
Hi, Tavicu,

My Samsung TV can be used normally with the HOME APP, but if it is on other apps, (idevices, home+ 4, eve) can't find this TV device, what am I getting wrong?

Thank you.

**Comment by mafyata** [comment]
This plugin is made to work with home app

**Comment by tavicu** [comment]
Homebridge as a platform is compatible only with HomeKit!

There are plugins that export the accessories for other platforms (like Amazon Alexa for example) but you will have to search and find yourself :)
