### ISSUE TITLE
Siri commands not working since iOS 13

### ISSUE THREAD

**Issue by sero2kk** [tavicu/homebridge-samsung-tizen#148]
I can Turn on and of tv and switching Channels by tap the homekit buttons but Siri commands are not working since the iOS 13 and Samsung-tizen  Update to 4.1.0

**Comment by tavicu** [comment]
Sorry but nothing to do with the plugin. Since you can control the TV from Home App means that the Homebridge server and this plugin works. Make sure you got the right names for accessories.
