### ISSUE TITLE
Overlay Support of Older Samsung Models?

### ISSUE THREAD

**Issue by jdtsmith** [tavicu/homebridge-samsung-tizen#151]
A fork of the related plugin [`homebridge-samsung-remote`](https://github.com/nitaybz/homebridge-samsung-remote) that works with older (pre-2014 aka pre-Tizen) Samsung models is [`homebridge-samsung-remote-older-tv`](https://github.com/kuglee/homebridge-samsung-remote-older-tv/blob/master/README.md).  It uses the relatively new [`samsung-remote`](https://github.com/natalan/samsung-remote#readme) library so it was a straightforward fork.  But it does not yet support the new HomeKit TV service as your plugin does.  I wonder what you think about incorporating (optional) support for older Samsungs via the `samsung-remote` library as well? If possible, a single up to date plugin that covers most Samsung models would be ideal. I could contribute some coding support if you are interested.

**Comment by tavicu** [comment]
Hi. I have looked over the `samsung-remote` library and indeed is using another method to send the commands to TV.

I have checked and looks like this method only works with older smart TV's that don't have Tizen.

I can implement this but some features will be missing. Like open an application by id!

**Comment by jdtsmith** [comment]
That would be awesome.  I had thought of porting one of the "older-tv" plugins to the use the new Homekit TV service, but given that you've done all the work on that already...  Let me know if you need some input on design.  If it's possible to abstract out the communication method as a separate class or module, then it would be as simple as adding a `pretizen: true` config flag or some such. 

 I have a Samsung UN7050 (2013), and after some investigation, I've realized it doesn't actually have Wake-On-Lan.  So probably not ideal for testing.

**Comment by tavicu** [comment]
Starting from December i should have a few days to try and implement it. If you are willing to help me testing i can do it!

**Comment by jdtsmith** [comment]
Be glad to test.  I realized I could in fact ask my Denon receiver to turn the TV on over HDMI-CEC if it is off and therefore not reachable (using PWON MNMEN ON commands, which turns on the receiver's graphical menu, and hence the TV if needed).  Clearly very specialized  to my setup, so not worth hard-coding, but maybe we could leave room for calling some external code in place of w-o-l in your updated plugin.

**Comment by huddx01** [comment]
I can also help you with testing. Got an old ES Series TV. And would be very happy to implement the old api.

**Comment by jdtsmith** [comment]
> I can also help you with testing. Got an old ES Series TV. And would be very happy to implement the old api.

Does wake-on-lan work with it?  Mine doesn't, which means I need a workaround.

**Comment by huddx01** [comment]
> Does wake-on-lan work with it? Mine doesn't, which means I need a workaround.

Short answer: No. As far as i know, WOL is generally not supported by pre 2015 models. 

Long answer: Yes - Turn the TV on via HDMI-CEC is the only method which is practicable. In my scenario - i have an AppleTV connected via CEC to TV. So if i wake up the AppleTV via HomeKit, the TV gets on.  
For me, the most interesting thing would be to act the old Samsung as a TV accessory in homekit.

**Comment by tavicu** [comment]
Unfortunately this means it will only be possible to turn off the tv from homekit :(

**Comment by huddx01** [comment]
> Unfortunately this means it will only be possible to turn off the tv from homekit :(

Not if you are a nerd. If you are able to root the tv with samygo, you could try this soft poweroff lib...
https://forum.samygo.tv/viewtopic.php?t=8987

But i think it is more easy to trigger a custom hdmi-cec connected device when the Button TV Power is set to on. Maybe in combination of the homebridge-cmd4 package...

But i think it is a further way.. For me it would be great to implement the television accessory with its characteristics like mute, source, etc.. to an old samsung tv first.

**Comment by jdtsmith** [comment]
Once the TV is on, samsung-remote can turn it off using via `KEY_POWEROFF`.  I've confirmed it works on my 2013 vintage.  So the only problem is getting it to turn on.  Like @huddx01, I can do this via HDMI-CEC, for me using IP control of a Denon receiver to ask it to turn on its graphical interface.

**Comment by NateUT99** [comment]
I have both a 2019 and 2014 Samsung television (both with Smart Hub)... if this would help potentially bring HomeKit support to my 2014 TV, I'd be glad to help testing too!

**Comment by mateutek** [comment]
Happy to help also, i have H6400 model, 
It's pairing via PIN so maybe there is a way to work around this somehow ?
I can see the status of the tv, but nothing more with current plugin version
