### ISSUE TITLE
homekit off/on

### ISSUE THREAD

**Issue by curla92** [tavicu/homebridge-samsung-tizen#152]
my samsung tv when turning off after a few seconds will turn on and stay on for other 1 minute.
I don't know the reason, i can't do an automation because it breaks all.. 
How can i do? thank y

**Comment by codyc1515** [comment]
Can you please explain the problem you are experiencing a little more clearly?

**Comment by curla92** [comment]
when i turn off the tv homekit, it turns off but after a few seconds tv turns on. it ll turn off after a while.

**Comment by jdtsmith** [comment]
If there are device plugged in by HDMI they may be controlling power over CEC.  Try removing one by one.
