### ISSUE TITLE
Add the ability to not bridge accessories

### ISSUE THREAD

**Issue by codyc1515** [tavicu/homebridge-samsung-tizen#153]
I only have a single TV so it would be good to add a flag to not have to pair the TVs separately. This also causes me issues with remote accessibility (when I am not on the local wifi). I believe the code in question is the call: `this.api.publishExternalAccessories(PLUGIN_NAME, [accessory.platformAccessory]);`. Changing this to `this.api.registerPlatformAccessories(PLUGIN_NAME, PLATFORM_NAME, [accessory.platformAccessory]);` causes an error about duplicate UUIDs (even though I have cleared the relevant section from my cachedAccessories file).

Any ideas?

**Comment by tavicu** [comment]
Hi,

This will not be changed. Also, i have no problem controlling my TV from outside my network!

Using an Apple TV as local hub

**Comment by mafyata** [comment]
My tv also work perfect. I don’t have problems.
