### ISSUE TITLE
In Home app only On/Off support is appearing and working (no volume buttons, info, etc)

### ISSUE THREAD

**Issue by rabh** [tavicu/homebridge-samsung-tizen#155]
Just installed the latest version of your plugin, on both my Samsung Q9 and Samsung Frame QLED, and whilst I am able to add both of them in the Home app (I'm on iOS 13.2.2), they appear correctly with the TV icon buy only seem to support switching on and off (the on/off bit is working really well). I've attached a picture below of what I see.

![IMG_C99D032C5CEC-1](https://user-images.githubusercontent.com/52424882/68627523-dec1a800-04d5-11ea-987e-a04bcc65b1e8.jpeg)

I've also added my config below - the reassigned keys for volume up/down are working fine in the remote app, as is arrow left/right, the info button and Back.

{
            "platform": "SamsungTizen",
            "keys": {
                "ARROW_UP": "KEY_VOLUP",
                "ARROW_DOWN": "KEY_VOLDOWN"
            },
            "devices": [
                {
                    "name": "Samsung Q9",
                    "ip": "xxx.xxx.xxx.xxx",
                    "mac": "xx:xx:xx:xx:xx:xx"
                },
                {
                    "name": "The Frame TV",
                    "ip": "xxx.xxx.xxx.xxx",
                    "mac": "xx:xx:xx:xx:xx:xx"
                }
            ]
        }

Is there some further config I am missing?

Thanks for all your efforts on this, looks like a great plugin with great support. Really appreciate your time.

**Comment by tavicu** [comment]
Hi, that's the default configuration. Inputs and switches are custom and needs to be configured.

https://github.com/tavicu/homebridge-samsung-tizen/wiki/Inputs
https://github.com/tavicu/homebridge-samsung-tizen/wiki/Switches
