### ISSUE TITLE
Volume doesnt work

### ISSUE THREAD

**Issue by gogo0884** [tavicu/homebridge-samsung-tizen#157]
Hi
Plugin work as expected, except the volume control from the homekit. I did have successful volume change if im adding commands manually to the appletv remote, but the volume from the home app refuses to work, moreover on the homebridge accessories tab i can see it as an separate accessory with comment “not supported” , i tried several tvs and had the same issue so i guess the is something wrong elsewhere 

Attaching the screen from the home app
![8ACEA455-267D-4C3A-83FB-D11B133B773B](https://user-images.githubusercontent.com/47993193/69364833-c1da6100-0c9b-11ea-9f74-2ed100ce916d.png)

Sorry that im not uploding debug. I tried but couldnt find any doc how to do it properly with windows and tried without success.

**Comment by mafyata** [comment]
The empty space on your pic is for apps and inputs of tv (eg.hdmi , youtube , hbo go.....). Volume is changing from remote. You can’t change volume from home app. This is limited by apple , not by plugin.

**Comment by gogo0884** [comment]
I see thx for the quick respond
