### ISSUE TITLE
“Active identifier” support

### ISSUE THREAD

**Issue by radiocolin** [tavicu/homebridge-samsung-tizen#158]
Is it possible to implement support for the “active identifier” function in the home device state?

On a native HomeKit TV, this returns an integer representing the current input.

**Comment by tavicu** [comment]
It is implemented but is working only for inputs of type “app”

**Comment by radiocolin** [comment]
Is that a technical limitation or a developer time limitation? Any way I could help?

**Comment by tavicu** [comment]
technical limitation! The samsung api doesn't tell you any information regarding the tv! You can't get the current volume, channel, etc! There is only one api where you can check if an app is active or not! So when you add 10 apps as inputs, the script send a request for each app to see if it's active!
That will be 10 requests (unless one is active and then it stops).
There is no api to get the active app or other information!

**Comment by radiocolin** [comment]
Well that stinks. I knew about that limitation on the Tizen API, I was hoping that maybe the smart things API did something a little saner. 

-CW

**Comment by radiocolin** [comment]
That’s wild. Such a strange decision.

**Comment by tavicu** [comment]
And even the current api is not documented! Had to do reverse engineering on their app to see how it works ...

**Comment by jnbht** [comment]
@tavicu is this possible for the Frame TV?
It would be great to know if there is something happening on the TV or if the picture was inactive for a while.

You said here  [https://github.com/tavicu/homebridge-samsung-tizen/issues/318#issuecomment-796942620](url)
 that the Frame is more communicative than the others and it is possible to get real time feedback.

**Comment by tavicu** [comment]
> It would be great to know if there is something happening on the TV or if the picture was inactive for a while.
> 
> You said here [https://github.com/tavicu/homebridge-samsung-tizen/issues/318#issuecomment-796942620](url)
> that the Frame is more communicative than the others and it is possible to get real time feedback.

Unfortunately the Frame TV api provide more info regarding the power state of TV. Nothing regarding the inputs.
When art mode is changed and when tv goes to sleep it sends a message on the websocket and then I can update the state in real time. But that's the only thing it offers :)

**Comment by jnbht** [comment]
Ok, to bad ;)
Thanks.

Great work by the way!
