### ISSUE TITLE
Are my switches showing correctly?

### ISSUE THREAD

**Issue by kinektech-au** [tavicu/homebridge-samsung-tizen#160]
I configured the plugin to operate my 2019 Samsung Smart TV (setup was effortless) but when I try to configure any inputs, commands and apps they all show up as physical switches in IOS13.2.2 .. is this normal? 

Unfortunately it makes the interface look really cluttered, is there any way to display these differently?

![IMG_2168](https://user-images.githubusercontent.com/57935060/69676065-16466c00-10f4-11ea-8f87-aad21a636057.jpg)

**Comment by kinektech-au** [comment]
My config looks like this: 

        {
            "platform": "SamsungTizen",
            "devices": [
                {
                    "name": "Samsung Smart TV",
                    "ip": "192.168.1.xxx",
                    "mac": "d0:03:df:fb:ae:xx",
                    "switches": [
                        {
                            "name": "Netflix",
                            "app": "11101200001"
                        },
                        {
                            "name": "Youtube",
                            "app": "111299001912"
                        },
                        {
                            "name": "Prime Video",
                            "app": "3201512006785"
                        }
                    ]
                }
            ]
        },

**Comment by kinektech-au** [comment]
I was hoping they would appear in this space? If not, what is this space typically used for?

![IMG_B4EAE009D982-1](https://user-images.githubusercontent.com/57935060/69676625-3cb8d700-10f5-11ea-8cde-a3c3b304fde3.jpeg)

**Comment by tavicu** [comment]
In that space will be displayed the “inputs”

You can choose in the setting to show as separate tiles, then every switch will be idependent of the main tv!

Please read the wiki how to configure every setting of the plugin

**Comment by kinektech-au** [comment]
Brilliant thank you! Now I understand :) Working perfectly now
