### ISSUE TITLE
Disney+ (Or any other App ID)

### ISSUE THREAD

**Issue by kinektech-au** [tavicu/homebridge-samsung-tizen#161]
Is there any way to add Disney+ (or how to find the App IDs for other installed apps) to the App list?

**Comment by tavicu** [comment]
Did you read the wiki? https://github.com/tavicu/homebridge-samsung-tizen/wiki/Applications

**Comment by kinektech-au** [comment]
Sorry I'm completely new to Homebridge! I am unsure how to "start the homebridge server with tizen-apps as parameter (homebridge tizen-apps) " - as in, I don't know what to do with that information? 

Where do I place that parameter and is there any examples to follow?

**Comment by kinektech-au** [comment]
Figured it out! So simple .. (sorry, it's late here!)  

For reference in case anyone else is looking for additional App IDs: 

The following have been taken from an Australian model 2019 Samsung Super AMOLED with built-in Apple TV

3201807016597 - Apple TV
11101200001 - Netflix
org.tizen.browser - Internet
111299001912 - YouTube
3201512006785 - Prime Video
3201601007250 - Google Play Movies
3201710015037 - Gallery
3201704012147 - 10 play
3201901017640 - Disney+
3201812017479 - ABC iview
3201901017758 - DocPlay
11101000407 - Telstra TV Box Office
3201607010031 - 9Now
3201803015934 - 7plus
3201606009798 - Stan
3201710015016 - SmartThings
3201904018182 - Garage Movies
3201808016819 - AnimeLab
3201611010983 - YouTube Kids
