### ISSUE TITLE
Can't connent to the bridge on HomeKit app

### ISSUE THREAD

**Issue by mipruch** [tavicu/homebridge-samsung-tizen#162]
Hey, when I install the plugin, copy and fill the "platform" code to the /.homebridge/config.json and start the homebridge, although I get the pop-up window on TV screen, whether it may connect to the Living Room TV (name of the platform), I don't see the bridge in the mobile app after I click the "I don't have a code or cannot scan".

Also, when I start the homebridge, I get these errors. But I don't think it may do something with my problem. Thank you for help.

[11/28/2019, 7:27:40 PM] Homebridge is running on port 51827.
(node:6060) UnhandledPromiseRejectionWarning: TypeError: this.api.publishExternalAccessories is not a function
    at SamsungPlatform.init (/Users/michal/.npm-global/lib/node_modules/homebridge-samsung-tizen/index.js:59:22)
(node:6060) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6060) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tavicu** [comment]
Hi,

Update your Homebridge to the latest version!
