### ISSUE TITLE
Cannot add accessory in Home

### ISSUE THREAD

**Issue by ekingme** [tavicu/homebridge-samsung-tizen#163]
I'm also having an issue getting the platform added with in the Home app.  I've added a UUID, deleted the accessory cache and persist files, updated home bridge to latest, enabled full debug.  Watching the debug output when adding the accessory doesn't display any output at all.

During setup, I did receive the request to allow the remote on the TV and have allowed it.

Home sees the accessory, allows me to enter the pin, but then just hangs on the "Adding" step and eventually says it is unable to add the accessory.

I have other accessories in Homebridge working without an issue (homebridge-harmony, for example) so I know Homekit can talk to Homebridge, just can't seem to add this new platform/accessory.

nodejs-8.12.0-1.fc28.armv7hl
iOS 13.2.3
npm list -g --depth 0 | grep homebridge
├── homebridge@0.4.50
├── homebridge-samsung-tizen@4.2.0

Pertinent debug info during startup of Homebridge:
  EventedHTTPServer Server listening on port 43383 +264ms
[2019-12-4 12:36:08] SamsungTV is running on port 43383.
[2019-12-4 12:36:08] Please add [SamsungTV] manually in Home app. Setup Code: XXX-XX-XXX

**Comment by rofranzoi** [comment]
Same problem here...

**Comment by LandoT7** [comment]
I can’t even get my TV to show up in the home app on iOS 13.3.1 beta. Tried adding uuid with no luck. All my files are up to date. I have a 2018 Q65F so it should be showing up I would think.

**Comment by hirnschallsebastian** [comment]
I have the same issue.

**Comment by scoobaspeaz** [comment]
Try this fix.  I was having the same issue and adding the UUID fixed the problem for me. 

https://github.com/tavicu/homebridge-samsung-tizen/issues/117#issuecomment-502435485

**Comment by tavicu** [comment]
Do you see something like this in the console when you start the Homebridge server?

```
[12/25/2019, 12:18:26 PM] Bedroom TV is running on port 51510.
[12/25/2019, 12:18:26 PM] Please add [Bedroom TV] manually in Home app. Setup Code: xxx-xx-xxx
```

**Comment by mrMiimo** [comment]
> Try this fix. I was having the same issue and adding the UUID fixed the problem for me.
> 
> [#117 (comment)](https://github.com/tavicu/homebridge-samsung-tizen/issues/117#issuecomment-502435485)

I was delete the accessory, then change the MAC address and then add again... and its works for me

**Comment by hirnschallsebastian** [comment]
> Do you see something like this in the console when you start the Homebridge server?
> 
> ```
> [12/25/2019, 12:18:26 PM] Bedroom TV is running on port 51510.
> [12/25/2019, 12:18:26 PM] Please add [Bedroom TV] manually in Home app. Setup Code: xxx-xx-xxx
> ```

Yes I get 
Dec 28 12:11:39 homebridge node[17223]: [12/28/2019, 12:11:39 PM] Fernseher is running on port 46049.    
Dec 28 12:11:39 homebridge node[17223]: [12/28/2019, 12:11:39 PM] Please add [Fernseher] manually in Home app. Setup Code: xxxxxxxx

I have already tried adding a uuid but I still cannot add the tv in home app. This is my config

`{
            "platform": "SamsungTizen",
            "devices": [
            {
                "name": "Fernseher",
                "ip": "xxxx",
                "mac": "xxxx",
                "uuid": "20da6722-0a02-47a8-afee-c4a80b360113"
            }
            ]
        }`

**Comment by mikelito80** [comment]
I can´t add the accessory to home app. The tv does nor pop up the pairing message.
Before i got it working, but I upgrades to hoops 3 and the system cracked , so i deleted everything, and now it doesn't work anymore.
Thank you

**Comment by tavicu** [comment]
Try the `uuid` method from above. More than that i'm sorry but i cannot do! It's not regarding the plugin, but how Homebridge and Home App connects.
