### ISSUE TITLE
Whenever I need to edit  a switch it gets confused and loses detail.

### ISSUE THREAD

**Issue by Subivan1** [tavicu/homebridge-samsung-tizen#164]
Whenever I try to edit a switch in home app, to change name or to stop it being favourite. It appears to get confused over it's name. 
![image](https://user-images.githubusercontent.com/44292198/71109938-38488100-21be-11ea-915a-dc25948044ad.png)
4th tile shows TV enter 

![image](https://user-images.githubusercontent.com/44292198/71109995-56ae7c80-21be-11ea-8316-535c2fbe8cb6.png)

change the tile to be not favourite

![image](https://user-images.githubusercontent.com/44292198/71110045-6f1e9700-21be-11ea-963c-2a951c68a008.png)

Tile loses it's name and only shows as TV.
![image](https://user-images.githubusercontent.com/44292198/71110324-f5d37400-21be-11ea-845f-85ed7f718ed6.png)

if you edit it again, the switch name (middle) can be edited, it appears to change the top name, if you press enter the name at the top seems OK, but reverts to the original on the middle field. When you leave the edit function, the switch retains none of the detail and just shows as TV again. 
![image](https://user-images.githubusercontent.com/44292198/71110389-156a9c80-21bf-11ea-9b48-a8447ce573c5.png)

This doesn't appear to happen to any other switches I have and it can be cleared by removing the switches from homebridge restarting, then putting them back and restarting again.

I am fairly sure this only started happening after the last set of updates, but I don't know exactly when it happened. I only noticed after I went in to tidy up by home app because I had too many favourites....

This is a nuisance rather than a real problem, and may well be something I have done,  but If anyone  can point out how to stop this happening, please let me know.

**Comment by tavicu** [comment]
Hei! Sorry but that's Apple's kitchen! Nothing to do with the plugin or Homebridge at all!

**Comment by Subivan1** [comment]
But, it only happens on the switches created in this plugin. Not any other homebridge plug in or Apple switches.
