### ISSUE TITLE
Cannot power on TV

### ISSUE THREAD

**Issue by mgmellia** [tavicu/homebridge-samsung-tizen#165]
I installed this plugin and everything works flawlessly - except that I cannot power-on the tv.
If I got it correctly, the power on is based on the WoL protocol. 
I checked if I could see the magic packet with Wireshark, but I was not able to spot it :(

I also checked with etherwake and wakeonlan linux commands. With etherwake I wasn't able to turn on the tv. Instead, wakeonlan works. The former sends ethernet WoL packets, while the latter sends UDP WoL packets (to the broadcast address). May be this could help to solve the problem.

**Comment by tavicu** [comment]
You seems to be the only one that has this problem! Are you sure it's not blocked by your firewall or router?

**Comment by mgmellia** [comment]
I did some more troubleshooting.

- From the command line - etherwake works if I explicitly state the wifi interface:
`sudo etherwake fc:3:9f:aa:52:fc -i wlan0` works
With this - I can see the WoL packet in the pcap trace and the TV gets on regularly. Without the -i wlan0 flag - there is no WoL packet sent - and the tv (obviously) remains off

- With Homebridge - I was never able to see a single WoL packet being sent through the wlan0 interface. Instead, I keep seeing ARP requests - where the PI is looking for the Mac address of the samsung TV. Since the TV is off - no reply ever come back.

Once the TV is on - then the ARP request gets the response, and some TCP flows (encrypted) to port 8001 and 8002 are visible.
For as long as the MAC address is in the arp tables, then I can turn the tv on and off from the home.app (on any device) as expected. Still - I cannot spot WoL packets here, but just the TCP flows to port 8001 and 8002
But as long as the ARP tables are purged, then I cannot turn the tv on anymore.

I can attach the pcap files if useful.

**Comment by mgmellia** [comment]
adding also what the debug shows in the Homebridge log

```
Accessory [Samsung TV] Processing characteristic set: [{"aid":1,"iid":10,"value":1}] +8ms
Accessory [Samsung TV] Setting Characteristic "Active" to value 1 +3ms
[2019-12-27 13:52:16] [Samsung TV] Failed to power on the TV
[2019-12-27 13:52:16] [Samsung TV] [DEBUG] WoLFailedError: Failed to power on the TV
    at wol.then.catch (/opt/node/lib/node_modules/homebridge-samsung-tizen/lib/remote.js:228:20)
    at <anonymous>
Accessory [Samsung TV] Error setting Characteristic "Active" to value 1:  Failed to power on the TV +316ms
```

**Comment by mgmellia** [comment]
solved - in the config file I has the MAC address with a single digit ":3:" instead of ":03:"
I would say the wakeonlan library is not the most robust one from this point of view 👎 

Anyway - now Homebridge/samsung-tizen is sending the WoL packets correctly.
Just my samsung tv is quite deaf and it does not wake up always to the WoL packets (this happens also with the command line tools - that's why those were inconsistent afaik)
