### ISSUE TITLE
PIn does not appear on the TV

### ISSUE THREAD

**Issue by WimBre** [tavicu/homebridge-samsung-tizen#166]
Hi Tavicu,

First of all, thank you for your time invested in this plugin.

Using the link, the page returns information regarding my TV (Samsung UE48JU7000).

I have installed the plugin on my raspberry pi 3 without any problems. When I start homebridge I get no error messages. I thought after starting up homebidge a PIN code would appear on my TV but that doesn't happen.

Can I do that manually?

**Comment by tavicu** [comment]
Hi! I'm sorry but looks like the plugin is not compatible with your TV!
