### ISSUE TITLE
No support for KEY_HDMI1, KEY_HDMI2 ?

### ISSUE THREAD

**Issue by poshwaffle** [tavicu/homebridge-samsung-tizen#167]
I've read through the other issues regarding this and I can see `KEY_HDMI` is supported, but not sure why HDMI this is choosing. However, when looking into this more there should seem to be a way to use different HDMI ports using these keys, see below.

https://toxblh.github.io/samsung-tv-control/enums/_keys_.keys.html#key_hdmi

Is this something that can be supported as I've tried already using:

~~~json
 {
                    "name": "PlayStation",
                    "type": "command",
                    "value": [
                        "KEY_HDMI1"
                    ]
                }
~~~

But this doesn't work and would be awesome if it could.

**Comment by tavicu** [comment]
Please use the search: https://github.com/tavicu/homebridge-samsung-tizen/issues?utf8=✓&q=is%3Aissue+is%3Aclosed+HDMI1+
