### ISSUE TITLE
Alternate method to switch to apps that don't work (like Apple TV App)

### ISSUE THREAD

**Issue by apexad** [tavicu/homebridge-samsung-tizen#168]
This is related to #100 
See https://github.com/nicholasrobinson/homebridge-cmd4-samsung-tizen-appletv
Why does this script work and the plugin is unable to switch to the Apple TV app?

**Comment by tavicu** [comment]
Just bought a new TV that should have the Apple TV app! I will take a look tonight and see if the parameters are different than other apps.

**Comment by tavicu** [comment]
I have checked and in my country i don't have the "Apple TV" app ... 

Someone that has this installed needs to run the plugin in debug mode and post here the console output so i can see what informations are for that app.

**Comment by apexad** [comment]
There is no error or anything, it just does not switch over when using an input or switch generated by this plugin.

**Comment by tavicu** [comment]
Yeah! Every app has a "type" that need to be passed when the command to switch is sent.
I think the problem is because the type that Apple TV app has is different that what is set right now.

**Comment by tavicu** [comment]
That SH script is sending a POST request to the TV.
My plugin works on different protocol.

Before i implement the same method as https://github.com/nicholasrobinson/homebridge-cmd4-samsung-tizen-appletv, i need to make sure it can't work over the method i already use

**Comment by apexad** [comment]
{
  appId: '3201807016597',
  app_type: 1,
  icon: '/opt/share/webappservice/apps_icon/FirstScreen/3201807016597/250x250.png',
  is_lock: 0,
  name: 'Apple TV'
}

**Comment by apexad** [comment]
To follow up,  if I change this line:
https://github.com/tavicu/homebridge-samsung-tizen/blob/master/lib/methods/ws.js#L65

from:
```javascript
action_type : application.app_type == 2 ? 'DEEP_LINK' : 'NATIVE_LAUNCH',
```
to:
```javascript
action_type : 'DEEP_LINK',
```
...it works as in the Apple TV Input switched to the Apple TV App

**Comment by tavicu** [comment]
Samsung and it's Developers ...

I will take a look and make the changes today!

**Comment by apexad** [comment]
I made a PR: https://github.com/tavicu/homebridge-samsung-tizen/pull/185

**Comment by tavicu** [comment]
Cool but i have to look because i remember it's an app that doesn't open with DEEP_LINK and needs NATIVE_LAUNCH.

**Comment by tavicu** [comment]
I will test it and i think i'm gonna switch to the POST method if it works with all apps!
