### ISSUE TITLE
Add more options

### ISSUE THREAD

**Issue by KowlinMC** [tavicu/homebridge-samsung-tizen#169]
Would it be possible to add options to change sources, volume, channel, etc?

**Comment by Reeon89** [comment]
"switches": [
                       {"name": "Mute",      "mute": true},
                       {"name": "Vol UP", "command": "KEY_VOLUP"},
                       {"name": "Change Source", "command": "KEY_SOURCE"}         
                    ]

try it out

**Comment by apexad** [comment]
The issue with volume is that as far as I understand it, there is no way to get the current volume.  So, as mentioned by @Reeon89, you can have 'toggle' buttons but not an actual slider or anything like that.

**Comment by tavicu** [comment]
Please read the Wiki! You can find all the informations over there!

https://github.com/tavicu/homebridge-samsung-tizen/wiki
