### ISSUE TITLE
can add to bridge and HomeKit but no actions possible

### ISSUE THREAD

**Issue by PedroRA561** [tavicu/homebridge-samsung-tizen#171]
Hello, I managed to add my tv to the bridge and afterwards to the HomeKit App.

I can see the TV status and all the properties but cannot send any actions. I have another TV with the same version ("msfVersion": "2.0.25) and works just fine.

both of them open the api url.

on the logs all I see is "xxxxxxxx TV is running on port 44233." for both TVs.

on the non-working TV there is no request for the pairing (press OK on the TV).

any ideias on how to trigger the request on the TV ? since I get all the data except send commands I would say it should work

**Comment by tavicu** [comment]
Hi! TV's should be on different ports! Make sure you have the latest version of Homebridge and also add the `ports` section in your configuration. Example: https://github.com/nfarina/homebridge/blob/master/config-sample.json
