### ISSUE TITLE
Channel and Volume not working.

### ISSUE THREAD

**Issue by larsoss** [tavicu/homebridge-samsung-tizen#173]

**Comment by larsoss** [comment]
After installed the plugin, the power on/off works. 
But not the volume or channel...

When installed the app there is asked to check the api from my tv.. included here.

`{"device":{"FrameTVSupport":"false","GamePadSupport":"true","ImeSyncedSupport":"true","OS":"Tizen","TokenAuthSupport":"true","VoiceSupport":"true","countryCode":"NL","description":"Samsung DTV RCR","developerIP":"0.0.0.0","developerMode":"0","duid":"uuid:0a203632-cb12-456d-9f81-b9326c8733ef","firmwareVersion":"Unknown","id":"uuid:0a203632-cb12-456d-9f81-b9326c8733ef","ip":"192.168.1.224","model":"17_KANTM_UHD_BASIC","modelName":"UE55MU6100","name":"[TV] Samsung 6 Series (55)","networkType":"wired","resolution":"3840x2160","smartHubAgreement":"true","type":"Samsung SmartTV","udn":"uuid:0a203632-cb12-456d-9f81-b9326c8733ef","wifiMac":"******"},"id":"uuid:0a203632-cb12-456d-9f81-b9326c8733ef","isSupport":"{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"false\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n","name":"[TV] Samsung 6 Series (55)","remote":"1.0","type":"Samsung SmartTV","uri":"http://192.168.1.224:8001/api/v2/","version":"2.0.25"}`

But i can't get the rest working.. I have tried to get the logs files but the online thing i see in my logs is google

**Comment by etienne-martin** [comment]
```
{
  "device": {
    "FrameTVSupport": "false",
    "GamePadSupport": "true",
    "ImeSyncedSupport": "true",
    "OS": "Tizen",
    "TokenAuthSupport": "true",
    "VoiceSupport": "true",
    "countryCode": "NL",
    "description": "Samsung DTV RCR",
    "developerIP": "0.0.0.0",
    "developerMode": "0",
    "duid": "uuid:0a203632-cb12-456d-9f81-b9326c8733ef",
    "firmwareVersion": "Unknown",
    "id": "uuid:0a203632-cb12-456d-9f81-b9326c8733ef",
    "ip": "192.168.1.224",
    "model": "17_KANTM_UHD_BASIC",
    "modelName": "UE55MU6100",
    "name": "[TV] Samsung 6 Series (55)",
    "networkType": "wired",
    "resolution": "3840x2160",
    "smartHubAgreement": "true",
    "type": "Samsung SmartTV",
    "udn": "uuid:0a203632-cb12-456d-9f81-b9326c8733ef",
    "wifiMac": "******"
  },
  "id": "uuid:0a203632-cb12-456d-9f81-b9326c8733ef",
  "isSupport": "{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"false\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n",
  "name": "[TV] Samsung 6 Series (55)",
  "remote": "1.0",
  "type": "Samsung SmartTV",
  "uri": "http://192.168.1.224:8001/api/v2/",
  "version": "2.0.25"
}
```

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/wiki

https://github.com/tavicu/homebridge-samsung-tizen/issues?utf8=✓&q=is%3Aissue+is%3Aclosed+volume

**Comment by etienne-martin** [comment]
Thank you @tavicu, didn't know there was a wiki

**Comment by larsoss** [comment]
Thanks for the Wiki. Only i don't have any knowledge of JSON.
