### ISSUE TITLE
Speaker output

### ISSUE THREAD

**Issue by kwoxford** [tavicu/homebridge-samsung-tizen#174]
I'd like to output sound from my new Samsung TV to my Apple HomePod. On my previous Sony TV the HomePod showed up as an Airplay accessory but not on this TV. I see that the plugin handles inputs but doesn't seem to handle outputs. Any suggestions?

Also, is there any way of interrogating the TV to find a list of commands?

**Comment by tavicu** [comment]
Hi. Samsung API doesn't provide informations about the TV settings.

So this is not possible.
