### ISSUE TITLE
New question. 

### ISSUE THREAD

**Issue by larsoss** [tavicu/homebridge-samsung-tizen#175]
As you can see i ad the code. 
And the command use Netflix Works. 

Only its a switch. And Its not a group (or more things) when i push on samsung tv. 

Do you know why?
![0DAE85FB-2064-4FBD-A2DF-E0727F07DBA4](https://user-images.githubusercontent.com/3639942/73785310-56326b00-4797-11ea-8b9a-d3bb0ccfaf7b.png)
![3A9BAF01-2D18-409D-8668-4ADCD568168C](https://user-images.githubusercontent.com/3639942/73785311-56326b00-4797-11ea-96af-181aefb46f93.png)

**Comment by tavicu** [comment]
Hi! The plugin is developed for Home App, not Google. Some of the features may not be available there or same as in HomeKit
