### ISSUE TITLE
Can't get it to start the pairing proces

### ISSUE THREAD

**Issue by WibiNorg** [tavicu/homebridge-samsung-tizen#176]
Hey there,

REAL CODING-NOOB HERE. :')

I really can't seem to start the pairing-proces with my Samsung QE49Q6FNA.
I've installed the plugin with Hoobs and edited the code like this (mac slightly edited):
```
    "platforms": [
         {
            "platform": "SamsungTizen",
            "devices": [
                {
                    "name": "Samsung TV",
                    "ip": "192.168.68.102",
                    "mac": "70:2a:d5:2b:3c"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-samsung-tizen"
            }
        },

```

The log shows up like this:

```
[Homebridge] [2/5/2020, 6:35:12 AM] [SamsungTizen] Initializing SamsungTizen platform...
[Homebridge] [2/5/2020, 6:35:12 AM] Loading 0 accessories...
[Homebridge] [2/5/2020, 6:35:12 AM] API launched
[Homebridge] [2/5/2020, 6:35:12 AM] [Samsung TV] is running on port 43885.
```
After this nothing happens, and I can't get it to show the pairing-popup to my tv.

Any thoughts?

**Comment by tavicu** [comment]
You sure the IP is correct and that the homebridge server is in the same network as TV? You also have to set a static IP for your TV since this can change with every power cycle!

Then, **AS THE WIKI SAY**: Start Homebridge in debug mode with `DEBUG=* homebridge -D` command and add the logs that are related to this plugin.

**Comment by WibiNorg** [comment]
Sorry for all this noob stuff:

I've now set a static IP for my TV, code still looks the same other than the IP now has changed to that static IP I set manually. I've now connected the Raspberry Pi through WiFi, making sure it get's connected to the same main-mesh-wifi-router as the Samsung TV is connected to.  

> Then, AS THE WIKI SAY: Start Homebridge in debug mode with `DEBUG=* homebridge -D` command and add the logs that are related to this plugin.

I can't start this with Hoobs, but I can start `hoobs -d` which results in this: 
```
Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1306:16)
    at listenInCluster (net.js:1354:12)
    at Server.listen (net.js:1442:7)
    at Function.serverListen [as listen] (/home/hoobs/.hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/home/hoobs/.hoobs/lib/api.js:157:17)
    at module.exports (/home/hoobs/.hoobs/lib/cli.js:164:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

Not so sure what to do know. Tried to follow every step in the Wiki, and Hoobs should even make this easier for noobs like me, but no luck so far.

**Comment by WibiNorg** [comment]
UPDATE:
I don't know exactly what I did, (restore TV to factory defaults, re-install hoobs, re-install the tizen-plugin) but somehow it now works, whoop! 😄
