### ISSUE TITLE
Doesn't work after new iOS beta 13.4

### ISSUE THREAD

**Issue by JonoHaysom** [tavicu/homebridge-samsung-tizen#177]
not sure if there are substantial HomeKit changes in iOS 13.4 beta but it doesn't seem to be working any more, can someone confirm so its not isolated?

also: (node:12938) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version. <-- incase this crops up.

**Comment by kutdenis** [comment]
I confirm that the plugin stopped working with the update to 13.4.

**Comment by tavicu** [comment]
Any news with the latest updates?

In the Apple changelog nothing has changed regarding the TV in HomeKit.

Also i don't have a testing device so i can see :)

**Comment by mszf** [comment]
Must be something else, I'm using it with all betas of 13.4 on Hoobs without any problems including latest  13.4 GM

**Comment by apexad** [comment]
iOS 13.4 out today and I see no issues.
