### ISSUE TITLE
Assigning a port 

### ISSUE THREAD

**Issue by scoobaspeaz** [tavicu/homebridge-samsung-tizen#178]
I am trying to setup firewall rules and I notice each time homebridge restarts that there is a new port specified for the TV. Is there a way to assign a port for this to use each time? This would enable me to setup a firewall rule for access to just that port.

**Comment by tavicu** [comment]
Hi.

You can set a range then allow it in firewall. Example: https://github.com/nfarina/homebridge/blob/master/config-sample.json
