### ISSUE TITLE
How does this work exactly?

### ISSUE THREAD

**Issue by scoobaspeaz** [tavicu/homebridge-samsung-tizen#180]
I am trying to figure out a way to make this work across subnets. In order to troubleshoot how to get this to work I need to understand how the plugin works :)

So far I understand that the plugin uses WoL to wake up the TV. For that I have found I can wake up the TV from a linux server thats on the same subnet as the TV. However once its woken up the plugin still doesnt issue whatever is needed to turn it off. The plugin does, however, monitor the TV to see if its on or off still even from the other subnet. 

So what I think I understand about this plugin so far is below:
1. Plugin uses wake on lan to wake up the tv
2. Plugin uses ping to periodically check to see if the TV responds. Depending on if it gets a response or not the plugin will show the TV as on or off.

What I dont know is how does the plugin shut off the TV?

**Comment by tavicu** [comment]
Sorry for the late response.

The plugin connects to a websocket that Tizen has and send commands.

https://github.com/tavicu/homebridge-samsung-tizen/blob/master/lib/methods/ws.js
