### ISSUE TITLE
Cant control tv in Homebridge web page but not showing up in homekit annymore

### ISSUE THREAD

**Issue by Job-Hoogeboom** [tavicu/homebridge-samsung-tizen#181]
Hi, I have my Samsung series 6 (43) connected to homebridge,  it showed up in homekit immediately. I later added some inputs in the config file and deleted the television from homekit.  I rebooted both the homebridge server and my phone. I can still control it on the homebridge webpage but my homekit app can't find the television anymore.

I also tried to delete the plugin and reinstalling it again but that didn't help either.

**Comment by anvial** [comment]
Have the same problem. Any suggestions?

**Comment by Job-Hoogeboom** [comment]
> Have the same problem. Any suggestions?

I clicked on the following button, make sure to backup your config and when it’s done paste the config back in the homebridge

![4D922084-EFA1-456D-83B8-C783671A1A34](https://user-images.githubusercontent.com/61543367/76708568-ff09a980-66f7-11ea-95ba-1aaf1348cb99.jpeg)

**Comment by luixiuno** [comment]
Uh.. I don’t know what ya talking about I don’t see me participating on
that issue

**Comment by anvial** [comment]
My solution:
1. go to logs (I use syslog).
2. find the message from homibridge-samsung-tizen, that I need to add TV manually.
3. Do manually "add accessory" procedure in homekit-app (using 8-digit code for homedridge).
4. Find TV in homekit-app, and use it normally.

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/wiki

Also: https://github.com/tavicu/homebridge-samsung-tizen/issues/117#issuecomment-502435485
