### ISSUE TITLE
Not asking for PIN or code

### ISSUE THREAD

**Issue by luixiuno** [tavicu/homebridge-samsung-tizen#182]
I got a Samsung TV 2015 and it has TIZEN and I put the Mac and the ip, But !It Wont Turn On OR Turn Off.

Model Posting soon

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/wiki

Make sure your TV is compatible.
Make sure your TV is on the same network.
Make sure your Router is not blocking traffic.

Make sure you give us more info so we can help you!

**Comment by luixiuno** [comment]
My tv model is a Samsung tizen UN55J6300
