### ISSUE TITLE
Failed to Ask for Approval Across Networks

### ISSUE THREAD

**Issue by ntableman** [tavicu/homebridge-samsung-tizen#184]
I have my homebridge on a different network than the TV, I can WOMP the TV fine, so I know these ARPs are going across the network, but it looks like your config assumes the IP of the TV is also the WOMP address, this is not the case in my setup (and most any multi net).

Any thoughts on how we can separate these 2 IPS out?

**Comment by ntableman** [comment]
seems the lib you are using takes in the right params - I need to pass in my broadcast 192.168.10.251 and the mac for my TV. I think I can modify the code to make it work...

**Comment by tavicu** [comment]
Hi.

The plugin connects on a websocket that TV has.
So in order to make it work, the homebridge server needs to connect to the ip you input in the config file. 

Theoretically the TV can be in another country but the IP of the TV must be public and ports opened.

**Comment by tavicu** [comment]
Hi! This will be implemented. Please follow https://github.com/tavicu/homebridge-samsung-tizen/issues/196
