### ISSUE TITLE
Keys

### ISSUE THREAD

**Issue by mhartung87** [tavicu/homebridge-samsung-tizen#187]
When I add Keys to the config. Looks like they are not showing up .

**Comment by apexad** [comment]
The `keys` block in the config is used to re-map the keys used by the remote (which in iOS is accessible in control center). The remote will not appear different, but with each function press it will perform a different action than the default.

 It won't add any new keys or change anything within the Home app/HomeKit. You may instead want to use the `switch` block which will add switches to the Home app/HomeKit.

**Comment by mhartung87** [comment]
Sorry I guess am confused. So the keys arent like a left right key to press etc? You mean the switch button will perform a different action

**Comment by apexad** [comment]
If you bring up Control Center, there is a Remote Icon:
![003-control-apple-tv-with-ios-control-center-4154515-4babbe3ea7d141ebb188e0c5c74b3140](https://user-images.githubusercontent.com/1437332/77113695-83a24380-69e8-11ea-895d-dc9d820de94d.jpg)
Selecting your TV at the top of the screen brings up this remote:
![qe9kb212v7441](https://user-images.githubusercontent.com/1437332/77113554-4b026a00-69e8-11ea-8a5a-8576bcbc806d.jpg)
No buttons can be added to this remote, you can just change their function.  This is what the `keys` block is used to do.The `switches` block adds switches the Home app/Home Kit.

**Comment by mhartung87** [comment]
Ah Gotca! makes sense. So I can only change the back, play/pause etc to something else. Is there a way to have this in the Home APP to control the TV this way instead a switch for every button?

**Comment by apexad** [comment]
Natively in HomeKit in a good way anything close to what is in control center? No.

The TV Icon in HomeKit will only have the Power button and Inputs. You can add commands as inputs and put everything there, but it makes for a odd experience there.

Also note, when the Remote is active, you use your phone's volume buttons to control the TV volume.

**Comment by mhartung87** [comment]
Yeah I noticed it a little weird every here is a switch for every button. Is there a way to change the button type for the switch?

**Comment by apexad** [comment]
There is no way to change the button type for a switch.

**Comment by apexad** [comment]
I assume this issue can be closed.
