### ISSUE TITLE
Old look of HomeKit layout

### ISSUE THREAD

**Issue by jonasborneland** [tavicu/homebridge-samsung-tizen#188]
Hi Tavicu. I really appricate the work you done on this. Works great! But after I installed it, I thought it would look like the screenshots here: https://9to5mac.com/2019/01/31/homekit-tv-home-app-ios-12-2/

But looks more like an old version of the homkit tv features ? 

I also don't see the TV in the apple remote app?

**Comment by apexad** [comment]
You need to check the Wiki and be sure you are adding imports. Otherwise, the Apple Remote app is now built into iOS and accessed through the control panel.

**Comment by apexad** [comment]
I think the look of the TV object in the Home app changed in iOS 13 too actually so that article showing iOS 12 is out of date possibly.

**Comment by jonasborneland** [comment]
Thanks! It made the Remote work 😊
