### ISSUE TITLE
Charge status in homebridge via remote

### ISSUE THREAD

**Issue by marithpl** [tavicu/homebridge-samsung-tizen#19]
Hi!

Is there any way to charge status of tv When I turn it on via TV Remote?

I wish to make automation When i turn on TV to also turn on led strip. 

Now when I turn it on I need to manually refresh HomeKit

**Comment by tavicu** [comment]
Hi, unfortunately the samsung api don't have this option.

The only possible way is to make some changes and check the TV status every second. Which will still have some delay. And also comes with a very bad performance :)

**Comment by tavicu** [comment]
Hi, i decided to open this issue to make a small announcement!

I just released a new version that will update the switch status in real time!
But this is off by default. You will have to turn it on.

You can read more here: https://github.com/tavicu/homebridge-samsung-tizen#update-in-real-time-on-the-background

**Comment by marithpl** [comment]
Thank you bro! Also for Apps!
