### ISSUE TITLE
problema con el plugin

### ISSUE THREAD

**Issue by rafamaren** [tavicu/homebridge-samsung-tizen#190]
![image2](https://user-images.githubusercontent.com/57326996/77898540-971c9c80-727b-11ea-9d78-b55555b93e70.jpeg)
![image5](https://user-images.githubusercontent.com/57326996/77898542-97b53300-727b-11ea-814d-6c44b025e34d.jpeg)
![thumbnail_image1](https://user-images.githubusercontent.com/57326996/77898546-984dc980-727b-11ea-8e30-5ce5c81b79b5.jpg)
![thumbnail_image3](https://user-images.githubusercontent.com/57326996/77898547-98e66000-727b-11ea-9a95-26e6c9dfe2e5.jpg)
![thumbnail_image4](https://user-images.githubusercontent.com/57326996/77898548-98e66000-727b-11ea-8bf2-39b7afbbf2b9.jpg)
![thumbnail_image6](https://user-images.githubusercontent.com/57326996/77898549-997ef680-727b-11ea-8178-7d11f5ac6b78.jpg)

**Comment by rafamaren** [comment]
hola, me carga el plugin, me detecta la tv, y me lo hace todo bien. Pero al pulsar sobre la tv para encender o apagar desde homekit me da error y en el log de homebrigde me da tambien error. La tele es compatible con el plugin,ya que he hecho lo de poner la ip, tal y como dice los pasos de instalacion.Que error puedo estar teniendo?

**Comment by rafamaren** [comment]
Alguien que me pueda ayudar?

**Comment by josehipo** [comment]
Tu TV es 48H6400? 
Si es así, olvídate. Los modelos H y J no son compatibles con el plugin.
Los modelos de 2014 (H) y 2015 (J) utilizan un método de emparejamiento con PIN, que no es compatible.

**Comment by tavicu** [comment]
Hi. Your TV is not compatible with this plugin.
