### ISSUE TITLE
DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.

### ISSUE THREAD

**Issue by roe1974** [tavicu/homebridge-samsung-tizen#193]
Hi

Just installed the pugin .... works perfect for Samsung QE43Q60R and QE55Q60R.
But ist this Warning in log normal ?

DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.

thx, Richard

**Comment by tavicu** [comment]
The error appears only when you activate this plugin?
I'm asking you because it has nothing to do with how the plugin works.

Also, i'm on the latest versions and i don't have this warning

**Comment by roe1974** [comment]
it comes first time power on one of the two TVs.
But the message comes only one time in the log.
Full Warning:
(node:8373) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
Using node 12.16.2

Richard

**Comment by roe1974** [comment]
in #177 there is another user that reported this log entry also ..... Richard

**Comment by tavicu** [comment]
Can you confirm that once you deactivate this plugin (only this plugin) the error disappear from the logs?

**Comment by roe1974** [comment]
yes, because your plug-in is the only one in this instance ... i use one homebridge-instance per plug-in...
the log appears after the first comand (on or off...) ... for one time ....

richard

**Comment by tavicu** [comment]
Found the problem and pushed an update.

I will not release a new version yet since it's just a warning and don't affect anything!

Thank you!
