### ISSUE TITLE
Add support for different broadcast address

### ISSUE THREAD

**Issue by dhutchison** [tavicu/homebridge-samsung-tizen#196]
I was about to add this as a comment to #184, as the comments (but not the title) sound like this issue I was about to open for discussion. 

I currently have this plugin running in Homebridge in Docker, without host networking (through some scripted Avahi setup). This plugin works great in this setup (thanks), with the exception of turning the TV on. I know this is because the Wake-on-Lan packets are being sent to the default broadcast address (255.255.255.255) and so are not being routed to the subnet the TV is located in. There is no way to customise this through this plugin, but the underlying wakeonlan library this plugin uses supports the feature. 

I have a pretty good idea how this could be implemented, but I've never done any Homebridge plugin development. 

I think this would require:
* an extra, optional, configuration property for the broadcast address for the accessory (I'm not sure where this would go in the code)
* changing the _turnOn method of remote.js, so when it calls the wol function it passes in an options object with the `address` property set to the broadcast address from the configuration (if defined)

**Comment by tavicu** [comment]
Hi! I will implement it today and release it!

**Comment by tavicu** [comment]
Hi! I have pushed a new version. Example of config:
```
{
    "name": "Bedroom TV",
    "ip": "10.20.30.40",
    "mac": "A0:B1:C2:D3:E4:F5",
    "wol": {
        "address": "255.255.255.255"
    }
}
```
