### ISSUE TITLE
Switch ... no name below the switch ?!?!?

### ISSUE THREAD

**Issue by roe1974** [tavicu/homebridge-samsung-tizen#198]
Hi
I added a switch today to my TV (for sleep) ... why there is no name printed below the switch ?
paramter in config.json is:

"switches": [
       {"name": "Sleep", "sleep": 15}
                  ],

looks like:
![IMG_6214](https://user-images.githubusercontent.com/30420568/79201378-4474e000-7e38-11ea-9cb5-d37f25182a46.PNG)

br, Richard

**Comment by tavicu** [comment]
Hi! That's how HomeKit display them. Unfortunately there is nothing you can do!

**Comment by roe1974** [comment]
@tavicu 
as you see in #160 there are names/descriptions below the switch ?!?!
Richard

**Comment by tavicu** [comment]
It's possible that the names will appear when you have multiple switches!
Unfortunately i don't know how Apple decided and when to show the names under the switches.

In #160 they where not switches, but inputs that did not propagated yet to appear in the inputs dropdown.

I will take a look if there is a special setting to force showing the title but from what i know, it isn't.

**Comment by roe1974** [comment]
thx for answer & investigating :-)
Richard
