### ISSUE TITLE
Support for QN82Q80RAFXZA?

### ISSUE THREAD

**Issue by ntableman** [tavicu/homebridge-samsung-tizen#199]
Hi-

I have a brand new QN82Q80RAFXZA and it seems to just keep ignoring this plugin no matter what I do.

I can WOMP the TV manually, so I know it is on the network and such.

Any idea of how I can help debug this?

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/wiki/Common-Issues#how-to-open-a-new-issue

**Comment by ntableman** [comment]
TV is online.

Responds to the API request: http://192.168.11.11:8001/api/v2/

```
[4/14/2020, 7:25:33 AM] [LR TV] [DEBUG] { event: 'ms.channel.timeOut' }
[4/14/2020, 7:25:33 AM] [LR TV] [DEBUG] Failed to open socket {"event":"ms.channel.timeOut"}
[4/14/2020, 7:25:34 AM] [LR TV] [DEBUG] { event: 'ms.channel.timeOut' }
[4/14/2020, 7:25:34 AM] [LR TV] [DEBUG] Failed to open socket {"event":"ms.channel.timeOut"}
[4/14/2020, 7:25:34 AM] [LR TV] Failed to pair! Make sure TV is online and you click "Allow" on the popup
[4/14/2020, 7:25:34 AM] [LR TV] [DEBUG] PairFailedError: Failed to pair! Make sure TV is online and you click "Allow" on the popup
    at WebSocketSecure.pair (/homebridge/node_modules/homebridge-samsung-tizen/lib/methods/wss.js:34:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Popup never happens.

TV is set up to allow pairing requests per set up instructions.

I can WOMP the TV manually, but nothing from this plugin.

**Comment by tavicu** [comment]
- Are you sure the IP of TV is correct in the config.json file?
- The homebridge server can access the TV?

From the homebridge server, if you ping your ip tv, do you get a response?

From what you posted above, looks like the plugin can't open a socket with the TV. Because the IP is not correct, the devices are not in the same network or access is restricted by router somehow.

Or because the TV is not compatible. But since it's a newer version, i don't think that's the case here.

**Comment by ntableman** [comment]
1 - I am sure.
2 - yes if I go to the terminal in hombridge I can ping the TV and get a reply
3 - I use curl from the homebridge terminal to the API url and it works.

WOMP = wake on magic packet

Any ideas on what I can try?

**Comment by ntableman** [comment]
And this works to turn the TV on from my laptop and from homebridge terminal

wakeonlan -i 192.168.11.251 _MAC_
Sending magic packet to 192.168.11.251:9 with _MAC_

**Comment by tavicu** [comment]
Means it's not connecting to the websocket.

You could try and set the developer mode on your tv: https://wiki.samygo.tv/index.php?title=Enter_developer_mode_on_Tizen_TV%60s

Then you will be able to see the logs on the tv here: http://192.168.11.11:8001/

Once you can see the logs, start the homebridge server and see what logs do you get

**Comment by ntableman** [comment]
OK it says APPS (Develop Mode) not and I hit http://192.168.11.11:8001/ and I get


`<html><body>401</body></html>`

**Comment by tavicu** [comment]
On the developer mode in TV enter your PC ip address. And then from that PC try to access: http://192.168.11.11:8001/logs/

**Comment by ntableman** [comment]
> On the developer mode in TV enter your PC ip address. And then from that PC try to access: http://192.168.11.11:8001/logs/

```
curl http://192.168.11.11:8001/logs/
<html><body>401</body></html>

```

**Comment by tavicu** [comment]
When you access /api/v2 there is a key `developerIP`. Is the correct IP there?

Looks like your TV don't see your ip as developer and it's not allowing you to access the debugs.

**Comment by ntableman** [comment]
```

ERROR | "socket(id:b3453b8f-4a3b-44c1-b142-7d5f24e77f8) is timeout by user" | "timestamp: 1586868271550, file: RemoteChannel.cpp, func: pairingResponder : 555"
-- | -- | --
INFO | "## RemoteChannel::pairingResponder ##"
```

does that help?

**Comment by ntableman** [comment]
Any ideas on why this is happening? It still is throwing the same error.

**Comment by tavicu** [comment]
Not helping. Your IP should be just as you see it in the settings! If is shown 1.1.1.1 then that is it. Not 01.01.01.01

**Comment by ntableman** [comment]
I do not understand your reply.

I have provided the error. 

> ```
> 
> ERROR | "socket(id:b3453b8f-4a3b-44c1-b142-7d5f24e77f8) is timeout by user" | "timestamp: 1586868271550, file: RemoteChannel.cpp, func: pairingResponder : 555"
> -- | -- | --
> INFO | "## RemoteChannel::pairingResponder ##"
> ```
> 

Do you have any sense of what that error might be caused by? Seems the pairing systems on the TV doesn't understand what your plugin is sending in.

If you provide me more information on the next step of debugging, I am happy to try.

**Comment by ntableman** [comment]
closing...the issue is that the WOMP subnet needs to be included in the config and the API is different on this TV it would seem.
