### ISSUE TITLE
Home App shows State Off but is shut On

### ISSUE THREAD

**Issue by DerDirsch** [tavicu/homebridge-samsung-tizen#200]
My home app shows that the TV is switched Off but actually it is turned ON. 

Is there a remedy?
Regards

**Comment by forresthamilton** [comment]
I'm assuming you have already tried but try closing the HK app and reopening. It might just need a refresh.

**Comment by asinger720** [comment]
Same issue as @DerDirsch .  TV is on but Home app says its off.  Tried closing HK app and reopening but it did not work.

**Comment by pat4020** [comment]
Unfortunately, I do have the same issue as above. I've tried to close HK and reopen it - no change. Also, I tried to remove the TV frome HK and re-add it - still the same issue. Lastely, I removed the the plugin and the configuration from homebridge, reinstalled and reconfigured it - issue still there ...

**Comment by WojtekWro** [comment]
I have the same issue

**Comment by tavicu** [comment]
Looks like homebridge server can't access the TV ip or it takes more than the timeout is set.

First you can try to change this in config:
```
{
    "name": "Bedroom TV",
    "ip": "10.20.30.40",
    "mac": "A0:B1:C2:D3:E4:F5",
    "timeout": 1000
}
```

Also try to ping the TV from the homebridge and see if it's responding.

The plugin used to check if TV is ON: https://www.npmjs.com/package/is-port-reachable
And the port is checking: 8001
If you have some node knowledge you could try to make a simple js only with that plugin and see if it works.

It should look something like this:
```
let isPortReachable = require('is-port-reachable');

isPortReachable(8001, {
    host: YOUR_TV_IP_HERE,
    timeout: 1000
}).then(reachable => console.log(reachable));
```
