### ISSUE TITLE
Additional Apps

### ISSUE THREAD

**Issue by forresthamilton** [tavicu/homebridge-samsung-tizen#201]
If I wanted to add the option to open additional apps like AppleTV, what would the ID be? How can I figure it out? Also, can I add keys for volume +- instead of having them as switches? Would it just be:
"platforms": [
    {
        "platform": "SamsungTizen",
        "devices": [
            {
                "name": "Bedroom TV",
                "ip": "10.20.30.40",
                "mac": "A0:B1:C2:D3:E4:F5",
                "keys": {
                    "VOLUME UP": "VOL_UP",
                    "VOLUME DOWN": "VOL_DOWN"
                }
            }
        ]
    }
]

**Comment by mafyata** [comment]
Read wiki. Everything is there.

**Comment by forresthamilton** [comment]
> Read wiki. Everything is there. 

I did but I didn’t see anything about adding additional keys. I found the part about running homebridge as a parameter to get a list of apps.

**Comment by tavicu** [comment]
Can't add additional keys! You can only changes the current ones.

The volume of tv can be controller with the volume buttons when you are in the Control Center

**Comment by forresthamilton** [comment]
So I can control the volume of the TV without adding any keys? Just by swiping down in control center and going where? Using the AppleTV remote? Should I have the option of selecting my Samsung TV from the top menu?

**Comment by mafyata** [comment]
Yes , yes. Just try. You can’t brick it. Open apple remote from control center and try buttons. You can change buttons funcions , but can’t add new buttons on the remote.

**Comment by mafyata** [comment]
Are you using config ui x plugin?

**Comment by forresthamilton** [comment]
I am not. I couldn’t get it to work when I first installed homebridge last year. I’m just editing my config file each time.

**Comment by forresthamilton** [comment]
Back home now, tried the remote, and it works. Going to try adding the Apple TV app.
