### ISSUE TITLE
Home automation .... coming home .... selecting switch not possible ?

### ISSUE THREAD

**Issue by roe1974** [tavicu/homebridge-samsung-tizen#202]
Hi

I have configured a switch for "power on + channel 200" for my TV....
Is it normal that this switch ist not available in automation "when first person is coming home" ?

Richard
PS: switch is grouped with TV

**Comment by tavicu** [comment]
Hi. I have tested and i can add my switches to automations. 
Tested grouped and as separate tiles.

**Comment by roe1974** [comment]
hmmmmm .... i will check it again !
thx, richard
