### ISSUE TITLE
Not responding when turn on request sent

### ISSUE THREAD

**Issue by devjulie** [tavicu/homebridge-samsung-tizen#203]
Hi, thanks for the great homebridge plugin. 

I’m encountering a slight issue when I ask Siri to turn on the TV or I turn on through the Home app I get a not responding error however the TV does turn on and after a minute the not responding error goes away. So the command is working but the TV doesn’t seem to relay that.
I checked terminal and this is what it looks like:
![62DBC341-1C90-400D-8458-2E5C8EB11535](https://user-images.githubusercontent.com/29554580/79683280-ec1b5500-8220-11ea-897d-c21c9fedbb6f.jpeg) 
Again although it says failed it definitely is working.
It’s only started happening recently. The only change I’ve made is that I’ve wiped my Pi and started using Docker Homebridge.

**Comment by tavicu** [comment]
No problem on my side and i have 3 TVs. Also using docker.

Closed since you didn't read the wiki! https://github.com/tavicu/homebridge-samsung-tizen/wiki/Common-Issues#how-to-open-a-new-issue
