### ISSUE TITLE
Setting the inputs

### ISSUE THREAD

**Issue by jgeorge1983** [tavicu/homebridge-samsung-tizen#205]
Sorry if this has been answered but i couldnt find it.  Hopefully something very simple.  
I have the code to swtich to Live TV:
"inputs": [
        {"name": "Live TV", "type": "command", "value": ["KEY_SOURCE", "KEY_LEFT*3", "KEY_ENTER"]},
        
THe issue with this is that if the source isn't on zero it moves right 3 from where it is.  So my hope was move it all the way to the left then the required amout right:

"inputs": [
          {"name": "Live TV", "type": "command","value": ["KEY_SOURCE", "KEY_left*10", "KEY_right*3", "KEY_ENTER"]},

This doesnt seem to work though, what actually happens here is that the source doesnt move,  any thoughts what i have done wrong?

Thanks,
Jay

**Comment by tavicu** [comment]
You forgot the `*` in `KEY_left10", "KEY_right3`

**Comment by jgeorge1983** [comment]
Sorry it does have the * in, not sure how that copied like that:

"inputs": [
                        {
                            "name": "Live TV",
                            "type": "command",
                            "value": [
                                "KEY_SOURCE",
                                "KEY_left*10",
                                "KEY_right*3",
                                "KEY_ENTER"
                            ]
                        },

This is how its written, but it just stays on the same source

**Comment by jgeorge1983** [comment]
I figured it out, capitals on the left and right should have been LEFT and RIGHT.  Still would be good if there were a way to "reset the source" before selecting the source but this works. 

And its a great pluggin, thanks
