### ISSUE TITLE
Mac Address/ IP

### ISSUE THREAD

**Issue by nfstange** [tavicu/homebridge-samsung-tizen#206]
Question: in the settings for the IP address we should be using the Ethernet ip and which MAC address Ethernet or wireless?

**Comment by tavicu** [comment]
The one that is connected to your network. If it’s wire, ethernet. If it’s wireless then the wlan

**Comment by Hochiss** [comment]
would you please implement option only based on MAC address? because some router may not be able to fix the IP address. If any new device in network, the TV's IP changed thus this plugin not working anymore, which means from HomeKit iPhone cannot control it anymore.

**Comment by nfstange** [comment]
?

**Comment by tavicu** [comment]
@Hochiss that’s not possible. In your router interface you can assign a static ip for the TV so it won’t change
