### ISSUE TITLE
After deleting in Homekit can't add again

### ISSUE THREAD

**Issue by Kaspermaat** [tavicu/homebridge-samsung-tizen#207]
Hi there,
Unfortunately I'm having some problems with the Tizen plugin. After a LAN connection I was experimenting to get it to work over WIFI. I deleted the accessory in HomeKit etc. It worked like a charm so far. But than I wanted to go back to the old LAN setting, same set-up, same settings but HomeKit won't let me add the accessory again? I can communicate via Homebridge UI X with the TV so I know it is working. It simply does'n show up in HomeKit?

Is there any way to fix this problem?

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/issues/117#issuecomment-502435485

**Comment by Kaspermaat** [comment]
Thanks! That did the job
