### ISSUE TITLE
Keys in Configuration doesn't work

### ISSUE THREAD

**Issue by nowycondro** [tavicu/homebridge-samsung-tizen#209]
The `keys` configuration doesn't work, `switches` and `inputs` works fine.

Environment : Samsung Q60
Example config : 
```
...
"keys": {
          "REWIND": "KEY_REWIND",
          "SELECT": "KEY_ENTER"
}
...
```

**Comment by tavicu** [comment]
Tested and they are working as it should

**Comment by sfguyfor20** [comment]
I'm having a similar issue, I'm only showing the on/off button... none of the keys I've added are showing up anywhere... 

"platforms": [
        {
            "platform": "SamsungTizen",
            "keys": {
                "REWIND": "KEY_REWIND",
                "SELECT": "KEY_ENTER",
                "FAST_FORWARD": "KEY_FF",
                "ARROW_UP": "KEY_UP",
                "ARROW_DOWN": "KEY_DOWN",
                "ARROW_LEFT": "KEY_LEFT",
                "ARROW_RIGHT": "KEY_RIGHT",
                "BACK": "KEY_RETURN",
                "EXIT": "KEY_HOME",
                "PLAY_PAUSE": "KEY_PLAY_BACK",
                "INFORMATION": "KEY_INFO",
                "NEXT_TRACK": [],
                "PREVIOUS_TRACK": []
            },
            "plugin_map": {
                "plugin_name": "homebridge-samsung-tizen"
            },
