### ISSUE TITLE
fixed port

### ISSUE THREAD

**Issue by Radstake** [tavicu/homebridge-samsung-tizen#210]
Hi everytime homebridge is restarted the plugin listens to a new port. But I am calling the api directly so after every reboot I need to change my config

**Comment by tavicu** [comment]
What ports? :) What exactly are you changing? I think this is a Homebridge issue, nothing related to the plugin

**Comment by Radstake** [comment]
this plugin listens to its own port instead of homebridge own port e.g.
`[2020-5-4 3:41:10 PM] TV is running on port 33943.
[2020-5-4 3:41:10 PM] Please add TV manually in Home app. Setup Code: ***-**-***`
This port can be used to access the core api via ip:33943/accessories, but not if its changes all the time :-)

**Comment by tavicu** [comment]
Try to set the ports as in Homebridge config. https://github.com/homebridge/homebridge/blob/master/config-sample.json

**Comment by Radstake** [comment]
I have, but this plugin listens it's **own** port. In my case homebridge listens to `[2020-5-4 3:41:16 PM] Homebridge is running on port **51826**.` and your plugin listen to `[2020-5-4 3:41:10 PM] TV is running on port **33943**.` Your plugin creates an owns instance within Homebridge, thats why one has to add it additionally to homebridge. You know how your plugin works right :-)

**Comment by tavicu** [comment]
Check that config! This part:
```
  "ports": {
    "start": 52100,
    "end": 52150,
    "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
  },
```

**Comment by Radstake** [comment]
I know you are, thanks and appreciated, a lot! Then I must look somewhere else :-)

**Comment by tavicu** [comment]
Again, don't know if you understand. Beside the port for the main homebridge server, you can also set a range of ports for separate accessories like this plugin! if you set that in config and you still get another port (from the 3xxxx range for example when you have set 5xxxx) means is possible that you have multiple homebridge instances open!

There is no way to get a 3xxxx port when you set a range of 5xxxx other than your config path is wrong or something with the homebridge instances.

**Comment by Radstake** [comment]
I do understand..., I did set the range, just the standard port hb, so I'll try that first :-)

**Comment by thehauntedmattress** [comment]
Hey @tavicu your solution solved this exact problem for me.  It also solves (this issue](https://github.com/NorthernMan54/homebridge-alexa/issues/287) over at Homebridge-Alexa.
