### ISSUE TITLE
At least trying to get Power ON/OFF to work - appreciate your help?

### ISSUE THREAD

**Issue by yasserabdalla** [tavicu/homebridge-samsung-tizen#214]
Hello, it looks a great plugin but unfortunately, I could not get it to work so I appreciate your help based on the inputs below:

Running my Homebridge with your plugin, I managed to get a "Television" icon in my HomeKit/Home App but the power on/off buttons don't work, there are two of them one is round and the second with a slide bar.

**The round button toggles blue and gray when clicked and after rebooting Homebridge it would return the following when the TV is on and it would not power TV off:**
[5/9/2020, 1:25:11 PM] [TV Remote] TV is ON
[5/9/2020, 1:25:28 PM] [Familyroom TV] Powering off is in progress
[5/9/2020, 1:26:54 PM] [TV Remote] TV is ON

**The slide bar Power ON/OFF causes the following message on Homebridge when clicked to turn TV on while it is off:**  
[5/9/2020, 1:31:52 PM] [TV Remote] TV is OFF
[5/9/2020, 1:31:56 PM] [Familyroom TV] WebSocket is not open: readyState 2 (CLOSING)
[5/9/2020, 1:32:22 PM] [Familyroom TV] Opening handshake has timed out

**My TV returns the info below when I ping it from a browser with http://TV_IP:8001/api/v2/**
{
  "id": "uuid:b7410844-4849-4106-85da-566f8b4da373",
  "name": "[TV] UN55JS8500",
  "version": "2.0.25",
  "device": {
    "type": "Samsung SmartTV",
    "duid": "uuid:b7410844-4849-4106-85da-566f8b4da373",
    "model": "15_HAWKM_UHD",
    "modelName": "UN55JS8000",
    "description": "Samsung DTV RCR",
    "networkType": "wired",
    "ssid": "",
    "ip": "192.168.0.51",
    "firmwareVersion": "Unknown",
    "name": "[TV] UN55JS8500",
    "id": "uuid:b7410844-4849-4106-85da-566f8b4da373",
    "udn": "uuid:b7410844-4849-4106-85da-566f8b4da373",
    "resolution": "1920x1080",
    "countryCode": "CA",
    "msfVersion": "2.0.25",
    "smartHubAgreement": "true",
    "wifiMac": "fc:f1:36:d9:17:e8",
    "developerMode": "0",
    "developerIP": ""
  },
  "type": "Samsung SmartTV",
  "uri": "http://192.168.0.51:8001/api/v2/"
}

**My Homebride is configured as follows:**
"accessories": [
        {
            "accessory": "DummySwitch",
            "name": "Switch 1"
        },
        {
            "accessory": "SamsungTV",
            "name": "TV Remote",
            "ip": "192.168.0.51",
            "mac": "fc:f1:36:d9:17:e8",
            "type": "power"
        },
        {
            "accessory": "SamsungTV",
            "name": "Mute TV",
            "ip": "192.168.0.51",
            "mac": "fc:f1:36:d9:17:e8",
            "type": "mute"
        },
        {
            "accessory": "SamsungTV",
            "name": "Channel 13",
            "ip": "192.168.0.51",
            "mac": "fc:f1:36:d9:17:e8",
            "type": "channel",
            "channel": "13"
        },
        {
            "accessory": "SamsungTV",
            "name": "Change HDMI",
            "ip": "192.168.0.51",
            "mac": "fc:f1:36:d9:17:e8",
            "type": "custom",
            "command": "KEY_HDMI"
        },
        {
            "accessory": "SamsungTV",
            "name": "Volume Up",
            "ip": "192.168.0.51",
            "mac": "fc:f1:36:d9:17:e8",
            "type": "custom",
            "command": "KEY_VOLUP",
            "repeat": 5,
            "delay": 500
        },
        {
            "accessory": "SamsungTV",
            "name": "Multiple Commands",
            "ip": "192.168.0.51",
            "mac": "fc:f1:36:d9:17:e8",
            "type": "custom",
            "command": [
                "KEY_UP",
                "KEY_DOWN",
                "KEY_LEFT",
                "KEY_RIGHT"
            ],
            "delay": 500
        }
    ],

Also, I never got a popup pairing message on my TV - I have other media devices on my TV and all of them are configured as "allowed" such as our iPhones.

Thank you

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/wiki/Installation#4-config

**Comment by yasserabdalla** [comment]
Thank you, Octavian.

I already went through this link before posting my issue ... so I really appreciate it if you would review my configurations above and let me know if I missed anything?

I already configured IP/Mac addresses and my Home App but I can not get the TV to turn on or off at all.

My TV does not pop up pairing confirmation at all.

Thank you again.

**Comment by tavicu** [comment]
My plugin is a `platform`, not an `accessory `

Your config is wrong, take a look again please at the config.

You can also find a sample over here: https://github.com/tavicu/homebridge-samsung-tizen/blob/master/config-sample.json

**Comment by yasserabdalla** [comment]
Thank you, Octavian ... yes, it's my bad, I copied the wrong part in my config to our case here ... 

Now, I removed all other plugins and my configuration looks as below but the problem remains the same, I keep getting "no response" and I can not turn the TV ON or OFF - appreciate any clues?

How I may add "Apple TV" as an Input or switch?

{
    "bridge": {
        "name": "Homebridge",
        "username": "0E:5A:D3:58:96:DE",
        "port": 53787,
        "pin": "416-97-801",
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "SamsungTizen",
            "app_list": false,
            "devices": [
                {
                    "name": "Family",
                    "ip": "192.168.0.51",
                    "mac": "fc:f2:38:d6:17:e8",
                    "switches": [
                        {
                            "name": "Mute",
                            "mute": true
                        },
                        {
                            "name": "Sleep",
                            "sleep": 60
                        },
                        {
                            "name": "Channel",
                            "channel": 13
                        },
                        {
                            "name": "VOLUP",
                            "command": "KEY_VOLUP"
                        },
                        {
                            "name": "VOLUP5",
                            "command": "KEY_VOLUP*5"
                        },
                        {
                            "name": "UP Down",
                            "command": [
                                "KEY_VOLUP",
                                "KEY_VOLDOWN"
                            ]
                        },
                        {
                            "name": "Command 4",
                            "command": [
                                "KEY_VOLUP*5",
                                "KEY_VOLDOWN*3"
                            ]
                        },
                        {
                            "name": "All",
                            "sleep": 60,
                            "mute": true,
                            "command": [
                                "KEY_VOLUP",
                                "KEY_VOLDOWN"
                            ],
                            "channel": 13
                        }
                    ],
                    "inputs": [
                        {
                            "name": "Netflix",
                            "type": "app",
                            "value": "11101200001"
                        },
                        {
                            "name": "VUDU",
                            "type": "app",
                            "value": "111012010001"
                        },
                        {
                            "name": "YouTube",
                            "type": "app",
                            "value": "111299001912"
                        }
                    ]
                }
            ]
        }
    ]
}

**Comment by tavicu** [comment]
From what i can see your TV is using an older version of Tizen that is not compatible with this plugin.

Even if it responds to that API, your tv user another method to pair (pin method).

**Comment by yasserabdalla** [comment]
Thank you, Octavian, do you think I should try the pair "pin method" before I give up? can you please recommend a link to the "pin method" or any procedures to configure it?

Much appreciated.

**Comment by tavicu** [comment]
Sorry but i cannot guide you to another plugin since i don't have any TV using that method and don't know what works :)

**Comment by yasserabdalla** [comment]
I was interested in your plugin than other ones ... 

Thank you for the great work and sharing out
