### ISSUE TITLE
Support for 2019 Frame TV

### ISSUE THREAD

**Issue by pwkrueger** [tavicu/homebridge-samsung-tizen#215]
Hello,

I'm very new to GitHub and not a programmer, so any help re: below would be greatly appreciated!

I have a 2019 Samsung Frame 55" TV, and Homebridge installed on my Synology NAS. I'm hoping to add Siri/Homekit functionality to the TV.

I managed to install the Samsung Tizen plugin and add the TV to Homekit. It successfully shows up as an accessory.

The plugin 'on/off' function will turn the tv on but doesn't turn it off. Rather it toggles between 'art' and 'tv' mode.

Is there a way to program the plugin so that I can toggle between "off", "art", and "tv" modes?

I suspect the issue may have to do with how the power button works on the Frame TV remote: a short press of the power button toggles between 'art' and 'tv' modes, and a long press turns the tv on and off.

Thanks again for any help or advice you can provide!

P

**Comment by baswijnands** [comment]
Might be able to setup a switch with a command that hold the power button down for a few seconds (like the volume example in docs) to get this done.

**Comment by mrMiimo** [comment]
I read in some post/comments there is a way to make "turn off" the frame model,  changing the file lib/remote.js line 247 from:
`await this.command('KEY_POWER');`
to
`await this.command('KEY_POWER*3s');`

I did it and it works.
R.

**Comment by pwkrueger** [comment]
> I read in some post/comments there is a way to make "turn off" the frame model, changing the file lib/remote.js line 247 from:
> `await this.command('KEY_POWER');`
> to
> `await this.command('KEY_POWER*3s');`
> 
> I did it and it works.
> R.

That worked for me too, thank you!! Now if I can switch to toggle between TV mode and art mode. :)

**Comment by pwkrueger** [comment]
> > I read in some post/comments there is a way to make "turn off" the frame model, changing the file lib/remote.js line 247 from:
> > `await this.command('KEY_POWER');`
> > to
> > `await this.command('KEY_POWER*3s');`
> > I did it and it works.
> > R.
> 
> That worked for me too, thank you!! Now if I can switch to toggle between TV mode and art mode. :)

Success! After following mrMiimo's instructions, the tv 'on/off' function worked. I then added a simple switch with 'KEY_POWER' as the command, to toggle between art and tv modes.

Thanks everyone!

**Comment by jiuguangw** [comment]
@pwkrueger, could you please clarify how you added a switch with KEY_POWER to toggle between art and TV modes?

**Comment by Ghitafjorback** [comment]
This sounds great, but @pwkrueger when you say you can now toggle between art and tv modes, can you then actually tell if the TV is on or in art mode? I mean in Homekit itself? My problem is that in Homekit the tile will show TV as ON, even though it is in ART mode. Which means that if I add a it to a goodnight schene i.e. I will ask to turn OFF the tv, it will actually just turn it ON. Hope it makes sense and that you can confirm that your above solution actually can solve this issue.
thanks

**Comment by CGDaveMac** [comment]
> This sounds great, but @pwkrueger when you say you can now toggle between art and tv modes, can you then actually tell if the TV is on or in art mode? I mean in Homekit itself? My problem is that in Homekit the tile will show TV as ON, even though it is in ART mode. Which means that if I add a it to a goodnight schene i.e. I will ask to turn OFF the tv, it will actually just turn it ON. Hope it makes sense and that you can confirm that your above solution actually can solve this issue.
> thanks

Yes, I have read through all the different issues and wondering if this was ever work properly with The Frame.
