### ISSUE TITLE
Samsung TV not in Apple Home app

### ISSUE THREAD

**Issue by WayneKP** [tavicu/homebridge-samsung-tizen#216]
I have the tavicu/homebridge-samsung-tizen plugin installed and it all seems to be working but I can't add or find the TV to the Apple home app. I allowed it to pair on the TV and seems to be recognised as shown in the attached file so I am not sure where to go next if you could help thanks. I have also added the debug log file so hope I have provided enough info thanks
[Debug log.pdf](https://github.com/tavicu/homebridge-samsung-tizen/files/4605093/Debug.log.pdf)
[Homebridge.pdf](https://github.com/tavicu/homebridge-samsung-tizen/files/4605094/Homebridge.pdf)

**Comment by tavicu** [comment]
Hi.

Looks like homebridge connects to the TV since it prints the installed apps.

Try this method please: https://github.com/tavicu/homebridge-samsung-tizen/issues/117#issuecomment-502435485

**Comment by WayneKP** [comment]
OK thank you for your help and we are making progress and have the TV added to the Home app by adding the "uuid": "A1" however it is a bit erratic working, sometimes accepting Siri commands and sometimes not and so I have attached files to give you an idea 
![No Response](https://user-images.githubusercontent.com/37004336/81627112-d0325a00-9440-11ea-9e42-8c1ec9097e91.jpeg)
![Siri](https://user-images.githubusercontent.com/37004336/81626845-2bb01800-9440-11ea-86aa-c95742407b83.jpg)
![image](https://user-images.githubusercontent.com/37004336/81626891-41254200-9440-11ea-9477-693e92754be4.png)

**Comment by WayneKP** [comment]
OK, I got it, The TV has a selection when I pair which allows to accept a request and has 2 options, "always ask" or "First time only" and after selecting first time time only , it works as expected, yay and thank you so much
