### ISSUE TITLE
the switch to change channels does not work as expected

### ISSUE THREAD

**Issue by mrMiimo** [tavicu/homebridge-samsung-tizen#217]
Hi,
I would like to use automation using a switch to change channels.
But when I press the switch it doesn't work, instead of changing channels it is as if I press the "enter" button.

My tv is "The Frame 2019".

Any suggestions?
Thanks,
R.

---- my json config --- 
```	"platform": "SamsungTizen",
		"devices": [{
			"name": "TV",
			"ip": "XXX.XXX.XXX.XXX",
			"mac": "XX:XX:XX:XX:XX:XX",
			"switches": [{"name": "Ch 13", "channel": 13}],
			"keys": {
				"INFORMATION": "KEY_HOME",
				"PLAY_PAUSE": "KEY_GUIDE",
				"BACK": "KEY_RETURN"
				},
			"inputs": [
				{"name": "Netflix", "type": "app", "value": "11101200001"},
				{"name": "Rakuten TV", "type": "app", "value": "3201511006428"},
				{"name": "Prime Video", "type": "app", "value": "3201512006785"},
				{"name": "DAZN", "type": "app", "value": "3201806016390"},
				{"name": "YouTube", "type": "app", "value": "111299001912"},
				{"name": "Apple TV", "type": "app", "value": "3201807016597"}
       				  ]
			    }]
```

**Comment by mrMiimo** [comment]
....more info ...
It doesn't work when I'm in an app (like Prime Video or Netflix ...).
It works only when I'm on LiveTV :-\
Is there an option or possibility for the channel change to always work?

**Comment by tavicu** [comment]
The channel only press the keys for you. In the example (ch 13) it press key 1, then 3, then enter.

You will have to work with commands and make a list where first it changes to live tv then switch to ch 13. But this will run all the time, even when you are already on live tv.

**Comment by mrMiimo** [comment]
Ahhhh OK ..
But the problem, if I make a command to go live on TV, is the starting point of the menu, it is not always the same ...
It's surprising how such a modern TV is so limited with integration and API.

Well, we can close this problem / question if you want ..
Thanks a lot!
