### ISSUE TITLE
msg.payload on/off state for nodered?

### ISSUE THREAD

**Issue by simonlock** [tavicu/homebridge-samsung-tizen#219]
Please would it possible to publish a property to the msg.payload so that nodered can determine if the tv is on or off?

Currently published are the following four properties:

ConfiguredName: "tvname"
SleepDiscoveryMode: 1
ActiveIdentifier: 0
Active: 0

These properties remain the same in both on and off states.

I'm using "node-red-contrib-homebridge-automation" in nodered with homebridge.

**Comment by tavicu** [comment]
Hi. I'm sorry but i'm not familiar with nodered.

I'm happy to accept a pull request if you have one :)
