### ISSUE TITLE
IP address not reading

### ISSUE THREAD

**Issue by man-knee** [tavicu/homebridge-samsung-tizen#22]
config.json file is correctly updated.  However, running Homebridge it stalls on line 25 of SamsungDevice.js for the IP check and generates an error that TV IP address is required for undefined.  IP address is present in the file as is the mac address.  Any input would be great.

**Comment by tavicu** [comment]
Can you show me your config?

**Comment by man-knee** [comment]
Here you go.  Full disclosure, bit of a noob here.  Trying to start small with the TV and work up from there.  Any thoughts are appreciated.

<img width="653" alt="screen shot 2018-12-04 at 7 01 26 pm" src="https://user-images.githubusercontent.com/45584336/49481040-18cef800-f7f7-11e8-8173-980b151cb365.png">

**Comment by tavicu** [comment]
As i said your config is wrong :)
On platforms it should look like this:

```
"platforms": [
    {
        "platform": "SamsungTizen",
        "devices": [
            {
                "name": "SamsungTizen",
                "ip": "192.168.1.17",
                "mac": "84:a4:66:3a:a5:f2",
                "token": ""
            }
        ]
    }
]
```

Let me know how it is after you update it :)
