### ISSUE TITLE
Inputs not working?

### ISSUE THREAD

**Issue by robinjb** [tavicu/homebridge-samsung-tizen#221]
Hi there!

I’m having trouble getting Inputs to work as I’d expect. My config file has two inputs set up...

    "inputs": [
                        {
                            "name": "Netflix",
                            "type": "app",
                            "value": "11101200001"
                        },
                        {
                            "name": "Plex",
                            "type": "app",
                            "value": "3201512006963"
                        }

Both inputs show as Accessories in Home (as part of the overall TV accessory) but tapping them does nothing. And they are not appearing as Inputs in the Control Centre TV remote (the inputs button is still missing).

![23D81520-6EB5-4C59-867C-35CB3D5E1C6F](https://user-images.githubusercontent.com/7364448/82154303-c22b7180-9864-11ea-9da6-51e2f7214eab.jpeg)

As an experiment I set up a switch to turn on Netflix, and that worked fine - but what I really want is the Inputs button in the Control Centre TV remote, which only looks like this ...

![D3C9B98B-24F9-404F-98D2-989AF631593B](https://user-images.githubusercontent.com/7364448/82154313-da9b8c00-9864-11ea-8779-2ab96ecaeb11.png)

Any guidance will be hugely appreciated! Thanks in advance.

**Comment by tavicu** [comment]
If only it was written in wiki ... :)

**Comment by enriquecaballero** [comment]
My TV is compatible and I followed what was on the wiki and they successfully show up as inputs 
but they still aren't working ― nothing really happens.

![Screen Shot 2020-05-19 at 12 45 19 PM](https://user-images.githubusercontent.com/7918284/82354268-99bf8680-99ce-11ea-90c2-822f8c7155a0.png)

**Comment by enriquecaballero** [comment]
Here are the logs from Homebridge running in debug mode:
```
[5/19/2020, 12:50:05 PM] [Living Room TV] [DEBUG] {
 method: 'ms.channel.emit',
 params: {
   to: 'host',
   event: 'ed.apps.launch',
   data: { action_type: 'DEEP_LINK', appId: 'org.tizen.browser' }
 }
}
[5/19/2020, 12:50:06 PM] [Living Room TV] [DEBUG] { data: 200, event: 'ed.apps.launch', from: 'host' }
[5/19/2020, 12:50:22 PM] [Living Room TV] [DEBUG] {
 method: 'ms.channel.emit',
 params: {
   to: 'host',
   event: 'ed.apps.launch',
   data: { action_type: 'DEEP_LINK', appId: '11101200001' }
 }
}
[5/19/2020, 12:50:23 PM] [Living Room TV] [DEBUG] { data: 200, event: 'ed.apps.launch', from: 'host' }
[5/19/2020, 12:50:33 PM] [Living Room TV] [DEBUG] {
 method: 'ms.channel.emit',
 params: {
   to: 'host',
   event: 'ed.apps.launch',
   data: { action_type: 'DEEP_LINK', appId: '111299001912' }
 }
}
[5/19/2020, 12:50:33 PM] [Living Room TV] [DEBUG] { data: 200, event: 'ed.apps.launch', from: 'host' }
[5/19/2020, 12:50:40 PM] [Living Room TV] [DEBUG] {
 method: 'ms.channel.emit',
 params: {
   to: 'host',
   event: 'ed.apps.launch',
   data: { action_type: 'DEEP_LINK', appId: '3201807016597' }
 }
```

**Comment by enriquecaballero** [comment]
@tavicu Thoughts?

**Comment by imnotLeonn** [comment]
Same here, tried to use the inputs but it's not working, I have my live tv as input but instead of using app's ids I used keys to navigate on the menu until I get an app open, I think I'm changing my input to this second way to make it work

**Comment by mmarras** [comment]
> If only it was written in wiki ... :)

The Wiki on inputs is not too helpful. Not a single image on what to expect when you add an input. Adding some images would help dramatically.

**Comment by tavicu** [comment]
> > If only it was written in wiki ... :)
> 
> The Wiki on inputs is not too helpful. Not a single image on what to expect when you add an input. Adding some images would help dramatically.

They were but the host that store the images was taken down.
It's in my plan to update all pages from wiki as soon as i will have some free time.
