### ISSUE TITLE
TV doesn't show up in homebridge + homeKit

### ISSUE THREAD

**Issue by renmlp** [tavicu/homebridge-samsung-tizen#223]
Hello,

currently I have the problem that my TV UE49MU6199 does not show up in homebridge as well as in the home app.

I did the installation according to the repository instructions.It was checked if the API URL on the server can be accessed via curl and the TV is also reachable via a ping.

The only message that appears in the log:
`[TV] Samsung 6 Series (49) is running on port 33451.`

I've tried everything mentioned in all other issues including adding the`uuid` in `config.json` and removing `accessories/samsung-tizen.json`.

## Versions
`npm -v`
6.14.4
`node -v`
v12.16.2
`hoobs -v`
3.2.6
`homebridge-samsung-tizen`
4.3.2

## Config
```
{
    "platform": "SamsungTizen",
    "plugin_map": {
        "plugin_name": "homebridge-samsung-tizen"
    },
    "devices": [
        {
            "name": "[TV] Samsung 6 Series (49)",
            "ip": "192.168.178.54",
            "mac": "XX:XX:5E:XX:07:XX",
            "keys": {
                "REWIND": "KEY_REWIND",
                "SELECT": "KEY_ENTER"
            },
            "switches": [
                {
                    "name": "Mute",
                    "mute": true
                },
                {
                    "name": "Sleep",
                    "sleep": 60
                }
            ]
        }
    ],
    "name": "SamsungTizen",
    "app_list": true
}
```

**Comment by BobbySlope** [comment]
same here with an hoobs user:

logs:
[logs.txt](https://github.com/tavicu/homebridge-samsung-tizen/files/4738316/logs.txt)

config:
[config.txt](https://github.com/tavicu/homebridge-samsung-tizen/files/4738323/config.txt)

**Comment by BobbySlope** [comment]
issue solved needed to update node to higher than 12.4.0

**Comment by renmlp** [comment]
@BobbySlope i have currently installed v12.16.2

**Comment by BobbySlope** [comment]
we deleted the plugin
run reinstalled hoobs over the existing one via terminal
sudo npm install -g --unsafe-perm @hoobs/hoobs

and then installed the plugin again

**Comment by renmlp** [comment]
@BobbySlope same issue ...

**Comment by tavicu** [comment]
Hi. This problem looks related to Hoobs. You should search for a solution on their part.

Looks like they are not exposing the ports or something.

**Comment by renmlp** [comment]
@BobbySlope what do you say about @tavicu answer?

**Comment by tavicu** [comment]
The plugin only use a public method from HomeBridge to initialise. After that, it's HomeBrige job to do it :)

**Comment by renmlp** [comment]
Is my tv compatible?

**Comment by tavicu** [comment]
I think so! On the samsung website it's a photo with the smart interface and looks that is the correct version :)
