### ISSUE TITLE
Can't connect new TV

### ISSUE THREAD

**Issue by marithpl** [tavicu/homebridge-samsung-tizen#226]
Hi!

I've got problem with pairing new TV.
My old one die and I bought new TV, change config.json with new IP and MAC. After that I remove old tv from home.app.

Now I try to add new TV but it doesn't show in Home.app to add it manually.

Do you know any workaround?

**Comment by tavicu** [comment]
Try this: https://github.com/tavicu/homebridge-samsung-tizen/issues/117#issuecomment-502435485

**Comment by marithpl** [comment]
I added UUID but nothing happened.
I have latest version (v4.3.2)

**Comment by marithpl** [comment]
Ok i have "-" despite ":" in 1 place in MAC. After fixing that it works!
