### ISSUE TITLE
[kitchen TV] Opening handshake has timed out

### ISSUE THREAD

**Issue by hanzala-123** [tavicu/homebridge-samsung-tizen#227]
Myplugin works for my 2016 samsung tv which is on LAN but i get this in my logs and in the home app it says no response.

thanks

**Comment by tavicu** [comment]
I think you forgot to tell what you get in logs :)

**Comment by hanzala-123** [comment]
> I think you forgot to tell what you get in logs :)

its the title
sorry

**Comment by tavicu** [comment]
That's an error when the homebridge server cannot access the TV endpoint.

The IP of tv in config is wrong or the tv is not compatible with the plugin.
