### ISSUE TITLE
TV doesn't appear in Eve app

### ISSUE THREAD

**Issue by raixer** [tavicu/homebridge-samsung-tizen#228]
TV only shows up in the Home app. Not in Eve app. 
Is that normal?

**Comment by tavicu** [comment]
Hi! Don't know how Eve app works and what it should do.

This plugin is made for Homebridge + HomeKit

**Comment by raixer** [comment]
Eve app is like the Home app. It uses homekit data to visualize it in a different way. You can do all the stuff you can do in Home app plus more.

**Comment by raixer** [comment]
Maybe I should’ve said. Apps that access the Homekit data aren’t able to see the TV. 
Because it isn’t only limited to Eve app. But I just mentioned that one because I thought that one is pretty popular.
