### ISSUE TITLE
IOS Control center remote home Button

### ISSUE THREAD

**Issue by spadival** [tavicu/homebridge-samsung-tizen#229]
This is more of a feature request/FYI than an issue - a control center remote control appeared on my ios device when I added this plugin. Since there isn't a Home Button, I re-programmed the Information button to KEY_HOME in the plugin config. Is it possible to add a Home button and maybe even a power button. Then we don't have to fiddle around with adding controls in the Home app.

![image](https://user-images.githubusercontent.com/2186498/85020000-04710700-b1b3-11ea-94e5-247f4738555d.png)

**Comment by tavicu** [comment]
Hi! unfortunately that's not possible! We cannot decide what buttons to show. We only have the option to map the buttons to an action

**Comment by michaellongden** [comment]
Could you please advise how you managed to remap the Information key to KEY_HOME. I would be interested in doing this myself.

**Comment by taw123** [comment]
Have you tried editing the "Keys" definition your config.json for the Samsung plugin?  There's a second there specifically for key mapping..... 

      {
            "platform": "SamsungTizen",
            "devices": [
                {
                    "name": "TV",
                    "ip": "XXXXX",
                    "mac": "XXXXX,
                    "keys": {
                        "REWIND": "KEY_REWIND",
                        "FAST_FORWARD": "KEY_FF",
                        "BACK": "KEY_RETURN",
                        "EXIT": "KEY_HOME"
                    },

**Comment by michaellongden** [comment]
Great, that worked, thanks very much.
