### ISSUE TITLE
How can I test commands from the CLI?

### ISSUE THREAD

**Issue by zx8** [tavicu/homebridge-samsung-tizen#231]
I'm trying to chain some commands together using the references on this page – https://github.com/tavicu/homebridge-samsung-tizen/wiki/Commands – but it's a process a trial & error to get it right.

My process goes:
- Edit the config to add the new command chain
- Reload Homebridge to pick up the config
- Activate the command chain via Siri to check if it's worked
- See that I got something wrong, repeat

This is fairly laborious. Is there an easier way to test things directly from the CLI without having to go through the above process?

**Comment by tavicu** [comment]
Hi! Nope.

But you can do it from your remote and note the buttons you press :)
