### ISSUE TITLE
TV doesn’t show up on HomeKit and on HOOBS accessories 

### ISSUE THREAD

**Issue by nimi110** [tavicu/homebridge-samsung-tizen#233]
I installed the plugin on home ridge via HOOBS.

I set up the device fine and according to the installation guide and in the logs I can see “tv bedroom in running on port xxxx” so it seems that everything set right.

While I can’t see the TV in HomeKit or in HOOBS as accessory.

Hoobs version 3.26
Node version 12.16.2

By the way I tried to delete plugin re install Hoobs and install plugin again but 
It didn’t work and my TV is supported by the plugin.

@tavicu @hoobs-org @bobbyslope

**Comment by jeromeof** [comment]
Same problem here

**Comment by BobbySlope** [comment]
can u provide logs? TV´s wont show up in HOOBS ui because they are not supported as acessories right now.
But it should show up in Homekit.

**Comment by BobbySlope** [comment]
It wont show up in HomeKit until the TV is paired

**Comment by BobbySlope** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/wiki/Installation (step 5 of the web page)
First time when you run the plugin with a new TV it will need to pair.
In order to do that the TV must be ON. Then start the Homebridge server and after everything loaded on the TV you should see a popup asking your permission to pair. You need to click Allow!

**Comment by BobbySlope** [comment]
Tech with Eddie will come up with a Tutorial video next week

**Comment by jeromeof** [comment]
It is paired - I will see can I get some debug logs from Homebridge - but I can for example see the list of apps from my samsung TV in the homebridge logs and I can see the Samsung TV in the Homebridge Accessories (I can turn it on / off etc from Homebridge), but no matter what I do it doesn't appear HomeKit - I have reset the accessories, reset completely homebridge, removed and repaired with the Apple Home app and it the only accessory (and I have > 20 accessories) that does not appear on the HomeKit App

**Comment by nimi110** [comment]
The TV is paired. But it doesn’t show up on HomeKit no matter what I tried to do.

**Comment by jeromeof** [comment]
Ok, I have found the problem - It probably was that I have too many accessories as I did not see this log until now: 

[6/27/2020, 12:15:53] Kitchen Samsung TV is running on port 46393.
[6/27/2020, 12:15:53] Please add [Kitchen Samsung TV] manually in Home app. Setup Code: 817-15-199

So separately adding the Samsung TV code to HomeKit has worked.

**Comment by BobbySlope** [comment]
you need to pair the TV with the Plugin, and then you need to add the TV to Homekit sparatly 
Glad that it worked :)

**Comment by nimi110** [comment]
23.6.2020, 0:24:31 HOOBS listening on port 80.
23.6.2020, 0:24:32 No plugins found.
23.6.2020, 0:24:32 Bridge is running on port 51826.
23.6.2020, 0:26:31 npm
23.6.2020, 0:26:31  WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
23.6.2020, 0:26:36 + homebridge-samsung-tizen@4.3.2
added 56 packages from 65 contributors in 5.647s
23.6.2020, 0:26:36 
1 package is looking for funding
  run `npm fund` for details
23.6.2020, 0:26:36 Plugin "homebridge-samsung-tizen" installed.
23.6.2020, 0:26:37 Got SIGINT, shutting down Bridge...
23.6.2020, 0:26:42 Loaded plugin "homebridge-samsung-tizen".
23.6.2020, 0:26:42 Bridge is running on port 51826.
23.6.2020, 0:27:20 Got SIGINT, shutting down Bridge...
23.6.2020, 0:27:25 Loaded plugin "homebridge-samsung-tizen".
23.6.2020, 0:27:25 Bridge is running on port 51826.
23.6.2020, 0:27:25 Bedroom TV is running on port 43551.

this is the only log that I see I didnt get any HomeKit pin for the tv

**Comment by nimi110** [comment]
Ok never mind I used the hoobs bridge code for the tv and it worked.

**Comment by BobbySlope** [comment]
im happy for you that it worked :)
