### ISSUE TITLE
New accessory after config changes

### ISSUE THREAD

**Issue by marithpl** [tavicu/homebridge-samsung-tizen#236]
@tavicu I had a strange issue today.
I made a new switch via UI X. After restart of home bridge I was forced to add new TV as accessory and delete older one.
Do you know the reason why changes in config may create a "new TV"?

**Comment by tavicu** [comment]
Strange! Accessories are different from the main TV and it should not have any impact!

Are you sure you didn't change anything else in the config?
The UUID is generated by these two: this.config.mac + this.config.uuid
