### ISSUE TITLE
Remote function not working

### ISSUE THREAD

**Issue by brj5** [tavicu/homebridge-samsung-tizen#240]
So I finally got the plug-in linked to my tv and it’s able to turn it off but not on, and that’s all that is shown on HomeKit is a power button, how do I get it to be a remote?

**Comment by mazmar** [comment]
I too have the same problem. Samsung QE65Q80R, it shows power button and empty scroller.
I am using Iphone XR with latest iOS currently.

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/wiki

Also the remote is not part of the Home App. You can find it in the Control Center
