### ISSUE TITLE
Cannot get app list because the data returned is empty

### ISSUE THREAD

**Issue by papin97** [tavicu/homebridge-samsung-tizen#243]
Hello! I've successfully added my Samsung TV to Homebridge, and I've set `app_list` to `true`, but whenever I restart Homebridge to get the app list, it can't get the data.
Debug log shown below.

```
[8/29/2020, 12:38:10 AM] [Bedroom TV] [DEBUG] {
  data: { clients: [ [Object] ], id: '2a98efb6-4284-47b6-b5b6-6787546e89fb' },
  event: 'ms.channel.connect'
}
[8/29/2020, 12:38:10 AM] [Bedroom TV] [DEBUG] {
  method: 'ms.channel.emit',
  params: { data: '', to: 'host', event: 'ed.installedApp.get' }
}
Bedroom TV
---------------------
[8/29/2020, 12:38:11 AM] [Bedroom TV] Cannot read property 'forEach' of null
[8/29/2020, 12:38:11 AM] [Bedroom TV] [DEBUG] TypeError: Cannot read property 'forEach' of null
    at /usr/lib/node_modules/homebridge-samsung-tizen/lib/remote.js:195:26
```

TV is Samsung TU8000 50inch, connected with wired.

**Comment by tomas0721xd** [comment]
Hi! I'm having the same issue, also on a TU8000KXZL (55", South American market). Software version: T-NKLUABC-134.0 , BT - S

**Comment by L4RGER** [comment]
I’m having the same issues on both my Samsung’s, Q80 65” and TU8000 50”
“Cannot read property ‘foreach’ of null

**Comment by tavicu** [comment]
There was a problem because the API would not return the installed applications.

I had changed the code to not crash again but you will still not be able to see applications.

I think it has something to do with a newer version of firmware.

**Comment by masterfordev** [comment]
Yes. They made some changes. I remember saw a notification about that but i dont find again for share it with you. But they made changes in the api.

**Comment by preamptive** [comment]
Has anyone found a way to get the app codes for the newer firmware?

**Comment by simoa** [comment]
Can anyone with the new TVs tell us if this command work or not ? Thanks very much
(Open Netflix)
curl -X POST -i 'http://IP:8001/api/v2/applications/11101200001 2'

**Comment by papin97** [comment]
> Can anyone with the new TVs tell us if this command work or not ? Thanks very much
> 
> (Open Netflix)
> 
> curl -X POST -i 'http://IP:8001/api/v2/applications/11101200001'

Tested on my TV and it returns 404

**Comment by tavicu** [comment]
> > Can anyone with the new TVs tell us if this command work or not ? Thanks very much
> > (Open Netflix)
> > curl -X POST -i 'http://IP:8001/api/v2/applications/11101200001'
> 
> Tested on my TV and it returns 404

Did you replaces IP from the link with your TV IP?

**Comment by simoa** [comment]
We just realise that it works with all other apps but not Netflix 

Can you please try these urls 

(Open YouTube)
curl -X POST -i 'http://IP:8001/api/v2/applications/111299001912'

(Open Prime)
curl -X POST -i 'http://IP:8001/api/v2/applications/3201512006785'

(Open browser)
curl -X POST -i 'http://IP:8001/api/v2/applications/org.tizen.browser'

Thanks very much

**Comment by papin97** [comment]
YouTube and browser work but not Prime Videos (it's also installed).
Maybe region-specific?

**Comment by simoa** [comment]
@papin97 For Netflix can you check with this 

if it works we might propose a solution
curl -X POST -i 'http://IP:8001/ws/apps/Netflix'

Thanks

**Comment by techiebod** [comment]
For me at least, I see the following from the above:
> $ curl -X POST -i 'http://192.168.1.13:8001/api/v2/applications/111299001912'
> HTTP/1.1 200 OK
> content-type: application/json; charset=utf-8
> content-length: 5
>
> true

But:
> curl -X POST -i 'http://192.168.1.13:8001/ws/apps/Netflix'
> HTTP/1.1 401 Unauthorized
> content-type: application/json; charset=utf-8
> content-length: 29
> 
> <html><body>401</body></html>

Whereas:
> curl -X POST -i 'http://192.168.1.13:8001/api/v2/applications/11101200001'
> HTTP/1.1 404 Not Found
> content-type: application/json; charset=utf-8
> content-length: 55
>
> {"code":404,"message":"Not found error.","status":404}

(NB: Developer mode is on for the TV, and the TV in question is a "UE85TU8000KXXU" )

**Comment by mirroringcontact** [comment]
> We just realise that it works with all other apps but not Netflix
> 
> Can you please try these urls
> 
> (Open YouTube) curl -X POST -i 'http://IP:8001/api/v2/applications/111299001912'
> 
> (Open Prime) curl -X POST -i 'http://IP:8001/api/v2/applications/3201512006785'
> 
> (Open browser) curl -X POST -i 'http://IP:8001/api/v2/applications/org.tizen.browser'
> 
> Thanks very much

Does it possible launch browser with url using this post request?

**Comment by AmirTallap** [comment]
> > We just realise that it works with all other apps but not Netflix
> > Can you please try these urls
> > (Open YouTube) curl -X POST -i 'http://IP:8001/api/v2/applications/111299001912'
> > (Open Prime) curl -X POST -i 'http://IP:8001/api/v2/applications/3201512006785'
> > (Open browser) curl -X POST -i 'http://IP:8001/api/v2/applications/org.tizen.browser'
> > Thanks very much
> 
> Does it possible launch browser with url using this post request?

**Comment by AmirTallap** [comment]
I'm really grateful for your comment here.
Is there a way to send a notification to the TV the same way? Like a "Hello world message" under my app name?
