### ISSUE TITLE
unable to Pair again with the TV

### ISSUE THREAD

**Issue by cosmit** [tavicu/homebridge-samsung-tizen#245]
I had the Plugin working with my TV Q9 2018 than i added apps to it there after there was no more connection.#

I deleted the TV on the home APP  and as well the device on the Samsung TV 
now i can not repair the TV again to the bridge and it doesn't show up in the home app as a new TV to add.

any idea to reset the connection and pair it again ?
in the past it was possible with the config "UUID" : "A1" for example but not possible any more with die actual plugin 

best Regards

**Comment by tavicu** [comment]
instead of A1 put anything else that you didn't used before

**Comment by cosmit** [comment]
Thanks it worked now 
most probably i find 10 time someting i used already

**Comment by anderslutzhoft** [comment]
@cosmit I'm having the same issue. Where do you add the "UUID" : "A1"?

**Comment by tavicu** [comment]
On the device settings. Example:
```
{
    "name": "Bedroom TV",
    "ip": "10.20.30.40",
    "mac": "A0:B1:C2:D3:E4:F5",
    "uuid": "A1"
}
```
