### ISSUE TITLE
ON/OFF and Art mode on Samsung The Frame

### ISSUE THREAD

**Issue by Stetocasa** [tavicu/homebridge-samsung-tizen#246]
Hi People, with the compatible Samsung The Frame 2019 the control has the function to switch ON/OFF in the same button to go to art mode (like a screen saver).
On Samsung remote, one press on the button go to art mode, long pressure switch on/off the TV.
With this plugin, the power off let the tv in art mode, so no possibility to really switch off.
To really switch off the tv now I have installed the Samsung SmartThings plugin creating a switch button to ON/OFF

Will be powerful to integrate the switch comand in this plugin

**Comment by Stetocasa** [comment]
Why you closed?

**Comment by tavicu** [comment]
Because the issue has been discussed before.

At the moment, an implementation for the support of Frame TVs has started but it has not been completed.

**Comment by Stetocasa** [comment]
Thanks for your feedback, I not found the discussion on this. Could you share the link? Thanks a lot for your work

**Comment by tavicu** [comment]
You can follow the indications from here if you want your tv to turn off when you switch it from home app.

https://github.com/tavicu/homebridge-samsung-tizen/issues/101#issuecomment-493863481
