### ISSUE TITLE
Unable to add to HomeKit

### ISSUE THREAD

**Issue by kylewalker2012** [tavicu/homebridge-samsung-tizen#247]
The tv did have me pair the device, but it still won't show up in HomeKit.  I keep getting the message below.

9/10/2020, 1:50:50 PM Livingroom TV
9/10/2020, 1:50:50 PM ---------------------
9/10/2020, 1:50:50 PM [Livingroom TV] Cannot read property 'forEach' of null

**Comment by anderslutzhoft** [comment]
I have the same issue
