### ISSUE TITLE
HomeKit can't find TV after re-pairing

### ISSUE THREAD

**Issue by anderslutzhoft** [tavicu/homebridge-samsung-tizen#248]
After removing the TV from HomeKit due to a re-install of homebridge, my Samsung The Frame 2019 can't be found as a nearby accessory. Before the re-install it worked with no issues.

The paring of the TV works.
The plugin shows a list of available applications in the log.
"UUID" has been changed several times with no luck.

I hope to find a solution, it worked perfectly before!

**Comment by saadatorama** [comment]
Having same issue. I did not re-install homebridge but the TV did a factory reset. I am on a Samsung Q series TV. After the factory reset, and reinstall of the homebridge plugin, the TV is not being found. Samsung DID have an OS update for my TV that I am having issues with.

**Comment by apexad** [comment]
If you have https://www.npmjs.com/package/homebridge-config-ui-x. Go to http://homebridge.local/settings and you will have several options to unpair external accessories  and/or delete cached accessories.

**Comment by anderslutzhoft** [comment]
Thanks for the response!
I am using hoobs. Is there a way through the terminal?

**Comment by tavicu** [comment]
do you set the config like "UUID" or "uuid"? cause the correct value is "uuid" with small letters

**Comment by saadatorama** [comment]
> If you have https://www.npmjs.com/package/homebridge-config-ui-x. Go to http://homebridge.local/settings and you will have several options to unpair external accessories and/or delete cached accessories.

Solved, thanks for the response

**Comment by tavicu** [comment]
Awesome. Could you tell us how? Maybe it will help others in the future :)

**Comment by saadatorama** [comment]
> Awesome. Could you tell us how? Did you used @apexad suggestion? Maybe it will help others in the future :)

Clearing the application cache resolved it. I use homebridge config UI and there’s an option in settings, removing it allowed me to re-pair the accessories.

**Comment by apexad** [comment]
@anderslutzhoft I am not familiar with HOOBS but it has to have a similar option in the UI.  You should consult HOOBS support to check.

**Comment by iMuadh** [comment]
> If you have https://www.npmjs.com/package/homebridge-config-ui-x. Go to http://homebridge.local/settings and you will have several options to unpair external accessories and/or delete cached accessories.

It is working with me. Thanks
