### ISSUE TITLE
Run Applications with siri?

### ISSUE THREAD

**Issue by adtoth** [tavicu/homebridge-samsung-tizen#249]
Is there any way to trigger applications with Siri?
And is it possible to combine applications with actions? For example, I'd like to start Spotify, and select an account, select the first album and start playing.

**Comment by thomasintrees** [comment]
Well, I have a simple solution using Shortcuts. You can access the Samsung TV in Shortcuts and you are also able to select the Apps you have made available in HomeKit like Spotify, etc. Once the shortcut is created, you can use Siri to start it. I haven’t been able to add any other key stroke or other parameters so far.

**Comment by adtoth** [comment]
Thanks a lot, I'll give it a try ;)
