### ISSUE TITLE
TV name is reset

### ISSUE THREAD

**Issue by Andrey1One** [tavicu/homebridge-samsung-tizen#251]
TV names are randomly reset in homekit. Maybe once a week, or several times a day.

<img width="717" alt="Снимок экрана 2020-09-19 в 16 44 56" src="https://user-images.githubusercontent.com/58969179/93668768-7e0cdf80-fa97-11ea-9124-29772084d61d.png">
<img width="705" alt="Снимок экрана 2020-09-19 в 16 45 02" src="https://user-images.githubusercontent.com/58969179/93668770-7fd6a300-fa97-11ea-9b6a-c5c8603d4c95.png">

**Comment by Andrey1One** [comment]
![Uploading 5078F82E-4D12-4A3D-93E9-CC967EC8B564.jpeg…]()

**Comment by Andrey1One** [comment]
![95DF9C8A-8330-40A0-B6F6-B634FEC41F6F](https://user-images.githubusercontent.com/58969179/94192742-089a7800-feb8-11ea-8f91-8782a584d169.jpeg)
![156C7989-5E2A-461A-8A82-563DC885B267](https://user-images.githubusercontent.com/58969179/94192745-09cba500-feb8-11ea-94da-138de7146dc6.jpeg)

**Comment by tavicu** [comment]
Hi. Don't know how to help you!
The name of the tv is set from the config and it's set only when the homebridge server is started

**Comment by Andrey1One** [comment]
bad news.  I also don’t know what the problem is.  The name is dumped into the homebridge and then into the homekit.

**Comment by tavicu** [comment]
Maybe one of the other plugins change things that it shouldn't.

Me for example i have set multiple instances of Homebridge! That way if one of the instances has problems, only a few accessories will not work
Check the homebridge docker. It's easy to set it up :)

**Comment by Andrey1One** [comment]
I don't have other instances and I have new problem:
one of the two TVs doesn’t want to connect to the homekit.
I managed to connect several times, but immediately disappears into the homekit.
And several random devices thrown through the home assistant have the status "no answer", although they are controlled from the homekit.
Full reinstallation system don't help.
