### ISSUE TITLE
TV only shows power (iOS14)

### ISSUE THREAD

**Issue by psiberfunk** [tavicu/homebridge-samsung-tizen#252]
Unclear if this is an iOS 14 change or unrelated, but my 2016 Tizen-powered TV only displays a power switch on the iOS side, even though it the homebridge side can enumerate apps (app_list: true) and such.  Any idea what could be causing this ? I've tried uninstalling and reinstalling and blowing away the config in addition to checking that http://192.168.2.6:8001/api/v2/ works as expected (it does, dumps the whole JSON with capabilities listing).

Power DOES work properly here, and so do switches (see below).  Pairing step on first time is allowed, as instructed.  Clearly the homebridge instance can control the TV, but what iOS sees is just a simple on/off button.. even though it seems to treat it like a TV (TV icon shown, at least).

Model from API JSON:  "model": "16_JAZZM_UHD",
    "modelName": "UN65KS8000",

**Comment by psiberfunk** [comment]
I should add:  when i try the sample config in the instructions, I can add custom switches , which do show up in iOS as on/off switches.. but still no volume control unless I want to toggle an on/off switch every time to move the volume by a single unit.. ?  I can't help but feel like i'm missing something or something changed in iOS 14 with how TVs are represented?

**Comment by tavicu** [comment]
Hi. Nothing changed!
By default you only get the on/off toggle! Everything else needs to be configured.

App list true only prints the ids of apps in console. Then you need to configure the inputs. https://github.com/tavicu/homebridge-samsung-tizen/wiki/Inputs

The volume of TV can be changed only from the control center, not from the home app.

**Comment by psiberfunk** [comment]
Ah , ok , I misunderstood then !  Perhaps add a comment in the setup instructions for the morons like me and close the issue ?
