### ISSUE TITLE
Can send commands with input sources, but not launch apps

### ISSUE THREAD

**Issue by mectorfector** [tavicu/homebridge-samsung-tizen#255]
Great plugin!

As the title tells you, I am having difficulties using your plugin...
I can send commands to the TV like the default Live TV example you have made. However, I cannot launch any apps, installed from app store or natively installed -- none launch! :-(

Could anyone help?

**Comment by Akira-Maia** [comment]
Hey mectorfector,

You'r not alone with this, having the same issue. What Tizen version and model is your TV on? The app id number values don't seem to be working for me, and I thought it might be to latest version of Tizen or the specific country your in using different id codes for apps. 
Anyway on other thread https://github.com/tavicu/homebridge-samsung-tizen/wiki/Applications
they suggest running "homebridge tizen-apps" and it will show a table with the app ids. Haven't got this to work for me. Turned on "app_list": "true" didn't work either for revealing app id codes but would recommend it on. The workaround I've got is to use inputs. So if you use this and change the ip, mac, and make the menuitems names to correspond to the apps what's on your SmartHub, add this (disclaimer I'm pretty new to this and there are probably much better solutions but hope it helps anyone in this community)

"devices": [
                {
                    "name": "TV",
                    "ip": "your.ip",
                    "mac": "your.TV.MAC dress",
                    "inputs": [
                        {
                            "name": "Home",
                            "type": "command",
                            "value": [
                                "KEY_HOME",
                                "KEY_RETURN"
                            ]
                        },
                        {
                            "name": "MenuItem1",
                            "type": "command",
                            "value": [
                                "KEY_HOME",
                                "KEY_RIGHT",
                                "KEY_ENTER"
                            ]
                        },
                        {
                            "name": "MenuItem2",
                            "type": "command",
                            "value": [
                                "KEY_HOME",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_ENTER"
                            ]
                        },
                        {
                            "name": "MenuItem3",
                            "type": "command",
                            "value": [
                                "KEY_HOME",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_ENTER"
                            ]
                        },
                        {
                            "name": "MenuItem4",
                            "type": "command",
                            "value": [
                                "KEY_HOME",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_ENTER"
                            ]
                        },
                        {
                            "name": "MenuItem",
                            "type": "command",
                            "value": [
                                "KEY_HOME",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_ENTER"
                            ]
                        },
                        {
                            "name": "MenuItem5",
                            "type": "command",
                            "value": [
                                "KEY_HOME",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_ENTER"
                            ]
                        },
                        {
                            "name": "MenuItem6",
                            "type": "command",
                            "value": [
                                "KEY_HOME",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_ENTER"
                            ]
                        },
                        {
                            "name": "MenuItem7",
                            "type": "command",
                            "value": [
                                "KEY_HOME",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_ENTER"
                            ]
                        },
                        {
                            "name": "MenuItem",
                            "type": "command",
                            "value": [
                                "KEY_HOME",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_ENTER"
                            ]
                        },
                        {
                            "name": "MenuItem8",
                            "type": "command",
                            "value": [
                                "KEY_HOME",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_ENTER"
                            ]
                        },
                        {
                            "name": "MenuItem9",
                            "type": "command",
                            "value": [
                                "KEY_HOME",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_ENTER"
                            ]
                        },
                        {
                            "name": "MenuItem10",
                            "type": "command",
                            "value": [
                                "KEY_HOME",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_ENTER"
                            ]
                        }
                    ]
                }

**Comment by mectorfector** [comment]
> Hey mectorfector,
> 
> You'r not alone with this, having the same issue. What Tizen version and model is your TV on? The app id number values don't seem to be working for me, and I thought it might be to latest version of Tizen or the specific country your in using different id codes for apps.
> Anyway on other thread https://github.com/tavicu/homebridge-samsung-tizen/wiki/Applications
> they suggest running "homebridge tizen-apps" and it will show a table with the app ids. Haven't got this to work for me. Turned on "app_list": "true" didn't work either for revealing app id codes but would recommend it on. The workaround I've got is to use inputs. So if you use this and change the ip, mac, and make the menuitems names to correspond to the apps what's on your SmartHub, add this (disclaimer I'm pretty new to this and there are probably much better solutions but hope it helps anyone in this community)
Hey akira-maia,
I live in Denmark, Europe, and couldn't get the app list working either. @tavicu suggests running homebridge in debug mode, which should get the app list working. I'm currently at work and won't be able to test or reply with tizen version right now.
I also ended up temporarily using input commands (instead of app IDs) and that naturally works.
I'll run homebridge in debug mode asap, and will do my best to reply.
I'm thinking the solution is debug mode, running app list, and then applying those app IDs if they deviate from the ones listed in the plugin wiki (perhaps due to new update or different country)

**Comment by MarkBarbieri** [comment]
>{
"name": "MenuItem10",
"type": "command",
"value": [
"KEY_HOME",
"KEY_RIGHT",
"KEY_RIGHT",
"KEY_RIGHT",
"KEY_RIGHT",
"KEY_RIGHT",
"KEY_RIGHT",
"KEY_RIGHT",
"KEY_RIGHT",
"KEY_RIGHT",
"KEY_RIGHT",
"KEY_RIGHT",
"KEY_RIGHT",
"KEY_ENTER"
]
}

You can also do things like:
```
"KEY_RIGHT*3"            // Same as 3 presses of KEY_RIGHT
```
or 
```
"KEY_LEFT*2s"           // Same has holding down key for 2secs
```

**Comment by tavicu** [comment]
Hei Guys. Yeah, it looks like some features where removed/changed from the latest firmware.
But right now in my country i am on the latest firmware and works without problems. Probably it was not pushed yet in my country
