### ISSUE TITLE
Status of TV has dropped off since iOS 14.0.1 upgrade

### ISSUE THREAD

**Issue by woodgieboodgie** [tavicu/homebridge-samsung-tizen#256]
Just noticed since the upgrade to 14.0.1 the status of the TV's no longer appear at the top of the HomeKit app.  Was convenient to see at a glance whether the TVs were on or not.

Great plugin, keep up the good work.

**Comment by Final-Hawk** [comment]
Just noticed this as well, also none of my commands work so it is basically a dummy switch that is always off.

**Comment by tavicu** [comment]
Unfortunately that's in Apple's kitchen :) 

We have no power to change how the Home app display things ...

**Comment by woodgieboodgie** [comment]
The status area remains but is presented differently.  Numerous other bulbs, sensors, thermostat can advertise their status in the new format and I was hoping the TV would fall into the same category.
