### ISSUE TITLE
volume controle 

### ISSUE THREAD

**Issue by lordchris78** [tavicu/homebridge-samsung-tizen#257]
Hello,
it is possible to get the volume as a slider instead of a switch or lamp
 i have a samsung samsung q90 series.
and works perfectly

**Comment by boomcreativemartin** [comment]
if you use the apple remote in control center, you can use the ios volume buttons to adjust volume, rather than have a button in home kit.

**Comment by sanskardhanda** [comment]
Can I use remote with Apple TV remote app?

**Comment by boomcreativemartin** [comment]
I dont believe thats possible as it is only for apple tv boxes. But all IOS devices get the remote in the command center, you just have to enable it in Settings.

**Comment by lordchris78** [comment]
Thank you
