### ISSUE TITLE
Add additional keys for apple remote on ios

### ISSUE THREAD

**Issue by boomcreativemartin** [tavicu/homebridge-samsung-tizen#258]
On the [support page](https://support.apple.com/en-us/HT201664) for the remote tv app, it shows the screenshot has other keys for display search and mute. is it possible to implement these through the json Keymapping? I've tried allocating them to NEXT TRACK to try it out, however, I can't get it to work.

is this possible, or can you add functionality for it?

M

**Comment by apexad** [comment]
These extra functions are only available for an Apple TV, not a HomeKit TV.  The screenshot on the support page shows an Apple TV.
