### ISSUE TITLE
Status of TV-accessory takes 10-30 seconds to update.

### ISSUE THREAD

**Issue by WibiNorg** [tavicu/homebridge-samsung-tizen#259]
Hey there, 

The status of TV-accessory takes 10-30 seconds to update when I manually turn it of with the remote. 
Changing the refresh-rate in the config didn't help, also because it already was on it's lowest. 
Also sometimes it doesn't even change at all and the TV appears "ON" in Homekit when in fact it's off.

Any suggestions?

**Comment by tavicu** [comment]
You can't do anything. After turning off, the TV still responds for a good seconds to everything. It's still ON but with the display OFF.

https://github.com/tavicu/homebridge-samsung-tizen/wiki/Common-Issues#--delay-when-turning-tv-off-from-remote
