### ISSUE TITLE
Custom delay

### ISSUE THREAD

**Issue by Sp9nky** [tavicu/homebridge-samsung-tizen#262]
Is there a way i can set a custom delay after each command in switches section?

**Comment by capote2345** [comment]
I Try this, and run

                            "name": "TDT",
                            "command": [
                                "KEY_SOURCE",
                                [
                                    {
                                        "delay": 1200
                                    }
                                ],
                                "KEY_LEFT",
                                "KEY_ENTER"
                            ]
                        },

**Comment by tavicu** [comment]
Hi. Nope, there is no option to set a delay right now between commands!

**Comment by MarkBarbieri** [comment]
Just try adding a non-existant command with a time factor.  Works fine for me.

"PAUSE*3s"
```
                    {
                            "name": "Guide",
                            "power": true,
                            "command": [
                                "KEY_SOURCE",
                                "PAUSE*0.5s",
                                "KEY_LEFT*2s",
                                "KEY_ENTER",
                                "KEY_GUIDE"
                            ]
                        }
```

**Comment by tavicu** [comment]
Awesome! Didn't think of that :D
