### ISSUE TITLE
Compatibility of new QLED 2020 Q series

### ISSUE THREAD

**Issue by jordindc** [tavicu/homebridge-samsung-tizen#264]
Hi, just to confirm.

I've installed the plugin to connect my two Samsung Q series (Q60T and Q80T) 2020, to homekit. My issue is that, although the TV is shown in Home app, I just can switch it on and off, but any of the other button, apps or commands don't work, despite they are also shown in the homekit device.

Looking at the troubleshooting chapter, this means probably that my tv's are not compatible with the plugin (with the API in fact). IP:8001/api/v2/ works and show all the information expected, but the only functionality that works is On and Off TV.

As we are talking about the newest 4k series of Samsung, can we expect that they will be  compatible soon?

Thanks and regards,

JN
JN

**Comment by tarakanof** [comment]
Q80T work fine with default iphone remote. 
```
{
            "name": "SamsungTizen",
            "devices": [
                {
                    "name": "Samsung Q80",
                    "ip": "192.168.77.98",
                    "mac": "4A:C5:7E:B6:A8:65",
                    "switches": [
                        {
                            "name": "YouTube",
                            "app": "111299001912",
                            "power": true
                        }
                    ]
                }
            ],
            "platform": "SamsungTizen"
```

**Comment by tavicu** [comment]
From what I can see Samsung will discontinue the current app (that we are using the same enpoints) and it want to force people to use Smart Things app.

I don't have a 2020 TV so i won't be able to offer support for their new implementation (if it will be one available to others and not just for their apps).

I will keep an eye on this and if it will be something easy  to implement, i will try! But nothing i can say for sure now ...

**Comment by jordindc** [comment]
Thanks, @tarakanof.

I've used the standard config you shared and it, effectively, works. What happens is that the standard configuration using "inputs" section, what produces an much better usability, doesn't work in my case. Have you tried "inputs" section for "apps" like Netflix?

**Comment by claude5555** [comment]
Hi,

I habe a Q series of 2019. It also works fine, but it is impossible to add keys and change some command from keys. What is the exact syntax for keys? Where must be located in config.json? After input? 
I can add switches connected to dedicated commands. It's a little bit complicated to change programme or volume with a switch.

Thanks for your help

Kind regards

**Comment by preamptive** [comment]
Has anyone tried using the developer debug mode on the 2020 tv’s to work out the new commands? I have everything working but had to use the key press commands to open apps. Would be great to actually get the proper input commands. Will probably give this a try when I have some time.

https://developer.samsung.com/smarttv/develop/extension-libraries/smart-view-sdk/receiver-apps/debugging.html

**Comment by mschinis** [comment]
I have a 2019 Q60R and tried opening apps using the guide on the wiki, but the apps don't open either. I can't see any logs in the homebridge logs either.

**Comment by simoa** [comment]
> Hi, just to confirm.
> 
> I've installed the plugin to connect my two Samsung Q series (Q60T and Q80T) 2020, to homekit. My issue is that, although the TV is shown in Home app, I just can switch it on and off, but any of the other button, apps or commands don't work, despite they are also shown in the homekit device.
> 
> Looking at the troubleshooting chapter, this means probably that my tv's are not compatible with the plugin (with the API in fact). IP:8001/api/v2/ works and show all the information expected, but the only functionality that works is On and Off TV.
> 
> As we are talking about the newest 4k series of Samsung, can we expect that they will be compatible soon?
> 
> Thanks and regards,
> 
> JN
> JN

Hi, anyone with the new Samsung tv 2020 is able to run this ?

(Open Netflix)
curl -X POST -i 'http://IP:8001/api/v2/applications/11101200001'

**Comment by matthijsf** [comment]
> > Hi, just to confirm.
> > I've installed the plugin to connect my two Samsung Q series (Q60T and Q80T) 2020, to homekit. My issue is that, although the TV is shown in Home app, I just can switch it on and off, but any of the other button, apps or commands don't work, despite they are also shown in the homekit device.
> > Looking at the troubleshooting chapter, this means probably that my tv's are not compatible with the plugin (with the API in fact). IP:8001/api/v2/ works and show all the information expected, but the only functionality that works is On and Off TV.
> > As we are talking about the newest 4k series of Samsung, can we expect that they will be compatible soon?
> > Thanks and regards,
> > JN
> > JN
> 
> Hi, anyone with the new Samsung tv 2020 is able to run this ?
> 
> (Open Netflix)
> curl -X POST -i 'http://IP:8001/api/v2/applications/11101200001'

Unfortunately is does not work;

```
root@srv-001:~# curl -X POST -i 'http://192.168.0.5:8001/api/v2/applications/11101200001'
HTTP/1.1 404 Not Found
content-type: application/json; charset=utf-8
content-length: 55

{"code":404,"message":"Not found error.","status":404}
```

**Comment by Maykel1969** [comment]
Same problem here with the Q80T. Only the power button appears and works correctly.
No other button shows up.
Anything I van try?

**Comment by Fez92** [comment]
Hi,

I'm sorry if something in this post does not match GitHub requirements.

I have a Q90 2020 and launching apps is not working. I tried to understand why:

- curl -X POST -i 'http://feztv:8001/api/v2/applications/111299001912' worked and opened YouTube (worked on Netflix 3201907018807, YouTube 111299001912, Disney+ 3201901017640, Spotify 3201606009684, missing NowTV and DAZN IDs)

- In the plugin I received this error:

> InvalidAppIdError: No application found with this id (111299001912)
    at WebSocketSecure.openApplication (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/methods/ws.js:58:19)

- Looking at line 58 it seems that the list of installed apps does not contain the id 111299001912. But this is valid for the cURL. So I think that something changed in how to retrieve IDs of application installed

On this last statement I found this discussion #https://github.com/ollo69/ha-samsungtv-smart/issues/35 which explains how to retrieve app IDs.

I hope this can help @tavicu

**Comment by tavicu** [comment]
Hei @Fez92, Samsung discontinued the app that used current endpoints and probably they removed the endpoints from newer TVs.

I have read all replies from that issue but it doesn't help! Even if we implement the new method of opening apps will not help since all "Inputs" implementation will not work as it should.

We will not be able to extract the App IDs in a simple way (not everybody will want to install the samsung sdk to get installed apps, also the IDs are different based on location so a public list will not help) and we will not be able to get the status of application so we can tell if it's active/open or not.

I will look more into it but right now the only option looks like creating a new method for `Switches` where you can open an app by this endpoint.

But it will be complicated since everybody will start asking for IDs and i will not be able to provide them.
So implementing a method that I can't fully support doesn't look to good of a decision right now.

Another method that can work now is creating a list of keys for a Switch that will open that App. Just like we do with HDMI inputs.
`{"name": "Live TV",  "type": "command", "value": ["KEY_SOURCE", "KEY_LEFT*3", "KEY_ENTER"]},`

I will try to document myself as well as possible to make the right decision but it will be hard since all of my TVs are having current endpoints as working (and one of them is from 2020 :D)

**Comment by Fez92** [comment]
Hi @tavicu,

thank you for the quick reply.
And what about changing the way you do that call? Try to explain: instead of searching the ID given by the request "...v2/applications/<given_ID>" among the ones of the app installed why you cannot call the POST and catch eventual errors? If you try the cURL with the post on a fake ID it will return 404. 
So no check before, fire and try, and then eventually catch 404 error.

In this way you are free of which IDs are currently present on TV. As long as Samsung does not block the POST call we are done. Do you agree?

PS: personally I don't like `Switches` very much :p

**Comment by tavicu** [comment]
Yup, i understand what you are saying but that's just opening an app, not Inputs functionality :)

Inputs should also have a method of allowing to check the status so you can tell if that app is active or not.
Otherwise will be just a switch, and not a pretty one :P

I could implement this, not a problem. But i still don't like that i don't have an option to get the IDs of installed applications.

The plugin should target users without experience who only knows how to click Install :D, forcing them to install SDKs and other magic tricks will not be an option.

Could you help me with some informations? Does the option to list installed applications work on your TV?

Also could you open this link and tell me if you have any response? Or replace the id with one you have and you know it's installed.
http://192.168.10.202:8001/api/v2/applications/11101200001

And this request, `v2/applications/` is used only to get the status of application, it's not used to get the installed apps. 
The list of the apps is requested via WebSocket

**Comment by tavicu** [comment]
And another thing, if you could get me a copy of what `http://TV_IP:8001/api/v2/` outputs. I am interested in what value `isSupport` has.

**Comment by Fez92** [comment]
Ok, backing home from work tonight I will provide you every information you are asking for.

About the idea I had, I understand your points (app active or not, having the list of installed apps, etc) but rather that not working I think it can be a starting point :) 
Anyway I'm glad to help!

**Comment by tavicu** [comment]
From what i can read we have a flag on the TV info (from /api/v2) if it supports or not opening the apps via websocket (method used right now).

if that is right and the flag is ok, we can automate the code and call the `curl` method to open apps.
But still, getting the IDs will remain a problem :)

**Comment by keithsamsung** [comment]
I have been looking at similar ways to get the ID's but didnt get quite as far as Fez92 will try his method this evening.

with http://10.0.1.2:8001/api/v2/applications/11101200001 i get response {"code":404,"message":"Not found error.","status":404}

and with http://10.0.1.2:8001/api/v2/outputs i get response SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data also the same SyntaxError for http://10.0.1.2:8001/ws/apps/Netflix

Dont know if this is of any use but this is what i get when i go to http://10.0.1.2:8001/api/v2/

![Image 002](https://user-images.githubusercontent.com/75796792/109951193-4b694300-7cd5-11eb-93d2-f5c56754a1e8.png)

Would be great to get this working and also happy to help where I can.

**Comment by Fez92** [comment]
@keithsamsung try using the IDs of my previous messages, if I remember correctly http://10.0.1.2:8001/api/v2/applications/<APP_ID> will display some informations about the app, such as name, the ID again etc.
But I think 11101200001 is not valid anymore, try with 3201907018807 for Netflix.

Thank you

**Comment by tavicu** [comment]
Hei @keithsamsung, thank's for your help. 
On http://10.0.1.2:8001/api/v2/applications/11101200001 looks like it didn't find the app.

Are you having the same problems? Can't get the installed apps listed and also can't open any app?
Cause your `api/v2` output is identical to mine (except names, ips ofc :D)

**Comment by keithsamsung** [comment]
Yep same issue cant get app list or open any direct app id's

now that is strange! with your app number http://10.0.1.2:8001/api/v2/applications/3201907018807
I get response...
{"id":"3201907018807","name":"Netflix","running":true,"version":"5.2.550","visible":false}

but when using  "name": "Netflix",
                            "type": "app",
                            "value": "3201907018807"

the comand doesnt work.

**Comment by tavicu** [comment]
Hmm, nice that the endpoint is working. We can get the status of the app.
Probably they changed the app for the newer TVs (new id and version) cause my Netflix app looks like this:
`{"id":"11101200001","name":"Netflix","running":false,"version":"7.0.000","visible":true}`

Ok, so we know we can launch the apps (by changing the code) and we can get the status of the apps.

Still sucks that we can't get the list of applications with an API. I will search and see if we have an option and maybe ask you to do some Frankenstein calls.

@Fez92  when you get home please still run the commands. I'm very interested to see what your `isSupport` output is. Cause from what i read the `EDEN_available` should be `false` on your tvs but looks like on @keithsamsung is `true`

**Comment by keithsamsung** [comment]
no the new code still doesnt open the app for me.

[04/03/2021, 10:04:41] [TV] [DEBUG] InvalidAppIdError: No application found with this id (3201907018807)
    at WebSocketSecure.openApplication (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/methods/ws.js:58:19)

**Comment by Fez92** [comment]
@keithsamsung try to use the cURL POST that I have posted last night, it works for me.
Using the plugin of @tavicu is not working, as written above, because it searches for IDs installed in TV which is an empty list (error at line 58 is not at lauch but before in a previous check)

**Comment by tavicu** [comment]
You, as @Fez92 said, I have to make some changes tot he code in order to launch the application (with the new id) from the plugin :)

So it's ok for not working and getting that error.

**Comment by keithsamsung** [comment]
ahh ok yes so this works.....

curl -X POST -i "http://10.0.1.2:8001/api/v2/applications/111299001912"
HTTP/1.1 200 OK
content-type: application/json; charset=utf-8
content-length: 5

true

**Comment by tavicu** [comment]
Can one of you make these steps?
1. Make sure `app_list` is set to `true` in `config.json` so it will try to get the apps at load
2. Run the homebridge in debug mode with `homebridge -D`
3. Check the console for everything that outputs from TV and post it here.

I'm interested especially for something that looks like this:
```
[3/4/2021, 1:39:11 PM] [Game TV] [DEBUG] {
  data: {
    data: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  event: 'ed.installedApp.get',
  from: 'host'
}
```

**Comment by keithsamsung** [comment]
like this.....

[04/03/2021, 09:29:47] [TV] [DEBUG] { data:
   { clients: [ [Object] ],
     id: '25717f2d-dcd0-4714-a97d-9053741f95be' },
  event: 'ms.channel.connect' }
[04/03/2021, 09:29:47] [TV] [DEBUG] { method: 'ms.channel.emit',
  params: { data: '', to: 'host', event: 'ed.installedApp.get' } }
TV

**Comment by Fez92** [comment]
@tavicu tried yesterday and not working, here is logs:

> [3/3/2021, 9:40:30 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[3/3/2021, 9:40:30 PM] [HB Supervisor] Started Homebridge v1.3.1 with PID: 92492
Initializing HAP-NodeJS v0.9.2...
[3/3/2021, 9:40:30 PM] Loaded config.json with 0 accessories and 2 platforms.
[3/3/2021, 9:40:31 PM] Loaded 0 cached accessories from cachedAccessories.
[3/3/2021, 9:40:31 PM] ---
[3/3/2021, 9:40:31 PM] Loaded plugin: homebridge-blinds-cmd@3.1.0
[3/3/2021, 9:40:31 PM] Registering platform 'homebridge-blinds-cmd.Blinds Command'
[3/3/2021, 9:40:31 PM] ---
[3/3/2021, 9:40:31 PM] Loaded plugin: homebridge-config-ui-x@4.39.1
[3/3/2021, 9:40:31 PM] Registering platform 'homebridge-config-ui-x.config'
[3/3/2021, 9:40:31 PM] ---
[3/3/2021, 9:40:31 PM] Loaded plugin: homebridge-samsung-tizen@4.3.6
[3/3/2021, 9:40:31 PM] Registering platform 'homebridge-samsung-tizen.SamsungTizen'
[3/3/2021, 9:40:31 PM] ---
[3/3/2021, 9:40:31 PM] Loading 2 platforms...
[3/3/2021, 9:40:31 PM] [Config] Initializing config platform...
[3/3/2021, 9:40:31 PM] [Config] Running in Service Mode
[3/3/2021, 9:40:31 PM] [SamsungTizen] Initializing SamsungTizen platform...
Preparing Advertiser for 'Homebridge 429E D9FD' using bonjour-hap backend!
Setup Payload:
X-HM://0024XCZHK382P
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 880-59-816 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge 429E D9FD' using bonjour-hap backend!
[3/3/2021, 9:40:31 PM] Homebridge v1.3.1 (Homebridge 429E) is running on port 51054.
Preparing Advertiser for 'Fez's TV 4D88' using bonjour-hap backend!
Starting to advertise 'Fez's TV 4D88' using bonjour-hap backend!
[3/3/2021, 9:40:31 PM] Fez's TV 4D88 is running on port 54674.
[3/3/2021, 9:40:31 PM] Please add [Fez's TV 4D88] manually in Home app. Setup Code: 880-59-816
[3/3/2021, 9:40:40 PM] [Fez's TV] [DEBUG] {
  data: { clients: [ [Object] ], id: '4fd68fb0-f05b-402-b8bd-7b873a9ff7fc' },
  event: 'ms.channel.connect'
}
[3/3/2021, 9:40:41 PM] [Fez's TV] [DEBUG] {
  method: 'ms.channel.emit',
  params: { data: '', to: 'host', event: 'ed.installedApp.get' }
}
Fez's TV
---------------------
[3/3/2021, 9:42:52 PM] [Fez's TV] [DEBUG] {
  method: 'ms.channel.emit',
  params: { data: '', to: 'host', event: 'ed.installedApp.get' }
}
[3/3/2021, 9:42:53 PM] [Fez's TV] [DEBUG] InvalidAppIdError: No application found with this id (111299001912)
    at WebSocketSecure.openApplication (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/methods/ws.js:58:19)
    at Remote.openApplication (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/remote.js:108:9)
    at Input.setInput (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/services/input.js:39:13)
    at /usr/local/lib/node_modules/homebridge-samsung-tizen/lib/services/television.js:106:13

**Comment by tavicu** [comment]
So it only sends the request to get installed apps but don't get the response. not even an error that the event does not exists

**Comment by tavicu** [comment]
Ok. I just pushed a new version which uses the `curl` method to open applications. You can update the plugin then try it :)
https://github.com/tavicu/homebridge-samsung-tizen/commit/1bbd57eef1fd84dbcc415caebd2965bf0cedb984

**Comment by keithsamsung** [comment]
That works perfectly! So now we just need to start a new list of app id's for the 2020 tv's

**Comment by tavicu** [comment]
Yeah, i will think of a way to update the Wiki so it will adapt the newer and older TVs

**Comment by Fez92** [comment]
Thanks @tavicu tonight I will try it!!
@keithsamsung I agree, @tavicu is it possible to load these IDs in your wiki page about apps?

For now:

- Netflix 3201907018807 
- YouTube 111299001912 
- Disney+ 3201901017640 
- Spotify 3201606009684 

Missing NowTV and DAZN IDs in which I'm very interested in.

**Comment by keithsamsung** [comment]
Here is what my tv spat out of Tizen Studio...

[ 1 - Prime Video]
- App Name                            :     Prime Video
- App Version                         :     2.01.26
- App ID - WAS                        :     3201910019365
- App ID - Tizen                      :     org.tizen.primevideo
-----------------------------------------------------------------------------------------------------
[ 2 - BBC iPlayer]
- App Name                            :     BBC iPlayer
- App Version                         :     1.1.40
- App ID - WAS                        :     3201601007670
- App ID - Tizen                      :     DqEoaplKlw.bbchybrid
-----------------------------------------------------------------------------------------------------
[ 3 - ITV Hub]
- App Name                            :     ITV Hub
- App Version                         :     16.0.13
- App ID - WAS                        :     121299000089
- App ID - Tizen                      :     OEvCiupaFR.ITVHub
-----------------------------------------------------------------------------------------------------
[ 4 - Apple TV]
- App Name                            :     Apple TV
- App Version                         :     6.2.2
- App ID - WAS                        :     3201807016597
- App ID - Tizen                      :     com.samsung.tv.ariavideo
-----------------------------------------------------------------------------------------------------
[ 5 - Rakuten TV]
- App Name                            :     Rakuten TV
- App Version                         :     5.0.3
- App ID - WAS                        :     3201511006428
- App ID - Tizen                      :     vbUQClczfR.Wuakitv
-----------------------------------------------------------------------------------------------------
[ 6 - YouTube]
- App Name                            :     YouTube
- App Version                         :     2.1.498
- App ID - WAS                        :     111299001912
- App ID - Tizen                      :     9Ur5IzDKqV.TizenYouTube
-----------------------------------------------------------------------------------------------------
[ 7 - discovery+]
- App Name                            :     discovery+
- App Version                         :     1.0.8
- App ID - WAS                        :     3201803015944
- App ID - Tizen                      :     pIaMf8YZyZ.whiteLabelTal
-----------------------------------------------------------------------------------------------------
[ 8 - UKTV Play]
- App Name                            :     UKTV Play
- App Version                         :     2.9.1
- App ID - WAS                        :     3201806016432
- App ID - Tizen                      :     VQr0RGkyS9.UKTVPlay
-----------------------------------------------------------------------------------------------------
[ 9 - All 4]
- App Name                            :     All 4
- App Version                         :     6.25.401
- App ID - WAS                        :     111299002148
- App ID - Tizen                      :     OCaxbgg9v6.chfourctv
-----------------------------------------------------------------------------------------------------
[ 10 - Explore Google Assistant]
- App Name                            :     Explore Google Assistant
- App Version                         :     0.20.10081
- App ID - WAS                        :     3202004020674
- App ID - Tizen                      :     AkhP5nCr24.GoogleAssistant
-----------------------------------------------------------------------------------------------------
[ 11 - Amazon Alexa]
- App Name                            :     Amazon Alexa
- App Version                         :     0.20.08060
- App ID - WAS                        :     3202004020626
- App ID - Tizen                      :     AQKO41xyKP.AmazonAlexa
-----------------------------------------------------------------------------------------------------
[ 12 - My5]
- App Name                            :     My5
- App Version                         :     162.63.51
- App ID - WAS                        :     121299000612
- App ID - Tizen                      :     EkzyZtmneG.My5
-----------------------------------------------------------------------------------------------------
[ 13 - Samsung Health]
- App Name                            :     Samsung Health
- App Version                         :     1.2.6
- App ID - WAS                        :     3201909019211
- App ID - Tizen                      :     com.samsung.tv.samsunghealth
-----------------------------------------------------------------------------------------------------
[ 14 - Internet]
- App Name                            :     Internet
- App Version                         :     3.1.11260
- App ID - WAS                        :     3201907018784
- App ID - Tizen                      :     org.tizen.browser
-----------------------------------------------------------------------------------------------------
[ 15 - SmartThings]
- App Name                            :     SmartThings
- App Version                         :     2.0.86
- App ID - WAS                        :     3201910019378
- App ID - Tizen                      :     com.samsung.tv.iotdashboard
-----------------------------------------------------------------------------------------------------
[ 16 - BritBox]
- App Name                            :     BritBox
- App Version                         :     5.1.72
- App ID - WAS                        :     3201909019175
- App ID - Tizen                      :     FHl9B04ug2.ITV
-----------------------------------------------------------------------------------------------------
[ 17 - Apple Music]
- App Name                            :     Apple Music
- App Version                         :     2.1.0
- App ID - WAS                        :     3201908019041
- App ID - Tizen                      :     org.tizen.apple.applemusic
-----------------------------------------------------------------------------------------------------
[ 18 - BBC Sounds]
- App Name                            :     BBC Sounds
- App Version                         :     1.0.0
- App ID - WAS                        :     3202003020365
- App ID - Tizen                      :     GR7TWEBh5d.BBCSounds
-----------------------------------------------------------------------------------------------------
[ 19 - NOW TV]
- App Name                            :     NOW TV
- App Version                         :     2.0.5
- App ID - WAS                        :     3201603008746
- App ID - Tizen                      :     1Qb6IoAcGC.NowTV
-----------------------------------------------------------------------------------------------------
[ 20 - TikTok]
- App Name                            :     TikTok
- App Version                         :     1.0.9
- App ID - WAS                        :     3202008021577
- App ID - Tizen                      :     9FhM0cODbY.TikTokTV
-----------------------------------------------------------------------------------------------------
[ 21 - Gallery]
- App Name                            :     Gallery
- App Version                         :     1.9.216
- App ID - WAS                        :     3201710015037
- App ID - Tizen                      :     com.samsung.tv.gallery
-----------------------------------------------------------------------------------------------------
[ 22 - eManual]
- App Name                            :     eManual
- App Version                         :     3.0.9
- App ID - WAS                        :     20202100002
- App ID - Tizen                      :     EJZZ9Mr6D2.emanual
-----------------------------------------------------------------------------------------------------
[ 23 - Netflix]
- App Name                            :     Netflix
- App Version                         :     5.2.550
- App ID - WAS                        :     3201907018807
- App ID - Tizen                      :     org.tizen.netflixapp
-----------------------------------------------------------------------------------------------------
[ 24 - YouTube Kids]
- App Name                            :     YouTube Kids
- App Version                         :     1.0.8
- App ID - WAS                        :     3201611010983
- App ID - Tizen                      :     5SLwh7m3En.TizenYouTubeKids
-----------------------------------------------------------------------------------------------------
[ 25 - Spotify  Music and Podcasts]
- App Name                            :     Spotify  Music and Podcasts
- App Version                         :     1.7.2
- App ID - WAS                        :     3201606009684
- App ID - Tizen                      :     rJeHak5zRg.Spotify
-----------------------------------------------------------------------------------------------------
[ 26 - Plex]
- App Name                            :     Plex
- App Version                         :     5.1.0
- App ID - WAS                        :     3201512006963
- App ID - Tizen                      :     kIciSQlYEM.plex
-----------------------------------------------------------------------------------------------------
[ 27 - Eurosport Player]
- App Name                            :     Eurosport Player
- App Version                         :     3.1.0
- App ID - WAS                        :     3201703012079
- App ID - Tizen                      :     OTVxm7JAu0.Eurosport
-----------------------------------------------------------------------------------------------------

**Comment by Fez92** [comment]
Hey guys,

tried new version 4.3.7: everything works except for NowTV, the id above here seems not working.

Thank you

PS: if you need help to implement recovery of all apps installed count on me as beta tester @tavicu

**Comment by simoa** [comment]
> Hey guys,
> 
> tried new version 4.3.7: everything works except for NowTV, the id above here seems not working.
> 
> Thank you
> 
> PS: if you need help to implement recovery of all apps installed count on me as beta tester @tavicu

appId": "3201603008746",
            "name": "Now TV"

appId": "3201607009920",
            "name": "DAZN"

**Comment by Fez92** [comment]
> > Hey guys,
> > tried new version 4.3.7: everything works except for NowTV, the id above here seems not working.
> > Thank you
> > PS: if you need help to implement recovery of all apps installed count on me as beta tester @tavicu
> 
> appId": "3201603008746",
> "name": "Now TV"
> 
> appId": "3201607009920",
> "name": "DAZN"

They are not working on Q90 2020:
![image](https://user-images.githubusercontent.com/11198581/110015971-ca399c80-7d24-11eb-9ed0-a15961d888c1.png)

**Comment by keithsamsung** [comment]
@Fez92 It looks like the only way to currently make sure you get the app id's for you tv is to follow the explaination you pointed me in the direction of....

Download and install Tizen Studio, the SDK (TV Extensions included) as outlined here https://developer.samsung.com/smarttv/develop/getting-started/setting-up-sdk/installing-tv-sdk.html

Put your TV in Developer Mode and connect to it as outlined here https://developer.samsung.com/smarttv/develop/getting-started/using-sdk/tv-device.html
 
 In Tizen Studio Device Manager, right clicked on the entry for the TV and selected Installed Web App List in the drop down menu.
 That returns the list of all the Web Apps installed on your TV and for each of them you can find the code as App ID - WAS

@tavicu Tizen studio uses a different port. I wonder if that makes a difference? port 26101

**Comment by tavicu** [comment]
Just installed the Tizen Studio. I will try to see if i can reverse engineering their method of getting the apps.
But most likely not since there ar other connections and using Developer Mode ...

**Comment by Fez92** [comment]
Here's mine, DAZN and NOWTV are different:

[ 1 - Netflix]
- App Name                            :     Netflix
- App Version                         :     5.2.550
- App ID - WAS                        :     3201907018807
- App ID - Tizen                      :     org.tizen.netflixapp
-----------------------------------------------------------------------------------------------------
[ 2 - Prime Video]
- App Name                            :     Prime Video
- App Version                         :     2.01.26
- App ID - WAS                        :     3201910019365
- App ID - Tizen                      :     org.tizen.primevideo
-----------------------------------------------------------------------------------------------------
[ 3 - Apple TV]
- App Name                            :     Apple TV
- App Version                         :     6.2.2
- App ID - WAS                        :     3201807016597
- App ID - Tizen                      :     com.samsung.tv.ariavideo
-----------------------------------------------------------------------------------------------------
[ 4 - YouTube]
- App Name                            :     YouTube
- App Version                         :     2.1.498
- App ID - WAS                        :     111299001912
- App ID - Tizen                      :     9Ur5IzDKqV.TizenYouTube
-----------------------------------------------------------------------------------------------------
[ 5 - Rakuten TV]
- App Name                            :     Rakuten TV
- App Version                         :     5.0.3
- App ID - WAS                        :     3201511006428
- App ID - Tizen                      :     vbUQClczfR.Wuakitv
-----------------------------------------------------------------------------------------------------
[ 6 - SmartThings]
- App Name                            :     SmartThings
- App Version                         :     2.0.86
- App ID - WAS                        :     3201910019378
- App ID - Tizen                      :     com.samsung.tv.iotdashboard
-----------------------------------------------------------------------------------------------------
[ 7 - Gallery]
- App Name                            :     Gallery
- App Version                         :     1.9.216
- App ID - WAS                        :     3201710015037
- App ID - Tizen                      :     com.samsung.tv.gallery
-----------------------------------------------------------------------------------------------------
[ 8 - Internet]
- App Name                            :     Internet
- App Version                         :     3.1.11260
- App ID - WAS                        :     3201907018784
- App ID - Tizen                      :     org.tizen.browser
-----------------------------------------------------------------------------------------------------
[ 9 - Apple Music]
- App Name                            :     Apple Music
- App Version                         :     2.1.0
- App ID - WAS                        :     3201908019041
- App ID - Tizen                      :     org.tizen.apple.applemusic
-----------------------------------------------------------------------------------------------------
[ 10 - Amazon Alexa]
- App Name                            :     Amazon Alexa
- App Version                         :     0.20.08060
- App ID - WAS                        :     3202004020626
- App ID - Tizen                      :     AQKO41xyKP.AmazonAlexa
-----------------------------------------------------------------------------------------------------
[ 11 - Scopri l'Assistente Google]
- App Name                            :     Scopri l'Assistente Google
- App Version                         :     0.20.10081
- App ID - WAS                        :     3202004020674
- App ID - Tizen                      :     AkhP5nCr24.GoogleAssistant
-----------------------------------------------------------------------------------------------------
[ 12 - RaiPlay]
- App Name                            :     RaiPlay
- App Version                         :     3.1.1
- App ID - WAS                        :     111399002034
- App ID - Tizen                      :     5im3FztIhW.RaiTVtizen
-----------------------------------------------------------------------------------------------------
[ 13 - eManual]
- App Name                            :     eManual
- App Version                         :     3.0.9
- App ID - WAS                        :     20202100002
- App ID - Tizen                      :     EJZZ9Mr6D2.emanual
-----------------------------------------------------------------------------------------------------
[ 14 - DAZN]
- App Name                            :     DAZN
- App Version                         :     1.69.9
- App ID - WAS                        :     3201806016390
- App ID - Tizen                      :     yu1NM3vHsU.DAZN
-----------------------------------------------------------------------------------------------------
[ 15 - Disney+]
- App Name                            :     Disney+
- App Version                         :     1.6.0
- App ID - WAS                        :     3201901017640
- App ID - Tizen                      :     MCmYXNxgcu.DisneyPlus
-----------------------------------------------------------------------------------------------------
[ 16 - Spotify  Musica e podcast]
- App Name                            :     Spotify  Musica e podcast
- App Version                         :     1.7.2
- App ID - WAS                        :     3201606009684
- App ID - Tizen                      :     rJeHak5zRg.Spotify
-----------------------------------------------------------------------------------------------------
[ 17 - NOW TV]
- App Name                            :     NOW TV
- App Version                         :     1.0.6
- App ID - WAS                        :     3201803015896
- App ID - Tizen                      :     jcz0WrZYdy.NOWTV
-----------------------------------------------------------------------------------------------------

**Comment by tavicu** [comment]
I have installed Tizen Studio and managed to get the apps but unfortunately nothing is shown in TV logs. So i won't be able to get a list.

But we will update the wiki with all IDs that we have and also post step by step on how to install Tizen Studio and get the apps :)

**Comment by keithsamsung** [comment]
compairing what @Fez92 and My Tizen studio app id dump it looks like every app version will have a new id. @Fez92 are there any updates for your now tv app?

[ 19 - NOW TV]

    App Name : NOW TV
    App Version : 2.0.5
    App ID - WAS : 3201603008746
    App ID - Tizen : 1Qb6IoAcGC.NowTV

[ 17 - NOW TV]

    App Name : NOW TV
    App Version : 1.0.6
    App ID - WAS : 3201803015896
    App ID - Tizen : jcz0WrZYdy.NOWTV

**Comment by tavicu** [comment]
It's possible to be different depending on the Region.

**Comment by Fez92** [comment]
> compairing what @Fez92 and My Tizen studio app id dump it looks like every app version will have a new id. @Fez92 are there any updates for your now tv app?
> 
> [ 19 - NOW TV]
> 
> ```
> App Name : NOW TV
> App Version : 2.0.5
> App ID - WAS : 3201603008746
> App ID - Tizen : 1Qb6IoAcGC.NowTV
> ```
> 
> [ 17 - NOW TV]
> 
> ```
> App Name : NOW TV
> App Version : 1.0.6
> App ID - WAS : 3201803015896
> App ID - Tizen : jcz0WrZYdy.NOWTV
> ```

Nope :)

**Comment by tavicu** [comment]
Hi, I have updated the wiki: https://github.com/tavicu/homebridge-samsung-tizen/wiki/Applications

When i will have some free time i will take a look over all the pages from Wiki and update the texts and also add pictures again :).
