### ISSUE TITLE
 'Active Identifier': characteristic was supplied illegal value: undefined! 

### ISSUE THREAD

**Issue by tomiy1** [tavicu/homebridge-samsung-tizen#267]
Hello, I've recently noticed that my tizen plugin (v. 4.3.3) has been showing the following in my log.  Hopefully you can take a look at this and maybe patch it up. thanks in advance! :) 

Error in HB log:
Received warning for the plugin 'homebridge-samsung-tizen' from the characteristic 'Active Identifier': characteristic was supplied illegal value: undefined! This might throw errors in the future!

**Comment by apexad** [comment]
This is Homebridge 1.3 beta

**Comment by tomiy1** [comment]
ah yes... sorry for leaving that out... im using HB 1.3b14. thanks!

**Comment by dheckl** [comment]
I have running HB 1.3.0-beta.30 and see the same warnings in the log. I also have the problem that the on/off switch always resets to off and an input change does nothing. However, the on/off switch does turn on/off and the remote keys work as well.
