### ISSUE TITLE
TV not appearing on Nearby Accessories section

### ISSUE THREAD

**Issue by jonasborneland** [tavicu/homebridge-samsung-tizen#269]
I've followed the instructions:
On the bottom click Don't Have a Code or Can't scan?
TV should appear on Nearby Accessories section

But my TV dosen't apper.

I've used the plugin before with out issues.
The homebridge installation is running fine and everything is loaded and TV is paired.
Log shows:
[11/1/2020, 21:08:49] Homebridge is running on port 51826.
[11/1/2020, 21:08:50] TV is running on port 44163.
[11/1/2020, 21:08:50] Please add [TV] manually in Home app. Setup Code: 987-65-432
TV
---------------------
11101200001 - Netflix
111299001912 - YouTube

Just can't get to add it to homekit.

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/issues/266
