### ISSUE TITLE
no allow incoming on samsung tv

### ISSUE THREAD

**Issue by KennyVB** [tavicu/homebridge-samsung-tizen#27]
Hello

i dont get the messege on my Samsung TV (the allow access messege)
i dont have this  "Settings - General - External Device Manager - Device List. Maybe you clicked Disallow."
i can how ever go here "Settings - Network - Expertsettings - Device Manager - and in here set allow/first time only/reject messege" and see connected devices

Samsung UE40KU6075 Tizen
SW: 1231.1 

it's Tizen and it worked before you added this token thingy
```
"platform": "SamsungTizen",
                        "refresh": true,
                        "devices": [{
                                "name": "Samsung TV",
                                "ip": "10.0.2.44",
                                "mac": "68:27:xx:xx:xx:xx",
                                "token": "",
```

it just keeps saying "0|homebridge  | [12/11/2018, 8:00:53 AM] [Samsung TV] Please turn ON the TV for pairing."

It's on allrigth, also tried reset of tv but no dice!

**Comment by tavicu** [comment]
Looks like you have a problem with IP :)
Are you sure it's correct?

Try to run this command (replace TV_IP with the real ip of tv) from the terminal and see if it's responding.
`ping -t 1 -c 1 TV_IP`

**Comment by KennyVB** [comment]
` ping -t 1 -c 1 10.0.2.44
PING 10.0.2.44 (10.0.2.44): 56 data bytes
64 bytes from 10.0.2.44: icmp_seq=0 ttl=64 time=4.143 ms

--- 10.0.2.44 ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 4.143/4.143/4.143/0.000 ms`

ip is correct, got it reservet in my router on it's mac adress.
so got it correct both ip and mac adress

**Comment by KennyVB** [comment]
it's running on a Raspberry Pi 2, got a backup running on freenas/bsd in a jail, and that one works, just not rpi..

**Comment by tavicu** [comment]
Strange ... that error, "Please turn ON the TV for pairing.", it's only because the ping command don't respond. Did you run the command from the Pi?

**Comment by tavicu** [comment]
I will add more debug on this with the new release and see what the problem is.

**Comment by fighterzg6** [comment]
I have the same Problem, with the Version 2.1.0 it works not! With 2.0.0 it works!

**Comment by tavicu** [comment]
Pushed a new version. Open the server with debug mode and check if the ping command returns any error when it checks if TV is online.

**Comment by WimBre** [comment]
I have the same problem (also Version 2.1.2). I don't get a popup on my Samsung TV (to allow access).

Staps made by me:
1. The token field from configuration file it's empty. 
2. I have checked and my TV is compatible with the plugin.
3. I don't have this "Settings - General - External Device Manager - Device List. 
4. Try to hard reset your TV. Done.
5. I have run the command "ping -t 1 -c 1 TV_IP" from the terminal and it responded.

**Comment by Rens93** [comment]
Got the same problem :(

**Comment by kyleringram** [comment]
Have the same issue. Not sure if this is relevant but it is trying to use a different port when running through homebridge. 
Going through the browser to make sure it is compatible, it uses port 8001
http://x.x.x.x:8001/api/v2/
Going through homebridge 
[2018-12-22 22:59:23] [Living Room TV] Trying to pair the TV
[2018-12-22 22:59:23] [Living Room TV] [DEBUG] Pair to wss://x.x.x.x:8002/api/v2/channels/samsung.remote.control?name=TGl2aW5nIFJvb20gVFY=
[2018-12-22 22:59:23] [Living Room TV] [DEBUG] { id: '479294c0-0680-11e9-932c-237961e31f6e',
  clients:
   [ { id: '479294c0-0680-11e9-932c-237961e31f6e',
       connectTime: 1545548363788,
       attributes: [Object],
       deviceName: 'TGl2aW5nIFJvb20gVFY=',
       isHost: false } ] }
[2018-12-22 22:59:23] [Living Room TV] Pair failed. Make sure you click Allow on the TV!

**Comment by kyleringram** [comment]
same issue, I noticed that there is no directory channels when using ip/api/v2/channels

**Comment by tavicu** [comment]
Hei. please follow and check my last comment from this issue #41
