### ISSUE TITLE
Tv Remote in control Centre not showing Next track and Previous track

### ISSUE THREAD

**Issue by Genestro** [tavicu/homebridge-samsung-tizen#271]
I set u channel controls in Homebridge for the Next and Previous track for the remote control.
But when i open the remote from the control center the buttons the Next and Previous track buttons are not showing.
How can i make them show up?

**Comment by tavicu** [comment]
You cannot add new buttons to the interface. Only what you see it will work.
That's Apple's kitchen and don't allow us to change the interface, only what buttons do
