### ISSUE TITLE
Input naming and programming

### ISSUE THREAD

**Issue by aberthil** [tavicu/homebridge-samsung-tizen#272]
I'd like to be able to add the inputs of the TV, basically, TV, HDMI 1, HDMI2, HDMI3, Composite, how would this work exactly?
Thanks

**Comment by aberthil** [comment]
I can see how it works for the apps, but really need guidance to program the input sources as this is not that clear in your wiki. 
Thank you for your support.

**Comment by lorenzofiamingo** [comment]
If I understood well from the wiki, you can't set inputs directly, you can only give a set of commands.
In my case worked this:
 {"name": "Live TV", "type": "command", "value": ["KEY_SOURCE", "KEY_UP, "KEY_ENTER"]}

**Comment by tavicu** [comment]
You can also find a lot of responses if you search the closed issues
