### ISSUE TITLE
Ambient Mode

### ISSUE THREAD

**Issue by imanolpadillo** [tavicu/homebridge-samsung-tizen#273]
Hi,

I am using your plugin with a Q60T (2020), and it works perfectly! My question is if you could include new functionalities related to Tizen 5.5. For example including the "ambient mode", or the OneRemote key "KEY_AMBIENT.

Thanks in advance

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/wiki/Switches
