### ISSUE TITLE
Delay as a command

### ISSUE THREAD

**Issue by imanolpadillo** [tavicu/homebridge-samsung-tizen#275]
Hi, is it possible to set a delay as a command? (Instead of using delay among commands as a global parameter).
The global delay of 400ms is working perfectly, except when pressing the first key when the TV is previously switched off. In my case i only want to set a longer delay after pressing the first key, and not to use a longer delay for all commands.
Thanks in advance and great job!!!

**Comment by MarkBarbieri** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/issues/262#issuecomment-716249768

**Comment by imanolpadillo** [comment]
Thanks for the feedback! This workarround is working! The only small issue that I see is that when a command is ordered by voice, the command is executed correctly, but siri responds (by voice) that the device is not answering.
