### ISSUE TITLE
Tv won't show up in home kit. 

### ISSUE THREAD

**Issue by ironapple0915** [tavicu/homebridge-samsung-tizen#278]
When I go to add the tv in HomeKit nothing shows up for the code or HomeKit doesn't find it.  Home bridge has control over the tv.  Homekit just can't find it.

**Comment by nessimabadi** [comment]
@ironapple0915 how did you solve this?

**Comment by nessimabadi** [comment]
Fixed it, had to purge the cache from Homebridge
