### ISSUE TITLE
siri commands issue

### ISSUE THREAD

**Issue by iondarie** [tavicu/homebridge-samsung-tizen#28]
Hello,

My TV is called "Living TV", i have 3 commands Volume Up / Volume Down / Mute.

If i call out siri with the following command: Living TV Volume Up it tells me that there is nothing playing... 

But if i say: Volume Up Living TV it works perfectly fine.

as far as i can understand the plugin list the command and then the parent and i think it should be PARENT (living tv) and the COMMAND (volume up) 

Is this right?

`{
            "platform": "SamsungTizen",
            "devices": [
                {
                    "name": "Living TV",
                    "ip": "192.168.0.79",
                    "mac": "7c:64:56:30:0b:a4",
                    "token": "14269986",
                    "switches": [
                        {"name": "Volume Up","command": "KEY_VOLUP*5"},
                        {"name": "Volume Down","command": "KEY_VOLDOWN*5"},
                        {"name": "Mute", "mute": true}
                    ]
                }
            ]
        },`

**Comment by wnuczek** [comment]
I had a similar issue. All switches get „TV” at the end of homekit name. Ended up renaming them all manually. Anyway Siri still recognizes it awkwardly.

**Comment by iondarie** [comment]
SamsungDevice.js line 140

needs to be changed from:                element.name = `${element.name} ${this.config['name']} `;
to:                 element.name = `${this.config['name']} ${element.name}`;

**Comment by tavicu** [comment]
@iondarie as @wnuczek told, you can rename the switches from the Home app. No need to change the source code of the plugin!

**Comment by iondarie** [comment]
Yes you are absolutely right, i forgot i can rename from home app 😂

Thank you for the great plugin, one question is there a key for energy saving mode?

**Comment by tavicu** [comment]
I an not aware of something like this. But if you can find it in the Samsung Remote App from the phone i can have a look and see how they are doing it :)

**Comment by langovoi** [comment]
You can use my plugin for control volume with slider in HomeKit and with Siri: https://github.com/langovoi/homebridge-upnp#readme

**Comment by Pensive** [comment]
You can use elgato eve app to rename accessories as well and it’s free ;)
