### ISSUE TITLE
No function works

### ISSUE THREAD

**Issue by iMuadh** [tavicu/homebridge-samsung-tizen#280]
Firstly, I like your plugin and how it is working with a simple configuration.
Secondly, I follow your setup guide and connected my tv with homebridge and I add it to the Home app on iPhone.
But the function is not working. I tried to turn the TV on and off OR trying to control it from the (control center). But no response.
On the other hand, When Tv is coming off or On. It appears that in the Home app on the iPhone.

By the way. When I paired the TV with the phone, it did not appear to be a popup asking me permission to pair

IOS:14.3
TV: UA60JU6400
Homebridge: 1.1.7

**Comment by tavicu** [comment]
Looks like your TV is not compatible or homebridge server can't access it.
