### ISSUE TITLE
No off BUT art mode on samsung frame

### ISSUE THREAD

**Issue by platini76** [tavicu/homebridge-samsung-tizen#283]
hello, switch off in samsung frame is art mode and not off (long press)
how to solve?
thanks

**Comment by tavicu** [comment]
"how to solve?" -> searching the closed issues

**Comment by platini76** [comment]
totally do not understand if find a solution or not... anyway thanks and happy new year!

**Comment by tavicu** [comment]
Hey! This issue has been discussed many times! A quick search would get your response.
Thank you and happy new year :)
https://github.com/tavicu/homebridge-samsung-tizen/issues/101#issuecomment-493863481
