### ISSUE TITLE
App list empty and app switches/inputs don't work. Everything else seems to work.

### ISSUE THREAD

**Issue by mikemaat** [tavicu/homebridge-samsung-tizen#284]
**Setup Details**
- I have a **Samsung UN58TU7000FXZC**
- http://TV_IP:8001/api/v2/ successfully returns my TV info
- I have authorized Homebridge from the popup on the TV and can confirm it to be in the authorized device list in the TV settings
- The TV is hard wired to ethernet

**What Works:**
- TV on/off
- Remote control in the remote app from Control Center
- Sending commands in switches (tested KEY_VOLUP, KEY_ENTER, Mute, etc.)

**What Doesn't Work**
- app_list: true in config results in an empty list in the log
- Putting app ID's in switches  "No application found with this id (11101200001)"
- Putting app ID's in inputs
- Basically, none of the installed apps seem to be getting recognized. I have Netflix, Disney+, and Amazon Prime Video all installed.

---------------------------

**Log**

[31/12/2020, 13:54:05] Homebridge is running on port 51826.
actual connected
Login Request Response: 3 
login requested... sending response...
sendcommand 005iwuw82CB
Command 005 Acknowledged
Login Request Response: 1 
successfully logged in!  getting current data...
sendcommand 00191
[31/12/2020, 13:54:06] Main Floor TV is running on port 37719.
[31/12/2020, 13:54:06] Please add [Main Floor TV] manually in Home app. Setup Code: 031-45-154
Command 001 Acknowledged
Zone 001 is restored
[31/12/2020, 13:54:15] [Main Floor TV] [DEBUG] {
  data: { clients: [ [Object] ], id: 'a22b09d-fa53-4778-b6c0-78883d89aae' },
  event: 'ms.channel.connect'
}
[31/12/2020, 13:54:15] [Main Floor TV] [DEBUG] {
  method: 'ms.channel.emit',
  params: { data: '', to: 'host', event: 'ed.installedApp.get' }
}
Main Floor TV
---------------------  **<-- Notice this list is empty**
[31/12/2020, 13:56:59] [Main Floor TV] [DEBUG] {
  method: 'ms.remote.control',
  params: {
    Cmd: 'Click',
    DataOfCmd: 'KEY_ENTER',
    Option: false,
    TypeOfRemote: 'SendRemoteKey'
  }
}
[31/12/2020, 13:57:04] [Main Floor TV] [DEBUG] {
  method: 'ms.remote.control',
  params: {
    Cmd: 'Click',
    DataOfCmd: 'KEY_ENTER',
    Option: false,
    TypeOfRemote: 'SendRemoteKey'
  }
}
[31/12/2020, 13:57:11] [Main Floor TV] [DEBUG] {
  method: 'ms.remote.control',
  params: {
    Cmd: 'Click',
    DataOfCmd: 'KEY_MUTE',
    Option: false,
    TypeOfRemote: 'SendRemoteKey'
  }
}
[31/12/2020, 13:57:18] [Main Floor TV] [DEBUG] {
  method: 'ms.remote.control',
  params: {
    Cmd: 'Click',
    DataOfCmd: 'KEY_MUTE',
    Option: false,
    TypeOfRemote: 'SendRemoteKey'
  }
}
[31/12/2020, 13:57:30] [Main Floor TV] [DEBUG] {
  method: 'ms.remote.control',
  params: {
    Cmd: 'Click',
    DataOfCmd: 'KEY_VOLUP',
    Option: false,
    TypeOfRemote: 'SendRemoteKey'
  }
}
[31/12/2020, 14:00:56] [Main Floor TV] [DEBUG] {
  data: { clients: [ [Object] ], id: '91fa55f2-f18c-4422-add1-9c8981339c' },
  event: 'ms.channel.connect'
}
[31/12/2020, 14:00:57] [Main Floor TV] [DEBUG] {
  method: 'ms.remote.control',
  params: {
    Cmd: 'Click',
    DataOfCmd: 'KEY_ENTER',
    Option: false,
    TypeOfRemote: 'SendRemoteKey'
  }
}
[31/12/2020, 14:21:32] [Main Floor TV] [DEBUG] {
  data: { clients: [ [Object] ], id: '97819f2f-c32-4111-a219-a562b0491dcb' },
  event: 'ms.channel.connect'
}
[31/12/2020, 14:21:32] [Main Floor TV] [DEBUG] {
  method: 'ms.remote.control',
  params: {
    Cmd: 'Click',
    DataOfCmd: 'KEY_ENTER',
    Option: false,
    TypeOfRemote: 'SendRemoteKey'
  }
}
[31/12/2020, 14:22:19] [Main Floor TV] [DEBUG] {
  method: 'ms.channel.emit',
  params: { data: '', to: 'host', event: 'ed.installedApp.get' }
}
[31/12/2020, 14:22:20] [Main Floor TV] **No application found with this id (11101200001)**
[31/12/2020, 14:22:20] [Main Floor TV] **[DEBUG] InvalidAppIdError: No application found with this id (11101200001)
    at WebSocketSecure.openApplication (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/methods/ws.js:56:19)
    at Remote.openApplication (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/remote.js:108:9)
    at Object.set (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/options/switch.js:87:17)
    at Switch.setSwitch (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/services/switch.js:63:17)**

------------------------

**TV API Response/Support Details**

```json
{
   "device":{
      "FrameTVSupport":"false",
      "GamePadSupport":"true",
      "ImeSyncedSupport":"true",
      "Language":"en_US",
      "OS":"Tizen",
      "PowerState":"on",
      "TokenAuthSupport":"true",
      "VoiceSupport":"false",
      "WallScreenRatio":"0",
      "WallService":"false",
      "countryCode":"CA",
      "description":"Samsung DTV RCR",
      "developerIP":"192.168.7.220",
      "developerMode":"1",
      "duid":"uuid:985b04f0-0901-4e33-8a3f-119448cfd7ca",
      "firmwareVersion":"Unknown",
      "id":"uuid:985b04f0-0901-4e33-8a3f-119448cfd7ca",
      "ip":"192.168.7.218",
      "model":"20_KANTSU2_UHD_BASIC",
      "modelName":"UN58TU7000FXZC",
      "name":"[TV] Main Floor TV",
      "networkType":"wired",
      "resolution":"3840x2160",
      "smartHubAgreement":"true",
      "type":"Samsung SmartTV",
      "udn":"uuid:985b04f0-0901-4e33-8a3f-119448cfd7ca",
      "wifiMac":"4c:c9:5e:67:da:28"
   },
   "id":"uuid:985b04f0-0901-4e33-8a3f-119448cfd7ca",
   "isSupport":"{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"false\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"false\"}\n",
   "name":"[TV] Main Floor TV",
   "remote":"1.0",
   "type":"Samsung SmartTV",
   "uri":"http://192.168.7.218:8001/api/v2/",
   "version":"2.0.25"
}
```

**Comment by techiebod** [comment]
I'm also seeing this problem (although I've only tried turning the tv on/off rather than anything about the remote)

The only thing I can add is that I see the following in the TV debug log:
> ERROR | "connect error" | "timestamp: 1609773386900, file: IpcClient.cpp, func: transceive : 126"
> VERBOSE | "## emitToRCR ##" | "timestamp: 1609773386896, file: TizenDevice.cpp, func: emitToRCR : 720"
> DEBUG | "msg : {\"method\":\"ms.channel.emit\",\"params\":{\"data\":\"\",\"event\":\"ed.installedApp.get\",\"to\":\"host\"}}\n"

 I've also tried upping the timeout on the ws-connection in the code (in ws.js) but that doesn't appear to have helped

**Comment by tavicu** [comment]
Hei!

Thank you for all the details.
Unfortunately looks like Samsung did something with the latest OS and removed the feature for opening and getting status of installed apps.

I think is related with decommissioning "Samsung Smart View" app and forcing us to migrate to Smart Things
