### ISSUE TITLE
Accessory doesn't shown up

### ISSUE THREAD

**Issue by Feherfy** [tavicu/homebridge-samsung-tizen#285]
I have had installed the plugin, I could add my TV to homekit, and it works mostly well with it. Only problem is, it doesen't shown up at Accessories page in Hoobs UI.
Log writes " UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/hoobs/etc/accessories/samsung-tizen.json' ".

Any ideas how to fix it?

**Comment by tavicu** [comment]
samsung-tizen.json should be created first time when you install the plugin. Probably your server don't have enough access to write that file.

You can create it manually
