### ISSUE TITLE
Cant add Plugin to Apple Homekit

### ISSUE THREAD

**Issue by dariushaendel** [tavicu/homebridge-samsung-tizen#286]
**Version**
3.3.1

**Config** (XXX instead of sensitive Info)
[
    {
        "name": "TV von Darius",
        "ip": "XXX",
        "mac": "XXX",
        "uuid": "A1",
        "inputs": [
            {
                "name": "YouTube",
                "type": "app",
                "value": "111299001912"
            },
            {
                "name": "Sky+ ",
                "type": "app",
                "value": "3201802015776"
            },
            {
                "name": "Prime Video",
                "type": "app",
                "value": "3201512006785"
            },
            {
                "name": "Disney+ ",
                "type": "app",
                "value": "3201901017640"
            },
            {
                "name": "Apple TV",
                "type": "app",
                "value": "3201807016597"
            },
            {
                "name": "Apple Music",
                "type": "app",
                "value": "3201908019041"
            }
        ],
        "keys": {
            "INFORMATION": "KEY_HOME"
        },
        "switches": [
            {
                "name": "Mute",
                "mute": true
            },
            {
                "name": "VOL+",
                "command": "KEY_VOLUP"
            },
            {
                "name": "VOL-",
                "command": "KEY_VOLDOWN"
            },
            {
                "name": "HDMI",
                "command": "KEY_HDMI"
            }
        ]
    }
]

**Log**

2.1.2021, 22:14:48 [SamsungTizen] Initializing SamsungTizen platform...
2.1.2021, 22:14:49 External port pool ran out of ports. Fallback to random assign.
2.1.2021, 22:14:49 TV von Darius is running on port 45891.
2.1.2021, 22:14:49 Please add [TV von Darius] manually in Home app. Setup Code: XXX
2.1.2021, 22:15:03 TV von Darius
2.1.2021, 22:15:03 ---------------------
2.1.2021, 22:15:03 org.tizen.browser - Internet
2.1.2021, 22:15:03 20192100002 - e-Manual
2.1.2021, 22:15:03 111299001912 - YouTube
2.1.2021, 22:15:03 11101200001 - Netflix
2.1.2021, 22:15:03 3201511006428 - Rakuten TV
2.1.2021, 22:15:03 3201803016013 - HD Austria
2.1.2021, 22:15:03 3201909019271 - PrivacyChoices
2.1.2021, 22:15:03 3201807016705 - Brandworld
2.1.2021, 22:15:03 3201812017464 - Sky X
2.1.2021, 22:15:03 3201612011392 - Drei TV
2.1.2021, 22:15:03 3201710015037 - Gallery
2.1.2021, 22:15:03 3201807016597 - Apple TV
2.1.2021, 22:15:03 3201908019041 - Apple Music
2.1.2021, 22:15:03 3201802015776 - Sky Q
2.1.2021, 22:15:03 3201512006785 - Prime Video

**Additional context**

The config worked perfectly, except some Names didn't change in homekit after I changed them in the config in hoobs. When I tried readding them in homekit, it did not work. Even with just the simple ip, mac and name config nothing showed up in homekit. I also tried entering the code as stated in the log. I dont think its a problem with the config because it shows the code and the installed applications. I would absolutely love if someone could help me... Thanks in advance

**Comment by dariushaendel** [comment]
I also tried resetting the TV. All other plugins work fine on hoobs. When I restart the plugin I also get the "devices wants to access" Notification on the TV. Unfortunetly accepting it does not solve the problem.

**Comment by tavicu** [comment]
search of `uuid` in closed issues.
