### ISSUE TITLE
"characteristic was supplied illegal value" warnings from Homebridge 1.3.0

### ISSUE THREAD

**Issue by Zer0x00** [tavicu/homebridge-samsung-tizen#287]
**Describe the bug**
Homebridge 1.3.0 is logging warnings about illegal values for characteristics returned by `homebridge-samsung-tizen`.

**To Reproduce**
Upgrade to [Homebridge 1.3.0 public beta](https://github.com/homebridge/homebridge/issues/2765).

Information from the log:
```
[03/01/2021, 04:20:02] Received warning for the plugin 'homebridge-samsung-tizen' from the characteristic 'Active Identifier': characteristic was supplied illegal value: undefined! This might throw errors in the future!
```

**Comment by tavicu** [comment]
Yeah, the problem can be with the latest OS which won't return the apps anymore.
I will resolve the warning.

**Comment by mrMiimo** [comment]
there is also a caveat, here the log:

**Comment by Zer0x00** [comment]
@tavicu I think you closed this issue by accident.

**Comment by masterfordev** [comment]
The homebridge 1.3 version was released today. After upgrading, i have same warn.

**Comment by Tontonpat** [comment]
Hi, it is same for me since i’ve update to 1.3

**Comment by tavicu** [comment]
Hei. Pushed a new version which fix the warning.

Apparently new version of Homebridge don't want to wait for you to check which app is opened. So it wants to set it to default then change it manually after you identified which app is running :)
