### ISSUE TITLE
Problems pairing my Samsung Serif TV

### ISSUE THREAD

**Issue by vanzuiden** [tavicu/homebridge-samsung-tizen#29]
Hi,

I'm having troubles connecting to my Samsung Serif TV (UE40LS001).

I do not get a modal asking for permission when I run homebridge and therefore cannot seem to pair the tv. The log shows:

[12/11/2018, 10:20:38 PM] Homebridge is running on port 51826.
[12/11/2018, 10:20:43 PM] [Serif TV] Trying to pair the TV
[12/11/2018, 10:20:44 PM] [Serif TV] Trying to pair the TV
[12/11/2018, 10:20:46 PM] [Serif TV] Trying to pair the TV
[12/11/2018, 10:20:46 PM] [Serif TV] Pair failed. Make sure you click Allow on the TV!

I followed the instructions as described by the readme but have the following problem. I have no Settings - General - External Device Manager - Device Connection Manager settings available to me. 

I can connect to the tv API via the api/v2/ url and the output shows most of the same information as shown on the Samsung developer page. The only mayor difference seems to be that there is no "remote:" "1.0" line at the end of the output.

As I understand, this television does run Tizen but has a different UI from the general version of Tizen. There is a menu item called 'Multimedia Device Manager'. There are no real options here.

I tried connecting to the Samsung Smartview app and this showed a modal with PIN number immediately. 

Is my TV unsupported? Is there any other way to obtain a Token for the remote script?

Thanks

**Comment by tavicu** [comment]
Hi,

Unfortunately your TV is running a version of Tizen which is not compatible with this plugin.

It's another method where pairing is made by PIN as you seen.

Adding this method to the plugin takes time and i don't have a TV where i can test it. So everything i will do will be blind.

Right now it's not in my priorities list but if i'll have the time i want to do it in the future so more people can enjoy the plugin :)

**Comment by vanzuiden** [comment]
Alright, that's too bad. Thanks for your feedback and work on the plug-in.

I will definitely keep an eye out for any possible future releases with the PIN method 👍

**Comment by ChrisGSXR** [comment]
Had exactly same problem with Samsung "The Frame" TV. Tried 20+ times with same result as described. But then turned off youtube app, went to home screen and everything worked perfectly.

was: 
0|homebrid | [2018-12-17 21:28:28] [TV2] Trying to pair the TV
0|homebrid | [2018-12-17 21:28:30] [TV2] Trying to pair the TV
0|homebrid | [2018-12-17 21:28:34] [TV2] Trying to pair the TV
0|homebrid | [2018-12-17 21:28:39] [TV2] Pair failed. Make sure you click Allow on the TV!

Shut down youtube app - went to home screen
became:
0|homebridge  | [2018-12-17 21:36:39] [TV3] Trying to pair the TV
0|homebridge  | [2018-12-17 21:36:41] [TV3] Pair success. SAVE THE TOKEN! Update config file to use {'token': 'XXXX'}

**Comment by vanzuiden** [comment]
Hi @ChrisGSXR, thanks for your comment. 

Can you elaborate a bit more on what you exactly did? 

Did you first try to pair the TV while you had the YouTube app open? Or did you somehow terminated the YouTube app? If so, how does this work?

I don't think the Frame and the Serif run the same version of Tizen but I hope you can help me further.

**Comment by ChrisGSXR** [comment]
1) I was trying while tv was showing some youtube stuff. I have just hold the "go back" button for several seconds to shut down youtube app. Went to original home screen and it worked for me. I know, sound weird. 
2) I think it's the same Tizen I went to http://192.168."tv ip address":8001/api/v2/
and there is parameters: "FrameTVSupport":"true","OS":"Tizen"
full result here: https://github.com/tavicu/homebridge-samsung-tizen/issues/31
