### ISSUE TITLE
The confirmation screen is not showing on my TV

### ISSUE THREAD

**Issue by nrxofficial** [tavicu/homebridge-samsung-tizen#294]
Model: UE48JU6410

**Comment by skom27** [comment]
On UE55NU7452 also there is no confirmation screen on TV after sending the command "samsungctl --host 10.1.1.40 --port 8001 --method websocket -v KEY_MUTE" from raspberry.
Some solution?

**Comment by todesto** [comment]
make sure to check device connect manager in TV setting. Check connected device.

**Comment by skom27** [comment]
In the settings I have "Notify only the first time" (or something like that, I write from memory, I'm away from home) and in the connected devices I only have a Samsung phone that prompted for permission

**Comment by todesto** [comment]
There is your problem. TV is not allowing access to your Pi.

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/wiki/Common-Issues#--tv-is-not-showing-the-pair-popup
https://github.com/tavicu/homebridge-samsung-tizen/wiki/Common-Issues#--tv-is-always-asking-for-permissions
