### ISSUE TITLE
Always show "no response" in Home app after a period of time with Homebridge

### ISSUE THREAD

**Issue by djminmin** [tavicu/homebridge-samsung-tizen#295]
I have been using the plugin in Hoobs (Rasp Pi) and it works great. 
But after I switched to Homebridge (Rasp Pi), it always show "no response" in Home app. I've try reseting Homebridge + reinstall the plugin a few times, the same issue never fix. Any idea of this?

**Comment by danielniemeyer** [comment]
+1

**Comment by tavicu** [comment]
Clear caches of homebrige and add the TV again in homekit.
