### ISSUE TITLE
Is it possible to wait for an app to load or for a command to be issued?

### ISSUE THREAD

**Issue by AndersKlinting** [tavicu/homebridge-samsung-tizen#298]
Issuing commands to control an app may require the app to load first, but it looks to me like that is not happening. The result is that my commands do not move the cursor as expected.

Is there a way to specify a wait until the first command should be issued - giving the app amble time to load?

similarly, doing a sequence of KEY_RIGHT, KEY_DOWN and KEY_ENTER also gives random results. I tried specifying delay=3000 (other numbers were tried as well), but it only has little effect. 
is there a WAIT command one can issue between the others to enforce a period between them - to let the TV react and the app to update accordingly?

**Comment by MarkBarbieri** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/issues/262#issuecomment-716249768
