### ISSUE TITLE
TvOfflineError

### ISSUE THREAD

**Issue by bayramog** [tavicu/homebridge-samsung-tizen#299]
I always get TvOfflineError when I try to turn on my TV. Other commands are working fine. 

![image](https://user-images.githubusercontent.com/61725918/106357515-8dd6e300-6317-11eb-9183-301dfb159d5c.jpeg)

**Comment by tavicu** [comment]
Not much i can help you with ... the plugin check if the TV is on by sending a ping request.
The request is blocked by your network or your ip is wrong in config.
