### ISSUE TITLE
TV turn on issue 

### ISSUE THREAD

**Issue by Avigdorrr** [tavicu/homebridge-samsung-tizen#301]
Samsung TV turn on issue

Hey,
I added this plug-in to my Samsung series 7 TV
I noticed an issue: 
The TV does not turn on properly when using Homekit (does not respond and turns on only if I press the button several times). I can turn it off and transfer inputs without a problem. The only problem is just turning the TV on.
Is there a way to solve it?

**Comment by xnonim** [comment]
I'm pretty sure the problem is in your tv config, you must allow the tv to be turned on by smartphones (don't remember exactly the name) in your wifi settings

**Comment by tavicu** [comment]
The plugin use a Wake on Lan method to turn it on. There may be a problem on your network for the delay or blocking the requests.

Unfortunately i cannot help you on this problem
