### ISSUE TITLE
PIN authentication

### ISSUE THREAD

**Issue by MrRubberDucky99** [tavicu/homebridge-samsung-tizen#302]
Hi, 
I am using an older TIZEN tv (UE40J6000) and was wondering if the implementation of pin authentication was still on the to do list or if any progress had been made.
Thanks!

**Comment by tavicu** [comment]
Hei! PIN method will not be implemented

**Comment by djsomi** [comment]
Hi all,

Anyway did you guys know any working homebridge plugin for PIN type auth TVs? 
Even Samsung official app is not supporting my TV :(  ( JS8000 series )

Thanks!

**Comment by benfysh** [comment]
hi @djsomi try [Homebridge-SamsungTV-Control](https://github.com/mmende/homebridge-samsungtv-control2#readme) this is working for me with a UE55JS8000
