### ISSUE TITLE
Keys don‘t appear

### ISSUE THREAD

**Issue by Knightsabes** [tavicu/homebridge-samsung-tizen#305]
Hey,

the keys don‘t appear. My config is:
"platforms": [
        {
            "platform": "SamsungTizen",
            "name": "SamsungTizen",
            "devices": [
                {
                    "name": "Fernseher",
                    "ip": "xxx.xxx.xxx.xx",
                    "mac": "xx:yy:zz",
                    "keys": {
                        "ARROW_UP": "KEY_UP",
                        "ARROW_DOWN": "KEY_DOWN",
                        "ARROW_LEFT": "KEY_LEFT",
                        "ARROW_RIGHT": "KEY_RIGHT",
                        "SELECT": "KEY_ENTER",
                        "BACK": "KEY_RETURN",
                        "EXIT": "KEY_HOME",
                        "PLAY_PAUSE": "KEY_PLAY_BACK",
                        "INFORMATION": "KEY_INFO"
                    },
                    "switches": [
                        {
                            "name": "Internet",
                            "power": true,
                            "app": "org.tizen.browser"
                        },
                        {
                            "name": "Netflix",
                            "power": true,
                            "app": "11101200001"
                        },
                        {
                            "name": "Youtube",
                            "power": true,
                            "app": "111299001912"
                        },
                        {
                            "name": "Kanal vor",
                            "command": "KEY_CHUP"
                        },
                        {
                            "name": "Kanal zurück",
                            "command": "KEY_CHDOWN"
                        },
                        {
                            "name": "Kanalliste",
                            "command": "KEY_CH_LIST"
                        },
                        {
                            "name": "lauter",
                            "command": "KEY_VOLUP*3"
                        },
                        {
                            "name": "leiser",
                            "command": "KEY_VOLDOWN*3"
                        },
                        {
                            "name": "Ton ausschalten",
                            "mute": true
                        },
                        {
                            "name": "Programmübersicht",
                            "command": "KEY_GUIDE"
                        },
                        {
                            "name": "Quelle",
                            "command": "KEY_SOURCE"
                        },
                        {
                            "name": "Menü",
                            "command": "KEY_MENU"
                        }
                    ]
                }
                
The switches do work. Does anyone see my mistake?

**Comment by tavicu** [comment]
Keys are just a mapping for the buttons of remote from control center! They will not appear anywhere in home app! You don’t need to add it in the config unless you want to overwrite one button!


![](https://www.lifewire.com/thmb/LtHZE_r-QOPmVaeSn2iCeXBc7jU=/1700x1334/filters:no_upscale():max_bytes(150000):strip_icc()/003-control-apple-tv-with-ios-control-center-4154515-4babbe3ea7d141ebb188e0c5c74b3140.jpg)

**Comment by Knightsabes** [comment]
Works, thank you 🙂
