### ISSUE TITLE
Q80T 

### ISSUE THREAD

**Issue by wildman199** [tavicu/homebridge-samsung-tizen#306]
Once tv is turned off for 5 minutes I can’t turn it on without using the physical remote. All other switches work when power is on.

**Comment by tavicu** [comment]
The plugin is using Wake on Lan protocol to turn the TV on. Here are some possible problems:
1. Wrong MAC address in config
2. Your network is blocking WoL requests
3. If you try over WiFi it may not work! One of my TVs for example, works only over cable! Don't know why ...
