### ISSUE TITLE
after update with hombridge 1.3 it will not working again

### ISSUE THREAD

**Issue by cryptominingbe** [tavicu/homebridge-samsung-tizen#308]
Hi, 

After the update to homebridge 1.3.0 it gives: 

[homebridge-samsung-tizen] This plugin generated a warning from the characteristic 'Active Identifier': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.

can you help me please ?

**Comment by tavicu** [comment]
Fixed in 4.3.4 (https://github.com/tavicu/homebridge-samsung-tizen/releases/tag/v4.3.4)
