### ISSUE TITLE
Plugin generated a warning from the characteristic.

### ISSUE THREAD

**Issue by todesto** [tavicu/homebridge-samsung-tizen#309]
This plugin generated a warning from the characteristic 'Active Identifier': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.

Plug in is working but it keeps throwing error in the log. Should I be concerned? Didn't have this until updated Homebridge 1.3

**Comment by tavicu** [comment]
Update the plugin to the latest version
