### ISSUE TITLE
Samsung The Frame Art Mode

### ISSUE THREAD

**Issue by thevisualist** [tavicu/homebridge-samsung-tizen#31]
Hi, 
thanks for the plugin! Is it possible to control the On/Off/ArtMode switch for Samsung The Frame? If turned "Off" in Apple Home it switches to ArtMode and then it goes back to "On" in Home. 

Thanks in advance!

**Comment by tavicu** [comment]
Hei!

I'm sorry but i am not aware of Samsung Frame and how it works. I will not be able to replicate and try to fix the problem.

**Comment by thevisualist** [comment]
Ok thanks!

**Comment by ChrisGSXR** [comment]
JFYI "the frame" is UE65LS003 that could be turned off or could just show static picture like a painting. ("FrameTVSupport":"true")

So while it shows static picture in turned off mode it shows incorrect status (like it's "on").

{"device":{"FrameTVSupport":"true","GamePadSupport":"true","ImeSyncedSupport":"true","OS":"Tizen","TokenAuthSupport":"true","VoiceSupport":"true","countryCode":"RU","description":"Samsung DTV RCR","developerIP":"0.0.0.0","developerMode":"0","duid":"uuid:d3693fc3-1be7-4150-bc60-ab7e8069311c","firmwareVersion":"Unknown","id":"uuid:d3693fc3-1be7-4150-bc60-ab7e8069311c","ip":"192.168.1.30","model":"17_KANTM_UHD","modelName":"UE65LS003","name":"[TV]Frame","networkType":"wired","resolution":"3840x2160","smartHubAgreement":"true","type":"Samsung SmartTV","udn":"uuid:d3693fc3-1be7-3150-bc60-ab7e8069311c","wifiMac":"7c:64:56:40:60:23"},"id":"uuid:d3693fc3-1be7-8150-bc60-ab7e8069311c","isSupport":"{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"true\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n","name":"[TV]Frame","remote":"1.0","type":"Samsung SmartTV","uri":"http://192.168.3.30:8001/api/v2/","version":"2.0.25"}
