### ISSUE TITLE
Changing Inputs (HDMI 1, HDMI 2, ect)

### ISSUE THREAD

**Issue by K0pp3r** [tavicu/homebridge-samsung-tizen#310]
I added this plugin to my Homebridge, but now that it's added, it appears I can only turn the TV on and off. I'm aware I can add applications to the plugin, but we actually use it for xbox and Apple TV. I'd like to be able to have an option to change inputs. Is there a way to add that? Or did I miss something. Thanks again for creating this plugin. So far it's working well in Homekit.

**Comment by tavicu** [comment]
Hi! https://github.com/tavicu/homebridge-samsung-tizen/issues/77
