### ISSUE TITLE
Unable to add plugin as a new accessory

### ISSUE THREAD

**Issue by UnbendableStraw** [tavicu/homebridge-samsung-tizen#312]
I was first able to discover and add my samsung tv as an accessory in the Home app after installing and configuring the plugin.

I've been experimenting with adding new switches. Things kept working after a few homebridge restarts, but then the accessory said "Not Responding" in the Home app, so I tried removing it and re-adding it.

Now I cannot even get the accessory to show up when trying to readd it to my Home app. I've tried completely uninstalling the plugin with its config and reinstalling **only** specifying the IP and MAC of the tv trying to get it to add again. I still can't get it to show in my home app. no errors in the homebridge console.

```
Preparing Advertiser for 'Big TV 0CB6' using bonjour-hap backend!
Starting to advertise 'Big TV 0CB6' using bonjour-hap backend!
[2/26/2021, 6:13:15 PM] Big TV 0CB6 is running on port 62603.
[2/26/2021, 6:13:15 PM] Please add [Big TV 0CB6] manually in Home app. Setup Code: xxx-xx-xxx```

Plugin Config
```json
{
    "name": "SamsungTizen",
    "app_list": false,
    "devices": [
        {
            "name": "Big TV",
            "ip": "VERIFIED.IP.ADDRESS",
            "mac": "VERIFIED:MAC:ADDRESS"
        }
    ],
    "platform": "SamsungTizen"
}```

**Comment by UnbendableStraw** [comment]
Adding  `"uuid": "A1"` to the plugin's config made it appear in homekit again. This was not an obvious solution, I only found it after browsing the existing issues, and it looks somewhat common. Can we put something in the readme?

**Comment by UnbendableStraw** [comment]
the uuid keeps getting removed from the plugin's json config as I keep restarting homebridge, reintroducing the issue. is there a better fix?

**Comment by tavicu** [comment]
When you remove the accessory from homekit it remains linked in homebridge! That’s why i implemented the uuid thing! 

Other solution is to remove the persist folder of homebrdige but this will unlink everything and you should add all again to homekit!

Search and see what does remove your uuid from config cause that’s not normal :)

**Comment by Myth0zz** [comment]
I have the exact same issue. How can I edit the plugin's json and add the "uuid": "A1" ?? Thanks for any help ;)

**Comment by Myth0zz** [comment]
Thank you for the quick reply! I added it manually. And it worked! One LAST question, not related to this. I added the Application Inputs for the Netflix, Prime etc apps of my TV. How do I return to the TV program? I mean I have inputs:

"inputs": [
            {"name": "Netflix",
             "type": "app",
             "value": "11101200001"},
            {"name": "Prime",
             "type": "app",
             "value": "3201512006785"},
            {"name": "YouTube",
             "type": "app",
             "value": "111299001912"},
            {"name": "YouTube Kids",
             "type": "app",
             "value": "3201611010983"},
            {"name": "Spotify",
             "type": "app",
             "value": "3201606009684"}
         ]

How do I return to normal TV programm (not an app that is) from my Homekit tab? Thanks again for the excellent support.

**Comment by tavicu** [comment]
Unfortunately there is only a hack where you are sending a list of keys just like you would do with your remote.
I have it set up like this: `{"name": "Live TV", "type": "command", "value": "KEY_SOURCE,KEY_DOWN,KEY_UP,KEY_LEFT*3,KEY_ENTER"}`
