### ISSUE TITLE
Update Deprecated Dependencies

### ISSUE THREAD

**Issue by YPyltiai** [tavicu/homebridge-samsung-tizen#313]
Hi @tavicu,

Thanks for the module! You are probably aware but there are multiple deprecated dependencies like `request` and one other which pop up on update. Did you consider replacing those with actively supported alternatives?

Thanks!

**Comment by tavicu** [comment]
Hi. Thank you. I was not aware that `request` became deprecated in February.

I have updated the plugin to use another method

**Comment by YPyltiai** [comment]
Thank you!
