### ISSUE TITLE
Slider switch volup and voldown

### ISSUE THREAD

**Issue by jose2392** [tavicu/homebridge-samsung-tizen#314]
Hi, 
I configured this plugin with homebridge and I added my TV Samsung in HomeKit.

I configured the volume up and down as two switches. Now is it possible to configure it as a slider?

Or Can I configure volume up and down as a unique switch but with slider?

Thanks in advance.

**Comment by tavicu** [comment]
Hi, nope. That won't be possible because a slider need to have a value and we can't get the value of the volume from TV.

Also, you can control the volume of TV with your phone volume buttons (physical ones) when you are in Remote Control from Control Center.
