### ISSUE TITLE
Is there a command to simulate double tap

### ISSUE THREAD

**Issue by Cha7lie** [tavicu/homebridge-samsung-tizen#315]
Looking for a command to simulate the touch pad double tap. Is this possible yet? If not could this be a feature request?

**Comment by tavicu** [comment]
Hi @Cha7lie, unfortunately i don't know if such method exists because there was no option to implement touch support since Apple only gives us option to have buttons in Remote Control.

Until Apple won't allow us to use touch pad, i won't look to implement it.

`KEY_ENTER` is not working?

**Comment by Cha7lie** [comment]
Thanks for the quick response. I was looking to simulate it for a specific use case - to double tap to 'zoom' in on a media (outside a 16:9 ratio) being played so it fills the whole tv screen. In my case it was within the Plex app. The `key_enter` command just play/pauses (as do other commands), so wasn't sure if there was one that could simulate that double tap to zoom in.

**Comment by tavicu** [comment]
I understand. Unfortunately the plugin does not support anything related to touch pad.
