### ISSUE TITLE
Different setup/requirements: 2020 TU8000 CANADA 

### ISSUE THREAD

**Issue by HVR88** [tavicu/homebridge-samsung-tizen#316]
I can only connect via web browser to my UN75TU8000 (Canada model) from ONE host IP - all others are denied.

To get any IP response from the TV via browser I had to do the following first:

Sign in to a Samsung account (Developer)
Enable Developer Mode setting to ON (12345 in Apps UI)
Set ONE specific host PC IP address in Developer Mode enable window
Power ON With Mobile  in EXPERT Settings turned ON
IP Remote in EXPERT Settings Enable

Also need to "Allow" access when prompted on TV.

With the above I can access via web browser ONLY by going to http://192.168.8.140:8001/ (see output below in next post)

http://192.168.8.140:8001/api/v2 or V3 or ms/1.0 all produce a 404 error.

Accessing from any host other than the one specified in the developer window will produce a 401 error (Unauthorized).

With CURL, I can launch an app from any host IP like this:

curl -X POST -i 'http://192.168.8.140:8001/api/v2/applications/111299001912' (opens Youtube)

Still trying to get it going with Homebridge (Hoobs) - not getting any promt on TV yet for access.

**Comment by HVR88** [comment]
Output in browser of http://192.168.8.140:8001


**MultiScreen Service**
Service Information
APIVERSION	2.0
PORT	8001
REMOTEVERSION	1.0
SECUREPORT	8002
VERSION	2.0.25
Memory Information
test
Device Information
FRAMETVSUPPORT	false
GAMEPADSUPPORT	true
IMESYNCEDSUPPORT	true
LANGUAGE	en_US
OS	Tizen
POWERSTATE	on
TOKENAUTHSUPPORT	true
VOICESUPPORT	true
WALLSCREENRATIO	0
WALLSERVICE	false
COUNTRYCODE	CA
DESCRIPTION	Samsung DTV RCR
DEVELOPERIP	192.168.8.180
DEVELOPERMODE	1
DUID	uuid:HIDDEN
FIRMWAREVERSION	Unknown
ID	uuid:HIDDEN
IP	192.168.8.140
MODEL	20_NIKEL_UHD_BASIC
MODELNAME	UN75TU8000FXZC
NAME	[TV] Samsung 8 Series (75)
NETWORKTYPE	wired
RESOLUTION	3840x2160
SMARTHUBAGREEMENT	true
TYPE	Samsung SmartTV
UDN	uuid:HIDDEN
WIFIMAC	HIDDEN
Developer Options     View Logs
Logging Level

CHECKED - Allow All Content

**Comment by HVR88** [comment]
Another significant difference is that navigating the menus to manipulate the SOURCE to achieve an HDMI input won't work the way I've read it described.  This is the only way it can work on this TV series:

                    "name": "HDMI N",
                    "type": "command",
                    "value": [
                        "KEY_SOURCE",
                        "KEY_DOWN",
                        "KEY_UP",
                        "KEY_LEFT*1.5s",
                        "KEY_RIGHT*N",
                        "KEY_ENTER"
                    ]

Where "N" is the HDMI #.  You need to confirm which position in the source list your HDMI input appear in. 

The main difference here is the key down and key up - this resets the selection to make sure you are on the source list. 

When using KEY_SOURCE from a built-in app, your selection is simply on the Source icon - you'll need to KEY_UP to get to the source list. When coming from an HDMI source, then your selection will already be in the source list with the current HDMI source selected - if you do KEY_UP here, you'll highlight the edit option for that source. Moving down and then up resets the selection to an always-known state.

**Comment by tavicu** [comment]
Hi. Your TV is compatible with the plugin.
The `http://192.168.8.140:8001/api/v2` endpoint is not working because you forgot a `/` at the end. It should be `http://192.168.8.140:8001/api/v2/`

Regarding Hobbs i can't help you since i am not using it. The plugin was designed for Homebridge.

With HDMIs, Samsung allows us to send commands to TV. And commands are buttons found on physical remotes. The only key regarding HDMI is KEY_HDMI which cycles through HDMI inputs, there is no direct way to select a hdmi source.
So the only option now is creating your own configuration of keys to select a source.

**Comment by HVR88** [comment]
Yes the trailing slash was missing above, thanks.

Looks like you'd have to use the SmartThings API if you want full access:
https://smartthings.developer.samsung.com/docs/api-ref/capabilities.html

The API used now seems best suited for remote control only - but still strange it lacks discrete inputs. That's a big oversight on Samsung's part.

KEY_HDMI on my set cycles through active HDMI inputs plus LiveTV.

**Comment by tavicu** [comment]
Yeah, unfortunately Samsung didn't want us to have access to these endpoints which are already limited. Everything that is found was by reverse engineering their apps or finding sources of code from Tizen.

At least we have something to work with. It's not perfect but is better than nothing :)

But yeah ... the HDMI thing is fucked up reaaallllyyy bad! Especially if you disconnect your cables.

Did you manage to make it work through Hoobs?

**Comment by tavicu** [comment]
> I gave up on Hoobs and uninstalled the docker I was using. Instead I set up an Ubuntu server VM to run Homebride and its GUI exclusively - which it turns out I prefer from a usability POV as well.

if it helps i am using this: https://github.com/oznu/docker-homebridge

> I haven't spent any time really looking into the ins and outs of the link I pasted above, but is the SmartThings API a possible avenue? At least it's all official/public/published developer material. Provided of course their TV(s) also use their own API. Has to use something, as of course Sammy's own SmartThings mobile software can do direct/instant source switching.

Nope! I don’t have the time to learn SmartThings api and develop the plugin almost from 0!

As long as Samsung will keep the current endpoint running, i will not change it since it does 98% of what we need right now!

Yeah, i would like to get the volume of tv, or the current channel but these are just gimmicks! We can live without them :)
