### ISSUE TITLE
Only 0n/off button on 2020 65Q90

### ISSUE THREAD

**Issue by Maykel1969** [tavicu/homebridge-samsung-tizen#319]
Hi,
I got the plugin working and the tv is added to the home app.
But the only thing I see is a on/off button, nothing else.
The on/off button works fine but how do I get all the other buttons?
Am I missing something??

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/wiki. By default only on/off switch is available.

**Comment by Maykel1969** [comment]
Ok, I read the wiki but it’s still not clear how to get the extra buttons.
I tested the link to the ip adress of the tv and i get a lot of text.
But what is the next step? That’s not clear from the wiki.

**Comment by tavicu** [comment]
What extra buttons are you looking for?

**Comment by Maykel1969** [comment]
Just the basics. Up down left right enter etc.

Sent from my mobile device.

**Comment by tavicu** [comment]
That you will find in Remote from Control Center, note in Home App!

https://github.com/tavicu/homebridge-samsung-tizen/issues/305#issuecomment-778611523

**Comment by Maykel1969** [comment]
That’s briljant! This works!
As a newbee I expected these buttons in the home app :-)
You could put some screenshots in the wiki to prevent these silly mistakes.
Where will the netflix button popup? (If configured right of course)

Sent from my mobile device.

**Comment by tavicu** [comment]
> You could put some screenshots in the wiki to prevent these silly mistakes. 

Wiki had photos but they where removed from the image hosting. I will update the wiki pages but right now i am working on another feature.

> Where will the netflix button popup? (If configured right of course) Sent from my mobile device.

You cannot change the buttons from Remote. Apple doesn't give us that option!
But you can set an Input and then control it from the Home App or ask Siri to switch Input to Neftlix. https://github.com/tavicu/homebridge-samsung-tizen/wiki/Inputs
