### ISSUE TITLE
Failed to fetch installed applications! Your TV may not support this feature. Read our Wiki for more informations!

### ISSUE THREAD

**Issue by wildman199** [tavicu/homebridge-samsung-tizen#323]
model code: QN55Q80TAFXZA
Software Version: T-NKMAKUC-1462.1

**Comment by tavicu** [comment]
Hi! What did you not understand from that message?

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/wiki/Applications#getting-list-with-installed-applications-from-your-tv

**Comment by wildman199** [comment]
Is there a patch or update to fix this failure?

**Comment by tavicu** [comment]
> Is there a patch or update to fix this failure?

Man ... i just posted the link to the wiki! Did you read it?

**Comment by wildman199** [comment]
👍
