### ISSUE TITLE
[Request] Command-line control of TV

### ISSUE THREAD

**Issue by HVR88** [tavicu/homebridge-samsung-tizen#332]
Is there any possibility that you might leverage this work to create a script that can send keys and app commands via the *nix command line?

I've tried a few other solutions to achieve this (in Python) and they've all failed. Your Homebridge plugin however works brilliantly and easily connects to my TV.

I'm looking to be able to send arbitrary commands to the TV, triggered by an external device. In my case, my Home Automation platform can take incoming webhook/URL calls and then do actions with devices/scripts.

**Comment by tavicu** [comment]
Hi.

You can configure switches that trigger a key or a list of keys (https://github.com/tavicu/homebridge-samsung-tizen/wiki/Switches) then control these switches with your automations.
