### ISSUE TITLE
Remote disappears

### ISSUE THREAD

**Issue by jianyu-li** [tavicu/homebridge-samsung-tizen#333]
The remote in the control center often disappears. Sometimes I feel like if I open the home app it'll come back but not all the time

**Comment by tavicu** [comment]
Hi. You, it happens to me also but not too often. Usually when I'm outside my local network. Probably it takes longer to make a connection from outside with the Homebridge server and Apple sees the devices as offline.

I don't know on which terms Apple decide to show devices so I can guide you but the plugin set the TVs as reachable all the time.

Unfortunately there is nothing i can do more :)

**Comment by jianyu-li** [comment]
Ok thank you
