### ISSUE TITLE
Getting list of installed apps Samsung TU8500 

### ISSUE THREAD

**Issue by Greminn** [tavicu/homebridge-samsung-tizen#334]
Hi There, I have a Samsung TU8500 and Hoobs setup and have just updated to the latest version of homebridge-samsung-tizen. I note the following (which did not work before the update either)... for some reason it wont show the list of apps in hoobs:

31/03/2021, 12:56:22 pm Loaded plugin 'homebridge-samsung-tizen'
31/03/2021, 12:56:22 pm [3/31/2021, 12:56:22 PM] Registering platform 'homebridge-samsung-tizen.SamsungTizen'
31/03/2021, 12:56:22 pm [SamsungTizen] Initializing SamsungTizen platform...
31/03/2021, 12:56:23 pm Lounge TV is running on port 52402.
31/03/2021, 12:57:15 pm Please add [Lounge TV] manually in Home app. Setup Code: 031-45-154

PS: Lounge TV is already added in the home app. Does this always show? 

31/03/2021, 12:56:31 pm [Lounge TV] TV is offline! Can't get installed apps!

PS: So, duh turn the TV on! Then I get this:

31/03/2021, 12:57:26 pm [Lounge TV] Failed to fetch installed applications! Your TV may not support this feature. Read our Wiki for more informations!

Otherwise works as it should. Note that the TV is a 2020 model. Here is the output from the API web page if that helps:

{"device":{"FrameTVSupport":"false","GamePadSupport":"true","ImeSyncedSupport":"true","Language":"en_GB","OS":"Tizen","PowerState":"on","TokenAuthSupport":"true","VoiceSupport":"true","WallScreenRatio":"0","WallService":"false","countryCode":"NZ","description":"Samsung DTV RCR","developerIP":"0.0.0.0","developerMode":"0","duid":"uuid:xxxxxxxx","firmwareVersion":"Unknown","id":"uuid: xxxxxxxx","ip":"10.1.1.16","model":"20_NIKEL_UHD","modelName":"UA50TU8500SXNZ","name":"[TV] Samsung TV","networkType":"wired","resolution":"3840x2160","smartHubAgreement":"true","type":"Samsung SmartTV","udn":"uuid: xxxxxxxx","wifiMac":"68:72:c3:45:9f:93"},"id":"uuid: xxxxxxxx","isSupport":"{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"false\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n","name":"[TV] Samsung TV","remote":"1.0","type":"Samsung SmartTV","uri":"http://10.1.1.16:8001/api/v2/","version":"2.0.25"}

**Comment by tavicu** [comment]
Hei,

https://github.com/tavicu/homebridge-samsung-tizen/wiki/Applications#newer-tvs-model-year--2020

**Comment by Greminn** [comment]
> Hei,
> 
> https://github.com/tavicu/homebridge-samsung-tizen/wiki/Applications#newer-tvs-model-year--2020
> 
> also at the top of the page you have a list with ids, maybe you already find what you are looking for :)

Ha! Sorry I read the wiki wrong :)
