### ISSUE TITLE
Update to installation page on the wiki

### ISSUE THREAD

**Issue by benfysh** [tavicu/homebridge-samsung-tizen#335]
Hi @tavicu I know you have confirmed that the PIN pairing method wont be supported here https://github.com/tavicu/homebridge-samsung-tizen/issues/302 I just wondered if it might be worth linking to [Homebridge-SamsungTV-Control](https://github.com/mmende/homebridge-samsungtv-control2#readme) which works with those models from the [installation page on the wiki](https://github.com/tavicu/homebridge-samsung-tizen/wiki/Installation) so that people can see the alternative. Thanks

**Comment by tavicu** [comment]
Hi @benfysh 

Unfortunately i cannot recommend something that i can't test it or even know how it's working.
People will think the plugins are related and start asking for support and i won't be able to help them.

**Comment by benfysh** [comment]
no problem @tavicu makes sense.
