### ISSUE TITLE
TV Not responding when off [TV] Remote.setActive is not a function

### ISSUE THREAD

**Issue by MarkBarbieri** [tavicu/homebridge-samsung-tizen#340]
On version v5.0.0, with Homebridge version v1.3.4.  TV is a 2017 QLED

This has all been working fine until the last update.   Previously on v4.4.0

When the TV is powered off, this accessory will no longer power on the TV.
```
                        {
                            "name": "Channel Two",
                            "power": true,
                            "channel": 20
                        },
```
I'm seeing this error being logged
```
[13/04/2021, 8:54:14 am] [TV] Remote.setActive is not a function
```
If I turn on the TV first, then the channel is switched correctly using this accessory.

Any thoughts?

**Comment by MarkBarbieri** [comment]
And I've confirmed that just turning on the TV works via this plugin, so the issue appears to be isolated to turning on the TV using power: true as part of a channel input

**Comment by tavicu** [comment]
My bad :) 
Pushed a new version with the fix

**Comment by MarkBarbieri** [comment]
Excellent, thanks
