### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by jontucker311** [tavicu/homebridge-samsung-tizen#341]
My TV keeps asking me for permission. How can I get it to stop that?

**Comment by deepontech** [comment]
Disable "keep asking permission" @ your TVs menu. 

It worked for me

**Comment by jontucker311** [comment]
Thank you, I got it turned off and it stopped asking me for permission.

**Comment by jontucker311** [comment]
new problem, if i use the home app to turn the tv off it will turnoff but after about 10 seconds the app reflects on and the tv makes the turn on sound but doesn't turn on.

**Comment by deepontech** [comment]
Im a beginner also so I couldn't help you much better, I would try a fresh install of the plugin, after trying to restart the home bridge system. Are running HB on a rasp?

**Comment by jontucker311** [comment]
I'm a beginner as well. This is a fresh install of the plugin, I've uninstalled and reinstalled a couple times now. Yes, I'm running HOOB on a rasp.

**Comment by tavicu** [comment]
Hei. Is the problem still present?

I did not fully understand your problem. Especially the 'on sound' :D, i have 4 samsung tvs and none of them make any sound.

i understand that after 10 seconds the accessory turns on, but how is the accessory after more seconds? Let's say 20 :)

I need more infos, like your TV model year, and an output of `http://TV_IP:8001/api/v2/` (replace TV_IP with your TV IP)
