### ISSUE TITLE
Power

### ISSUE THREAD

**Issue by bearreth** [tavicu/homebridge-samsung-tizen#342]
Hi guys,

I'm using a 2020 55" Frame TV (QN55LS03TAFXZC).

Is anyone else having an issue with powering it on via Home? It works through the SmartThings app, and I do have the setting for powering on with mobile on in the settings. Restarted the TV as well (and unplugged and power cycled).

**Comment by mrMiimo** [comment]
Hi,
first of all, which version are you using?
You looked at the wiki [https://github.com/tavicu/homebridge-samsung-tizen/wiki/Configuration](url) and other open and solved issues, such as #165
?

**Comment by tavicu** [comment]
Hei. https://github.com/tavicu/homebridge-samsung-tizen/issues/336#issuecomment-812912842

Make sure your mac address is correct! If you are using WiFi then use the wifi mac address, if you are using cable, make sure  to use that mac address.

**Comment by bearreth** [comment]
Thanks everyone! Turns out my MAC address had a typo in it. It was supposed to be "CC" instead of "CD".
