### ISSUE TITLE
TV Frame with 5.0.1

### ISSUE THREAD

**Issue by Stetocasa** [tavicu/homebridge-samsung-tizen#343]
Hello, finally after months Samsung The Frame in compatible and until yesterday works fine with HomeKit (Art Mode and Off mode works fine)
Today art mode and power disappear and the pure switch tv icon still in HomeKit losing the new features.
Tried to delete and add the accessory and deleting and installing again the plug-in 
How can come back with the complete options?![image](https://user-images.githubusercontent.com/70729310/114682179-2376f180-9d0f-11eb-9726-73b2cd4f36a7.png)

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/issues/318#issuecomment-817726064
