### ISSUE TITLE
Samsung Frame HomeKit Display error

### ISSUE THREAD

**Issue by Maeri21** [tavicu/homebridge-samsung-tizen#345]
Hey
TV Model: UExxLS003
HomeBridge Plugin: homebridge-samsung-tizen v5.0.1
I got the TV in HomeKit but every Time I turn off the TV (from on to Art Mode) the HomeKit shows Off. After 30 seconds the HomeKit shows On again, but the TV is still in Art Mode.
I have already tried all three options (Display and control Real Power with Main Acccessory, Disable Art Swith, Disable Power Switch) but no one fix the problem.
I also tried to add an refresh but also no problem fix
Can somone help me?
Thanks a lot and best Regards.

**Comment by tavicu** [comment]
Hi.

Start the homebridge in debug mode (`homebridge -D` or if you are using config-ui-x you have a setting).
That way we can see the requests.

**Comment by Maeri21** [comment]
Thanks a lot for your suggestions
I started the HomeBridge in Debug Mode > still error.
When the TV turns off -> Key_Power Option false
After  30 Sec, the TV shows in HomeKit on again and therese no request shows in the console.
You have any Ideas? Thanks a lot!!

**Comment by tavicu** [comment]
If the TV is detected as Frame it should refresh the art mode status every 5 seconds and you should see the calls in the console. Since you don't see anything looks like your TV is not detected as frame.

You can see here how to force it to use frame method: https://github.com/tavicu/homebridge-samsung-tizen/issues/318#issuecomment-817726064

**Comment by Maeri21** [comment]
Thanks, i will try that and let you know if it works :)

**Comment by Maeri21** [comment]
Hey, everything works perfectly. Thank you very much for the plugin and the great support. I really appreciate it!
Best regards
Maeri
