### ISSUE TITLE
How to fully turn off the Frame?

### ISSUE THREAD

**Issue by RAFd3v** [tavicu/homebridge-samsung-tizen#348]
Hi. 
first: Awesome plug-in!

But have can I turn off the Frame completely?
If I toggle the Main Switch in Home App it only switches to the Art Mode and back.

**Comment by tavicu** [comment]
Hi!

you have more options that you can set. Please read https://git.io/JOII1

**Comment by RAFd3v** [comment]
Thank you!
Worked for me!
