### ISSUE TITLE
ID Molotov application 

### ISSUE THREAD

**Issue by lgarbell** [tavicu/homebridge-samsung-tizen#349]
First, @tavicu thanks you so much for this great plugin :)

If someone have the ID off the Molotov application I would like to have it. 

Another question that has nothing to do with this plugin but is it possible to connect the Homepod as an audio input to the samsung tv ? With a homebridge plugin or another method ?

Have a good day

**Comment by zim1498** [comment]
Hello, thank you very much for the work, I am also very interested in the application numbers of Molotov TV

**Comment by tavicu** [comment]
> If someone have the ID off the Molotov application I would like to have it.

If they id from @zim1498 don't work you can follow the steps from here and get a list with all your applications: https://github.com/tavicu/homebridge-samsung-tizen/wiki/Applications#getting-list-with-installed-applications-from-your-tv

> Another question that has nothing to do with this plugin but is it possible to connect the Homepod as an audio input to the samsung tv ? With a homebridge plugin or another method ?

Can't you do that from Bluetooth on TV? I know you can connect speakers through bluetooth

**Comment by EMP83** [comment]
Hello,
Does anyone know the Focus Romania app ID? 
I have a KS6500 but when i run "hoobs tizen-apps" in terminal i get this:

>hoobs@hoobs:/home/hoobs/.hoobs/etc $ hoobs tizen-apps
Error: listen EADDRINUSE: address already in use :::88
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 88
}
[HOOBS] Stopping server.
hoobs@hoobs:/home/hoobs/.hoobs/etc $ 
> 
Thanks

**Comment by EMP83** [comment]
Problem solved,I found him [here](https://github.com/tavicu/homebridge-samsung-tizen/wiki/Applications).
