### ISSUE TITLE
Additional Apps for your list!

### ISSUE THREAD

**Issue by BReligion** [tavicu/homebridge-samsung-tizen#351]
Here are a few more apps for your list.
These are all for the model < 2020 model side of your chart!

App Name :  MLB 
App ID   :  3201603008210

App Name :  Crave
App ID   :  3201506003488

App Name :  Love Nature 4K
App ID   :  3201703012065

App Name :  SiriusXM
App ID   :  111399002220

App Name :  YouTube Kids
App ID   :  3201611010983

thanks again for all the work you do!

**Comment by tavicu** [comment]
Hi! Thank you for your support :)

I have updated the page
