### ISSUE TITLE
Samsung TV shows in Home app but not 3rd Party (eg Home+) apps

### ISSUE THREAD

**Issue by BarneyHam** [tavicu/homebridge-samsung-tizen#352]
I love this Homebridge plugin / Homekit integration implementation.

I'm using 5.01, with two Frame TVs, and am successfully able to move them in and out of Art mode etc.

However, I'd like to use some conditional automations using light, motion etc to switch the TV into Art mode (while the 55 inch+ have their own motion sensors, the smaller 32inch bizarrely doesn't). Can't do conditional automation in Home, so need to use Home+ or Controller apps. 

However, the Samsung TVs are their related controls are not showing up in these apps, only in the Home app. Is there a reason for that?

Thank you so much.

**Comment by tavicu** [comment]
Hi,

For every TV it's created a separate bridge (that's why you need to add it in Home app). It could be related to this and how those apps detect accessories.

Unfortunately i don't use any of them and don't know how to help you.
