### ISSUE TITLE
Frame TV type no longer recognized

### ISSUE THREAD

**Issue by mbolo01** [tavicu/homebridge-samsung-tizen#354]
Dear team,

First, thanks for your development.
I was expecting these Frame enhancements since a while, particularly the real power off switch, but unfortunately my Frame is no longer recognized as such.
When I first upgraded the plugin, I could see the Frame switches (Art, power off) in the Accessories page of the HomeBridge UI and they were all operational.
As I was not seing the change reflected in Home app, I removed the device from the Home app and tried to add it back without success. I thought I may have to recreate the Frame so I removed the TV from the plugin settings and recreated it which unfortunately is now showing like a regular Samsung TV, no longer as a Frame ( i try many things, including removing/installing the plugin from scratch).
What can I do so the TV is recognized for what it is and so I can use the new Frame switches?
Kind regards.

TV Information:
Manufacturer: Samsung TV
Model: Tizen OS
Name :Frame 343B
Firmware Revision: 5.0.1

**Comment by tavicu** [comment]
Hi :)
You can force the plugin to see the TV as a frame: https://github.com/tavicu/homebridge-samsung-tizen/issues/318#issuecomment-817726064
