### ISSUE TITLE
Long press or 3D Touch app list display issue

### ISSUE THREAD

**Issue by EMP83** [tavicu/homebridge-samsung-tizen#357]
![IMG_0175](https://user-images.githubusercontent.com/36104474/116821428-23ce1400-ab7a-11eb-8c6f-44f99c8c31a1.PNG)
![IMG_0174](https://user-images.githubusercontent.com/36104474/116821430-2892c800-ab7a-11eb-95b4-4528da59800d.PNG)

How can I make the Samsung app list to look like LG menu? In the homekit it is displayed correctly but in control center is not. 
TV Samsung KS6500 + hoobs on raspberry pi 4

This is my config:

`[
    {
        "name": "TV Samsung",
        "ip": "192.168.1.23",
        "mac": "FF:FF:FF:FF:FF:FF",
        "inputs": [
            {
                "name": "Focus Sat",
                "type": "app",
                "value": "3201906018693"
            },
            {
                "name": "Netflix",
                "type": "app",
                "value": "11101200001"
            },
            {
                "name": "HBO GO",
                "type": "app",
                "value": "3201706012478"
            },
            {
                "name": "YouTube",
                "type": "app",
                "value": "111299001912"
            },
            {
                "name": "Prime",
                "type": "app",
                "value": "3201512006785"
            },
            {
                "name": "Spotify",
                "type": "app",
                "value": "3201606009684"
            }
        ],
        "keys": {
            "PLAY_PAUSE": "KEY_HOME",
            "INFORMATION": "KEY_CH_LIST"
        }
    }
]`

**Comment by tavicu** [comment]
Because you added the inputs after you added the TV you need to wait some time until homekit process it and display as it should :)

just wait! A few restarts of home app also helps

**Comment by EMP83** [comment]
No luck so far. 
Maybe it's something I can change in config?!

Mulțumesc și un Paște Fericit!

**Comment by tavicu** [comment]
> No luck so far.
> Maybe it's something I can change in config?!

nope! Config is ok! Just wait for tomorrow :) trust me ;)

> Mulțumesc și un Paște Fericit!

Multumesc :) La fel si tie!

**Comment by EMP83** [comment]
Problem solved by resetting HOOBS and connecting it to the router via cable.


Mulțumesc, 
Mult succes în continuare.
