### ISSUE TITLE
Frame TV - Permission

### ISSUE THREAD

**Issue by Stetocasa** [tavicu/homebridge-samsung-tizen#359]
Hi, every server restart my tv ask to confirm the permission.
It's normal?

**Comment by tavicu** [comment]
Hi. It’s not normal!

Maybe this helps: https://github.com/tavicu/homebridge-samsung-tizen/wiki/Common-Issues#--tv-is-always-asking-for-permissions

**Comment by Stetocasa** [comment]
Already tried!
I'm running hoobs4 this could be the issue ?

**Comment by tavicu** [comment]
Hi. Sorry for the delay.

I am not very familiar with hoobs.

The only problem that hoobs could generate is not allowing the plugin to write the config file.
Every time you confirm permission the TV generates a pin that is saved in a config file and it's used for the next requests so it won't have to pair every time.

But i didn't see anyone else having this problem with Hoobs. Maybe you made some "security" improvements and not allowing it to write files?

The path for the file is like this: `~/.homebridge/accessories/samsung-tizen.json`
Or where your homebridge instance is saved.

**Comment by jakubhavel** [comment]
@tavicu Hi, I have exactly the same issue as @Stetocasa – Hoobs is updated to the newest version, same applies for the plugin. Every time i restart TV or HOOBS the TV wants me to grant permission for a remote device despite the fact i have the notification turned off (according to the configuration steps).

Any update would be appreciated 😊.

Thanks.

**Comment by breather74** [comment]
any updates on this I'm having the same issue?

**Comment by inwaar** [comment]
same problem

**Comment by tavicu** [comment]
> same problem, @tavicu could the issue be re-open?

Hi. Unfortunately no because at the moment I don’t offer support for Hoobs! The plugin is for Homebridge. 

Hoobs it’s a wrapper that may have other security measures as I told on a previous message.

**Comment by Stetocasa** [comment]
Why using hoobs?
Homebridge UI is more user friendly and the system more stable

I was an hoobs user but after switched to homebridge I understood that I lose my time!

If you have Hoobs box, just open the box and reflash the SD with homebridge iso
Your life will change

**Comment by jakubhavel** [comment]
@Homekitdude imho it's resolved indeed or at least @tavicu mentioned several times the plugin DOES NOT support HOOBS 😊 in my case i just migrated from HOOBS to Homebridge and things started to work as supposed to – my suggestion would be doing the same thing and your life will be a lot easier 😊 i don't even know why i chose HOOBS over Homebridge back then – now it simply does not make any sense 😃

**Comment by Homekitdude** [comment]
I have no idea how to even do that. I’ve been enjoying HOOBS and it was simple enough to install and get up and running. But apart from that, I’m lost.

**Comment by jakubhavel** [comment]
@Homekitdude Homebridge is almost the same 😊 you install it onto a SDcard, boot it, login over WebUI, install your plugins and configure them 😊 so in my case i backed up the existing config of all plugins, then i erased HOOBS, installed Homebridge, installed plugins and pasted there the backed up configuration 😊 simple as that, took me about 1,5 hours with my RPi 2 😊 if you dont know how to do this, just find some tutorial on Google/YouTube 😊

**Comment by Stetocasa** [comment]
> I have no idea how to even do that. I’ve been enjoying HOOBS and it was simple enough to install and get up and running. But apart from that, I’m lost.

I was an Hoobs user for months, thinking that Hoobs was more user friendly 

Reflash the Hoobs box SD to homebridge your life will change !!
More stability, better compatible plug-in 

Upgrade to homebridge !

**Comment by jakubhavel** [comment]
@Stetocasa amen 👌🏻
> > I have no idea how to even do that. I’ve been enjoying HOOBS and it was simple enough to install and get up and running. But apart from that, I’m lost.
> 
> I was an Hoobs user for months, thinking that Hoobs was more user friendly
> 
> Reflash the Hoobs box SD to homebridge your life will change !! More stability, better compatible plug-in
> 
> Upgrade to homebridge !
