### ISSUE TITLE
Accessory no longer shows up in Homekit - flat is not a function in logs

### ISSUE THREAD

**Issue by stueybee** [tavicu/homebridge-samsung-tizen#361]
After a recent upgrade (hoops and plug-in) my interface to Homekit stopped working. Below are output from logs and the configuration. 

Note the last line ....tlat is not a function. Not sure where that is coming from.

Any thoughts on what to check. Permissions to allow remote access are ok, I have reset TV and Homekit and Hobbs interface numerous times. but the Accessory no longer shows up. 

Got SIGINT, shutting down Bridge...
5/9/2021, 7:21:00 AM Initializing HAP-NodeJS v0.9.3...
5/9/2021, 7:21:02 AM Loaded plugin 'homebridge-bond'
5/9/2021, 7:21:02 AM [5/9/2021, 7:21:02 AM] Registering platform 'homebridge-bond.Bond'
5/9/2021, 7:21:03 AM Loaded plugin 'homebridge-samsung-tizen'
5/9/2021, 7:21:03 AM [5/9/2021, 7:21:03 AM] Registering platform 'homebridge-samsung-tizen.SamsungTizen'
5/9/2021, 7:21:03 AM Loading 2 platforms...
5/9/2021, 7:21:03 AM [SamsungTizen] Initializing SamsungTizen platform...
5/9/2021, 7:21:03 AM Preparing Advertiser for 'HOOBS 2502' using bonjour-hap backend!
5/9/2021, 7:21:03 AM Starting to advertise 'HOOBS 2502' using bonjour-hap backend!
5/9/2021, 7:21:03 AM Bridge is running on port 51826.
5/9/2021, 7:21:03 AM [SamsungTizen] [(...Object.values(...).map(...)),(...Object.values(...).map(...))].flat is not a function

 {
            "platform": "SamsungTizen",
            "plugin_map": {
                "plugin_name": "homebridge-samsung-tizen"
            },
            "devices": [
                {
                    "name": "TV",
                    "ip": "10.0.0.167",
                    "mac": "B8:BC:5B:F1:18:4A"
                }

**Comment by tavicu** [comment]
Hi. You need to update your node.js to a newer version.

Flat function was introduced in node 11.0.0

**Comment by stueybee** [comment]
Thanks I am using Hoobs interface (3.3.5)  to homebridge and it shows node.js at (10.17.0). I will reach out to that community to find out how to update node.js or if there is an upcoming Hoobs upgrade that will address this. Thanks for getting back to me so quickly
