### ISSUE TITLE
Unable to connect TV

### ISSUE THREAD

**Issue by blackbasket** [tavicu/homebridge-samsung-tizen#364]
Hi,

I am new with Homebridge. I installed the plugin, gut there is no possibility to allow the new remote control on TV.

Please find the only debug message as well as the json attached.

Regards,
Marcel

![image](https://user-images.githubusercontent.com/64146687/118133163-c8fdad80-b400-11eb-9e08-e25de978a248.jpeg)
![image](https://user-images.githubusercontent.com/64146687/118133198-d31fac00-b400-11eb-8385-9a1aee61b829.jpeg)

**Comment by tavicu** [comment]
Don’t understand the problem!

the plugin connected with success to the tv

**Comment by blackbasket** [comment]
Hmm, I cannot do anything. Not even switch on/off.

**Comment by blackbasket** [comment]
I got some more debug output after trying to switch the TV off.

![image](https://user-images.githubusercontent.com/64146687/118136660-a4a3d000-b404-11eb-8a6b-53b9a031ae47.jpeg)

![image](https://user-images.githubusercontent.com/64146687/118136676-a9688400-b404-11eb-8d4a-b360b5d51bdc.jpeg)

**Comment by blackbasket** [comment]
I am out of ideas... I tried unplugging TV for more than 30 seconds, changed the IP, did a factory reset...

**Comment by tavicu** [comment]
From the logs, your tv is not compatible.  What model is?

**Comment by blackbasket** [comment]
Hi @tavicu ,

it is a UE55JS8590. I am able to connect to the api using http://ip:8001/api/v2/

Regards,
Marcel

**Comment by tavicu** [comment]
Yup! Looks like the model is older and using another method to pair! This plugin is not compatible with your tv!

you can search the closed issues for “pin” keyword and see what others used!

**Comment by tavicu** [comment]
For example: https://github.com/tavicu/homebridge-samsung-tizen/issues/335

**Comment by blackbasket** [comment]
Thank you :)

I know that I bought it in 2016. and because the api was working, I thought it matches.

Regards,
Marcel
