### ISSUE TITLE
Apple Music ID note working

### ISSUE THREAD

**Issue by doddsey123** [tavicu/homebridge-samsung-tizen#365]
Samsung frame tv nothing happening using the input value 3201910019378 all others seem to work as expected. On a side note noticed when adding and removing inputs stale code gets left behind in config resulting in unnamed services in HomeKit. Easy to remove code but extra step

**Comment by neotic82** [comment]
Hi!, the Apple Music Code is 3201908019041

I have it configured in homebridge and it works correctly :/

**Comment by tavicu** [comment]
As @neotic82 said, you are using the wrong code :)

3201910019378 is for SmartThings app
