### ISSUE TITLE
update common issues page

### ISSUE THREAD

**Issue by ramz35** [tavicu/homebridge-samsung-tizen#366]
I just had a similar issue to the one on #312 and there’s also another one that was raised and closed but without success (don’t remember the number, typing on my phone). 

Basically after adding the plugin and configuring the TV if you remove the plugin and/or delete it’s accessories when you re-add the plug in or TV then it won’t appear in homekit - not even if you go and add accessory. The solution is to add A1 to the uid. 

I think it’s been raised a few times now to warrant a place in the common issues just to help the next lot of users who might give up on this plugin if they get to this stage. Which would be a shame.

**Comment by tavicu** [comment]
Hi, sorry for the delay! It's a very busy period on my work and don't have time for github :)

I have in plan to update all wiki pages with more informations and also images (you know, picture worth 1000 words) :)

Until then, i have added the issue to common issues (https://github.com/tavicu/homebridge-samsung-tizen/wiki/Common-Issues#--cant-add-tv-after-removing-or-making-changes)
