### ISSUE TITLE
Samsung The Frame no detected 

### ISSUE THREAD

**Issue by Stewart06** [tavicu/homebridge-samsung-tizen#367]
Bonjour,

Depuis la dernière mise à jour du plugin, ma télé The Frame avait été détectée et de nouvelle option était apparu dans HomeKit pour la gestion du mode art.

Depuis j’ai dû réinitialiser ma maison dans HomeKit suite à un bug avec iOS 14.5.1 et maintenant ma télé n’est plus reconnu en tant que The Frame.

Avez-vous une solution pour que je puisse retrouvé les options dans HomeKit permettant de gérer le mode Art ?

PS: J’ai essayé de revenir à une version précédente et ensuite faire une mise à jour mais rien ne change malheureusement.

Hello,

  Since the last plugin update, my The Frame TV had been detected and a new option had appeared in HomeKit for art mode management.

  Since then I had to reset my home in the HomeKit suite to a bug with iOS 14.5.1 and now my TV is no longer recognized as The Frame.

  Do you have a solution so that I can find the options in HomeKit to manage Art mode?

  PS I tried to go back to a previous version and then update but unfortunately nothing changes.

**Comment by tavicu** [comment]
Hi.

https://github.com/tavicu/homebridge-samsung-tizen/issues/354#issuecomment-827570385

**Comment by Stewart06** [comment]
Thank you !
