### ISSUE TITLE
Unable to select specific HDMI channel

### ISSUE THREAD

**Issue by eduardoboucas** [tavicu/homebridge-samsung-tizen#37]
Sending commands such as `HDMI_1` doesn't work. I've previously reported this in #18, but since that issue is now closed I thought it'd be useful to open a new one for future reference.

Thanks!

**Comment by tavicu** [comment]
As i already said in that issue, `HDMI_*` or `HDMI*` keys don't exist. I will remove them from README with the next push

**Comment by Yamch** [comment]
Sending commands such as HDMI_1 does not work. Thank you
