### ISSUE TITLE
iOS 15 - new layout for remote 

### ISSUE THREAD

**Issue by ShayShahar** [tavicu/homebridge-samsung-tizen#372]
iOS 15 bring a new layout for remote controllers for Apple TV with more buttons compared to the previous remotes. Is it possible to implement the new layout for tizen?

**Comment by tavicu** [comment]
Hi. Once we will have more betas from Apple i will implement the changes.

Right now i don't know what you're talking about :D didn't had time to dig in and also i don't have a testing device where i can install betas. I only have my main devices.

Also if they changed the apis or something, first we will have to wait for Homebridge and hap-nodejs to be updated.
