### ISSUE TITLE
Samsung tv has Disappeared from my Home app - (after update)

### ISSUE THREAD

**Issue by danielero** [tavicu/homebridge-samsung-tizen#376]
Hello 

I Would love your help.
after I updated to the new version, My Samsung tv's has disappeared from The Home app, I tried to Reset The settings of my tv, Hoobs and And even I tried to reboot the Home in The home app.

I can't find the reason why it stopped working, I can see the tv on The LOG in the hoobs Ui but from some reason The tv can not be aded to The Home app.

Is it something known? How can I fix it?

**Comment by tavicu** [comment]
HI,

I don't understand what you updated. Tv, phone, homebridge, plugin, hoobs ...

Anyway! You could add uuid in your config and after that you will be able to add it again in home app. https://github.com/tavicu/homebridge-samsung-tizen/wiki/Common-Issues#--cant-add-tv-after-removing-or-making-changes

Keep in mind that it will have to repair, so the TV should be on when you start the homebridge server.
