### ISSUE TITLE
only one input

### ISSUE THREAD

**Issue by sonezu** [tavicu/homebridge-samsung-tizen#377]
Hi guys,

pretty simple:
I have added three inputs:

```
"inputs": [
                        {
                            "type": "command",
                            "name": "LiveTV",
                            "value": "KEY_SOURCE,KEY_LEFT*3,KEY_ENTER"
                        },
                        {
                            "type": "command",
                            "name": "ARD",
                            "value": "KEY_0,KEY_1"
                        },
                        {
                            "type": "app",
                            "name": "Netflix",
                            "value": "11101200001"
                        }
                    ]
```

In Home it only show the first entry (LiveTV).

Another observation:
Clicking on Plugins / homebridge-samsung-tizen / settings in the input section I can only see the first input entry. Adding another input shows the new entry filled with the values of the config file.

Thank you!

**Comment by tavicu** [comment]
Hi,

Do the inputs appear as separate accessories? If yes, https://github.com/tavicu/homebridge-samsung-tizen/wiki/Common-Issues#--inputs-are-appearing-like-separate-accessories

Also, yeah, in config-ui-x only first entry will be shown by default when you edit and when you click add more it will populate with the input settings from config. Didn't find an option to display all entries from config when it's a list of options ...

**Comment by SeydX** [comment]
@tavicu 

it seems that the default config.schema.json has problems showing nested arrays and therefore it displays only one item

But it can be fixed with custom ui

https://github.com/homebridge/plugin-ui-utils

**Comment by tavicu** [comment]
Hi,

I have took a look but at this time it's not a priority for me to create custom ui.

if one of you have knowledge and want to help, you can create a pull request and we will look together into it :)
