### ISSUE TITLE
command for rotate sero tv screen portrait or landscape? 

### ISSUE THREAD

**Issue by strebela** [tavicu/homebridge-samsung-tizen#392]
anibody know:

command for rotate sero tv screen portrait or landscape?

best regards, andré

**Comment by tavicu** [comment]
Hi, i'm sorry but i am not aware of a command like this.

The api supports only commands that are physically on a remote.

Here is a list where you can see some of the commands: https://github.com/tavicu/homebridge-samsung-tizen/wiki/Commands

**Comment by tavicu** [comment]
Unfortunately i still can't help you since i don't have a remote with a button like this to try and intercept what key is. You will have do search other repos/google for someone that had the same problem and found the key command
