### ISSUE TITLE
Samsung TV Frame Turns to on when off!

### ISSUE THREAD

**Issue by adavison007** [tavicu/homebridge-samsung-tizen#395]
Hi, Love the plugin, I am having an issue where when I turn the TV off from homekit, the tv does turn off... but 30 seconds later homekit shows it as on again.... but the tv is not on (Frame TV and the art is on) then everything works in reverse, off becomes on and on becomes off.... so in short, for some reason when you turn it off in home kit, the TV shows as on again in homekit 30 seconds later, but the TV does not turn on itself....

**Comment by adavison007** [comment]
UPDATE. If I turn the TV off, off and not with art on, then homekit shows as off and stays off, so there is an issue with art making the TV show as on.

**Comment by Fish2** [comment]
is this a frame 2021 im having issues no mater what settings that on turning off it goes to art mode

**Comment by tavicu** [comment]
Uoff …
Your tv is not detected as frame automatically!

https://github.com/tavicu/homebridge-samsung-tizen/issues/354#issuecomment-827570385

**Comment by adavison007** [comment]
OK, "method": "frame" in the json makes it all work, you can then use the 3 frame options in the UI... but these only work once you have entered Method Frame first... Suggestion, add is it a frame TV in the UI too?

**Comment by tavicu** [comment]
Hi, yup. 

I am planning to make an option so you could select the TV as frame manually in Config UI X :)

It will be in the next release

**Comment by thomasgaillard** [comment]
Hello there,
same problem for me.
when turn off (art mode) my samsung the frame 2021, It appear as off in homekit ... but a few second later it turns on.

I tried to put on and off each options in the attachment but nothing.
<img width="576" alt="Capture d’écran 2021-08-20 à 17 05 10" src="https://user-images.githubusercontent.com/681454/130253939-378400a2-49e5-4db8-8ee5-1e7b57e003f0.png">

is there any way to fix that ? In the UI or JSON.

Thanks to you and for this plugin :)

**Comment by Fish2** [comment]
> Hello there,
> same problem for me.
> when turn off (art mode) my samsung the frame 2021, It appear as off in homekit ... but a few second later it turns on.
> 
> I tried to put on and off each options in the attachment but nothing.
> <img alt="Capture d’écran 2021-08-20 à 17 05 10" width="576" src="https://user-images.githubusercontent.com/681454/130253939-378400a2-49e5-4db8-8ee5-1e7b57e003f0.png">
> 
> is there any way to fix that ? In the UI or JSON.
> 
> Thanks to you and for this plugin :)

you need to add `"method": "frame",`

**Comment by adavison007** [comment]
> Hello there,
> same problem for me.
> when turn off (art mode) my samsung the frame 2021, It appear as off in homekit ... but a few second later it turns on.
> 
> I tried to put on and off each options in the attachment but nothing.
> <img alt="Capture d’écran 2021-08-20 à 17 05 10" width="576" src="https://user-images.githubusercontent.com/681454/130253939-378400a2-49e5-4db8-8ee5-1e7b57e003f0.png">
> 
> is there any way to fix that ? In the UI or JSON.
> 
> Thanks to you and for this plugin :)

@thomasgaillard  @Fish2  OK, add "method": "frame" in the json makes it all work, you can then use the 3 frame options in the UI... but these only work once you have entered Method Frame first... 

<img width="567" alt="image" src="https://user-images.githubusercontent.com/47482260/130283111-9e3def57-bfa4-404e-bb64-3b5312bb33ba.png">

**Comment by thomasgaillard** [comment]
@adavison007 @Fish2 👍 thanks to you guys, that's perfect with the frame method activated.
+++
![Capture-d’écran-2021-08-21-à-13 58 14](https://user-images.githubusercontent.com/681454/130321095-8385be1a-5152-4c31-8e62-edb20c6c9552.jpg)

**Comment by tavicu** [comment]
Ok. So i found the problem!

When i developed the frame implementation i forgot to change a function that checks if TV is online to fetch the settings automatically and had always seen TV as offline and not save them. https://github.com/tavicu/homebridge-samsung-tizen/issues/383#issuecomment-933577298

That problem was fixed but i still added an option in config.schema to select the type of TV.
But I advise to leave it set to `None` and let the plugin do it's thing :)

The changes are not live yet. I still have something to do and i will push a new version this week.
I will come back with a message when it's live.

**Comment by tavicu** [comment]
[v5.1.0](https://github.com/tavicu/homebridge-samsung-tizen/releases/tag/v5.1.0) released
