### ISSUE TITLE
Switching from inputs to apps and back

### ISSUE THREAD

**Issue by superbraz** [tavicu/homebridge-samsung-tizen#397]
hey there,
thanks for this great plugin - i love it!
i didn´t have to buy any LG or Sony TV for homekit support, so i can stay on samsung :)

my little problem is, if i switch back the input from app to input (netflix to live tv), it doesn´t work.

i can switch between live tv, apple tv (physical), playstation, denon avr... everything is fine.
i can also switch to apps (netflix, tv now, youtube, zdf, ard...) 
but than i want to switch back from app to hdmi input (live tv, playstation,...) and the tv opens the tv settings...

hope you understand, what i mean ^^

here is my config:
`{
            "devices": [
                {
                    "name": "Samsung GQ75",
                    "ip": "192.XXX.XXX.XXX",
                    "mac": "XX:XX:XX:XX:XX:XX",
                    "options": [
                        "Frame.RealPowerMode"
                    ],
                    "inputs": [
                        {
                            "type": "command",
                            "name": "Live TV",
                            "value": "KEY_SOURCE,KEY_LEFT*3,KEY_ENTER"
                        },
                        {
                            "type": "command",
                            "name": "Apple TV",
                            "value": "KEY_SOURCE,KEY_LEFT*3,KEY_RIGHT*1,KEY_ENTER"
                        },
                        {
                            "type": "command",
                            "name": "Denon",
                            "value": "KEY_SOURCE,KEY_LEFT*3,KEY_RIGHT*2,KEY_ENTER"
                        },
                        {
                            "type": "command",
                            "name": "Playstation",
                            "value": "KEY_SOURCE,KEY_LEFT*3,KEY_RIGHT*3,KEY_ENTER"
                        },
                        {
                            "type": "app",
                            "name": "Netflix",
                            "value": "3201907018807"
                        },
                        {
                            "type": "app",
                            "name": "TV Now",
                            "value": "3201908018988"
                        },
                        {
                            "type": "app",
                            "name": "Youtube",
                            "value": "111299001912"
                        },
                        {
                            "type": "app",
                            "name": "ARD Mediathek",
                            "value": "3201412000679"
                        },
                        {
                            "type": "app",
                            "name": "ZDF Mediathek",
                            "value": "3201705012365"
                        }
                    ]
                }
            ],
            "platform": "SamsungTizen"
        }`

thanks for your help!

**Comment by tavicu** [comment]
Hi, the plugin don't support to change to a specific source, that's why we send a list of commands.
I think you copied from some other issues and they may not work since your tv can have other order of inputs.
You need to play with the commands one by one and see what fits your TV.

Example of my input for Live TV:

Also you can follow this issue: https://github.com/tavicu/homebridge-samsung-tizen/issues/321 where we discussed and i will give updates when will be implemented to select a hdmi specific.

```
{
    "name": "Live TV",
    "type": "command",
    "value": "KEY_SOURCE,KEY_DOWN,KEY_UP,KEY_LEFT*3,KEY_ENTER"
}
```

**Comment by superbraz** [comment]
thank you, but i dont think thats the problem...

i can switch betweern hdmi 1, hdmi 2, hdmi 3...without any problems
i select playstation - it works, 
i switch back to live tv - it works
i switch to an app (like netflix) - it works
i switch back to live tv / or playstation >>> problem

i can try with "key down, key up..."

**Comment by superbraz** [comment]
did not work

**Comment by AnnBlu** [comment]
does the GQ75 have smart hub ? 
Hope this helps 

- Samsung Q95T - using the       Smarthub      layout,
name: HOME is a blank input (default being 1st input & provides a no effect "scroll to input"  if needed)
Note the : KEY_RIGHT. star. number  1,2,3,etc

"inputs": [
                        {
                            "value": "KEY_HOME,KEY_HOME",
                            "type": "command",
                            "name": "Home"
                        },
                        {
                            "value": "KEY_HOME,KEY_RIGHT*1,KEY_ENTER",
                            "type": "command",
                            "name": "Watch TV"
                        },
                        {
                            "value": "KEY_HOME,KEY_RIGHT*2,KEY_ENTER",
                            "type": "command",
                            "name": "Watch Apple"
                        },
                        {
                            "value": "KEY_HOME,KEY_RIGHT*3,KEY_ENTER",
                            "type": "command",
                            "name": "Watch Google"
                        },
                        {
                            "value": "KEY_HOME,KEY_RIGHT*4,KEY_ENTER",
                            "type": "command",
                            "name": "Watch DVD"
                        },
                        {
                            "value": "KEY_HOME,KEY_RIGHT*5,KEY_ENTER",
                            "type": "command",
                            "name": "Watch Mac"
                        },
                        {
                            "value": "3201910019354",
                            "type": "app",
                            "name": "Watch Kayo"
                        },
                        {
                            "value": "3201512006963",
                            "type": "app",
                            "name": "Watch Plex"
                        },
                        {
                            "value": "3201807016597",
                            "type": "app",
                            "name": "Apple TV"
                        },
                        {
                            "value": "3201908019041",
                            "type": "app",
                            "name": "Apple Music"
                        }
                    ]

**Comment by tavicu** [comment]
As I said previously, you need to try your own combination of keys or to follow https://github.com/tavicu/homebridge-samsung-tizen/issues/321 for updates. Until then, there is not much we can help you with.
