### ISSUE TITLE
Approve Device with Samsung TV

### ISSUE THREAD

**Issue by jungopro** [tavicu/homebridge-samsung-tizen#4]
Hi
I was wondering if there's away to initially approve the "remote" on the samsung TV.
My issue is this:

Whenever I connect a new remove (such as the samsung app) to control the TV, I get a pop-up on the TV to approve the device
When I first try to control Samsung TV via homebridge-samsung-tizen plugin, I get "Can't reach TV". I can only assume it's because I didn't approve the device... I didn't get any popup on the TV, nor did I saw a setting to remove the approval on the TV side... I assume the error is due to the TV not allowing the connection...

Any idea how to make the initial pairing successful?

Thanks

**Comment by tavicu** [comment]
Hi! Try to turn the tv on from your remote. After 30 second in Home app you should see the tv as on. Try to turn it off!

It should ask for to approve the device.

If not, check in Settings - General - External Device Manager - Device List. Maybe you clicked Disallow.

**Comment by jungopro** [comment]
Thank you
This is what I get in the log:

```bash
May 07 23:00:44 raspberrypi homebridge[12074]: [2018-5-7 23:00:44] [Living Room TV] Power: Can't reach TV
May 07 23:00:54 raspberrypi homebridge[12074]: [2018-5-7 23:00:54] [Living Room TV] Power: Can't reach TV
```

This is my config:
```yaml
{
      "platform": "SamsungTizen",
      "devices": [
        {
          "name": "Living Room TV",
          "ip": "192.168.14.189",
          "mac": "f4:7b:5e:60:83:8e"
        }
      ]
    }
...
```

I couldn't find _Settings - General - External Device Manager - Device List_. Maybe my TV is not supported? (UA46F6400)

Thank you

**Comment by tavicu** [comment]
Hey!

Yup, your TV is not supported by this plugin. It must be a newer model with the Tizen Operating System. Yours is an older version.

You can try this one: https://github.com/mmende/homebridge-samsungtv-control
From what i read in the description it should work with your TV.

**Comment by jungopro** [comment]
Hi

Thank you, the other plugin did work for my TV. Although only to turn it off, but this is good enough to start with :-)
