### ISSUE TITLE
Siri and apps

### ISSUE THREAD

**Issue by hanses89** [tavicu/homebridge-samsung-tizen#400]
Hi.

I just got this plugin up an running, and i got some "issues" regarding Siri.

I can tell Siri to to turn on the tv, without any problems. But if i say start youtube on tv, Siri tells me she cant do that.

This is my config:
          "inputs": [
                {
                    "name": "Netflix",
                    "type": "app",
                    "value": "11101200001"
                },
                {
                    "name": "YouTube",
                    "type": "app",
                    "value": "111299001912"
                },
                {
                    "name": "Spotify",
                    "type": "app",
                    "value": "3201606009684"
                }
            ]
        }
    ]
}

And all the apps show up in homekit in a list underneath the powerswitch icon.

Any thoughts?

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/wiki/Common-Issues#--inputs-are-appearing-like-separate-accessories

**Comment by hanses89** [comment]
I dont think you understand what i mean. It is linked in one accessory, but saying start netflix on TV to siri, will not work.. Changing it in the home app will though

**Comment by tavicu** [comment]
Well ... maybe that command don't exist.

You could try "Switch Bedroom TV input to Netflix"

**Comment by hanses89** [comment]
I cant wind any command that will make sire do that:( Maybe that is not possible with this setup:
![image](https://user-images.githubusercontent.com/62284780/130766658-26a3c0bb-35ab-464f-85fe-3da5d3ed5a90.png)


Maybe it then needs to be separate accessories?

**Comment by mrMiimo** [comment]
I think you can't directly tell Siri to change the input. 
But you can create a scene that changes the input, and tell Siri to run the scene.

**Comment by tavicu** [comment]
Indeed looks like you can't change the input with Siri ...

But yeah, the @mrMiimo suggestion should work just fine :)
