### ISSUE TITLE
ERROR Failed to pair! Make sure TV is online and you click Allow

### ISSUE THREAD

**Issue by ChrisTav424** [tavicu/homebridge-samsung-tizen#406]
I'm trying to set up this plugin on the Samsung UE40H6400AK. I can ping the IP and also access the API successfully. 

This is the error im getting: 
![26F9182C-1E94-4F43-8EAE-B71B25BED665](https://user-images.githubusercontent.com/44398463/132572972-d5158668-790b-46ea-93be-0d01a89db178.png)

and I'm not getting a prompt on the TV screen. I can connect my iPhone to the TV, it successfully asks for a PIN and allows control. 

Reading the documentation, PINs aren't supported, are there any plans to support them? 

Any help would be great!

**Comment by SeanHama** [comment]
following, i have same issue.

**Comment by tavicu** [comment]
Hi @ChrisTav424 , unforunately your TV is not compatible with this plugin. You have an older Tizen version which works with PIN method to pair.
You could search closed issues, others recommended some plugins:https://github.com/tavicu/homebridge-samsung-tizen/issues?q=is%3Aissue+pin

For your TV to be compatible the interface should look like this:
![Samsung-Tizen-TV-OS](https://user-images.githubusercontent.com/172068/133047118-9db5329a-0ad6-4385-93cd-d5880158107f.jpg)

NOT like this:
![Samsung-Electronics-Redefines-TV-Experience-with-New-Smart-TV-Powered-by-Tizen1](https://user-images.githubusercontent.com/172068/133047181-21a4ecc9-44d8-4d15-a2ba-aca3467aa0cd.jpg)

**Comment by glueslug** [comment]
Hi Tavicu, I can confirm that I have this same issue and my Samsung TV is from 2021 and matches the images of the interface you show above.

**Comment by MrNoooooooob** [comment]
The problem also exists with my Samsung TV 2021 Q60AA 85Zoll  but could pair but does not respond in HomeKit.

**Comment by tavicu** [comment]
> Hi Tavicu, I can confirm that I have this same issue and my Samsung TV is from 2021 and matches the images of the interface you show above.

You don't have the same issue since his TV is not supported and yours is. You should open a new issue.



> The problem also exists with my Samsung TV 2021 Q60AA 85Zoll but could pair but does not respond in HomeKit.

Also your problem is not related to this issue. Since you were able to pair the TV then the plugin part is done. The problem is between your phone and homebridge server.
You could open a new issue where you can tell me what you did, what you tried, and what is not working. Also start homebridge in debug mode so we can see if we have any errors or indications of a problem.
