### ISSUE TITLE
Tv Status not Stable and turns off when using remote

### ISSUE THREAD

**Issue by PierreBebawy** [tavicu/homebridge-samsung-tizen#408]
the Tv status keeps switching on and off when on and if when using the remote from control Centre most of the time is switching off the tv 
my tv support   PowerState

**Comment by tavicu** [comment]
I'm sorry but i will need more than that :)

You could try first by starting the homebridge in debug mode and see the logs. Especially what is write when you try to change the state.

But it may be a problem from your network. Sometimes to respond hard to ping/requests.
