### ISSUE TITLE
Volume down/up from control centre shuts down TV

### ISSUE THREAD

**Issue by JB4Lyfe** [tavicu/homebridge-samsung-tizen#410]
Hello! Ive got a Samsung q80t 2020 model and recently just installed this plugin on Homebridge running from a raspberry pi. All other features and functions are working as expected, occasionally I can't turn on the tv after it being off for long periods of times. 

Another issue that ive been getting quite frequently is that the TV shuts down when I use the volume keys from the iOS remote app. It happens quite frequently. Anyone had the same issues and any potential fixes? Attached is an image of my config. 

Thank you so much in advance.
<img width="576" alt="Screen Shot 2021-10-02 at 10 51 34 pm" src="https://user-images.githubusercontent.com/40929699/135717004-60a4cc44-2f01-46c3-88f1-bbd6ce1e9cc5.png">

**Comment by tavicu** [comment]
Hi,

Your problem is interesting. First time i hear about it. The volume controls only send a command (VOL_UP or VOL_DOWN) to TV.
So i really don't know from where the problem could be or how to try and catch it.

We could try by opening the homebridge in debug mode `homebridge -D` and see the logs that are triggered when you press volume up/down

**Comment by JB4Lyfe** [comment]
> Ok. After one hour i finally found a possible scenario.
> 
> The plugin doesn't request to change the power when you interact with any key from control center. HomeKit does if it sees that the TV is off.
> 
> So somehow HomeKit sees your TV as off when you try to control the volume and sends the volume command then it tries to turn it on. Since it's the same key as powering off and your tv is already on it just powers it off.
> 
> The problem is that somehow homekit sees it off. So is a problem of slow responding network or something to requests.
> 
> If you want to dig deeper you could what i suggested here to other member: [#417 (comment)](https://github.com/tavicu/homebridge-samsung-tizen/issues/417#issuecomment-935961245) That way we could see what is returning false as power status.
> 
> But i bet it's the same problem as him :)

Cant seem to locate the /lib/methods/base.js file.

**Comment by JB4Lyfe** [comment]
> > I’m running it off a raspberry pi 4
> 
> You, that i got it from the first message :D i was interested to see how you are running it so i can guide you where to find the files.
> 
> You could run `npm list -g --depth=0`. It will get you a list with the packages installed and the first line will be the path to the folder.
> 
> Usually it should be in `/usr/local/lib/node_modules/homebridge-samsung-tizen`

Managed to find the file via ssh Cyberduck and homebridge.local terminal. But my access was denied when I tried to edit the file.

**Comment by maiiikell1995** [comment]
I'm having the same issue. Could this be because i'm using a WiFi connection only on the Homebridge Host? Should it be more reliable on an wired connection?
Running homebridge from an intel compute stick within windows 10, this device doesn't have an ethernet port.
