### ISSUE TITLE
List of applications to add to wiki

### ISSUE THREAD

**Issue by jjgrayston** [tavicu/homebridge-samsung-tizen#411]
See below - thanks

[ 1 - Netflix]
- App Name                            :     Netflix
- App Version                         :     5.3.26
- App ID - WAS                        :     3201907018807
- App ID - Tizen                      :     org.tizen.netflixapp
-----------------------------------------------------------------------------------------------------
[ 2 - Prime Video]
- App Name                            :     Prime Video
- App Version                         :     2.5.24
- App ID - WAS                        :     3201910019365
- App ID - Tizen                      :     org.tizen.primevideo
-----------------------------------------------------------------------------------------------------
[ 3 - Disney+]
- App Name                            :     Disney+
- App Version                         :     1.7.1
- App ID - WAS                        :     3201901017640
- App ID - Tizen                      :     MCmYXNxgcu.DisneyPlus
-----------------------------------------------------------------------------------------------------
[ 4 - Apple TV]
- App Name                            :     Apple TV
- App Version                         :     8.0.1
- App ID - WAS                        :     3201807016597
- App ID - Tizen                      :     com.samsung.tv.ariavideo
-----------------------------------------------------------------------------------------------------
[ 5 - YouTube]
- App Name                            :     YouTube
- App Version                         :     2.1.502
- App ID - WAS                        :     111299001912
- App ID - Tizen                      :     9Ur5IzDKqV.TizenYouTube
-----------------------------------------------------------------------------------------------------
[ 6 - Internet]
- App Name                            :     Internet
- App Version                         :     4.1.03230
- App ID - WAS                        :     3202010022079
- App ID - Tizen                      :     org.tizen.browser
-----------------------------------------------------------------------------------------------------
[ 7 - Stan]
- App Name                            :     Stan
- App Version                         :     3.7.21
- App ID - WAS                        :     3201606009798
- App ID - Tizen                      :     73iTZRTc34.Stan
-----------------------------------------------------------------------------------------------------
[ 8 - BINGE]
- App Name                            :     BINGE
- App Version                         :     1.0.0
- App ID - WAS                        :     3202010022098
- App ID - Tizen                      :     as6cYRgkPy.Binge
-----------------------------------------------------------------------------------------------------
[ 9 - Kayo Sports]
- App Name                            :     Kayo Sports
- App Version                         :     1.3.0
- App ID - WAS                        :     3201910019354
- App ID - Tizen                      :     eYuOiOLYQX.KayoSports
-----------------------------------------------------------------------------------------------------
[ 10 - Spotify  Music and Podcasts]
- App Name                            :     Spotify  Music and Podcasts
- App Version                         :     2.1.5
- App ID - WAS                        :     3201606009684
- App ID - Tizen                      :     rJeHak5zRg.Spotify
-----------------------------------------------------------------------------------------------------
[ 11 - Explore Google Assistant]
- App Name                            :     Explore Google Assistant
- App Version                         :     0.21.11110
- App ID - WAS                        :     3202004020674
- App ID - Tizen                      :     AkhP5nCr24.GoogleAssistant
-----------------------------------------------------------------------------------------------------
[ 12 - Amazon Alexa]
- App Name                            :     Amazon Alexa
- App Version                         :     0.21.10220
- App ID - WAS                        :     3202004020626
- App ID - Tizen                      :     AQKO41xyKP.AmazonAlexa
-----------------------------------------------------------------------------------------------------
[ 13 - Google Duo]
- App Name                            :     Google Duo
- App Version                         :     1.0.23
- App ID - WAS                        :     3202008021439
- App ID - Tizen                      :     IewQEY143t.GoogleDuoWeb
-----------------------------------------------------------------------------------------------------
[ 14 - Kidoodle.TV  FREE, KidSafe Videos]
- App Name                            :     Kidoodle.TV  FREE, KidSafe Videos
- App Version                         :     2.3.0
- App ID - WAS                        :     3201910019457
- App ID - Tizen                      :     LTqDGxS6NK.KidoodleTV
-----------------------------------------------------------------------------------------------------
[ 15 - Gallery]
- App Name                            :     Gallery
- App Version                         :     3.0.8
- App ID - WAS                        :     3201710015037
- App ID - Tizen                      :     com.samsung.tv.gallery
-----------------------------------------------------------------------------------------------------
[ 16 - eManual]
- App Name                            :     eManual
- App Version                         :     7.0.0
- App ID - WAS                        :     20212100003
- App ID - Tizen                      :     jPPp4KCHp4.emanual
-----------------------------------------------------------------------------------------------------
[ 17 - Foxtel]
- App Name                            :     Foxtel
- App Version                         :     3.1.0
- App ID - WAS                        :     3201910019449
- App ID - Tizen                      :     AtbFvatetY.FoxtelTizenApp
-----------------------------------------------------------------------------------------------------
[ 18 - Apple Music]
- App Name                            :     Apple Music
- App Version                         :     4.0.0
- App ID - WAS                        :     3201908019041
- App ID - Tizen                      :     org.tizen.apple.applemusic
-----------------------------------------------------------------------------------------------------
[ 19 - Security Center]
- App Name                            :     Security Center
- App Version                         :     1.1.14
- App ID - WAS                        :     3202009021877
- App ID - Tizen                      :     J9fZJDMi1v.SecurityCenter
-----------------------------------------------------------------------------------------------------
[ 20 - 9Now]
- App Name                            :     9Now
- App Version                         :     1.8.0
- App ID - WAS                        :     3201607010031
- App ID - Tizen                      :     Ne2ZsPWdKl.9NOW
-----------------------------------------------------------------------------------------------------
[ 21 - ABC iview]
- App Name                            :     ABC iview
- App Version                         :     3.2.0
- App ID - WAS                        :     3201812017479
- App ID - Tizen                      :     mWK87Xghap.ABCiview
-----------------------------------------------------------------------------------------------------
[ 22 - SBS On Demand]
- App Name                            :     SBS On Demand
- App Version                         :     3.8.7
- App ID - WAS                        :     3201510005981
- App ID - Tizen                      :     OyE7OuxlUi.SBSOnDemand
-----------------------------------------------------------------------------------------------------
[ 23 - 10 play]
- App Name                            :     10 play
- App Version                         :     06.00.02
- App ID - WAS                        :     3201704012147
- App ID - Tizen                      :     KaLitts8bq.tenplaySamsungTizen
-----------------------------------------------------------------------------------------------------
[ 24 - 7plus]
- App Name                            :     7plus
- App Version                         :     3.5.0
- App ID - WAS                        :     3201803015934
- App ID - Tizen                      :     icp4AvUPiA.7plus
-----------------------------------------------------------------------------------------------------

**Comment by tavicu** [comment]
Thank you,

I have updated the list with the missing apps!
