### ISSUE TITLE
Didn't get the channel buttons on Control Center

### ISSUE THREAD

**Issue by ZaydelSenpai** [tavicu/homebridge-samsung-tizen#416]
Hello, i leave my code righ there and also a screenshot, the buttons are not showing :(
Thanks in Advance

> {
>     "platform": "SamsungTizen",
>     "app_list": true,
>     "devices": [
>         {
>             "name": "Samsung 50",
>             "ip": "MY_TV_IP",
>             "mac": "THIS_IS_ALSO_WORKING
",
>             "keys": {
>                 "FLECHA_ARRIBA": "KEY_UP",
>                 "FLECHA_DERECHA": "KEY_RIGHT",
>                 "FLECHA_ABAJO": "KEY_DOWN",
>                 "FLECHA_IZQUIERDA": "KEY_LEFT",
>                 "SELECCIONAR": "KEY_ENTER",
>                 "ATRAS": "KEY_RETURN",
>                 "SUBIR_VOL": "KEY_VOLUP",
>                 "BAJAR_VOL": "KEY_VOLDOWN",
>                 "MUTE": "KEY_MUTE",
>                 "CANAL_ARRIBA": "KEY_CHUP",
>                 "CANAL_ABAJO": "KEY_CHDOWN",
>                 "PLAY": "KEY_PLAY",
>                 "PAUSA": "KEY_PAUSE",
>                 "KEY_HDMI": "KEY_HDMI"
>             },
>             "inputs": [
>                 {
>                     "name": "Youtube",
>                     "type": "app",
>                     "value": "111299001912"
>                 },
>                 {
>                     "name": "Netflix",
>                     "type": "app",
>                     "value": "11101200001"
>                 },
>                 {
>                     "name": "Apple Music",
>                     "type": "app",
>                     "value": "3201908019041"
>                 },
>                 {
>                     "name": "Disney Plus",
>                     "type": "app",
>                     "value": "3201901017640"
>                 },
>                 {
>                     "name": "Steam Link",
>                     "type": "app",
>                     "value": "3201702011851"
>                 },
>                 {
>                     "name": "Apple TV",
>                     "type": "app",
>                     "value": "3201807016597"
>                 },
>                 {
>                     "name": "Funimation",
>                     "type": "app",
>                     "value": "3201706014180"
>                 }
>             ]
>         }
>     ]
> }

![IMG_3465](https://user-images.githubusercontent.com/58988280/135926791-4a5213c8-c465-453a-8841-b5ceb731ed77.PNG)

**Comment by tavicu** [comment]
Hi.

you can’t add new keys! You can only change what the current buttons do when you click them.

**Comment by ZaydelSenpai** [comment]
> Hi.
> 
> you can’t add new keys! You can only change what the current buttons do when you click them.

wow! too bad! Anyway, why do i get only get 8 buttons?

**Comment by tavicu** [comment]
Unfortunately for us that’s what Apple decided and we can’t control at all what buttons are shown! We can only change what they do when are pressed.

**Comment by ZaydelSenpai** [comment]
Thank you so much! Nice work who

**Comment by sfDuhNinja** [comment]
Hi,

In the latest iOS17 beta I found in Settings > Accessibility an option to turn on Channels and Guide buttons. Is it possible to integrate them in the plugin? Also, as a side note, a power button and a mute button appeared in the remote.

Thanks
![IMG_1357](https://github.com/tavicu/homebridge-samsung-tizen/assets/27433856/24c5b999-4342-4d9e-9c71-30de7eb4976c)
![IMG_1358](https://github.com/tavicu/homebridge-samsung-tizen/assets/27433856/ef06c67f-124d-4cc2-8fcb-401cf1c59a95)

**Comment by tavicu** [comment]
Hi @sfDuhNinja,

If the buttons are there, then we can bind them :)
But unfortunately right now I don't have another device where I can install the beta software and I don't want to do it on my main device since it's an early beta. I will wait for a few more releases and then I will update one of my devices to it.

If you want you can open a new Issue and I will keep you updated on it :)
