### ISSUE TITLE
Can't turn on TV when upgrading to 5.1.0

### ISSUE THREAD

**Issue by nogoonoo** [tavicu/homebridge-samsung-tizen#419]
I'm unable to turn the TV on when upgrading to 5.1.0 (Samsung UN55MU6290).  Downgrading to v5.0.1 fixed it

**Comment by mandys** [comment]
Hey there,

I too am not able to start my Samsung TV (UA50AUE60AKLXL) using the command,

Hey Siri, Turn on Samsung TV

I get the following in console.

[10/30/2021, 4:33:24 PM] [Bedroom Samsung Tv] TV is offline! Can't get installed apps!
[10/30/2021, 4:33:24 PM] [Bedroom Samsung Tv] [DEBUG] TvOfflineError: TV is offline! Can't get installed apps!
    at WebSocketSecure.getApplications (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/methods/ws.js:55:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[10/30/2021, 4:33:48 PM] [Bedroom Samsung Tv] Failed to power on the TV
[10/30/2021, 4:33:48 PM] [Bedroom Samsung Tv] [DEBUG] WoLFailedError: Failed to power on the TV
    at /usr/local/lib/node_modules/homebridge-samsung-tizen/lib/methods/base.js:86:33
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

However, once TV is on, I am able to turn it off by saying.

Hey Siri, Turn off Samsung TV.

[10/30/2021, 4:35:33 PM] [Bedroom Samsung Tv] [DEBUG] {
  method: 'ms.remote.control',
  params: {
    Cmd: 'Click',
    DataOfCmd: 'KEY_POWER',
    Option: false,
    TypeOfRemote: 'SendRemoteKey'
  }
}
[10/30/2021, 4:35:35 PM] [Bedroom Samsung Tv] [DEBUG] {
  data: { clients: [ [Object] ], id: '5e6098ad-911d-44dc-9873-294cb94b86d0' },
  event: 'ms.channel.connect'
}

**Comment by mandys** [comment]
I have also checked settings
On TV go to Settings - General - External Device Manager - Device Connection Manager - Device List
It's set to Allow.

This link only works if the TV is ON.

http://192.168.4.167:8001/api/v2/

If I switch off the TV ( cable is still plugged in and the switch is ON )

Then the above link isn't reachable.
Also, I cannot ping to the IP from my computer.

{
device: {
FrameTVSupport: "false",
GamePadSupport: "true",
ImeSyncedSupport: "true",
Language: "en_GB",
OS: "Tizen",
PowerState: "on",
TokenAuthSupport: "true",
VoiceSupport: "false",
WallScreenRatio: "-1",
WallService: "false",
countryCode: "IN",
description: "Samsung DTV RCR",
developerIP: "0.0.0.0",
developerMode: "0",
duid: "uuid:cffe7218-b7e1-4499-9a32-f97bb93acd37",
firmwareVersion: "Unknown",
id: "uuid:cffe7218-b7e1-4499-9a32-f97bb93acd37",
ip: "192.168.4.167",
model: "21_KANTSU2E_UHD_BASIC",
modelName: "UA50AUE60AKLXL",
name: "Samsung AUE60A 50 TV",
networkType: "wireless",
resolution: "3840x2160",
smartHubAgreement: "true",
ssid: "68:ff:7b:5f:97:2e",
type: "Samsung SmartTV",
udn: "uuid:cffe7218-b7e1-4499-9a32-f97bb93acd37",
wifiMac: "64:07:F6:60:B5:86"
},
id: "uuid:cffe7218-b7e1-4499-9a32-f97bb93acd37",
isSupport: "{"DMP_DRM_PLAYREADY":"false","DMP_DRM_WIDEVINE":"false","DMP_available":"true","EDEN_available":"true","FrameTVSupport":"false","ImeSyncedSupport":"true","TokenAuthSupport":"true","remote_available":"true","remote_fourDirections":"true","remote_touchPad":"true","remote_voiceControl":"false"} ",
name: "Samsung AUE60A 50 TV",
remote: "1.0",
type: "Samsung SmartTV",
uri: "http://192.168.4.167:8001/api/v2/",
version: "2.0.25"
}

**Comment by tavicu** [comment]
Hi @mandys as we could see from the logs the plugin is failing to send Wake on Lan command to the TV.
It is possible that the MAC address from config to be wrong or homebridge server and TV to not be on same network or somehow the router is blocking wol packages.

Make sure you put the correct mac address in your config. If the TV is connected through wifi get the mac from wifi, if it's on wire get the mac from wire card.

Since you could turn off the TV that means homebridge server could connect to the TV to send the command, so more indications that MAC is wrong.

If you are sure the MAC address is correct there are still two possible scenarios:
1. By default the newer TVs have wake on lan disabled and you need to enable it.  I don't remember exactly where the option is in the settings but you could search on Google :)
2. One of my old TVs wakes on lan only connected by wire, on wifi it doesn't work ... don't know why!

**Comment by tavicu** [comment]
> Then the above link isn't reachable. Also, I cannot ping to the IP from my computer.

If you can't ping the TV from your computer when the TV is on then there is your problem. Cause the plugin can't interact with the TV. Something is blocking the requests of ping and wol ... it could be your PC or your router.

**Comment by mandys** [comment]
Hey @tavicu 

I downgraded to 5.01 and restarted and it's working now.
Strange..

But, thank you!

Power On/Off are working great.

Now, onto controlling opening of apps through Siri.

Seems like it can't control inputs.
Have to create a scene and try it out.

Thanks.

**Comment by tavicu** [comment]
> Hey @tavicu
> 
> I downgraded to 5.01 and restarted and it's working now. Strange..
> 
> But, thank you!
> 
> Power On/Off are working great.

Strange cause nothing was changed ...

> Now, onto controlling opening of apps through Siri.
> Seems like it can't control inputs. Have to create a scene and try it out.

Siri don't know how to change the inputs for TVs ...
Don't know how many years will take Apple to implement such hard thing ... uoff
