### ISSUE TITLE
Can't get installed applications! Your TV may not support this feature. - Everything works except this.

### ISSUE THREAD

**Issue by Tapsel99** [tavicu/homebridge-samsung-tizen#420]
When I restart my Homebridge I get this error message even though my TV is turned on during the start up and is compatible, everything works fine, but I can't get an list of the applications. Also I dont understand where I should see the list, even though I turned the app_list to true. Any ideas?

**Comment by MarkBarbieri** [comment]
> Sorry but no other ideea! Samsung could have removed the old endpoint with an update even for older TVs!
> 
> Since we already have a long list of applications already i will probably remove this feature in a future version of the plugin.
> 
> The second method works for sure but it’s a bit more complicated!

I will check and confirm for you on my 2017 TV later as I know it worked previously

**Comment by Tapsel99** [comment]
> Sorry but no other ideea! Samsung could have removed the old endpoint with an update even for older TVs!
> 
> Since we already have a long list of applications already i will probably remove this feature in a future version of the plugin.
> 
> The second method works for sure but it’s a bit more complicated!

Don't remove it! I setup a new Homebridge and this time it worked! I get a full list of my TV Apps, so it looks like Samsung hasn't cut of this this feature!

**Comment by tavicu** [comment]
> Don't remove it! I setup a new Homebridge and this time it worked! I get a full list of my TV Apps, so it looks like Samsung hasn't cut of this this feature!

Cool. I'm glad that we managed to create a very huge list of applications IDs making it possible to remove this feature in a future version. For now it will stay :)
