### ISSUE TITLE
Frame TV automation for art mode

### ISSUE THREAD

**Issue by fillmoreracer** [tavicu/homebridge-samsung-tizen#428]
Thank you so much for creating this plugin! I have searched through all of the issues for your plugin and haven’t found a similar instance to what I am encountering. 

I have two Samsung tizen tv’s, one is a frame tv, both are connected through your plugin. The frame tv has only one device connected via hdmi, an Apple TV 4K. I use the Apple TV remote to power on/off the frame tv. This works fine out of the box. I’m trying to configure your plugin so that when the Apple TV powers off the frame tv (using the Apple TV remote), the frame tv will go to art mode instead of a power off state. 

In the homekit home app, if I create an automation that says, “if the frame tv turns off, turn on frame tv art mode” it seems to work, however, randomly while using the Apple TV to watch anything, the plugin senses a “power off” trigger somehow and sends the frame tv into art mode. I’ve tried configuring the different frame tv specific toggles for displaying/controlling “real power” vs “art mode power”. All seem to behave similarly. 

I would like the Frame TV’s CEC hdmi power off signal from the Apple TV, to put the frame tv into “art mode” instead of “power off”, without using the physical Samsung remote control. I think I’m describing this accurately, but please correct me if I am wrong. I really wish Samsung would have just included this in the programming of the tv (art mode instead of off), just like the art mode button on the physical Samsung remote control.

**Comment by tavicu** [comment]
Sorry but no other ideas :(

You could write to Samsung (i think they need to add an option to select what you want to do when power off triggers). But i won't put much faith on it ...
