### ISSUE TITLE
App ID for Emby application

### ISSUE THREAD

**Issue by ckeech** [tavicu/homebridge-samsung-tizen#433]
Hi there, thanks for the great plugin! 

At the moment in most countries you have to install Emby manually from USB stick. I previously used app id "emby" which is the App ID - WAS entry, however it's stopped working. This however does work!

vYmY3ACVaa.emby

Hopefully it doesn't keep changing each manual install, I'll keep you posted if it does. Thanks.

**Comment by tavicu** [comment]
Hi! thank you! I have added to the apps list :)

**Comment by MarkBarbieri** [comment]
> Hi there, thanks for the great plugin!
> 
> At the moment in most countries you have to install Emby manually from USB stick. I previously used app id "emby" which is the App ID - WAS entry, however it's stopped working. This however does work!
> 
> vYmY3ACVaa.emby
> 
> Hopefully it doesn't keep changing each manual install, I'll keep you posted if it does. Thanks.

It will stay the same for each install.
