### ISSUE TITLE
App ID's

### ISSUE THREAD

**Issue by maiiikell1995** [tavicu/homebridge-samsung-tizen#434]
Hi I got a list of app id's from a couple of Dutch apps. 
These come from a 2020+ TV

Pathe Thuis: 3201506003175
Canaal Digitaal: 3201803015869
NL Ziet: 3202012022421
NPO: 3201706014250
Kijk: 3201901017768
Videoland:3201810017074

Couldn't get a pul request out for some reason thought I'd let you know this way to update the list.

**Comment by tavicu** [comment]
Hi @maiiikell1995 ! Thank you very much! I have added the apps to the list :)
