### ISSUE TITLE
[Feature Request]: Apple Layout

### ISSUE THREAD

**Issue by steplein** [tavicu/homebridge-samsung-tizen#437]
First of all thanks for this great plug-in which works fine for me, especially after mapping the Info key to KEY_HOME.

I would love to see a similar layout like the Apple TV remote (especially Channel Up, Channel Down, Mute and Power On/Off) would be interesting.

Is there a way to configure this or do we need to stick with what Apple offers. 

Thanks!

**Comment by aledebla03** [comment]
I'm also interested, I'd like to add the CH+ and CH- keys that have been added on iOS 15

**Comment by tavicu** [comment]
I would like this feature too but unfortunately we cannot customize it. Apple decide what to show and right now they are showing this interface with limited options (it’s the same for TVs that come with HomeKit integration).

Maybe in a few years Apple will allow us to customize it.

**Comment by steplein** [comment]
Thanks! Expected an answer like this. Still it is a cool plug-in and maybe Apple will give us some options in future.
