### ISSUE TITLE
Tv doesn't show up in Home App 

### ISSUE THREAD

**Issue by finnwell** [tavicu/homebridge-samsung-tizen#438]
Hello,

I can connect the TV with Homebridge and control it from there but when I´m starting the TV Bridge and connect it with the Home app the Tv doesn't show up just the bridge without any devices. I couldn't find a solution at the common issues page or anywhere else. Has anyone experience with this issue?

Thanks in advance!

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/wiki/Installation#6-adding-the-tv-to-home-app

**Comment by finnwell** [comment]
Yes, I've done this and I see the bride in my home app but without the TV as a device witch I can toggle.

**Comment by tavicu** [comment]
What bridge you can see? Did you read the last step?

Every  TV is a separate bridge that need to be added to the home app.

**Comment by finnwell** [comment]
I´ve done every step and I see the Samsung TV in my Home app (Screenshot added) but without controls for the tv. I can control the tv via the Homebridge interface. I have a 2020 so the conation woks but not in the home app on my iPhone.

![IMG_0CD6C08E38DE-1](https://user-images.githubusercontent.com/50054381/145000372-ab1510ac-86f6-4ef1-a622-3e8028e3286c.jpeg)

**Comment by tavicu** [comment]
You are not adding the correct bridge.

You have the Homebridge server that creates the main bridge. As i can see here you called it "Samsung TV".
Then for every TV there is a new bridge created with the name you set for TV in config.
You need to add the TV bridge to be able to control the TV

**Comment by tavicu** [comment]
When you click Add Accessory, then click "More options" and there you should see the TV accessory with a TV icon.

**Comment by finnwell** [comment]
I found the mistake. I had to add the uuid. now it works. Thanks for your quick help!

**Comment by tavicu** [comment]
Awesome! Glad it worked.

UUID was the next suggestion if you told me you don't see anything in the list after clicking more options :D
