### ISSUE TITLE
When remote control in Control Center use, TV power going off.

### ISSUE THREAD

**Issue by vanillaICS** [tavicu/homebridge-samsung-tizen#439]
I setted config like this.
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/43630612/145661397-ab45234a-7b82-407d-9c41-496f9941d3c9.png">
It worked. But for example when I tapped right arrow button, TV going off after cursor moved right. The other buttons happened same problem. So, I downgraded from "v5.2.0 beta" to "v5.1.0". but It didn't solved. I don't know what is reason. Any solution?

**Comment by maiiikell1995** [comment]
Look at this comment 

https://github.com/tavicu/homebridge-samsung-tizen/issues/417#issuecomment-935961245)https://github.com/tavicu/homebridge-samsung-tizen/issues/417#issuecomment-935961245


I experienced the same but couldn't fix it I bought a cheap Nedis IR Remote Blaster and flashed with other firmware to achieve homekit compatibility based om IR commands.
