### ISSUE TITLE
Is it possible to disable the remote?

### ISSUE THREAD

**Issue by codyc1515** [tavicu/homebridge-samsung-tizen#446]
Per title. Cannot see anything in wiki or config.

**Comment by tavicu** [comment]
Hi, nope. No option for this since you are the first to ask. I will take in consideration for a future version

**Comment by codyc1515** [comment]
The use case is that I simply use the TV only with an Apple TV, so no need for the remote (as I have disabled all of the inputs). I will take a look later if you would accept PR?

**Comment by tavicu** [comment]
Ah. Now that you said and i've took a look at the code I remember that the plugin only change the button mapping. Don't know if homekit allows to disable remote functionality.

I have looked over hap-nodejs and doesn't look like it's an option to disable it. It's added by default to Television type. https://github.com/homebridge/HAP-NodeJS/blob/900a4324f76f0c732d41795faa9f70e432388c3a/src/lib/definitions/ServiceDefinitions.ts#L1374

Don't know if calling removeCharacteristic will work. https://github.com/homebridge/HAP-NodeJS/blob/900a4324f76f0c732d41795faa9f70e432388c3a/src/lib/Service.ts#L412
