### ISSUE TITLE
The Frame Art Mode customization

### ISSUE THREAD

**Issue by lovethisshit** [tavicu/homebridge-samsung-tizen#447]
Hi!

First things first: awesome work! I do not have homebridge or any automation in place, but I have a Samsung The Frame TV and I'm currently searching for ways of "tweaking" it a little bit - that's why I came across this plugin.
I'm currently reading a bunch of stuff regarding the API and how you implemented this (also on the SmartThings stuff). What I'm trying to do is pretty basic:

If it is a certain time in the day/night (maybe also with light sensor), switch the frame color of the "art mode" to black/white. 

Do you think this is by any means possible - either by your plugin or generally with the API? I had a look at the documentation but could not find details on the art mode or light sensors.

Best regards!

**Comment by tavicu** [comment]
Hi. I didn't find something in the API regarding the light sensor or changing the color.
The API is very limited and everything we found it was by reverse engineering. Samsung didn't want to provide a documentation and tried to lock all the features only for their app.

So I don't think it's possible to do this from your smart home integration.

**Comment by lovethisshit** [comment]
Thanks for the answer! I guess I'll have to dig deeper into the API or find a way maybe with the SDKs - there is definitely a documentation for using sensors and maybe I can provide them as a service
