### ISSUE TITLE
the "devices": [{ line gives me error, i just can configure it without this line, but my tv doesnt ask for permission

### ISSUE THREAD

**Issue by AlexHFOkumura** [tavicu/homebridge-samsung-tizen#45]
always when it ry to add "devices": [{ line the config.json gives me error, and whitout that line, my tv doesnt ask me permission...please help

**Comment by dannyharuh** [comment]
I have the same problem is there someone who has the solution?

**Comment by tavicu** [comment]
Hi, #38
