### ISSUE TITLE
How do I contribute

### ISSUE THREAD

**Issue by AeroDig** [tavicu/homebridge-samsung-tizen#450]
I'd like to work on this plugin for homebridge.  How do I ramp up?  I cloned the code, I have some features I'd like to start developing.  1. I need to reliably turn the TV on when off, off when on 2. I need to switch the HDMI source HDMI1, 2, 3, 4 etc.  3. I need to switch between line out and tv sound.  

Let me know!  I have a CS degree, just need to know how to debug, details of the APIs, etc.

**Comment by tavicu** [comment]
Hi. Feel free to clone the project and do what changes you want.

1. Good luck doing that with what api Samsung provided us. 
2. https://github.com/tavicu/homebridge-samsung-tizen/issues/321
3. Don't know if SmartThings api provide this feature. You could search on samsung documentation and clone the branch from point 2 where the connection with SmartThings it's already implemented.

The plugin is written modular and everything it's easy to understand for someone who knows JavaScript.
