### ISSUE TITLE
Apple TV App ID will not work

### ISSUE THREAD

**Issue by Nasuada** [tavicu/homebridge-samsung-tizen#451]
I recognized that issue a bit longer ago. If I select from homekit my AppleTV Shortcut to select the app on the samsung tv, I get always the message „Network is not available“ with little more text and two buttons to choose „Reload“ or „Quit“ (hope I translate it correctly, because I‘m using the german language) on the Smasung TV. And this happen always and only with the Apple TV app. 

![AD6F819D-25A3-4C01-89BC-8AEEF460279B](https://user-images.githubusercontent.com/8783226/147984832-66b5e13c-c3e2-4f60-a955-2d3c91afaa0a.jpeg)

I rechecked the code today for Apple TV but it‘s still the same (3201807016597). 

If I start the App over the Menu with the original remote, all working fine. 

It‘s an Samsung UE65RU7179UXZG. Software is up to date (checked today)

Any Idea?

**Comment by tavicu** [comment]
Hi,

I'm sorry but i have no idea why does he have this behavior.

I remember there were problems with the AppleTV application in the past and more people complained.
Don't know what Samsung is doing different for the AppleTV app.
