### ISSUE TITLE
Siri can't adjust volume

### ISSUE THREAD

**Issue by RotemAkerman** [tavicu/homebridge-samsung-tizen#452]
TV Model: Q7FN (2018)
When asking Siri to either "mute" or "set volume" it replies:
`Sorry there was a problem adjusting volume`
Volume controls and mute commands works just fine in the home app / control center remote

Is this a configuration issue?

**Comment by tavicu** [comment]
Siri don't know how to mute tv and volume can't be adjusted since we have option to only go up/down, not set a specific volume.

Regarding the mute you could create a separate switch just for mute and then ask siri something like: "Turn on Mute TV" where the switch will have "Mute TV" as name

**Comment by RotemAkerman** [comment]
Thanks for your quick reply!
Is that a siri limitation or `homebridge-samsung-tizen` limitation?
I really wanted to add a mute button, the switch is ugly so I removed it 🤣
