### ISSUE TITLE
Changing picture mode/adding home key

### ISSUE THREAD

**Issue by samwhu30** [tavicu/homebridge-samsung-tizen#453]
Hi,

Really love the plug in great work. 

I have a picture mode set up which makes the brightness really dark along with some other settings and I have set that to my ‘Movie’ picture mode. So when I go to bed I put that on so it’s still really dark in the room. 

Is there any chance of making picture mode an option in the plug in?

If not, is it possible to add the ‘Home’ button in the keys? That way I would be able to add the button sequence to my HomeKit. Eg. Press home, press left x3, select… etc etc. 

Thanks
Sam

**Comment by tavicu** [comment]
Hi. There is no way to select the picture mode in the current API that the plugin is using.
You could only send keys that are found on a physical remote.
So adding a key it's not possible since we don't add these keys :)

A list with the keys could be found here: https://github.com/tavicu/homebridge-samsung-tizen/wiki/Commands

**Comment by tavicu** [comment]
Hi.

I have looked in the SmartThings API and found there is a way to set the picture mode with SmartThings.

These are the possible options: `"dynamic", "movie", "standard", "unknown"`

Right now I am working on v5.2.0 which will have SmartThings API integrated. Please follow the release and after it's live open a new issue where i will guide you and try to help you how to set a Switch that will change the picture mode

**Comment by samwhu30** [comment]
Thanks for replying. I have changed the settings of my movie picture mode so if that could be an option that would solve a massive problem for me! 

It wasn’t possible to change the picture mode via the keys as I couldn’t access the home button. 

I look forward to the new release. 

Thanks,
Sam

**Comment by samwhu30** [comment]
Hi @tavicu it looks like the update is now out for this. Any chance you’d be able to tell me how I can set my screen mode to movie via HomeBridge please?

Sam

**Comment by tavicu** [comment]
Hi @samwhu30,

It’s not released yet. Yesterday i made a quick fix that improved the compatibility with the HOOBS.

I will try today to make the changes in order to create the switch for the picture mode and if you would like you will be able to install the beta version.

**Comment by samwhu30** [comment]
> Hi @samwhu30,
> 
> It’s not released yet. Yesterday i made a quick fix that improved the compatibility with the HOOBS.
> 
> I will try today to make the changes in order to create the switch for the picture mode and if you would like you will be able to install the beta version.

That would be great 🙂

**Comment by tavicu** [comment]
Hei,
I have released a new version which allows you to select picture mode.
Unfortunately Home app don't allow us to create a select box or something (maybe in the future) and right now the only option is to create a separate switch for every mode you want to toggle.

Here you can find informations on how to install beta version of the plugin and how to setup your SmartThings API: https://github.com/tavicu/homebridge-samsung-tizen/issues/321#issuecomment-935886172

Then you can create switches like this:
```
{
    "platform": "SamsungTizen",
    "devices": [
        {
            "api_key": "xxx",
            "device_id": "xxx",
            "name": "Test TV",
            "ip": "192.168.x.x",
            "mac": "xxx",
            "switches": [
                {
                    "name": "Mode Dynamic",
                    "picture_mode": "Dynamic"
                },
                {
                    "name": "Mode Standard",
                    "picture_mode": "Standard"
                },
                {
                    "name": "Mode Natural",
                    "picture_mode": "Natural"
                },
                {
                    "name": "Mode Movie",
                    "picture_mode": "Movie"
                }
            ]
        }
    ]
}
```

**Comment by samwhu30** [comment]
Hi, 

Thanks a lot, I have installed it and it seems to be working great! 

I had some trouble for some reason setting it up at first but think I was missing something simple, I went back to square one and started again and it's all working.

Sam

**Comment by samwhu30** [comment]
Interestingly, not able to set an automation “When tele turns on, switch on standard mode switch”

I wonder if that’s a beta problem.

**Comment by samwhu30** [comment]
Hmm… so after some investigating. 

If I turn the tele on via the switch in the home app it will ignore the automation and not set the mode to standard. 

If I turn on the tele with the tv remote then it changes the picture mode perfectly.

**Comment by tavicu** [comment]
> If I turn the tele on via the switch in the home app it will ignore the automation and not set the mode to standard.
> 
> If I turn on the tele with the tv remote then it changes the picture mode perfectly.

Yup, because the TV won't accept any requests for a few seconds after it just turned ON. I will look into it today.

**Comment by tavicu** [comment]
Hi,

In the next beta i will implement some changes that will wait for the TV to turn ON.
I will close this issue and please follow this one for the next releases: https://github.com/tavicu/homebridge-samsung-tizen/issues/321
