### ISSUE TITLE
Always ask for permission

### ISSUE THREAD

**Issue by Stewart06** [tavicu/homebridge-samsung-tizen#455]
Bonjour,

Depuis que je suis passé sur la dernière version de HOOBS 4, j’ai bien réussi à configurer le plugin mais à chaque fois que je redémarre le bridge ça redemande sur chaque téléviseur que je possède de donner l’autorisation au plugin pour contrôler mon téléviseur.

J’avoue ne pas savoir si cela vient de HOOBS ou du plugin en lui même.

J’ai également remarqué que même après avoir donné l’autorisation au plugin de contrôler chaque téléviseur, quand je me rend dans les paramètres de mon téléviseur à la fonction périphérique externe, le plugin n’apparaît pas dans la liste.

Bizarre car avant cela fonctionnait sans problème même après un redémarrage complet de mon Raspberry Pi 4.

Avez-vous une idée d’où cela peut venir ?

Hello,

 Since I switched to the last version of HOOBS 4, I have succeeded in configuring the plugin but each time I restart the bridge it asks again on each television that I have to give the authorization to the plugin to control my television  .

 I admit not knowing if this is from HOOBS or the plugin itself.

 I also noticed that even after giving permission to the plugin to control each TV, when I go to my TV's settings to external device function, the plugin does not appear in the list.

 Weird because before it worked without problem even after a complete restart of my Raspberry Pi 4.

 Do you have any idea where this might come from?

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/issues?q=is%3Aissue+hoobs

**Comment by Homekitdude** [comment]
Has this been resolved? I still get the notification for permission everytime. Do I need to adjust anything after the latest update? I know you dont support HOOBS but would like to have it working there if possible.

**Comment by Homekitdude** [comment]
That did not work for me

**Comment by tavicu** [comment]
> That did not work for me

Guess we cannot satisfy everybody!
Since you didn't post any logs and you also moved on and uninstalled the plugin, good luck :)
