### ISSUE TITLE
Morning scene wont complete

### ISSUE THREAD

**Issue by Danlipanovich** [tavicu/homebridge-samsung-tizen#456]
HI,
in trying to set up a scene that turns the tv and opens Spotify but when the tv turns on only by default button and as a comment, it says the tv is offline.
I'm trying the following code: 

"switches": [
                        {
                            "name": "Morning Music",
                            "command": "KEY_LEFT*3,KEY_ENTER,PAUSE*6s,KEY_PLAY_BACK"
                        }
                    ],
the scene is turned on the tv and this command ^

iv tried to add pause but because the command is sent at the same time it won't work. 
is there a way to turn the tv on by command or to delay an action?
I'm using homebridge for home kit and neo qled 2020

**Comment by tavicu** [comment]
power:true will turn on the TV before executing any command. https://github.com/tavicu/homebridge-samsung-tizen/wiki/Switches#power

**Comment by Danlipanovich** [comment]
> power: true will turn on the TV before executing any command. https://github.com/tavicu/homebridge-samsung-tizen/wiki/Switches#power

Hi,
I'm getting this message: This plugin slows down Homebridge. The write handler for the characteristic 'On' on the accessory 'Samsung TV B6C4' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.

and it says in the app that's the scene failed

**Comment by Danlipanovich** [comment]
fixed it and it works thanks! @tavicu 
but it keeps saying the scene failed even it worked

**Comment by tavicu** [comment]
> fixed it and it works thanks! @tavicu
> but it keeps saying the scene failed even it worked

Hei. Homebridge expects a command to run fast. And your command takes a few seconds.
I will make some changes to not display that information message anymore and to respond to request sooner.

I will leave this Issue open until the changes will be made.

**Comment by Danlipanovich** [comment]
Hi, where do I add the code you sent?
