### ISSUE TITLE
error - plugin not working at all on 2 tvs

### ISSUE THREAD

**Issue by MattRoe84** [tavicu/homebridge-samsung-tizen#460]
Hi 

im getting errors whenever i try to use this plugin, i have 2 samsung frame tvs one 2019 and the other 2020. This is the latest error 

[homebridge-samsung-tizen] This plugin slows down Homebridge. The write handler for the characteristic 'Mute' on the accessory 'Bedroom TV 9DCE' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.

[19/01/2022, 14:13:53] [Bedroom TV] Cannot read properties of undefined (reading 'send')
[19/01/2022, 14:13:53] [Livingroom TV] WebSocket was closed before the connection was established

**Comment by codyc1515** [comment]
Same. Not sure what happened exactly but I had to reset the cache and re-pair the plugin before it started working again.

**Comment by tavicu** [comment]
All the errors indicate the plugin could not connect to TV socket. Probably the IP wrong, TV was off, problem on your network
