### ISSUE TITLE
Unnamed Services not able to remove

### ISSUE THREAD

**Issue by bodhisatwa28** [tavicu/homebridge-samsung-tizen#461]
I tried to remove the cache from Homebridge. But still seeing the Unnamed Services. How can I remove them?

**Comment by tavicu** [comment]
Nothing from what you wrote make sense to me :) Sorry

I think your question should be asked on [homebridge repo](https://github.com/homebridge/homebridge)

**Comment by alexjje** [comment]
I have the same issue. For some reason at random “Unnamed Services” are created. I set up a couple of apps and that is working fine.

my list at this moment:

HDMI 1
HDMI 2
HDMI 3
Netflix
YouTube 
Prime Video
Unnamed service 
Unnamed service 
Unnamed service 
Unnamed service 

Hope this makes sense. To clarify: I didn’t add the unnamed services myself
