### ISSUE TITLE
OQEE by Free ID

### ISSUE THREAD

**Issue by Stewart06** [tavicu/homebridge-samsung-tizen#466]
Bonjour,

Si quelqu’un aurait le code ID de l’application ( OQEE by Free ) ?

Hello,

 If someone has the ID code of the application ( OQEE by Free )?

**Comment by Stewart06** [comment]
-----------------------------------
 App Name :  YouTube
App ID   :  111299001912
-----------------------------------
App Name :  Internet
App ID   :  org.tizen.browser
-----------------------------------
App Name :  Disney+
App ID   :  3201901017640
-----------------------------------
App Name :  Prime Video
App ID   :  3201512006785
-----------------------------------
App Name :  Netflix
App ID   :  3201907018807
-----------------------------------
App Name :  Universal Guide
App ID   :  3201710015067
-----------------------------------
App Name :  CANAL+
App ID   :  3201606009910
-----------------------------------
App Name :  Molotov
App ID   :  3201611011210
-----------------------------------
App Name :  Rakuten TV
App ID   :  3201511006428
-----------------------------------
App Name :  Apple TV
App ID   :  3201807016597
-----------------------------------
App Name :  OQEE by Free
App ID   :  3202103023185
-----------------------------------
App Name :  SmartThings
App ID   :  3201710015016
-----------------------------------
App Name :  B.tv
0App ID   :  3201910019420
-----------------------------------
App Name :  PrivacyChoices
App ID   :  3201909019271
-----------------------------------
App Name :  e-Manual
App ID   :  20192100002
-----------------------------------
App Name :  RMC Sport
App ID   :  3201704012212
-----------------------------------
App Name :  Google Play Films et séries
App ID   :  3201601007250
-----------------------------------
App Name :  Gallery
App ID   :  3201710015037
-----------------------------------
App Name :  Playzer
App ID   :  3201810017091
-----------------------------------
App Name :  Samsung Promotion
App ID   :  3201807016658
----------------------------------
App Name :  The Explorers
App ID   :  3201907018740
-----------------------------------
App Name :  OCS
App ID   :  3201703012029
-----------------------------------
App Name :  Apple Music
App ID   :  3201908019041
-----------------------------------
App Name :  Telefoot
App ID   :  3202008021462
-----------------------------------
App Name :  ARTE
App ID   :  3202011022316
-----------------------------------
App Name :  Benshi
App ID   :  3202007021336
-----------------------------------
App Name :  Spotify - Musique et podcasts
App ID   :  3201606009684
-----------------------------------
App Name :  france.tv
App ID   :  3202103023232
-----------------------------------
App Name :  Spotify - Musique et podcasts
App ID   :  3201606009684
-----------------------------------

**Comment by Stewart06** [comment]
Si cela peut aider.

**Comment by tavicu** [comment]
Thank you for the list.

I will update it on our wiki
