### ISSUE TITLE
Sleep Mode and Power OFF Tv

### ISSUE THREAD

**Issue by Stewart06** [tavicu/homebridge-samsung-tizen#468]
Bonjour, serait-il possible dans une prochaine mis à jour que la fonction veille du téléviseur puisse se réinitialiser si jamais on éteint le téléviseur avant la fin de la veille. Car parfois il m’arrive de rallumer le téléviseur et celui-ci s’éteint car la fonction veille était resté allumé.

Hello, would it be possible in a future update that the TV standby function can be reset if the TV is ever turned off before the end of standby.  Because sometimes I turn on the television again and it turns off because the standby function had remained on.

**Comment by tavicu** [comment]
I'm sorry but i did not understand your problem.

From the Home app you can toggle on/off the TV with a limit of one action at 5 seconds.

Also the status of TV is refreshed by default every 5 seconds
