### ISSUE TITLE
HMErrorDomain Code 3 with Frame TV Siri Shortcuts

### ISSUE THREAD

**Issue by SydProom** [tavicu/homebridge-samsung-tizen#469]
Hi there, since I started using the Tizen plug in every few days my Siri shortcuts with my Samsung TV would randomly stop working and give the error (HMErrorDomain, 3) and I have to go through each shortcut that involves the TV and re-add the switches that it removed. I thought this issue was due to my set up not using a HomeKit Hub (Homepod, apple tv etc) but now that I am using a Homepod mini, it still occurs and ruins the magic experience of controlling my TV with cool automations. I'm wondering if you have any guidance on how to stop the error occurring. Thanks

**Comment by tavicu** [comment]
Hi,

I have checked and that error seems to be related with Apple. More likely a problem from your network.

It's the first time when i see it and when i try to search over the internet all the results are indicating a problem in the Apple system, nothing to do with Homebridge.

I'm sorry but don't have more informations regarding this or ideas on how to help you
