### ISSUE TITLE
Some problems with Samsung Q9 Series

### ISSUE THREAD

**Issue by drtp** [tavicu/homebridge-samsung-tizen#47]
Hi, 

we have a GQ65-Q9FN and unfortunately it does not react on all possible commands. Well, to tell the truth, the TV only reacts on the "channel" command so that it is possible to switch between differnt TV programs using Siri and to turn it on and off by using the respective toggel switch. However, up to now I was not able to use any of the KEY commands or the mute function. 

I would really appreciate to have full support for the Q9 Series.

Best regards,

Thorsten

**Comment by Pensive** [comment]
I have a similar problem with a Samsung UE65MU8000 - on and off works and channel select, and app select (Netflix/YouTube etc) but I can’t choose HDMI source :-/

I’m out this morning but I’ll try and get a verbose log later on

**Comment by tavicu** [comment]
Ha! :)) i have a same problem with one of my routers :)) starting to fail because of too many connections!

Just ordered some new ones :P
