### ISSUE TITLE
Sleep Problem 

### ISSUE THREAD

**Issue by Stewart06** [tavicu/homebridge-samsung-tizen#470]
Bonjour, depuis quelque jours j’ai la veille d’un de mes téléviseurs qui ne fonctionne plus. Avez-vous une idée de où cela pourrait venir ?

Cela s’est produit d’un coup.

Thank you.

 I noticed an abnormal behavior of the plugin for my fans.

 Let me explain, if my fan is off and I activate the day before, it activates and deactivates immediately.  Except that when I then turn on the fan the standby comes back on again.  This is unpleasant because I have a rule that activates the standby of my son's fan for the summer and except that when the day he activates the fan and well it turns off on its own because the timer has remained in memory.  It should be stable.

**Comment by tavicu** [comment]
Hi,

I'm sorry but I didn't understand what this have to do with this plugin.

My TV doesn't have any FAN ...

**Comment by Stewart06** [comment]
Sorry

**Comment by Stewart06** [comment]
Hello, for a few days I have the day before one of my televisions which no longer works.  Do you have any idea where this could be coming from?

 It happened all of a sudden.

**Comment by tavicu** [comment]
> Hello, for a few days I have the day before one of my televisions which no longer works. Do you have any idea where this could be coming from?

Did you set a static IP address for your TV?

If not, after a router restart your TV probably have other IP address and the plugin tries to connect to the old IP address and is failing.

**Comment by Stewart06** [comment]
Oui tout mes accessoires HomeKit ont une adresse ip fixe configuré sur mon routeur. Et parfois sur l’accessoire également.

Tout fonctionne sur le téléviseur, si je met la veille à 1 minutes cela fonctionne. Quand je règle la veille sur 60 minutes ou bien 90 minutes et bien le téléviseur ne s’éteint pas tout seul. Je ne comprend pas d’où le problème vient. Sur trois téléviseurs Samsung c’est le seul qui a ce problème.

La semaine dernière cela fonctionnait correctement pourtant.


Yes all my HomeKit accessories have a fixed ip address configured on my router.  And sometimes on the accessory too.

 Everything works on the TV, if I set standby to 1 minute it works.  When I set the standby to 60 minutes or 90 minutes and the TV does not turn off by itself.  I don't understand where the problem comes from.  Out of three Samsung TVs this is the only one that has this problem.

 Last week it was working fine though.

**Comment by tavicu** [comment]
You can run Homebridge in debug mode and post the error you get when the TV should turn OFF.

**Comment by Stewart06** [comment]
Je reviens vers vous une fois que j’ai le log.

En ce qui concerne le commutateur VEILLE, cela serait bien si il pouvait s’éteindre et donc se réinitialiser si jamais on éteignez le téléviseur manuellement avant la fin de la VEILLE. Car aussi non, si on rallume le téléviseur quelque temps après et bien la veille reste allumé et va éteindre le téléviseur d’un coup. Vous voyez se que je veux dire ?


I'll come back to you once I have the log.

 Regarding the STANDBY switch, it would be nice if it could turn off and therefore reset itself if you ever turn off the TV manually before the end of STANDBY.  Because also no, if the television is turned on again some time later and the standby remains on and will turn off the television all of a sudden.  Do you see what I mean?

**Comment by tavicu** [comment]
> Regarding the STANDBY switch, it would be nice if it could turn off and therefore reset itself if you ever turn off the TV manually before the end of STANDBY. Because also no, if the television is turned on again some time later and the standby remains on and will turn off the television all of a sudden. Do you see what I mean?

I had made a change regarding this and now when the TV turns off the sleep timer will clear out.
