### ISSUE TITLE
Constantly requesting to "Add Device"

### ISSUE THREAD

**Issue by jhnielson** [tavicu/homebridge-samsung-tizen#471]
When I configured all my TVs (4 of them), they all worked great. However, they all now ask to "Add Device" every time they turn on or if I try to control something from the Home app.

If I "Approve" the add request, it will work fine again until the TVs are turned off.  Having to constantly "Add Device" is getting frustrating. 

Any ideas/suggestions?

**Comment by jhnielson** [comment]
Hi, I'm running HomeBridge on Docker.  However, I was running on it on a Mac prior and it did the same thing.

**Comment by tavicu** [comment]
With docker you should not have any problem regarding saving the token in file.

Looks like a "problem" on your TVs.

I know there was a setting where you could set to not ask every time.

Try this: On TV go to `Settings` - `General` - `External Device Manager` - `Device Connection Manager` and set `Access Notification` to `Off`.
