### ISSUE TITLE
Cant find pin?

### ISSUE THREAD

**Issue by lsd05** [tavicu/homebridge-samsung-tizen#472]
Hi i cant seem to locate the pin required to add to Homekit. 

Thanks for any help

**Comment by tavicu** [comment]
It's the pin set for the main bridge.

Also the PIN is written in the console after you start the server
![Screen Shot 2022-02-11 at 09 39 54](https://user-images.githubusercontent.com/172068/153553695-35041215-0a36-4f10-8b35-9f8dbc11f136.png)
.

**Comment by tavicu** [comment]
> Is there any remote control features at all for homekit?

In the Home app you have only controls of the state of TV.

But you have some options to control the TV (volume, arrows, press, and others) with Remote from Control Centre.

- [Open Control Center](https://support.apple.com/kb/HT202769)
- Click on Remote (if you don't have it, you can add it from the Settings -> Control Centre -> **Apple TV Remote**)
- Select the TV from the top and then everything you press will be sent to TV.
- The volume is controlled with the phone physical volume buttons while you are in the Remote screen.
