### ISSUE TITLE
add pin setting in hombridgeui

### ISSUE THREAD

**Issue by Dorian-Grim** [tavicu/homebridge-samsung-tizen#475]
Hi,

Instead of going to config.json to add a bridge -> pin. Enable users to add the pin from homebridge ui

**Comment by tavicu** [comment]
Hi,

What pin are you talking about?
The plugin has no setting for any pin.

**Comment by Dorian-Grim** [comment]
> 

[Yes it does, right?](https://github.com/tavicu/homebridge-samsung-tizen/wiki/Installation#6-adding-the-tv-to-home-app)

**Comment by tavicu** [comment]
Nope, it doesn't.

The pin is part of the main homebridge configuration, not the plugin.
Then homebridge assign the same pin to all its child bridges.

config.json should be in `var/lib/homebridge`

**Comment by Dorian-Grim** [comment]
Alright, sry for the confusion.
