### ISSUE TITLE
TV box Vodafone 

### ISSUE THREAD

**Issue by Reddyzinho** [tavicu/homebridge-samsung-tizen#477]
Hi there. 
I have a Samsung TV that works great with this plugin. I only have a question: 
I have a set up box from my operator (Vodafone). When I use ACCESSORIES, and click on “FLIXIPTV” (e.g.), it goest to the app. And……then I want to return to the live to channels, how can I do it? The “app” Vodafone don’t appear on the apps (because it isn’t, actually). What do you recommend? 
![0F53597B-4F30-4F1F-B4E7-4799EFB41A00](https://user-images.githubusercontent.com/3985096/154475410-02d0370c-31f1-4c4c-b3d2-549db5c72cf6.jpeg)

**Comment by tavicu** [comment]
Hi,

I didn't understand if you want to open Vodafone and then go to live channels or you are already on vodafone app and you just want to switch to live tv.

**Comment by Reddyzinho** [comment]
Sorry :(

I want to return to vodafone after opening an accessorie. Example: I have clicked on Netflix accessorie. Enter in Netflix. Then want to return to vodafone …. But don’t know how ;(( 


Atentamente,

Tiago Cunha

No dia 17/02/2022, às 12:14, Octavian Ruda ***@***.***> escreveu:

﻿
Hi,

I didn't understand if you want to open Vodafone and then go to live channels or you are already on vodafone app and you just want to switch to live tv.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tavicu** [comment]
i understand.
Did you try to get installed applications and Vodafone is not in the list?

https://github.com/tavicu/homebridge-samsung-tizen/wiki/Applications#newer-tvs-model-year--2020 (follow the Newer TVs instructions)

**Comment by Reddyzinho** [comment]
I don’t  know if Vodafone is a app actually. Because this icon appears when I select the set up box connected to hdmi1 port. If I was other operator . It will change the icon for this operator. 

I will try what you have sent me. Thanks for your help. 


Atentamente,

Tiago Cunha

No dia 21/02/2022, às 10:01, Octavian Ruda ***@***.***> escreveu:

﻿
i understand.
Did you try to get installed applications and Vodafone is not in the list?

https://github.com/tavicu/homebridge-samsung-tizen/wiki/Applications#newer-tvs-model-year--2020 (follow the Newer TVs instructions)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tavicu** [comment]
Other version will be to create an Input/Switch that runs a series of commands like `KEY_SOURCE,KEY_LEFT,...`
To copy the buttons you press on the physical remote to switch to Vodafone source.
