### ISSUE TITLE
"TV is offline" error

### ISSUE THREAD

**Issue by StefanScanteie** [tavicu/homebridge-samsung-tizen#478]
Hello,

I have two Samsung Q series in the same house, the same Wi-Fi network connected to the same Homebridge. One is a Q7 series that works perfectly fine with the plugin, absolutely no issues. The other one, a Q8 series, works fine, "answers" to my morning automation, but in the Homebridge log I have this error:

```[17/02/2022, 09:00:13] [Samsung TV Q8] TV is offline```

Clearly, it is not offline :), as it is working with my automations, streaming platforms are working perfectly fine etc.

**Comment by tavicu** [comment]
That error appears when you try to send a command, make an action and the TV is offline.

What are you trying to do? When do you get that error?

**Comment by Angel5** [comment]
The error appears ONLY when the TV si powered ON by a personal automation set in the Home app. And this happen every morning. But the TV powers ON as expected.

Any other action (manual on/off, changing sources) does not throw this error.

**Comment by StefanScanteie** [comment]
```When my wake-up alarm is stopped```
```Set Top Lights, Wait, Set Samsung TV Q8```

Basically, after I turn off my morning alarm, this personal automation will (a) turn on my kitchen top lights, (b) waits for 5 seconds and then (c) turns on the TV. And the TV turns ON. Is just the error that bugs me :).

**Comment by tavicu** [comment]
What inputs do you have set? Which is the first input?

Also you can start the homebridge in debug mode to see which command is throwing that error.

**Comment by StefanScanteie** [comment]
{
            "name": "SamsungTizen",
            "app_list": false,
            "devices": [
                {
                    "name": "Samsung TV Q8",
                    "ip": "192.168.1.138",
                    "mac": "00:00:00:00:00:00",
                    "refresh": {
                        "main": 1000,
                        "switch": 1000
                    },
                    "inputs": [
                        {
                            "type": "command",
                            "name": "Live TV",
                            "value": "KEY_SOURCE,KEY_RIGHT*5,KEY_ENTER"
                        },
                        {
                            "type": "app",
                            "name": "YouTube",
                            "value": "111299001912"
                        },
                        {
                            "type": "app",
                            "name": "Netflix",
                            "value": "11101200001"
                        },
                        {
                            "type": "app",
                            "name": "Apple TV",
                            "value": "3201807016597"
                        },
                        {
                            "type": "app",
                            "name": "Prime Video",
                            "value": "3201512006785"
                        },
                        {
                            "type": "app",
                            "name": "HBO Max",
                            "value": "3201601007230"
                        }
                    ]
                },
                
This is my config for this particular TV. I changed the MAC Address for this conversation.

Sure, I can run Homebridge in debug mode and come back tomorrow morning when this will occur.

**Comment by tavicu** [comment]
Yup, the error comes from a line that try to set an input.
So HomeKit sends 2 commands. One to turn on the TV and the 2nd to change the input. It send them at the same time.

The turn ON command works well but the 2nd to change the input will fail because it see the TV as offline and throw the error.

What you can do in your automation is to edit it and remove the TV then add it again without long pressing the pill to open the popup where you can set which input to set.

Also, this will be fixed in another feature we are working on.

**Comment by StefanScanteie** [comment]
Hello!

It took me a few days, but I can confirm that your workaround works. I no longer have the error in Homebridge.
