### ISSUE TITLE
Command for changing Audio Output

### ISSUE THREAD

**Issue by valeale08** [tavicu/homebridge-samsung-tizen#481]
Hi I'm looking for a switch changing the audio from TV to HDMI and back. Can't find the right the command. Can anyone help me with that?

**Comment by tavicu** [comment]
Hi,

I have checked and there is no API to change the source of audio. There is only one API to change sound mode (Standard, Optimised, Amplify)

I guess the only option is to create custom switches with a list of commands that copy what buttons you press on physical remote to change the source.

**Comment by tavicu** [comment]
Looks like you made a mistake. You wrote s with uppercase.
