### ISSUE TITLE
Cannot read properties of undefined (reading 'setinput')

### ISSUE THREAD

**Issue by seidnerj** [tavicu/homebridge-samsung-tizen#482]
Error show in up in Homebridge’s log

**Comment by tavicu** [comment]
I don't know how I may help you since you didn't post any log from debug mode, you didn't told me what you are trying to do when you get that error and also i don't know your config.

**Comment by seidnerj** [comment]
Sorry, yes - I’m going to check how to enable debug mode and collect more
information then update the thread 🙏

**Comment by seidnerj** [comment]
How do I enable debug mode? is it at the plugin level? searching for 'debug' at the [documentation page](https://github.com/tavicu/homebridge-samsung-tizen/wiki/Configuration) does not yield any result. Thanks!

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/wiki/Common-Issues#how-to-open-a-new-issue

**Comment by seidnerj** [comment]
👍

**Comment by seidnerj** [comment]
Is there a way to limit the logging to this specific plugin? since I have
many plugins the log cycles before I am able to capture this error.

Thanks

**Comment by seidnerj** [comment]
Cannot replicate this for the time being. Will reopen if I have more details.

Thanks

**Comment by killervette42** [comment]
I am having this same issue, was anything every discovered with it?
