### ISSUE TITLE
APP not visible when more than 1

### ISSUE THREAD

**Issue by platini76** [tavicu/homebridge-samsung-tizen#484]
hello, I have a problem on my tizen frame
when I add more than 1 app it show only the first one... inside config... (all time I save and re-enter in config it show only 1 app,  only first one)
thanks for help me solve

     {
            "name": "SamsungTizen",
            "app_list": false,
            "devices": [
                {
                    "name": "TV Soggiorno",
                    "ip": "192.168.0.90",
                    "mac": "8C:EA:__:98____:__",
                    "method": "frame",
                    "options": [
                        "Frame.RealPowerMode",
                        "Frame.ArtSwitch.Disable",
                        "Frame.PowerSwitch.Disable"
                    ],
                    "inputs": [
                        {
                            "type": "app",
                            "name": "Netflix",
                            "value": "3201907018807"
                        },
                        {
                            "type": "app",
                            "name": "Prime Video",
                            "value": "3201910019365"
                        },
                        {
                            "type": "app",
                            "name": "Disney +",
                            "value": "3201901017640"
                        },
                        {
                            "type": "app",
                            "name": "Apple TV",
                            "value": "3201807016597"
                        },
                        {
                            "type": "app",
                            "name": "DAZN",
                            "value": "3201806016390"
                        },
                        {
                            "type": "app",
                            "name": "Internet",
                            "value": "3201907018784"
                        }
                    ],
                    "switches": [
                        {
                            "name": "Play",
                            "command": [
                                "KEY_PLAY_BACK"
                            ]
                        }
                    ]
                }
            ],
            "_bridge": {
                "username": "0E:E5:89:6C:3F:52",
                "port": 43208
            },
            "platform": "SamsungTizen"
        },

**Comment by coogito** [comment]
I have the same issue.

**Comment by MarkBarbieri** [comment]
I've seen this a long time ago.  I have a feeling this is actually a homebridge-ui bug in one of the components. 

It would be great if it could be fixed, but I don't think it is related to anything this app is doing wrong. 

If I recall, if you press the + button to add another app you will see it automatically populates with the next app from your config. I think the issue is the component in the ui doesn't correctly interpret the number of elements, even though they are actually loaded from the config

**Comment by tavicu** [comment]
as @MarkBarbieri said, they don't appear but they are there. Once you click on the button to add new input it will be populated with the information from config. 

I have looked on Configu UI X and tried to solve the problem but i was not able to do it.

Also, i suggest not creating many inputs of type app if you are not using them. Each input represents a request to your TV each 30 seconds (or lower if you changed the config). In your case you will have 6 requests every 30 seconds.
