### ISSUE TITLE
Integration crashes Home Assistant

### ISSUE THREAD

**Issue by BrendanxP** [tavicu/homebridge-samsung-tizen#485]
Adding the integration to my configuration makes Home Assistant crash instantly at boot. It tries to reboot immediately after but keeps crashing. Meanwhile, other integrations do keep running such as Bitwarden. When I first tried to configure the integration and messed up the host IP, it obviously did not connect to the TV, but it also did not cause the crashing. After I properly configured it, the code did seem to work and control the TV for a second, but caused a crash very soon after. The TV is a Tizen Samsung The Frame 2020 50".

**Configuration.yaml**
`   - platform: samsungtv_tizen
     host: 192.XXX.XXX.XXX
     mac: 64:XX:XX:XX:XX:58
     name: "The Frame [lan]"
     api_key: !secret smartthings_hacs_tv
     device_id: !secret device_id_tv
     is_frame_tv: true`

**These are the last log events (I could see) before a crash:**
> 2022-03-02 18:41:07 INFO (MainThread) [custom_components.samsungtv_tizen.websockets] New token 52504358
2022-03-02 18:41:07 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call inside the event loop. This is causing stability issues. Please report issue to the custom component author for samsungtv_tizen doing blocking calls at custom_components/samsungtv_tizen/websockets.py, line 115: time.sleep(self.key_press_delay)

**System details:**
## System Health

version | core-2022.2.9
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.92-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4258
Installed Version | 1.23.0
Stage | running
Available Repositories | 1002
Downloaded Repositories | 32

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 457.7 GB
disk_used | 84.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Vaultwarden (Bitwarden) (0.15.0), File editor (5.3.3), MariaDB (2.4.0), Nginx Proxy Manager (0.11.0), Home Assistant Google Drive Backup (0.103.1), Samba share (9.5.1), Apache2 (2.2.0), Terminal & SSH (9.3.0), ArgonOne Active Cooling (24.1), phpMyAdmin (0.7.0), Portainer (1.5.1), DOODS2 (1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 21
views | 8
mode | yaml

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by tavicu** [comment]
Wrong platform.
This is a plugin for Homebridge, not Home Assistant
