### ISSUE TITLE
New version 5.1.0 is not backwards compatible

### ISSUE THREAD

**Issue by mourraille** [tavicu/homebridge-samsung-tizen#486]
I have a samsung series 8. As soon as I updated everything stoped working, had to rollback to 5.0.0.

**Comment by tavicu** [comment]
Nothing drastically changed between 5.0.x and 5.1.x

You will have to come up with more than that if you want help.
Like what stopped working?
Did you turn on the debug mode and you have errors? Which errors?
What did you tried to solve your problem?

Until you get the answers i will close this issue and open a new one when you are ready!
https://github.com/tavicu/homebridge-samsung-tizen/wiki/Common-Issues#how-to-open-a-new-issue

**Comment by mourraille** [comment]
Sorry about the short message. When I moved to 5.2.1 it wouldnt take any commands at all. I dont remember what the verbose was when I installed it. But I have moved to 5.2.2 and everything works fine. Thanks !
