### ISSUE TITLE
If my tv is turned off for a while I can’t turn it on 

### ISSUE THREAD

**Issue by Reddyzinho** [tavicu/homebridge-samsung-tizen#488]
Hi there :) 

I want to turn on my tv when I get at home, but the command never works. if I try in the home app, it doesn’t turn on. This just happens if the tv is on idle for some minutes to hours. If I try to turn it off and on in less than 2 minutes it gets the command. Any idea what I’m doing wrong ? The tv is connected on cable and not Wi-Fi. 

Sorry my bad English ;)))

**Comment by tavicu** [comment]
Hi! Check the mac address to be the correct one (cable) and not the mac from the wi-fi.

From what you described the plugin is failing to turn on the TV by Wake on Lan to the MAC address.

**Comment by Reddyzinho** [comment]
Well, i have change the MAC address and re add the TV. Now….its worse. On the Wi-Fi it was more fast and responsive.Now….I press to turn on, and it doesnt, or when try to turn off, gets “unresponsive”. Any idea ? The IP and MAC address are right (cable MAC address and IP).

**Comment by tavicu** [comment]
I'm sorry but something doesn't make sense. In the first message you said it's over the cable, now you say on the wi-fi was faster and more responsive.

So, let's start from the beginning.

If you TV is connected by cable make sure to get the mac address from the cable.
If the TV is connected via wifi (remove the cable) and get the mac address for the wifi.

In your router set a static IP address for the mac you want to use. Restart the router, make sure the TV receive the IP address you set.

Then in config enter the IP and the MAC address. Restart homebridge, add the TV to Home app if you changed the mac then make sure the TV is paired.

Also, i'm pretty sure you also have some errors that will help us if you start homebridge in debug mode

**Comment by Reddyzinho** [comment]
Sorry if I dont get me explained :) 

Just as a resume: 

MY TV is connected thought a CABLE (always). 
I get an IP (cable). 
I get a MAC ADRESS for cable and I have one for WI-FI 


My question here was: 

1) Alredy connected to CABLE, but have put the MAC ADRESS from WI-FI. Inside my home, the TV turns on and OFF very responsive. When I’m out of my house, this doesn’t happen. I have an automation that is “when I get at home, turn on TV”, but the TV nevers gets on. 

Solution? 

Change to MAC ADRESS CABLE (makes sense): 

When I done this, I verify that the TV wasn’t very responsive as the WI-FI MAC ADDRESS. And this is strange. And dont get the TV on again. 

MY question is: I can remotely control it outside my home? Is this possible? Or I have to be always inside home? 

I will try to restart everything as you explained me. Sorry bothering and thanks for your help. Much appreciated :)

**Comment by tavicu** [comment]
> Alredy connected to CABLE, but have put the MAC ADRESS from WI-FI. 

Sorry but still doesn't make sense to me ... since you are not connected over WiFi you should not be able to use the MAC address from the WiFi Card :)

> MY question is: I can remotely control it outside my home? Is this possible? Or I have to be always inside home?

You can, but this is not related to the plugin. It's part of the HomeKit and you will have to use a device which is always home as a home hub between your phone which is external and your Home. You can read more on the apple website: https://support.apple.com/en-us/HT207057

When you will have the hub every command sent from external will be like this:
- You send turn on command from external network
- The hub (apple tv, ipad, homepod) receive the command and forward it to the homebridge server
- Homebridge server receive the command and execute.

**Comment by Reddyzinho** [comment]
Thanks for your reply 

I have  two HomePods mini, Apple TV … homebridge. 

I know this doesn’t makes any sense for you but is the reality ehehe :) i Will try to restart everything and make some tests to verify. Thanks for your help I will keep you posted. 


Atentamente,

Tiago Cunha

No dia 09/03/2022, às 08:37, Octavian Ruda ***@***.***> escreveu:

﻿
Alredy connected to CABLE, but have put the MAC ADRESS from WI-FI.

Sorry but still doesn't make sense to me ... since you are not connected over WiFi you should not be able to use the MAC address from the WiFi Card :)

MY question is: I can remotely control it outside my home? Is this possible? Or I have to be always inside home?

You can, but this is not related to the plugin. It's part of the HomeKit and you will have to use a device which is always home as a home hub between your phone which is external and your Home. You can read more on the apple website: https://support.apple.com/en-us/HT207057

When you will have the hub every command sent from external will be like this:

You send turn on command from external network
The hub (apple tv, ipad, homepod) receive the command and forward it to the homebridge server
Homebridge server receive the command and execute.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
