### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by mafyata** [tavicu/homebridge-samsung-tizen#500]
Hi, I see that there is an update to v5.2.2, but there is no changelog and not officialy here in github.
![aaaaaaaa](https://user-images.githubusercontent.com/48009267/158857316-052e44aa-6cf6-417a-830c-964958096538.png)

**Comment by tavicu** [comment]
5.2.2 was a small release with a quick bugfix!
I didn’t add it to changelog
