### ISSUE TITLE
Input to open app then run command

### ISSUE THREAD

**Issue by mozilla33** [tavicu/homebridge-samsung-tizen#501]
Is there a way to edit my config so that an input will open an app then send a command? I can do each separately but would like to link the two. HomeKit does not allow input changes to trigger automations. 

Thank you for the great work on this app!

**Comment by tavicu** [comment]
Hi. 

With inputs no, you cannot do this. But you can create a custom switch that will be able to do this.

**Comment by mozilla33** [comment]
Thanks for the reply. Is the a way to add a delay between the the 2 actions in a switch? Without increasing the delay globally


On Mar 17, 2022, at 3:26 PM, Octavian Ruda ***@***.***> wrote:

﻿
Hi.

With inputs no, you cannot do this. But you can create a custom switch that will be able to do this.

**Comment by MarkBarbieri** [comment]
Cheats way is to add a dummy command. It will be ignored but they delay will still occur 

A_DELAY*2s

**Comment by tavicu** [comment]
Yup :) That's the way.

**Comment by JasonGoldenDDT** [comment]
I'm working on a Switch that open's the Hue Sync app and turns it on/off then returns back to the previous HDMI input. 

`{
                            "name": "Hue Sync",
                            "power": true,
                            "app": "3202205027312",
                            "command": [
                                "A_DELAY*2s",
                                "KEY_ENTER",
                                "KEY_RETURN",
                                "KEY_ENTER*2"
                            ]
                        }`

I've tried "Pause" and I found this "A_Delay" reference and I'm still stuck.  

The App opens, but it doesn't proceed past PAUSE:

`[8/19/2024, 2:55:46 PM] [Samsung TV] [DEBUG] {
  method: 'ms.remote.control',
  params: {
    Cmd: 'Press',
    DataOfCmd: 'A_DELAY',
    Option: false,
    TypeOfRemote: 'SendRemoteKey'`

I've created a "Test Key" to validate components of this switch, and they work out side of the App call switch.  I'm wondering if you've had any luck with your App switch.   if so can you post your config?

**Comment by mozilla33** [comment]
Here’s my config. I’m using PAUSE*3s  "inputs": [                        {                            "type": "command",                            "name": "Laguna Live.",                            "value": "KEY_LEFT*1s, KEY_ENTER, KEY_RIGHT*1s, PAUSE*3s, KEY_ENTER*2, KEY_RIGHT*3s"                        } ]On Aug 19, 2024, at 8:59 PM, Jason Golden ***@***.***> wrote:﻿
I'm working on a Switch that open's the Hue Sync app and turns it on/off then returns back to the previous HDMI input.
{ "name": "Hue Sync", "power": true, "app": "3202205027312", "command": [ "A_DELAY*2s", "KEY_ENTER", "KEY_RETURN", "KEY_ENTER*2" ] }
I've tried "Pause" and I found this "A_Delay" reference and I'm still stuck.
The App opens, but it doesn't proceed past PAUSE:
[8/19/2024, 2:55:46 PM] [Samsung TV] [DEBUG] { method: 'ms.remote.control', params: { Cmd: 'Press', DataOfCmd: 'A_DELAY', Option: false, TypeOfRemote: 'SendRemoteKey'
I've created a "Test Key" to validate components of this switch, and they work out side of the App call switch.  I'm wondering if you've had any luck with your App switch.   if so can you post your config?

**Comment by JasonGoldenDDT** [comment]
Appears you are working within the "inputs" structure.  Ideally, I have a switch in the UI can I can toggle Hue Sync functionality with. 

If anyone else has experience with calling an App via a switch and navigating it with key commands, I'd love to hear your approach.  It seems like the switch frame work is not correctly triggering key commands in the current plugin.

**Comment by mozilla33** [comment]
Gotcha. I was having trouble w/ a similar use case.My workaround: I created a dummy switch (homebridge-dummy) then built a HomeKit automation which selects that inputOn Aug 22, 2024, at 5:15 PM, Jason Golden ***@***.***> wrote:﻿
Appears you are working within the "inputs" structure.  Ideally, I have a switch in the UI can I can toggle Hue Sync functionality with.
If anyone else has experience with calling an App via a switch and navigating it with key commands, I'd love to hear your approach.  It seems like the switch frame work is not correctly triggering key commands in the current plugin.

**Comment by JasonGoldenDDT** [comment]
I just moved over the the SmartThings plugin to control the TV,  unclear how to recreate this function there... still trying to keep the device in sync with the Home App.

Seems like a lot of homebridge developers only use "SetCharactersitics" in their code when "updateCharacterstics" should be used.  Set only gets picked up when a full app refresh is triggered... and update is a push. 

I'm hoping this can be fixed in this plugin and I can switch back.. I had a solution built that worked really well.
