### ISSUE TITLE
Application ID needed for PlutoTV.

### ISSUE THREAD

**Issue by siddrajput** [tavicu/homebridge-samsung-tizen#504]
Hi,

I would like to know the Application ID for PlutoTV app.

**Comment by tavicu** [comment]
Hi.

I think it will also help if you tell us from what region you are because not all apps are available everywhere :)

**Comment by siddrajput** [comment]
USA.

**Comment by tavicu** [comment]
Could you please try this ID and let me know if it works so i can add it to the list:

```
App ID - WAS : 3201808016802
```

**Comment by siddrajput** [comment]
Yes it worked.

**Comment by tavicu** [comment]
Awesome! I have added it to the list!
