### ISSUE TITLE
Accessory is not responding in HomeKit

### ISSUE THREAD

**Issue by cosmin-sulita** [tavicu/homebridge-samsung-tizen#505]
Hello,
I'm currently running Hoobs:
![image](https://user-images.githubusercontent.com/23417639/160452830-4e17922f-51ce-4d70-870b-1623a8a014d9.png)
Last night, I ran the "Check for Updates" command and my Pi updated different components.
Now my Samsung TV in HomeKit shows "Accessory is not responding".
I've tried removing and adding the accessory again / reinstalling the plugin, but with no luck. I don't know what else to try.
The plugin appears to function properly, but I'm still getting the error in homekit.
![image](https://user-images.githubusercontent.com/23417639/160453612-862453ae-58fb-443e-b623-ae8848410051.png)
Can you please help ? Thank you very much !

**Comment by tavicu** [comment]
Hi.

I'm sorry but I'm not using Hoobs and don't know how to help you!
The plugin appears it works ok and the problem is with the connection between homekit and hoobs server.

I don't know but this may help you! https://github.com/tavicu/homebridge-samsung-tizen/issues/480#issuecomment-1047778466

**Comment by cosmin-sulita** [comment]
It seems like the issue was somehow related to my **Homepod Mini**. **Restarting** it fixed everything. Sorry for the trouble! 
Thanks a lot for this awesome plugin!
Have a great day!
