### ISSUE TITLE
Unnamed Service being added 

### ISSUE THREAD

**Issue by alexjje** [tavicu/homebridge-samsung-tizen#507]
I have the same issue. For some reason at random “Unnamed Services” are created. I set up a couple of apps and that is working fine.

my list at this moment:

HDMI 1
HDMI 2
HDMI 3
Netflix
YouTube 
Prime Video
Unnamed service 
Unnamed service 
Unnamed service 
Unnamed service 

Hope this makes sense. To clarify: I didn’t add the unnamed services myself

_Originally posted by @alexjje in https://github.com/tavicu/homebridge-samsung-tizen/issues/461#issuecomment-1082317852_

**Comment by tavicu** [comment]
Hi,

The plugin doesn't cache the inputs. They are always generated when you start the Homebridge server and it only contains what you have in your config file.

If you cleared the cache from Homebridge it may be a problem of sync between Homebridge and HomeKit.

Clearing the cache probably homebridge removed all connections while HomeKit still have them.

I would recommend to remove the TV from Home App and pair it again.
