### ISSUE TITLE
App ID

### ISSUE THREAD

**Issue by CKMartens** [tavicu/homebridge-samsung-tizen#51]
Hello,

i tried to get the app-id by start homebrige with command tizen-apps. But i get only information when i start the homebridge in debug mode an then i got this:
```
{ data:
   { clients: [ [Object] ],
     id: '9d8982f6-833a-48ec-a9f1-bde0d438c2' },
  event: 'ms.channel.connect' }
[2019-1-28 13:45:45] [Wohnzimmer TV] [DEBUG] { data:
   { data:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },
  event: 'ed.installedApp.get',
  from: 'host' }
```

I will loking from the app-if for MagentsSports (TelekomSports).

**Comment by villamann** [comment]
Hi!

Thanks for a great plugin. I second @CKMartens experience, no app id table when starting `homebridge tizen-apps`. It would be great to get the table, as we have some local (national) app providers which id is hard to find. Thanks.

**Comment by villamann** [comment]
> 
> 
> Hi!
> 
> Thanks for a great plugin. I second @CKMartens experience, no app id table when starting `homebridge tizen-apps`. It would be great to get the table, as we have some local (national) app providers which id is hard to find. Thanks.

To supplement my previous post, here is the debug output:
```{ data:
   { clients: [ [Object] ],
     id: '626f544d-973e-44e8-b3e7-a830c5faa955' },
  event: 'ms.channel.connect' }
[2019-1-28 22:21:17] [TV i stue] [DEBUG] { data:
   { data:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },
  event: 'ed.installedApp.get',
  from: 'host' }
```

**Comment by robin1604** [comment]
If I command "homebridge tizen-apps" it will just run Homebridge and doesn't see anything about apps. Is there a fix for this problem?

Btw I love this plugin <3 I hope a lot more people will give this plugin a star 👍

**Comment by tavicu** [comment]
in the debug mode the response is correct! 
Until the new version is released you can change the 425 line from `SamsungRemote.js`
Before: `this.device.debug(response);`
After: `this.device.debug(JSON.stringify(response));`

Then start the server again in debug mode and instead of `[Object]` you will see more info.

**Comment by phenix13** [comment]
> If I command "homebridge tizen-apps" it will just run Homebridge and doesn't see anything about apps. Is there a fix for this problem?
> 
> Btw I love this plugin <3 I hope a lot more people will give this plugin a star 👍

I also can't get APP ID with "Homebridge Tizen-apps", Do you have solved this problem?

**Comment by villamann** [comment]
> I also can't get APP ID with "Homebridge Tizen-apps", Do you have solved this problem?

Hi phenix13! I was running Node.js v8.x and experienced the same problem. I made a fresh install with Node.js v10.x, and then the command "homebridge tizen-apps" in debug mode returned the app id`s.

**Comment by phenix13** [comment]
Thanks a lot , I have soled this problem in your help.
