### ISSUE TITLE
No response in Home App

### ISSUE THREAD

**Issue by logictester** [tavicu/homebridge-samsung-tizen#510]
My TV shows no response all of a sudden. Tried removing and re-adding the accessory multiple times, tried changing uid, but nothing seems to help, it works fine when working with the accessory in hombridge UI in a web browser, but not in Home app

**Comment by Homekitdude** [comment]
Hate to say it but this is a poorly done plugin for HOOBS users. They released an update that supposedly fixed the constant pop up asking for permissions and it didn’t do a thing. I still get it everytime and had to just uninstall this and move on.

**Comment by tavicu** [comment]
> My TV shows no response all of a sudden. Tried removing and re-adding the accessory multiple times, tried changing uid, but nothing seems to help, it works fine when working with the accessory in hombridge UI in a web browser, but not in Home app

Removing and re-adding accessory multiple times will not solve the problem :)

First remove the accessory from the home app.
Then change the UUID to to something you didn't use before. (It can be anything you want)
Then restart the homebridge server.
Then on your iPhone make sure to force close the Home App.
Then open Home App and try to add the accessory.

How to change the uuid:
```
{
    "devices": [
        {
            "name": "...",
            "ip": "...",
            "mac": "...",
            "uuid": "X21A"
        }
    ],
    "platform": "SamsungTizen"
}
```

Since it works in the Config UI X it means the problem is the connection between Home App and Homebridge server.
The No Response message happens only in this case.

**Comment by logictester** [comment]
Followed the steps, after changing the UUID, got a new Allow request on the TV - Allowed, getting the following on HB:
[4/6/2022, 10:36:34 AM] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge DE4F) is running on port 52940.
[4/6/2022, 10:36:34 AM] [Samsung TV] [DEBUG] {
  frametv: false,
  tokenauth: true,
  powerstate: false,
  token: '18135416'
}
[4/6/2022, 10:36:35 AM] Publishing external accessory (name: Samsung TV, publishInfo: {
  username: '1C:A6:04:9C:4F:FA',
  pincode: '***-**-***',
  category: 31,
  port: undefined,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: undefined
}).
[4/6/2022, 10:36:35 AM] Samsung TV 3BCB is running on port 59727.
[4/6/2022, 10:36:35 AM] Please add [Samsung TV 3BCB] manually in Home app. Setup Code: 031-45-154
[4/6/2022, 10:36:43 AM] [Samsung TV] [DEBUG] Device paired with success (token: 18135416)

Killed the Home app and rebooted the phone (for a good measure), re-added the TV on Home app - same issue - No Response

**Comment by logictester** [comment]
welp, the issue is solved now, rebooted my router and everything is back to normal 😀 thank you for the help and great plugin!
