### ISSUE TITLE
Devices not found in Homekit - removed devices shown in statusbar

### ISSUE THREAD

**Issue by Maddin1684** [tavicu/homebridge-samsung-tizen#511]
Hello,
in my HK StatusBar are shown up two devices (removed TVs).
How can I clear the devices in the bar?
There is nothing shown up
![D95883DD-717E-42A6-8DD1-C38A7B396A18](https://user-images.githubusercontent.com/61165918/161850193-2a7ab390-9afa-40ff-a6f5-e94a6ddee815.jpeg)

**Comment by tavicu** [comment]
Hi,

Did you tried to force close the home app and open it again?

**Comment by Maddin1684** [comment]
> Hi,
> 
> Did you tried to force close the home app and open it again? Because it looks like a glitch from the Home App.

Yes, I did multiple times.

**Comment by tavicu** [comment]
At this point I don't know exactly what to recommend because it's a glitch from Apple ...

Did you tried to add the accessories again and see what happens?
Do you also have another iOS/iPadOS device? It's the same over there?

**Comment by tavicu** [comment]
Hi @Maddin1684,

Did you managed to resolve the problem?

**Comment by Maddin1684** [comment]
> Hi @Maddin1684,
> 
> Did you managed to resolve the problem?

Yes, I deleted the bridge and configured everything as new and clean homebridge… 
it takes many hours :(
but now everything is working fine. I think that Apple HomeKit had produced this problem

**Comment by tavicu** [comment]
> Yes, I deleted the bridge and configured everything as new and clean homebridge… it takes many hours :( but now everything is working fine. I think that Apple HomeKit had produced this problem

Glad you was able to figure it out! Indeed, HomeKit is "shit".
It was one of the first home automation systems but it looks like in the latest years it was not a priority for Apple. It has a lot of bugs and it's glitchy!

I hate to say it but i've started to migrate to Home Assistant because of HomeKit glitches.
