### ISSUE TITLE
Make iOS remote integration optional

### ISSUE THREAD

**Issue by jakubheglas** [tavicu/homebridge-samsung-tizen#514]
This might be great for us who solely use Apple TV to control everything and only want to control TVs inputs via Home app. 

Siri on iPhone tends to get confused which TV am I referring to, having an option to turn off the remote I'm not using anyway would be great addition to otherwise flawless plugin. Cheers!

**Comment by tavicu** [comment]
Hi.

In the HomeKit the remote keys are added by default and they are not optional. The plugin only maps the button to new actions.

I will check if it's possible to disable it but looking at the source code of HomeKit library it doesn't look like it's possible :)

**Comment by jakubheglas** [comment]
Wow, that wouldn't cross my mind, that's indeed surprising, even tho it makes _some_ sense. Thanks foor looking into it!

**Comment by tavicu** [comment]
Hi @jakubheglas,

Sorry for the late response.

As I told in my previous message the Remote characteristics is added as default (not optional) in the library that Homebridge uses. (https://github.com/homebridge/HAP-NodeJS/blob/900a4324f76f0c732d41795faa9f70e432388c3a/src/lib/definitions/ServiceDefinitions.ts#L1374)

I tried calling the removeCharacteristic function hoping it will remove the Remote functionality but unfortunately it's not working.

My guess is Apple adds the Remote feature by default for TVs and we can only map what the buttons to do. Leaving us no decision to remove the feature.
