### ISSUE TITLE
Add Applications to Application ID list

### ISSUE THREAD

**Issue by orevron** [tavicu/homebridge-samsung-tizen#516]
First, Thanks a lot for this awesome plugin :) very useful!
In Israel we have 3 main TV channels with their applications on the Tizen store:
```json
[
  {
    "name": "Mako",
    "type": "app",
    "value": "3201506003716"
  },
  {
    "name": "Reshet13",
    "type": "app",
    "value": "3201812017600"
  },
  {
    "name": "Kan11",
    "type": "app",
    "value": "3201803015997"
  }
]
```

It would be great if you'll add them to the application id list for other to use

**Comment by tavicu** [comment]
Hi @orevron,

Thank you! I have added the apps to the list :)
