### ISSUE TITLE
New Chilean Apps IDs for the Wiki

### ISSUE THREAD

**Issue by alcayaga** [tavicu/homebridge-samsung-tizen#517]
Please add the following App ID to the Wiki

- Movistar TV Chile 111299001957
- Estadio TNT Sports 3201712015454
- 13 Now 3201905018499
- Mi Perro Chocolo 3201706014259

They are for Older TVs (< 2020)

**Comment by tavicu** [comment]
Hi @alcayaga,

I have added them to the list!
