### ISSUE TITLE
Turn off debug mode?

### ISSUE THREAD

**Issue by kaganae** [tavicu/homebridge-samsung-tizen#518]
Just installed the plugin and using for my Frame TV - works wonderfully. However, I am getting these messages every 5 seconds in my homebridge.log, making it difficult to use the log for monitoring. Is there a switch to turn off/turn down logging levels/debug mode? Could not find any reference to this on the Wiki or closed issues.

[4/22/2022, 1:32:55 PM] [The Frame] [DEBUG] { request: 'get_artmode_status' }
[4/22/2022, 1:32:55 PM] [The Frame] [DEBUG] {
  data: '{\n' +
    '  "id": "xxxx-xxxx-xxx-xxxx-xxxxxxxx",\n' +
    '  "event": "artmode_status",\n' +
    '  "value": "on",\n' +
    '  "target_client_id": "xxxx-xxxx-xxx-xxxx-xxxxxxxx"\n' +
    '}',
  event: 'd2d_service_message',
  from: 'xxxx-xxxx-xxx-xxxx-xxxxxxxx'
}

**Comment by tavicu** [comment]
Hi. Debug mode is an option of Homebridge.
It depending on how you run your Homebridge instance. You should search for "Homebridge debug mode" on google.

**Comment by kaganae** [comment]
Thanks. The plug-in is a bit chatty, so wasn't sure if there were a way to tune it at the plug-in level.

**Comment by tavicu** [comment]
Unfortunately Homebridge doesn't offer an option to have multiple levels or domains of debug (from what I know).

There are a few debug logs because there are multiple features and it's my only option to try and help someone who has issues :). And sometimes I would even need more :P
