### ISSUE TITLE
Not able to pair with KU6079

### ISSUE THREAD

**Issue by niklaswa** [tavicu/homebridge-samsung-tizen#52]
Hey, I know, you're quite busy now with the iOS 12.2 beta update.. 😄 (If you're not interested in implementing those devices, because you closed the other issues 3 days ago, then you can close this one too 😃)
I have an issue with pairing my 2016 Samsung UE43KU6079.
The request pops up on the tv, but the pair is failing anyways.

I've tried the "samsung-remote-models-2014-and-newer" repo. It's returning the access keys but then it will follow with an [error](https://pastebin.com/raw/5T1aq5GT).
Here are some outputs of URLs I saw on the other issues regarding pairing:
`http://<IP>:8001/api/v2/`:
```
{
  "id": "uuid:104d509f-db57-45a6-bd81-xxxxxxxxxxxx",
  "name": "[TV] Niklas&apos; Fernseher",
  "version": "2.1.0",
  "device": {
    "type": "Samsung SmartTV",
    "duid": "uuid:104d509f-db57-45a6-bd81-xxxxxxxxxxxx",
    "model": "16_JAZZL_UHD_BASIC",
    "modelName": "UE43KU6079",
    "description": "Samsung DTV RCR",
    "networkType": "wired",
    "ssid": "",
    "ip": "<IP>",
    "firmwareVersion": "Unknown",
    "name": "[TV] Niklas&apos; Fernseher",
    "id": "uuid:104d509f-db57-45a6-bd81-xxxxxxxxxxxx",
    "udn": "uuid:104d509f-db57-45a6-bd81-xxxxxxxxxxxx",
    "resolution": "3840x2160",
    "countryCode": "DE",
    "msfVersion": "2.1.0",
    "smartHubAgreement": "true",
    "VoiceSupport": "false",
    "GamePadSupport": "true",
    "wifiMac": "d8:e0:e1:c9:xx:xx",
    "developerMode": "1",
    "developerIP": "...",
    "OS": "Tizen"
  },
  "type": "Samsung SmartTV",
  "uri": "http://IP:8001/api/v2/",
  "remote": "1.0",
  "isSupport": "{\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"false\",\"DMP_available\":\"true\",\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"EDEN_available\":\"true\"}"
}
```

`http://<IP>:8001/ms/1.0/`:
```
{
  "DUID": "uuid:104d509f-db57-45a6-bd81-xxxxxxxxxxxx",
  "Model": "16_JAZZL_UHD_BASIC",
  "ModelName": "UE43KU6079",
  "ModelDescription": "Samsung DTV RCR",
  "NetworkType": "wired",
  "SSID": "",
  "IP": "<IP>",
  "FirmwareVersion": "Unknown",
  "DeviceName": "[TV] Niklas&apos; Fernseher",
  "DeviceID": "uuid:104d509f-db57-45a6-bd81-xxxxxxxxxxxx",
  "UDN": "uuid:104d509f-db57-45a6-bd81-xxxxxxxxxxxx",
  "Resolution": "3840x2160",
  "CountryCode": "DE",
  "SmartHubAgreement": "true",
  "ServiceURI": "http://<IP>:8001/ms/1.0/",
  "DialURI": "http://<IP>:8001/ws/apps/",
  "Capabilities": [
    {
      "name": "samsung:multiscreen:1",
      "port": "8001",
      "location": "/ms/1.0/"
    }
  ]
}
```

**Comment by tavicu** [comment]
Hi. Start homebridge in debug mode to see what it returns

**Comment by niklaswa** [comment]
@tavicu [Here](https://hastebin.com/bucejoboga.cs) is the log with enabled debug mode.

**Comment by greensouth** [comment]
Same happens to me, K series :/

**Comment by greensouth** [comment]
I have discovered that getting a token is not needed if you already selected "allow" in your tv. Can turn on/off, send commands, receive the status, etc.

Just put whatever token you want in your config file. I put "0000" in mine and working flawlessly. (FINALLY! YAY!)

**Comment by tavicu** [comment]
When you will restart the Homebridge server it will ask you again to allow it :)

**Comment by greensouth** [comment]
I have restarted like 10 times, and not asking to pair. A X-File?

**Comment by tavicu** [comment]
I think even Samsung don’t understand their API ...

**Comment by greensouth** [comment]
AHAHAHAHAHAH!!

That is exactly the conversation we have at the other project I posted here before !

**Comment by niklaswa** [comment]
You're right, this is unbelievable.. 😂 
The 12.2 branch is working too (with input switching to HDMI!), haha

![img_1068](https://user-images.githubusercontent.com/7442307/52078006-7c289c80-2592-11e9-8a7c-900031a79f28.png)


The only thing, that doesn't work on my end, is turning the tv on and setting the volume :)

**Comment by tavicu** [comment]
I will close this Issue since the new version i am working on will not require to add the token in config file.
