### ISSUE TITLE
play button after openning the app

### ISSUE THREAD

**Issue by Danlipanovich** [tavicu/homebridge-samsung-tizen#522]
Hi, I'm trying thru API to open Spotify as the tv turns on and then hit play so the music start by itself
what is the best way to do it?
iv tried to KEY_PLAY_BACK*4s with no luck, but the switch stays turn on.
{
                            "name": "Morning Mood",
                            "power": true,
                            "app": "3201606009684",
                            "volume": 12,
                            "command": [
                                "KEY_PLAY_BACK*12s"
                            ]
                        }

**Comment by tavicu** [comment]
Hi.

KEY_PLAY_BACK don't exists. I think they key you are looking for is KEY_PLAY. Also, you don't need the 4s or 12s or any s because that means it keeps the key pushed for X seconds. You only need to press it.

So it should be `"command": "KEY_PLAY"`

If you want to have a bigger delay before pressing play, let's say 5 seconds you can do it like this:
`"command": "DELAY*5s,KEY_PLAY"`

**Comment by Danlipanovich** [comment]
It’s doesn’t do the play function,
I’m homebridge is shows a comment 401 unauthorized

Dan Lipanovich
***@***.***
+972 50 372 7333
________________________________
מאת: Octavian Ruda ***@***.***>
‏‏נשלח: Monday, May 9, 2022 10:27:36 AM
‏‏אל: tavicu/homebridge-samsung-tizen ***@***.***>
עותק: Danlipanovich ***@***.***>; Author ***@***.***>
‏‏נושא: Re: [tavicu/homebridge-samsung-tizen] play button after openning the app (Issue #522)


Hi.

KEY_PLAY_BACK don't exists. I think they key you are looking for is KEY_PLAY. Also, you don't need the 4s or 12s or any s because that means it keeps the key pushed for X seconds. You only need to press it.

So it should be "command": "KEY_PLAY"

If you want to have a bigger delay before pressing play, let's say 5 seconds you can do it like this:
"command": "DELAY*5s,KEY_PLAY"

**Comment by Danlipanovich** [comment]
How do I download them?

________________________________
מאת: Octavian Ruda ***@***.***>
נשלח: יום שני, מאי 9, 2022 4:10 אח׳
אל: tavicu/homebridge-samsung-tizen ***@***.***>
עותק: Danlipanovich ***@***.***>; Author ***@***.***>
נושא: Re: [tavicu/homebridge-samsung-tizen] play button after openning the app (Issue #522)


I’m homebridge is shows a comment 401 unauthorized

That's probably from SmartThings API since you have the volume. https://github.com/tavicu/homebridge-samsung-tizen/wiki/SmartThings-Setup

Without logs I cannot help you

**Comment by tavicu** [comment]
You need to start Homebridge in Debug mode. https://github.com/tavicu/homebridge-samsung-tizen/wiki/Common-Issues#how-to-open-a-new-issue

Then follow the console when you toggle the Switch.

**Comment by Danlipanovich** [comment]
JUST  NOTICES THAT THE COMMAND ITSELF SHOWN ONLY IN CONFIG AND NOT UN THE PLUGIN SETTINGS' COULD BE RELEVANT?

**Comment by tavicu** [comment]
Hi.

I'm sorry but the logs you posted are not related to the plugin. There are just the first logs of the server starting.

Also you didn't post your config so I can see it.

At this point I don't know how to help you without showing me at least the config section :)

**Comment by ElphaX** [comment]
An easy way to share logs would be to temporarily disable other plugins (if you don't have too many) and share the entire log with config. We should be able to find the culprit that way :)

**Comment by Danlipanovich** [comment]
> Hi.
> 
> I'm sorry but the logs you posted are not related to the plugin. There are just the first logs of the server starting.
> 
> Also you didn't post your config so I can see it.
> 
> At this point I don't know how to help you without showing me at least the config section :)



> An easy way to share logs would be to temporarily disable other plugins (if you don't have too many) and share the entire log with config. We should be able to find the culprit that way :)
"platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "devices": [
                {
                    "api_key": "f047dafb-95ac-4887-8fca-64de5e8f119d",
                    "device_id": "d9d6a68b-b9c6-58b5-3224-a623dc73a654",
                    "name": "Samsung TV",
                    "ip": "192.168.1.133",
                    "mac": "80:47:86:28:db:85",
                    "inputs": [
                        {
                            "type": "app",
                            "name": "Netflix",
                            "value": "3201907018807"
                        },
                        {
                            "type": "app",
                            "name": "YouTube",
                            "value": "111299001912"
                        },
                        {
                            "type": "app",
                            "name": "Internet",
                            "value": "3201907018784"
                        },
                        {
                            "type": "app",
                            "name": "Spotify",
                            "value": "3201606009684"
                        },
                        {
                            "type": "command",
                            "name": "Xbox",
                            "value": "KEY_HDMI,"
                        }
                    ],
                    "switches": [
                        {
                            "name": "Morning Mood",
                            "power": true,
                            "app": "3201606009684",
                            "volume": 12,
                            "command": "DELAY*5S,KEY_PLAY"
                        }
                    ]
                },
                {
                    "device_id": "a05959d5-9997-4fc7-bf13-77fa7d75d0c0",
                    "name": "Dan TV",
                    "ip": "192.168.1.201",
                    "mac": "d0:d0:03:c6:f0:c3",
                    "inputs": [
                        {
                            "type": "app"
                        }
                    ]
                },
                {
                    "inputs": [
                        {
                            "type": "app"
                        }
                    ]
                }
            ],
            "platform": "SamsungTizen"
        },

**Comment by Danlipanovich** [comment]
> Hi.
> 
> I'm sorry but the logs you posted are not related to the plugin. There are just the first logs of the server starting.
> 
> Also you didn't post your config so I can see it.
> 
> At this point I don't know how to help you without showing me at least the config section :)

the only  log is this  even that everything else works[5/31/2022, 2:51:53 PM] [Samsung TV] 401 - Unauthorized

**Comment by tavicu** [comment]
> the only log is this even that everything else works[5/31/2022, 2:51:53 PM] [Samsung TV] 401 - Unauthorized

That is an error returned by SmartThings API. Follow this guide, step by step, word by word! :)
https://github.com/tavicu/homebridge-samsung-tizen/wiki/SmartThings-Setup
