### ISSUE TITLE
Possibility to get TV as switch

### ISSUE THREAD

**Issue by McDin** [tavicu/homebridge-samsung-tizen#524]
Hi,

I'm using this plugin to automate such things depending on Frames Status (Power, Art Mode). Now I want to use Home+ 5. Because TV accessories are not shown in third party plugins I want to ask you if it is possible to use this plugin not as TV accessory but as single switches.

Thank you very much and best regards.

**Comment by McDin** [comment]
Thanks for the reply. I can't see the two switches. Only in original Home App. I think that is caused that they are provided within the TV accessory and not separate switches.

**Comment by tavicu** [comment]
> Thanks for the reply. I can't see the two switches. Only in original Home App. I think that is caused that they are provided within the TV accessory and not separate switches.

Hmm, but this doesn't make sense. Because the TV is just a bridge like any other bridge (the main homebridge for example) which contains the TV accessory + separate switches.
Probably because it sees the type of the bridge as TV and then it just ignore it and everything that is added to the bridge.
