### ISSUE TITLE
Side volume buttons don’t work

### ISSUE THREAD

**Issue by mafyata** [tavicu/homebridge-samsung-tizen#526]
Do you know how can I control TV volume? Side buttons don’t work. Other buttons work.  They worked before 3 months. Nothing changed in homebridge config file.
Restart don’t resolve the issue. 
Latest veraion of homebridge and samsung tizen, ios 15.5
![06E4D360-4A33-40C9-BB8D-12F12303E97B](https://user-images.githubusercontent.com/48009267/170867015-5d89b41f-13e8-4791-8483-13b4d18478e3.jpeg)

**Comment by engigeer** [comment]
Are you able to share any details on what resolve this issue for you? I have experienced similar behaviour (volume control stops working) several times in the last few weeks/months. Issue has occurred primarily on a Samsung 2021 Frame TV but also occurred once on a Samsung 2020 TU7000. Issue is only resolved after removing accessory from Apple home app and adding it back. Not a huge pain, but would be curious to know if there is a better resolution. Onset of issue is potentially associated with changing volume of content that is streaming via airplay, but hard to pinpoint if this is just a coincidence. Once issue occurs, it persists across all content until the accessory is removed and added back. Thanks!

**Comment by mafyata** [comment]
Restart my iPhone :)

**Comment by fate8383** [comment]
> Restart my iPhone :)

The same thing solved my problem :) it was funny because all buttons worked except the volume side once so didn't come to my mind reboot is needed
