### ISSUE TITLE
App ID request

### ISSUE THREAD

**Issue by SydProom** [tavicu/homebridge-samsung-tizen#527]
Could you please find the ID for the "Blackdove" app on Samsung TVs? I have had trouble getting the Tizen Studio to work. Thanks

**Comment by tavicu** [comment]
It will help if you tell us from what region you are. Because not all apps are available everywhere :)

**Comment by SydProom** [comment]
Apologies, I'm in the UK :)

**Comment by tavicu** [comment]
Cool, I have my TV set to UK region, I will try to find the app and install it :)

**Comment by tavicu** [comment]
[20 - Blackdove Video Art]
- App Name                            :     Blackdove Video Art
- App Version                         :     3.0.1
- App ID - WAS                        :     3201705012375
- App ID - Tizen                      :     hHgh0bbLZf.BlackDoveTizenApp

So it is `3201705012375`

Let me know if it works

**Comment by SydProom** [comment]
Works perfectly, cheers for the speedy response :)
