### ISSUE TITLE
Homebridge shows a speaker, but not exposed to Home.app

### ISSUE THREAD

**Issue by neekul** [tavicu/homebridge-samsung-tizen#536]
So after my projector (Tizen) stopped responding, I decided to start fresh.
How I can see in the Accessories tab (Homebridge web ) a "speaker" called Projector Volume next to my Projector.

This indeed toggles (mute / unmute) my projector but this doesn't show up in Home.app.
The projector with inputs works fine. However using Home.app to turn on the projector starts it without sound (should connect tot he soundbar). I noticed if I use the Homebridge "Speaker" to mute the Projector then start it (via Accessories / Home.app) it immediately connects to my soundbar (like using the regular remote).

What is this "Speaker" that has shown up in Homebridge Accessories? It's no where in the config...

**Comment by tavicu** [comment]
Hi.

Sorry for the late response.
Config UI and iOS uses things differently. In iOS you can control the volume from the Control Center Remote.

The plugin only sends a turn on command to the TV. It doesn't have the capability to select the speaker output. Looks like a problem on Samsung which I can't help you with unfortunately.

**Comment by neekul** [comment]
> Hi.
> 
> Sorry for the late response. Config UI and iOS uses things differently. In iOS you can control the volume from the Control Center Remote.
> 
> The plugin only sends a turn on command to the TV. It doesn't have the capability to select the speaker output. Looks like a problem on Samsung which I can't help you with unfortunately.

No problem on the late rely! The plugin is otherwise flawless, so you're already providing your skills (for free!) for the benefit of the community!

Maybe it's something Samsung that means turning it on via Homebridge / Home.app sometimes it just mutes and needs a restart / sometimes it just works as it's supposed to and I get audio from my soundbar. I can live with it ;)
