### ISSUE TITLE
TV Accessory Temporarily Goes Away on Router Restart or Power Outage

### ISSUE THREAD

**Issue by jackklink** [tavicu/homebridge-samsung-tizen#537]
Whenever I have a power outage and my router restarts, my television accessories remove themselves and then add themselves back upon restart. This causes any automations that use the television accessories to get deleted. I have to remake them every single time the power goes out or the router is restarted

Any advice? This doesn’t happen with any other homebridge accessories.

Thanks

**Comment by tavicu** [comment]
Hi.

Sounds like your problem comes from the router.
But from what you described I don't know what to suggest and check other than make sure your IPs are set to static in DHCP.
You could also set an interval for ports on homebridge to use for other bridges lile this:
```
{
    "bridge": {
        "name": "Main Bridge",
        "username": "*****",
        "port": 51500,
        "pin": "****",
        "advertiser": "bonjour-hap"
    },
    "ports": {
        "start": 51510,
        "end": 51550
    },
    ...
}
```

I never hear of something like this (to unpair then pair again).
The plugin is using a function from Homebridge to declare the accessory.

**Comment by tavicu** [comment]
@scottleestrange do you also have this problem?

Does the homebridge server have static IP?

**Comment by scottleestrange** [comment]
I was commenting because I never have seen the problem

And yes, I have two home bridge servers and both have static IP's

**Comment by QDUNI** [comment]
I have the same problem, the tv disappears and sometimes pops back up in the app with no response. Deleting and adding doesn't do the trick.

**Comment by tavicu** [comment]
Since @jackklink was not responding, I will close this issue.

**Comment by jackklink** [comment]
Hey sorry I disappeared on this! For some reason, GitHub stopped emailing me when there were updates to threads.

This issue did appear to go away without my really doing anything so I will let you know if it happens again and try to provide more details as well. Thanks to everyone for being so responsive.
