### ISSUE TITLE
Application Code for “IPTV Smarters” on Samsung’s Tizen App Store

### ISSUE THREAD

**Issue by JManuMartinez** [tavicu/homebridge-samsung-tizen#538]
Hello,
It should be nice if you can extract and document the app code for the app “IPTV Smarters” from the Samsung’s Tizen App Store.
Thanks before hand and best wishes.
Jose Manuel

**Comment by tavicu** [comment]
Hi Manuel,

It will help if you tell us your country :)
Not all apps are available everywhere

**Comment by JManuMartinez** [comment]
Hello,
Sorry, Spain, thanks.
Best wishes.

**Comment by tavicu** [comment]
Hei @JManuMartinez ,

I can see there is also a Pro app.

Here are the ids. Please try them and let me know if it works so I could add them to the list :)

3201812017585 - IPTV Smarters
3202009021808 - IPTV Smarters Pro

**Comment by JManuMartinez** [comment]
Hello again,
IPTV Smarters pro works!
I cannot check remotely IPTV Smarters because I’ve not installed the app from store and I have not prepare plug-in yet for remote control and move around all of the options up to arrive at the store and try to install it before launching.
Smarthings don’t let me install apps from the store.
I will try it and give the feedback here when I can test it.
I suppose it works as fine as pro version does.
Thanks for all and best wishes.

**Comment by tavicu** [comment]
Thank you for confirmation.

I have added them to the Wiki :)
