### ISSUE TITLE
Smart Monitor control works just like a TV but doesn't show up in HomeKit

### ISSUE THREAD

**Issue by alikhodrali** [tavicu/homebridge-samsung-tizen#539]
Hi there, I've attempted to pair my Samsung M8 Smart monitor to HomeBridge, and it worked well, surprisingly. I can control the device, see the input and send commands to it just fine from the HomeBridge UI, the same as I can with my TVs. My only issue is that the device does not show up in HomeKit for some odd reason. I tried setting the UUID to something else, but it didn't work. I've also tried to change "Type" under "Advanced Configuration" to "Default" and to "Legacy", but to no avail. Please help me, any help would be greatly appreciated. Also thanks for making this plugin, this is my third Samsung Screen that I'm able to add in thanks to you!

**Comment by tavicu** [comment]
Hi @alikhodrali ,

Did you follow the instructions from the Wiki?
After you add the TV to Homebridge you also have to add the TV to Home app.
For every TV a separate bridge will be created.

https://github.com/tavicu/homebridge-samsung-tizen/wiki/Installation#6-adding-the-tv-to-home-app

**Comment by alikhodrali** [comment]
Sorry for opening this issue. That solved it for me! It's 4AM here, and it seems that forgot to do that. It's working now though. Thank you🙏🏽
