### ISSUE TITLE
CEC inputs

### ISSUE THREAD

**Issue by albinmedoc** [tavicu/homebridge-samsung-tizen#542]
My TV doesn't support SmartThings...
I still want to use the input feature of course 😆

This can be possible by using CEC commands instead. 

I have found this homebridge plugin, [homebridge-cec-tv-control](https://github.com/electroflame/homebridge-cec-tv-control) that is working fine for changing inputs using CEC. 

It would be great having this feature integrated into this plugin, having a single accessory for the TV.

**Comment by tavicu** [comment]
Hi.

The CEC "feature" will not be implemented since it's required that your homebridge server to be connected to HDMI.

Why do you say your tv is not compatible with SmartThings? From what I know all TVs that support this plugin also works with SmartThings. Which model your TV is?

Other option for you is to use commands and send a list of instructions for inputs. You can see examples over here: https://github.com/tavicu/homebridge-samsung-tizen/issues/50#issuecomment-478863884

**Comment by albinmedoc** [comment]
This is the information about my TV.
It´s not listed at supported TVs in the SmartThings-app

```json
{
  "id": "uuid:ad87a8e3-ead5-42d3-92fc-05febfe6bb6a",
  "name": "[TV] TV Vardagsrum",
  "version": "2.1.0",
  "device": {
    "type": "Samsung SmartTV",
    "duid": "uuid:ad87a8e3-ead5-42d3-92fc-05febfe6bb6a",
    "model": "16_JAZZL_UHD_BASIC",
    "modelName": "UE55KU6075",
    "description": "Samsung DTV RCR",
    "networkType": "wireless",
    "ssid": "58:cb:52:d7:80:2b",
    "ip": "192.168.86.209",
    "firmwareVersion": "Unknown",
    "name": "[TV] TV Vardagsrum",
    "id": "uuid:ad87a8e3-ead5-42d3-92fc-05febfe6bb6a",
    "udn": "uuid:ad87a8e3-ead5-42d3-92fc-05febfe6bb6a",
    "resolution": "3840x2160",
    "countryCode": "SE",
    "msfVersion": "2.1.0",
    "smartHubAgreement": "true",
    "VoiceSupport": "false",
    "GamePadSupport": "true",
    "wifiMac": "E4:7D:BD:9D:2C:28",
    "developerMode": "0",
    "developerIP": "",
    "OS": "Tizen"
  },
  "type": "Samsung SmartTV",
  "uri": "http://192.168.86.209:8001/api/v2/",
  "remote": "1.0",
  "isSupport": "{\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"false\",\"DMP_available\":\"true\",\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"EDEN_available\":\"true\"}"
}
```

**Comment by tavicu** [comment]
Very strange. I can see by your model number that the TV is 6-series.
I also have a 6-series TV and it's working just fine with SmartThings (except the power on).

It may be something related to your country because I can see that model is specific from one region.

**Comment by albinmedoc** [comment]
Okey, thats strange...

How about adding a feature so when selecting an input a terminal script is ran? Then we could use [cec-utils](https://gist.github.com/rmtsrc/dc35cd1458cd995631a4f041ab11ff74) to change HDMI-input.

**Comment by albinmedoc** [comment]
I contacted the Samsung support to figure out what was wrong. I found out that I was not signed in to my Samsung account on the TV and was therefor not visible in SmartThings. 

I thought I had to search for the TV in the app....

Now I can use the SmartThings API to control the TV.

I still think the idea of running shell script on inputs would be a good feature.

**Comment by tavicu** [comment]
Glad you figure it out :)

> I still think the idea of running shell script on inputs would be a good feature.

The plugin is aimed to all users, including the ones that don't have programming skills.
Someone who create it's own shell scripts can also modify the plugin to do what they want :)
We can't cover any request that everybody have for their specific scenario, we try to cover the most important and demanding ones.
