### ISSUE TITLE
"123" Key Code

### ISSUE THREAD

**Issue by alessamndro** [tavicu/homebridge-samsung-tizen#544]
I'm trying to map the 123 key of my remote, the one just below the power button, see this [link](https://images.eprice.it/nobrand/0/Lightbox/926/207402926/AF9673B1-C883-4EB0-9A28-E93F56DFDD91.jpg) for reference, but I can't find anywhere the key code associated with it (if it even exists). Is anyone been able to remap one of the remote control keys to this specific button? 

Thanks in advance

**Comment by tavicu** [comment]
I don’t think there is a key for that since it’s just opening an overlay with keys from 0 to 9.

you can call KEY_1 for example, no need to open the overlay first :)

**Comment by alessamndro** [comment]
I didn't think either, I looked through the samsung dev docs without finding anything. The reason I wanted that specific key code was to set it as the "i" key on the remote control in the iOS control center to have all basic functionality there (the four arrows, select, home, back and the 123 key to open the overlay to then manage channels with the arrows). I know I can use the arrows and map them as program up and down but I would lose functionality within apps not having the arrows. Unfortunately that's the only way I can think of doing it, I don't know if there's some workaround for this thing.
