### ISSUE TITLE
Samsung TV cannot be added to Home app

### ISSUE THREAD

**Issue by sleehpy** [tavicu/homebridge-samsung-tizen#546]
hi,

i had this working, but recently i tried someting where i deleted the plugin, and now i want to re-add the TV to be available in the Home app for other to control.
But i cannot add it. 
Checked how i can add it, also checked a lot of people complaining about this, but i've tried everything, setting the new UUID, also deleting everything and re-adding again, does not work.
Now i'm really out of options here, can someone help me with this? I would really like to add the TV back to Home.
Also me: i can control the TV from the homebridge UI just fine, almost perfectly with no issues whatsoever, only Home does not let me add it.

logs here: https://pasteio.com/xdt9RaYaFWwD

**Comment by Knullack** [comment]
Same, I can control the TV ON/OFF but do not see it in Home IOS or MAC app

**Comment by sleehpy** [comment]
Well, today I checked again and it showed up in the add accessory screen and also I could add it as well. I don’t know why it it’s working not, but I’m happy :)
