### ISSUE TITLE
Voice input Volume

### ISSUE THREAD

**Issue by entoryFB** [tavicu/homebridge-samsung-tizen#551]
With the command "TV louder" comes the question : What value. However, none can be entered. It used to make the volume louder in the step specified in the config
Thanks

**Comment by tavicu** [comment]
Hi.
I don't understand exactly what you are trying to achieve but you can create a custom switch that increase the volume with a value you want.

For example: `KEY_VOLUP*10`

**Comment by entoryFB** [comment]
My config 
"'name"':"lauter"
"command"': "KEY VOLUP*2"

Previously, 'hey Siri TV louder' would increase the volume. Now the response is 'please enter value'.

**Comment by tavicu** [comment]
I can see from your post that the `name` is `lauter` not `lauder`. Maybe that's why.
