### ISSUE TITLE
Showmax application code

### ISSUE THREAD

**Issue by ThunderMild** [tavicu/homebridge-samsung-tizen#554]
```
- App Name: Showmax
- App Version: 2.0.0
- App ID - WAS: 3201506002963
```

[Showmax](https://www.showmax.com/) is a popular streaming service used in South Africa.

Thanks for all the hard work you've put in, it's been a blast playing with this plugin :)

**Comment by tavicu** [comment]
Hi @ThunderMild 
Thank you very much.

I have added the app to the list :)
