### ISSUE TITLE
Samsung Tizen running on random port makes it impossible to allow through firewall

### ISSUE THREAD

**Issue by iUnstable0** [tavicu/homebridge-samsung-tizen#555]
As the title said, Samsung Tizen running on random port makes it impossible to allow through firewall

Please fix this, I need to enable ufw for security but Samsung tixen wont work because it runs on different port everytime

**Comment by tavicu** [comment]
The plugin don't decide which port to use, Homebridge does.
And you can control that from the config.

Example:
```
{
    "bridge": {
        ...
    },
    "ports": {
        "start": 51510,
        "end": 51550
    },
    "description": "",
    "accessories": [],
    "platforms": []
}
```
