### ISSUE TITLE
Child bridge not showing properly

### ISSUE THREAD

**Issue by samwhu30** [tavicu/homebridge-samsung-tizen#558]
Hi,

I am trying to make my teles in child bridges to improve reliability as I have had problems recently. 

I have created the child bridge and added it to my Home and I can now see my tele in devices.

When I go to setting and check on the Samsung bridge, it doesn't show any devices connected to that specific bridge, every other bridge I have will say how many devices are connected.

Cheers,
Sam
![IMG_C1EE75DBFE67-1](https://user-images.githubusercontent.com/52747199/185095312-0d60ee34-2ef6-4205-b110-5578372652f6.jpeg)

**Comment by tavicu** [comment]
The plugin already create a child bridge for every TV.
No need to use child bridge for the plugin.

**Comment by qoodanny** [comment]
The Tv will not show up in Home App even it is in main bridge

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/wiki/Installation#6-adding-the-tv-to-home-app
