### ISSUE TITLE
New application IDs (for Netherlands/Dutch people)

### ISSUE THREAD

**Issue by HueZuX** [tavicu/homebridge-samsung-tizen#563]
[TMobile TV]
- App Name                            :     TMobile TV
- App Version                         :     1.0.16
- App ID - WAS                        :     3202008021516
- App ID - Tizen                      :     OyP0deWouM.SamsungSmartTV

[Videoland]
- App Name                            :     Videoland
- App Version                         :     3.1.81
- App ID - WAS                        :     3201810017074
- App ID - Tizen                      :     ESMP8SBFDH.videoland

[TL XL (nieuw)]
- App Name                            :     RTL XL (nieuw)
- App Version                         :     3.0.43
- App ID - WAS                        :     3201906018642
- App ID - Tizen                      :     8MWN8DJJB4.rtlxl

[NPO]
- App Name                            :     NPO
- App Version                         :     1.16.20
- App ID - WAS                        :     3201706014250
- App ID - Tizen                      :     qvVcLChmPo.NPO

[NLZIET]
- App Name                            :     NLZIET
- App Version                         :     5.1.0
- App ID - WAS                        :     3202012022421
- App ID - Tizen                      :     azFWqejcXJ.NLZiet

[Viaplay]
- App Name                            :     Viaplay
- App Version                         :     3.2.11
- App ID - WAS                        :     11111300404
- App ID - Tizen                      :     niYSnzL6h1.Viaplay

[Pathe Thuis]
- App Name                            :     Pathe Thuis
- App Version                         :     2.0.7
- App ID - WAS                        :     3201506003175

Would be nice if these applications can be added in the list of inputs :) Those are some Dutch apps for the Samsung Tizen TV's. I already have seen that there were a few Dutch apps in the input list and the ones I have here can be added in there too!
- App ID - Tizen                      :     0yc8StEOG6.PatheThuis

**Comment by tavicu** [comment]
Hei @HueZuX ,

I have updated the list with the missing apps.

Thank you :)
