### ISSUE TITLE
Volume switch exists in homebridge, but not in the homeApp

### ISSUE THREAD

**Issue by bojomojo** [tavicu/homebridge-samsung-tizen#571]
Hello,
I can see the volume switch (that mutes the TV) by default in the accessory list on homebridge, and it works just fine.
But it does not show on the home app.

On the home app I have:
- A generic switch for the Power on/of
- Art Mode switch
- Total power switch
- An iphone with The Frame on it (see screenshot)
![IMG_D79FFA1F509D-1](https://user-images.githubusercontent.com/62281574/193218988-8ebf1ea4-da16-4b04-a38b-eafddce11d3f.jpeg)

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/issues/536
