### ISSUE TITLE
[Feature Request] Add volume control in the Home app using a workaround as Light Slider

### ISSUE THREAD

**Issue by nefariouslegion** [tavicu/homebridge-samsung-tizen#577]
Hi,
I just wanted to request a feature. I know of a plugin for LG TVs that have volume control within the Home app by adding it as a Light Slider. I'm wondering if it's possible to add this to this plugin for Tizen TVs. It'd be cool to be able to control volume without having to switch to the Apple Remote app

**Comment by tavicu** [comment]
Hi. Samsung API don't offer informations regarding the volume so it will not be possible to do something like that unfortunately
