### ISSUE TITLE
Add new buttons to Remote app on iOS devices

### ISSUE THREAD

**Issue by samalero** [tavicu/homebridge-samsung-tizen#579]
Hello.

Can you add source button, mute button and power button (top 3 buttons) to the layout of Remote app on iOS devices?
![IMG_2874](https://user-images.githubusercontent.com/11965241/198155240-48eab0c3-a267-4f36-bfd9-22543587aac9.jpeg)

**Comment by tavicu** [comment]
Hi. That's not possible. HomeKit don't offer this option, only to map existing buttons to do something, but can't change buttons.
