### ISSUE TITLE
Unable to connect with samsung ue55ks9000

### ISSUE THREAD

**Issue by kajz3reczka** [tavicu/homebridge-samsung-tizen#58]
Hi, I can reach connection with TV :( 

Here is a debug log: https://pastebin.com/x9cvfDw2

Strange is that when Homebridge return message: "Pair failed. Make sure you click Allow on the TV!" I can turn tv off and on from home app. But it works occasionally.

```
{
  "id": "uuid:8584733c-147f-42f3-b2e9-33aa7e700c95",
  "name": "[TV] Home",
  "version": "2.1.0",
  "device": {
    "type": "Samsung SmartTV",
    "duid": "uuid:8584733c-147f-42f3-b2e9-33aa7e700c95",
    "model": "16_JAZZM_UHD",
    "modelName": "UE55KS9000",
    "description": "Samsung DTV RCR",
    "networkType": "wireless",
    "ssid": "38:43:7d:41:d4:ff",
    "ip": "192.168.0.122",
    "firmwareVersion": "Unknown",
    "name": "[TV] Home",
    "id": "uuid:8584733c-147f-42f3-b2e9-33aa7e700c95",
    "udn": "uuid:8584733c-147f-42f3-b2e9-33aa7e700c95",
    "resolution": "3840x2160",
    "countryCode": "PL",
    "msfVersion": "2.1.0",
    "smartHubAgreement": "true",
    "VoiceSupport": "true",
    "GamePadSupport": "true",
    "wifiMac": "C0:97:27:19:09:B2",
    "developerMode": "0",
    "developerIP": "",
    "OS": "Tizen"
  },
  "type": "Samsung SmartTV",
  "uri": "http://192.168.0.122:8001/api/v2/",
  "remote": "1.0",
  "isSupport": "{\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\",\"DMP_available\":\"true\",\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"EDEN_available\":\"true\"}"
}
```

and my config.json
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "This is an example configuration file.",

    "accessories": [
    ],

    "platforms": [
        {
            "platform": "SamsungTizen",
            "devices": [
                {
                    "name": "Bedroom TV",
                    "ip": "192.168.0.122",
                    "mac": "c0:...:b2",
                    "token": ""
                }
            ]
        }
    ]
}
```

**Comment by tavicu** [comment]
Hi, your tv is not using the method to pair with a token.
It may use the PIN method.

Please get the demo from here and try to see if it works https://github.com/tdudek/samsung-remote-models-2014-and-newer

**Comment by kajz3reczka** [comment]
@tavicu demo returns error. I got pin from tv, then I put this pin to textfield and clicked "Confirm" button.

**Comment by ivnDeb11** [comment]
Hi! I'm Spanish, sorry if my English is bad :p I have the same problem, with HomeBridge my Samsung KS7000UXXC no return PIN, but with this sample: https://github.com/tdudek/samsung-remote-models-2014-and-newer, yes... but returns error when I click confirm to pair.

You have any idea?

Log HomeBridge

2019-2-8 14:10:57] [Comedor TV] Trying to pair the TV
[2019-2-8 14:10:57] [Comedor TV] [DEBUG] Pair to wss://192.168.1.135:8002/api/v2/channels/samsung.remote.control?name=Q29tZWRvciBUVg==
[2019-2-8 14:10:57] [Comedor TV] [DEBUG] { id: '5a2b9b40-2bab-11e9-a6c7-211916455358',
  clients: 
   [ { id: '5a2b9b40-2bab-11e9-a6c7-211916455358',
       connectTime: 1549635056373,
       attributes: [Object],
       deviceName: 'Q29tZWRvciBUVg==',
       isHost: false } ] }


Thanks!

**Comment by ivnDeb11** [comment]
> Hi, your tv is not using the method to pair with a token.
> It may use the PIN method.
> 
> Please get the demo from here and try to see if it works https://github.com/tdudek/samsung-remote-models-2014-and-newer

Hi @tavicu this problem is solved? Thanks!!

**Comment by mmmrvn** [comment]
Hi @tavicu, how exactly do you run https://github.com/tdudek/samsung-remote-models-2014-and-newer? Completely newbie here using a Mac

**Comment by tavicu** [comment]
That’s not my repo. Ask there please

**Comment by mmmrvn** [comment]
> That’s not my repo. Ask there please

I know but the owner seems to have been inactive for a year now, and there aren't any instructions for beginners on how to run his demo. Since you recommended using it, I thought you might be able to help me out
