### ISSUE TITLE
New App IDs

### ISSUE THREAD

**Issue by Mikunics** [tavicu/homebridge-samsung-tizen#593]
Was wondering why my Disney+ wasn't working and it turns out that my version of Disney+ has a different ID (maybe because I live in the Philippines and its the SEA version?) anywhere here are some new App IDs I found out:

[ 3 - Disney+]
- App Name                            :     Disney+
- App Version                         :     2.0.2
- App ID - WAS                        :     3202009021709
- App ID - Tizen                      :     AwJZqXfE51.DisneyPlusHotstar

[ 13 - iQIYI]
- App Name                            :     iQIYI
- App Version                         :     3.5.1
- App ID - WAS                        :     3202006020934
- App ID - Tizen                      :     H16FaQOxRQ.iQIYI

[ 14 - iWantTFC]
- App Name                            :     iWantTFC
- App Version                         :     1.4.4
- App ID - WAS                        :     3201910019513
- App ID - Tizen                      :     k8v3scpLmy.TFC

[ 15 - Viu]
- App Name                            :     Viu
- App Version                         :     2.1.0
- App ID - WAS                        :     3201807016555
- App ID - Tizen                      :     TOSXgdzhCp.Viu

[ 16 - HBO GO Asia]
- App Name                            :     HBO GO Asia
- App Version                         :     59.0.745
- App ID - WAS                        :     3202004020575
- App ID - Tizen                      :     tvhykAYCgz.hbogo

All these should fall on the newer TVs column

**Comment by tavicu** [comment]
Thank you @Mikunics ,

I have added/updated the IDs
