### ISSUE TITLE
App id -WAS i missing

### ISSUE THREAD

**Issue by Nystro0m** [tavicu/homebridge-samsung-tizen#595]
Hi, im trying to find out some ID's from my tv.

Ive connected by Tizen Device manager byt my Web app list looks not that promising.
The correct App ID is missing, the "-WAS" is not in the list.
Any ideas?

`[ 1 - MorningBrief ]
- Name                                :     MorningBrief
- Version                             :     2.0.8
- GUID                                :     http://YourDomain.com/YourApp
- Package ID                          :     1234567890
- App ID                              :     1234567890.MorningBrief
-----------------------------------------------------------------------------------------------------
[ 2 - Red ]
- Name                                :     Red
- Version                             :     Bull
- GUID                                :     TV
- Package ID                          :     12.1.54
- App ID                              :     http://redbulltv.redbull.com/RedbullApp
-----------------------------------------------------------------------------------------------------
[ 3 - SVT ]
- Name                                :     SVT
- Version                             :     Play
- GUID                                :     2.0.1
- Package ID                          :     http://svt.se/svtplay
- App ID                              :     5exPmCT0nz
-----------------------------------------------------------------------------------------------------
[ 4 - C ]
- Name                                :     C
- Version                             :     More
- GUID                                :     7.0.1
- Package ID                          :     http://www.cmore.se
- App ID                              :     7fEIL5XfcE
-----------------------------------------------------------------------------------------------------
[ 5 - TwitchTV ]
- Name                                :     TwitchTV
- Version                             :     1.1.0
- GUID                                :     https://github.com/Gesha87/TwitchTV
- Package ID                          :     8m7wyPjHXD
- App ID                              :     8m7wyPjHXD.TwitchTV
-----------------------------------------------------------------------------------------------------
[ 6 - YouTube ]
- Name                                :     YouTube
- Version                             :     2.1.490
- GUID                                :     http://yourdomain/YouTube
- Package ID                          :     9Ur5IzDKqV
- App ID                              :     9Ur5IzDKqV.TizenYouTube
-----------------------------------------------------------------------------------------------------
[ 7 - Storytel ]
- Name                                :     Storytel
- Version                             :     1.0.1
- GUID                                :     http://www.storytel.com
- Package ID                          :     9wFXFo5DYv
- App ID                              :     9wFXFo5DYv.tizentest
-----------------------------------------------------------------------------------------------------
[ 8 - Disney+ ]
- Name                                :     Disney+
- Version                             :     22.21.0
- GUID                                :     https://www.disneyplus.com/tizen
- Package ID                          :     MCmYXNxgcu
- App ID                              :     MCmYXNxgcu.DisneyPlus
-----------------------------------------------------------------------------------------------------
[ 9 - DisneyPlusPreviewService ]
- Name                                :     DisneyPlusPreviewService
- Version                             :     22.21.0
- GUID                                :     https://www.disneyplus.com/tizen
- Package ID                          :     MCmYXNxgcu
- App ID                              :     MCmYXNxgcu.DisneyPlusService
-----------------------------------------------------------------------------------------------------
[ 10 - Epop-JazzUHD ]
- Name                                :     Epop-JazzUHD
- Version                             :     11.15.1
- GUID                                :     http://yourdomain/jazzUHD
- Package ID                          :     PiHS3iydgf
- App ID                              :     PiHS3iydgf.SmartTV
-----------------------------------------------------------------------------------------------------
[ 11 - Netflix ]
- Name                                :     Netflix
- Version                             :     6.0.003
- GUID                                :     http://yourdomain/Netflix
- Package ID                          :     RN1MCdNq8t
- App ID                              :     RN1MCdNq8t.Netflix
-----------------------------------------------------------------------------------------------------
[ 12 - e-Manual ]
- Name                                :     e-Manual
- Version                             :     1.1.3
- GUID                                :     http://yourdomain/Emanual
- Package ID                          :     VjcErbjAjH
- App ID                              :     VjcErbjAjH.Emanual
-----------------------------------------------------------------------------------------------------
[ 13 - App ]
- Name                                :     App
- Version                             :     Launcher
- GUID                                :     3.2.10
- Package ID                          :     http://yourdomain/MultiScreenWebLauncher
- App ID                              :     aQjWjLsPaO
-----------------------------------------------------------------------------------------------------
[ 14 - [NULL] ]
- Name                                :     [NULL]
- Version                             :     0.10.59
- GUID                                :     http://www.sra.samsung.com/
- Package ID                          :     adplatform
- App ID                              :     adplatform.ADPlayer
-----------------------------------------------------------------------------------------------------
[ 15 - TV4 ]
- Name                                :     TV4
- Version                             :     Play
- GUID                                :     1.1.0
- Package ID                          :     https://tv4play.se
- App ID                              :     cczN3dzcl6
-----------------------------------------------------------------------------------------------------
[ 16 - HBO ]
- Name                                :     HBO
- Version                             :     Max
- GUID                                :     52.50.0
- Package ID                          :     https://secure.hbomax.com/hbomax
- App ID                              :     cj37Ni3qXM
-----------------------------------------------------------------------------------------------------
[ 17 - HBO ]
- Name                                :     HBO
- Version                             :     Max
- GUID                                :     Worker
- Package ID                          :     52.50.0
- App ID                              :     https://secure.hbomax.com/hbomax
-----------------------------------------------------------------------------------------------------
[ 18 - Amazon ]
- Name                                :     Amazon
- Version                             :     Video
- GUID                                :     1.2.1
- Package ID                          :     http://yourdomain/AmazonIgnitionLauncher2
- App ID                              :     evKhCgZelL
-----------------------------------------------------------------------------------------------------
[ 19 - PrivacyChoices ]
- Name                                :     PrivacyChoices
- Version                             :     0.0.85
- GUID                                :     http://yourdomain/PrivacyChoices
- Package ID                          :     jLU2jKvbyN
- App ID                              :     jLU2jKvbyN.PrivacyChoices
-----------------------------------------------------------------------------------------------------
[ 20 - Viaplay ]
- Name                                :     Viaplay
- Version                             :     3.2.10
- GUID                                :     http://viaplay.tv/Viaplay
- Package ID                          :     niYSnzL6h1
- App ID                              :     niYSnzL6h1.Viaplay
-----------------------------------------------------------------------------------------------------
[ 21 - discovery+ ]
- Name                                :     discovery+
- Version                             :     1.0.8
- GUID                                :     http://yourdomain/whiteLabelTal
- Package ID                          :     pIaMf8YZyZ
- App ID                              :     pIaMf8YZyZ.whiteLabelTal
-----------------------------------------------------------------------------------------------------
[ 22 - ExtraTweetIM2 ]
- Name                                :     ExtraTweetIM2
- Version                             :     4.2.22
- GUID                                :     http://yourdomain/ExtraTweetIM2
- Package ID                          :     phm0eEdRZ4
- App ID                              :     phm0eEdRZ4.ExtraTweetIM2
-----------------------------------------------------------------------------------------------------
[ 23 - SF ]
- Name                                :     SF
- Version                             :     Anytime
- GUID                                :     6.1.4
- Package ID                          :     http://sfanytime.com
- App ID                              :     sntmlv8LDm
-----------------------------------------------------------------------------------------------------
[ 24 - HBO ]
- Name                                :     HBO
- Version                             :     7.13.3
- GUID                                :     http://hbonordic.com
- Package ID                          :     u5Sh825pOW
- App ID                              :     u5Sh825pOW.app
-----------------------------------------------------------------------------------------------------
[ 25 - HBO ]
- Name                                :     HBO
- Version                             :     preview
- GUID                                :     7.13.3
- Package ID                          :     http://hbonordic.com
- App ID                              :     u5Sh825pOW
-----------------------------------------------------------------------------------------------------
[ 26 - Rakuten ]
- Name                                :     Rakuten
- Version                             :     TV
- GUID                                :     4.4.12
- Package ID                          :     https://tizen30.wuaki.tv
- App ID                              :     vbUQClczfR
-----------------------------------------------------------------------------------------------------
[ 27 - Eden ]
- Name                                :     Eden
- Version                             :     4.4.12
- GUID                                :     https://tizen30.wuaki.tv
- Package ID                          :     vbUQClczfR
- App ID                              :     vbUQClczfR.service
-----------------------------------------------------------------------------------------------------
`

**Comment by tavicu** [comment]
Hi. Interesting.

What model or year is your TV?
