### ISSUE TITLE
Wiki instructions for pairing are out of date

### ISSUE THREAD

**Issue by schlosrat** [tavicu/homebridge-samsung-tizen#596]
Please update the Instructions page in the Wiki. It appears to have last been updated in 2019, and some things have changed. The current instructions for pairing a TV are wrong in at least two ways.

1. The third bullet under "6. Adding the TV to the Home App" advises the user to "click Don't Have a Code or Can't scan?". This is not an option in a modern up-to-date IOS device. Instead, one should "Click on 'More options...' under Scan code or hold iPhone near the accessory"
2. The sixth bullet under "6. Adding the TV to the Home App" advises the user to set the PIN using the information "The PIN is the code you set in config.json file on bridge - pin". This may be an old way of doing it, but it's apparently not how the app works now. The code the user needs is displayed in the Homebridge status when restarting with a text string like this: "Please add [Bedroom TV FF9B] manually in Home app. Setup Code: 750-50-160"

**Comment by tavicu** [comment]
Hi @schlosrat ,

Indeed the Wiki pages were made a few iOS versions ago.
Right now i'm working on a new documentation with images and everything that will be made with the latest iOS version.

The current Wiki will be removed after the new documentation will go live.
