### ISSUE TITLE
Nothing is showing up on home app but Home bridge is working and controlling it through accessories PLEASE HELP

### ISSUE THREAD

**Issue by Runtrons** [tavicu/homebridge-samsung-tizen#599]
This is exactly what I need but... It ain't working

### **Problem: **
Not seeing anything, no tv in home app
### Things I have tried: 
Restarting, uninstalling, and re installing Samsung tizen, looking through all the rooms. Re-adding home bridge two HomeKit. Nothing seems to be working

I can turn on and off the tv from the accessories tab in home bridge though, so I know its working.
Please help @tavicu

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/wiki/Installation#6-adding-the-tv-to-home-app
