### ISSUE TITLE
Open specific apps

### ISSUE THREAD

**Issue by tamasharasztosi** [tavicu/homebridge-samsung-tizen#6]
Hey! Great work! I haven't found 'KEY_COMMAND' to open specific apps (Spotify, Plex..).
What do you think? Is it doable? Or already exist?
Thank you!

**Comment by tavicu** [comment]
Hi,

Sorry but i'm not aware of any key to open apps.

The key commands are only the keys that can be found on a remote. From what i've seen none of Samsung remotes has key for apps.
