### ISSUE TITLE
App ID | RTL+

### ISSUE THREAD

**Issue by BassXT** [tavicu/homebridge-samsung-tizen#602]
Hello everyone,

I’m searching the app is for RTL+. Unfortunately I can’t get it m myself, because I don’t have a windows machine. 

Would be great if somebody could enlighten me!

thanks in advance

**Comment by tavicu** [comment]
Hi. The Tizen Studio app is also available for MacOS :)

**Comment by BassXT** [comment]
Easier than I thought it would be.

`[ 1 - Netflix]
- App Name                            :     Netflix
- App Version                         :     5.3.27
- App ID - WAS                        :     3201907018807
- App ID - Tizen                      :     org.tizen.netflixapp
-----------------------------------------------------------------------------------------------------
[ 2 - Prime Video]
- App Name                            :     Prime Video
- App Version                         :     2.51.04
- App ID - WAS                        :     3201910019365
- App ID - Tizen                      :     org.tizen.primevideo
-----------------------------------------------------------------------------------------------------
[ 3 - Disney+]
- App Name                            :     Disney+
- App Version                         :     22.21.0
- App ID - WAS                        :     3201901017640
- App ID - Tizen                      :     MCmYXNxgcu.DisneyPlus
-----------------------------------------------------------------------------------------------------
[ 4 - Apple TV]
- App Name                            :     Apple TV
- App Version                         :     13.1.1
- App ID - WAS                        :     3201807016597
- App ID - Tizen                      :     com.samsung.tv.ariavideo
-----------------------------------------------------------------------------------------------------
[ 5 - WOW]
- App Name                            :     WOW
- App Version                         :     4.0.8
- App ID - WAS                        :     3201411000562
- App ID - Tizen                      :     Mo5FtpAjGy.Skyonline
-----------------------------------------------------------------------------------------------------
[ 6 - Rakuten TV]
- App Name                            :     Rakuten TV
- App Version                         :     5.1.1
- App ID - WAS                        :     3201511006428
- App ID - Tizen                      :     vbUQClczfR.Wuakitv
-----------------------------------------------------------------------------------------------------
[ 7 - Joyn]
- App Name                            :     Joyn
- App Version                         :     1.42.2
- App ID - WAS                        :     3201502001386
- App ID - Tizen                      :     cg2m3QSB89.7tv
-----------------------------------------------------------------------------------------------------
[ 8 - MagentaTV]
- App Name                            :     MagentaTV
- App Version                         :     1.14.0
- App ID - WAS                        :     3201907018746
- App ID - Tizen                      :     g0nt8dscFO.MagentaTV
-----------------------------------------------------------------------------------------------------
[ 9 - PSBWebApp]
- App Name                            :     PSBWebApp
- App Version                         :     1.1.1
- App ID - WAS                        :     3202106024199
- App ID - Tizen                      :     Ja2mti1oVw.PSBWebApp
-----------------------------------------------------------------------------------------------------
[ 10 - DAZN]
- App Name                            :     DAZN
- App Version                         :     1.70.14
- App ID - WAS                        :     3201607009920
- App ID - Tizen                      :     8HwqClkwtp.DAZN
-----------------------------------------------------------------------------------------------------
[ 11 - Google Assistant entdecken]
- App Name                            :     Google Assistant entdecken
- App Version                         :     0.21.11110
- App ID - WAS                        :     3202004020674
- App ID - Tizen                      :     AkhP5nCr24.GoogleAssistant
-----------------------------------------------------------------------------------------------------
[ 12 - Amazon Alexa]
- App Name                            :     Amazon Alexa
- App Version                         :     0.21.10220
- App ID - WAS                        :     3202004020626
- App ID - Tizen                      :     AQKO41xyKP.AmazonAlexa
-----------------------------------------------------------------------------------------------------
[ 13 - Internet]
- App Name                            :     Internet
- App Version                         :     4.2.11030
- App ID - WAS                        :     3202010022079
- App ID - Tizen                      :     org.tizen.browser
-----------------------------------------------------------------------------------------------------
[ 14 - RTL+]
- App Name                            :     RTL+
- App Version                         :     1.16.1
- App ID - WAS                        :     3201908018988
- App ID - Tizen                      :     KbRHmu0vrC.TVNOWPREMIUM
-----------------------------------------------------------------------------------------------------
[ 15 - Plex]
- App Name                            :     Plex
- App Version                         :     5.55.2
- App ID - WAS                        :     3201512006963
- App ID - Tizen                      :     kIciSQlYEM.plex
-----------------------------------------------------------------------------------------------------
[ 16 - YouTube]
- App Name                            :     YouTube
- App Version                         :     2.1.507
- App ID - WAS                        :     111299001912
- App ID - Tizen                      :     9Ur5IzDKqV.TizenYouTube
-----------------------------------------------------------------------------------------------------
[ 17 - Couchplay SpieleCenter]
- App Name                            :     Couchplay SpieleCenter
- App Version                         :     1.3.2
- App ID - WAS                        :     3201609010528
- App ID - Tizen                      :     NeV3gZvFmN.Couchplay
-----------------------------------------------------------------------------------------------------
[ 18 - ZDF mediathek]
- App Name                            :     ZDF mediathek
- App Version                         :     1.15.0
- App ID - WAS                        :     3201705012365
- App ID - Tizen                      :     yPSlpvfeTf.ZDFmediathek
-----------------------------------------------------------------------------------------------------
[ 19 - ARD Mediathek]
- App Name                            :     ARD Mediathek
- App Version                         :     3.0.1
- App ID - WAS                        :     3201412000679
- App ID - Tizen                      :     SrAoJxGQUf.ARD
-----------------------------------------------------------------------------------------------------
[ 20 - Gallery]
- App Name                            :     Gallery
- App Version                         :     3.0.50
- App ID - WAS                        :     3201710015037
- App ID - Tizen                      :     com.samsung.tv.gallery
-----------------------------------------------------------------------------------------------------
[ 21 - eManual]
- App Name                            :     eManual
- App Version                         :     7.4.0
- App ID - WAS                        :     20212100002
- App ID - Tizen                      :     LzU5yAFXeg.emanual
-----------------------------------------------------------------------------------------------------
[ 22 - Samsung Promotion]
- App Name                            :     Samsung Promotion
- App Version                         :     3.2.45
- App ID - WAS                        :     3201807016658
- App ID - Tizen                      :     yL49PNFmjW.PromotionApp
-----------------------------------------------------------------------------------------------------
[ 23 - HD+]
- App Name                            :     HD+
- App Version                         :     1.2.4
- App ID - WAS                        :     3201810017070
- App ID - Tizen                      :     IpIKeB3u2B.HDPlusConnect
-----------------------------------------------------------------------------------------------------
[ 24 - Apple Music]
- App Name                            :     Apple Music
- App Version                         :     13.1.1
- App ID - WAS                        :     3201908019041
- App ID - Tizen                      :     org.tizen.apple.applemusic
-----------------------------------------------------------------------------------------------------
[ 25 - Twitch]
- App Name                            :     Twitch
- App Version                         :     12.0.0
- App ID - WAS                        :     3202203026841
- App ID - Tizen                      :     Jz7aUrV2Q4.Twitch
-----------------------------------------------------------------------------------------------------
[ 26 - Paramount+]
- App Name                            :     Paramount+
- App Version                         :     4.12.2
- App ID - WAS                        :     3202110025305
- App ID - Tizen                      :     rJyOSqC6Up.PPlusIntl
-----------------------------------------------------------------------------------------------------
`
