### ISSUE TITLE
MAC Address Issue

### ISSUE THREAD

**Issue by crashrider** [tavicu/homebridge-samsung-tizen#605]
For some reason, using the Hoobs Dashboard and clicking "Accessories" tab, the power on/off button works only when I have the MAC address setup using ":".  Using this method makes Homekit not able to turn the power on after the TV is off. 

Vice Versa...  If I use "." in the MAC address, Homekit will show the TV properly, but I'm not able to turn the TV "On".  Also, the "Accessories" button in Hoobs doesn't work...

Thoughts? Did I explain that right? 

Works for Hoobs "Accessory" Page, not Homekit
```
{
    "platform": "SamsungTizen",
    "name": "Living Room TV",
    "app_list": true,
    "devices": [
        {
            "name": "Living Room TV",
            "ip": "10.0.1.23",
            "mac": "C0:23:8D:DF:0F:6F"
         }
    ]
}
```

Works for Homekit, not Hoobs "Accessory" Page
```
{
    "platform": "SamsungTizen",
    "name": "Living Room TV",
    "app_list": true,
    "devices": [
        {
            "name": "Living Room TV",
            "ip": "10.0.1.23",
            "mac": "C0.23.8D.DF.0F.6F"
         }
    ]
}
```

**Comment by tavicu** [comment]
Hi. Mac address should be with `:`.
The plugin is designed for Homebridge, not Hoobs. Unfortunately I cannot assistant you further.
