### ISSUE TITLE
PING Output in log file

### ISSUE THREAD

**Issue by sergiobaiao** [tavicu/homebridge-samsung-tizen#61]
Hi there,

Is it possible to add a config option to not show the PING outputs from the TVs? That make very hard to keep debugging homebridge with this plugin enabled. In my case, it shows messages even when the TV is powered on, like this:

[2/5/2019, 11:52:57 PM] [TV Suite Master] PING 192.168.0.21 (192.168.0.21) 56(84) bytes of data.
64 bytes from 192.168.0.21: icmp_seq=1 ttl=64 time=0.683 ms

--- 192.168.0.21 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.683/0.683/0.683/0.000 ms

[2/5/2019, 11:53:00 PM] [TV Sala] PING 192.168.0.22 (192.168.0.22) 56(84) bytes of data.
From 192.168.0.243 icmp_seq=1 Destination Host Unreachable

--- 192.168.0.22 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms

[2/6/2019, 12:02:55 AM] [TV Sala] [DEBUG] { Error: Command failed: ping -t 1 -c 1 192.168.0.22

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:600:12)

  killed: false,
  code: 1,
  signal: null,
  cmd: 'ping -t 1 -c 1 192.168.0.22' }

Wouldn't be easier to get ping exit status code and use that as a variable to control the power button instead of just trowing it like that?

======================================================
If ping does not receive any reply packets at all it will exit with code 1. If a packet count and deadline are both specified, and fewer than count packets are received by the time the deadline has arrived, it will also exit with code 1. On other error it exits with code 2. Otherwise it exits with code 0. This makes it possible to use the exit code to see if a host is alive or not.

To list the results:

    Success: code 0
    No reply: code 1
    Other errors: code 2

For example:
if ping -c 1 "$otherhost" >/dev/null 2>&1; then
    printf 'The host "%s" is reachable\n' "$otherhost"
else
    printf 'The host "%s" is not reachable\n' "$otherhost"
fi

or 
if ping -c3 -w5 domain.com 2>&1 1>&- ; then 
    echo "ping was successful"
else
    echo "ping failed with code $?"
fi

That was using bash only.

**Comment by tavicu** [comment]
Hi. 

I am working on a new version which will not use ping anymore!
