### ISSUE TITLE
All worked great first install and config but then...

### ISSUE THREAD

**Issue by theRansoms** [tavicu/homebridge-samsung-tizen#610]
Hello All

After multiple HOOBS issues and a rebuild of my server, I have finally got this plugin moving forward again.

My problem however is that even with the same config.json (as far as I can tell), I cannot see the TV in the nearby accessories :(

Very frustrating as it worked "out of the box" with minimal tweeting!

My config.json looks like this:
================================================================
{
    "accessories": [],
    "platforms": [
        {
            "bridge": {
                "name": "Samsung Tizen Bridge",
                "username": "",
                "port": 51846,
                "pin": ""
            },
            "description": "This is an example configuration file.",
            "platforms": [
                {
                    "platform": "SamsungTizen",
                    "name": "Samsung Tizen Bridge"
                }
            ],
            "devices": [
                {
                    "name": "Lounge TV",
                    "ip": "10.10.21.82",
                    "mac": "10:2b:41:27:c0:75",
                    "api_key": "",
                    "device_id": "",
                    "uuid": "A6",
                    "inputs": [
                        {
                            "type": "input",
                            "name": "Apple",
                            "value": "HDMI1"
                        },
                        {
                            "type": "input",
                            "name": "du",
                            "value": "HDMI2"
                        }
                    ],
                    "switches": [
                        {
                            "name": "Mute",
                            "mute": true
                        },
                        {
                            "name": "Power",
                            "power": true
                        },
                        {
                            "name": "Source",
                            "command": "KEY_SOURCE"
                        }
                    ]
                }
            ]
        }
    ]
}

==========================================

Debug Log looks fine (full log attached)...

28/01/2023, 21:14:24Samsung Tizen BridgeLoaded plugin 'homebridge-samsung-tizen'
28/01/2023, 21:14:24Samsung Tizen BridgeLoading 1 platforms...
28/01/2023, 21:14:24Samsung Tizen BridgeBridge is running on port 51846.

[log.txt](https://github.com/tavicu/homebridge-samsung-tizen/files/10527871/log.txt)

Any great ideas on what I am doing wrong, and how I can get back on track, would be much appreciated.

Simon

**Comment by MaTr75** [comment]
Same issue here... I can not add an additional TV, it does not appear in the nearby devices.

**Comment by LavlavOP** [comment]
same here….

**Comment by tavicu** [comment]
Hi! Unfortunately I cannot assist you on Hoobs! The plugin is designed for Homebridge.

Do you see this message in the logs when you start the server?

```
[2/5/2023, 8:02:49 PM] Lounge TV is running on port xxxxxx.
[2/5/2023, 8:02:49 PM] Please add [Lounge TV] manually in Home app. Setup Code: xxxxxx
```

Also please never post api_key and device_id on the public internet again. With those keys anyone can control your device and changing them would require you to create a new Samsung account!

**Comment by theRansoms** [comment]
> Hi! Unfortunately I cannot assist you on Hoobs! The plugin is designed for Homebridge.
> 
> Do you see this message in the logs when you start the server?
> 
> ```
> [2/5/2023, 8:02:49 PM] Lounge TV is running on port xxxxxx.
> [2/5/2023, 8:02:49 PM] Please add [Lounge TV] manually in Home app. Setup Code: xxxxxx
> ```
> 
> Also please never post api_key and device_id on the public internet again. With those keys anyone can control your device and changing them would require you to create a new Samsung account!

Thanks for your response, my smart home project is a rapidly evolving thing and I have in fact moved my HOOBs devices over to a homebridge server on an old Mac mini.  The plugin appears to be working fine now after re-installation but worth keeping in mind that it did work in HOOBs originally too.

Thanks for your security comment too.
