### ISSUE TITLE
Samsung error in homebridge

### ISSUE THREAD

**Issue by LarryT8959** [tavicu/homebridge-samsung-tizen#611]
I have a 2013 Samsung TV. I installed the "homebridge-samsungtv-2014" plugin. I'm getting the following error in the homebridge log and the button is not working "controlling the TV". I've read the the post and tried everything, but evidently I'm missing something. Any help would be greatly appreciated. Thanks
Config file;

    "tvs": [
        {
            "name": "Samsung over garage",
            "ipAddress": "xxx.xxx.x.xxx",
            "mac": "78:99:bb:59:d9:99"
        }
    ],
    "platform": "SamsungTV2014",
    "_bridge": {
        "username": "0E:EE:B1:52:A0:E4",
        "port": 35400
    }
}

**Comment by tavicu** [comment]
Hi. Wront plugin. This is [homebridge-samsung-tizen](https://github.com/tavicu/homebridge-samsung-tizen)
