### ISSUE TITLE
Can't turn on TV (No responding)

### ISSUE THREAD

**Issue by Matejxx** [tavicu/homebridge-samsung-tizen#616]
Hello, 

every time couple of minutes after TV is off, I can't turn it on via Homekit (says No responding error). 

When I turn on TV manually, I can turn it off via homekit and then On again, but it stops working after couple of mins. 

Any help?

**Comment by tavicu** [comment]
After tuning the TV on or off you cannot do other powering action for 5 seconds.

Without debug logs I cannot help you.

**Comment by Matejxx** [comment]
I managed to fix it in the meantime. 

I have copied my TV's MAC address from router In xx-xx-xx-xx-xx format. It should be with ":" not "-" and it works now!
