### ISSUE TITLE
Can’t make Home automation based on TV input change

### ISSUE THREAD

**Issue by ThomasLvll** [tavicu/homebridge-samsung-tizen#617]
Hello, is it planned to add the ability to set up an automation in the Apple Home app triggered when the TV input is changed? I saw that when I manually switch the TV input using its remote, it is updated in the Home input list, so I guess HomeKit gets the information (more or less quickly based on the refresh delay set up). I use a SmartThings TV.

**Comment by tavicu** [comment]
Hi.
Unfortunately this is not a feature that we could add. It's added by Apple. And from my experience you can wait ... for ever!
I know there are other apps with more control over homekit. Maybe you could do it with those. A search on the App Store with "homekit" will probably give you some suggestions :)
