### ISSUE TITLE
Apple remote doesn’t show input/power/volume controls

### ISSUE THREAD

**Issue by TreehouseFalcon** [tavicu/homebridge-samsung-tizen#618]
When using the Tizen-connected remote app, there are many buttons missing from Apple TV-based remotes. Attached is a picture of what I’ve seen previously when using the remote with Apple TV and what I see when using it with this plugin. I’m not sure if this is intentional, but it’s inconvenient to use my physical remote to change volume or change source. Any help/response is appreciated. 

Apple TV remote layout with full controls:
![8BFBBD5C-B629-4D8E-84B5-7B7770D3C5CD](https://user-images.githubusercontent.com/56169608/219921669-687addd6-4241-4fcf-93e3-02133f44d964.jpeg)

Tizen plugin remote with limited controls and no ability to return home on the “No Source Found” screen:
![A12B2DCA-CE52-448C-BFFB-4C6304512939](https://user-images.githubusercontent.com/56169608/219921661-acf2af83-d362-4ce9-8286-a6d287ef0b32.jpeg)

Other than this issue, this plugin has worked wonders for me.

**Comment by tavicu** [comment]
Hi @TreehouseFalcon,

Unfortunately Apple don't give us the option to choose which buttons to be available, it only allows us to map the buttons to some action.
That layout is a generic one for all TVs that are compatible with HomeKit (even if they are native or through Homebridge).

**Comment by nmeliasp** [comment]
Is it possible to add a power on/off button to the remote?

**Comment by tavicu** [comment]
`Apple don't give us the option to choose which buttons to be available` ...

Your only option is to map one button to KEY_POWER if you want, but that will works only for power off since power on uses other method of powering up the tv

**Comment by town3r** [comment]
I found that sometimes after rebooting Homebridge I also have to restart my phone in order for it to correctly detect all the TV features via the iOS Remote.

ie: Here is what the remote looks like for my 2020 45" Frame TV.

![image](https://github.com/tavicu/homebridge-samsung-tizen/assets/12396203/2d4ad91c-9bd6-41cd-bb5f-715c26917a32)
