### ISSUE TITLE
Ambient Mode

### ISSUE THREAD

**Issue by sambatesdesign** [tavicu/homebridge-samsung-tizen#622]
hey could we get the app code for Ambient Mode please

**Comment by sambatesdesign** [comment]
@tavicu how do I go about finding the app codes from the TV, as I could try and find it myself =)

**Comment by tavicu** [comment]
Hi @sambatesdesign ,

https://tavicu.github.io/homebridge-samsung-tizen/extra/applications.html#get-installed-applications

But judging by the name, "Ambient Mode" doesn't sound like an app, it sounds more like a mode of tv.

**Comment by sambatesdesign** [comment]
ok, @tavicu I got the list of apps from the TV, and you're right sadly, this does not show up as an app.

This mode is built into all QLED TV's, its sort of the same thing that you get with the frames, but without the price tag, you can see more about it [here](https://www.samsung.com/uk/support/tv-audio-video/how-to-use-ambient-mode-on-samsung-qled-tv/) 

I did find you can trigger the mode from the smart things app if that's any help at all. Most of the Remotes I have seen in the UK for this type of TV don't have a button on the remote.

**Comment by tavicu** [comment]
I will take a look today and see if they added the option to control this over SmartThings API. 

Also, from the samsung website I can see in a picture that the app icon is on the home menu, on the second position? Is that right? Because if it is you can create a custom command :)
![image](https://user-images.githubusercontent.com/172068/226863441-fd2e7721-521d-4542-b1ac-01b6e0213e30.png)

**Comment by tavicu** [comment]
Try creating a custom switch with this key: `KEY_AMBIENT`


Example:
`{"name": "Ambient Mode", "command": "KEY_AMBIENT"}`

https://tavicu.github.io/homebridge-samsung-tizen/features/switches.html#switches
https://tavicu.github.io/homebridge-samsung-tizen/configuration/#advanced-configuration-with-all-settings

**Comment by sambatesdesign** [comment]
@tavicu the custom switch worked. Nicely done. I would add this to the docs if you can as I'm sure others will want this too.

Thanks for your help
