### ISSUE TITLE
DSTV and new Showmax ID

### ISSUE THREAD

**Issue by SCombrink** [tavicu/homebridge-samsung-tizen#629]
Here are the IDs for applications installed on my Samsung TV. It took a bit of effort to obtain these for me, so I am adding this here for others to use. This is on a 2022 Samsung TV.

[ 1 - Netflix]
- App Name                            :     Netflix
- App Version                         :     5.3.27
- App ID - WAS                        :     3201907018807
- App ID - Tizen                      :     org.tizen.netflixapp
-----------------------------------------------------------------------------------------------------
[ 2 - Prime Video]
- App Name                            :     Prime Video
- App Version                         :     3.001.022
- App ID - WAS                        :     3201910019365
- App ID - Tizen                      :     org.tizen.primevideo
-----------------------------------------------------------------------------------------------------
[ 3 - Disney+]
- App Name                            :     Disney+
- App Version                         :     1.6.3
- App ID - WAS                        :     3202204027038
- App ID - Tizen                      :     Di0N6xZMEA.disneyplus
-----------------------------------------------------------------------------------------------------
[ 4 - Apple TV]
- App Name                            :     Apple TV
- App Version                         :     13.3.0
- App ID - WAS                        :     3201807016597
- App ID - Tizen                      :     com.samsung.tv.ariavideo
-----------------------------------------------------------------------------------------------------
[ 5 - YouTube]
- App Name                            :     YouTube
- App Version                         :     2.1.506
- App ID - WAS                        :     111299001912
- App ID - Tizen                      :     9Ur5IzDKqV.TizenYouTube
-----------------------------------------------------------------------------------------------------
[ 6 - Internet]
- App Name                            :     Internet
- App Version                         :     5.1.11040
- App ID - WAS                        :     3202010022079
- App ID - Tizen                      :     org.tizen.browser
-----------------------------------------------------------------------------------------------------
[ 7 - Google Meet]
- App Name                            :     Google Meet
- App Version                         :     1.2.22
- App ID - WAS                        :     3202008021439
- App ID - Tizen                      :     IewQEY143t.GoogleDuoWeb
-----------------------------------------------------------------------------------------------------
[ 8 - Spotify  Music and Podcasts]
- App Name                            :     Spotify  Music and Podcasts
- App Version                         :     2.1.43
- App ID - WAS                        :     3201606009684
- App ID - Tizen                      :     rJeHak5zRg.Spotify
-----------------------------------------------------------------------------------------------------
[ 9 - Nifty Gateway]
- App Name                            :     Nifty Gateway
- App Version                         :     1.0.8
- App ID - WAS                        :     3202201026324
- App ID - Tizen                      :     niftytizen.NiftyGateway
-----------------------------------------------------------------------------------------------------
[ 10 - eManual]
- App Name                            :     eManual
- App Version                         :     5.7.0
- App ID - WAS                        :     20222100003
- App ID - Tizen                      :     h6D3hH79er.emanual
-----------------------------------------------------------------------------------------------------
[ 11 - DStv]
- App Name                            :     DStv
- App Version                         :     2.1.7
- App ID - WAS                        :     3201804016109
- App ID - Tizen                      :     CXNLCPYe82.dstvnow
-----------------------------------------------------------------------------------------------------
[ 12 - Showmax]
- App Name                            :     Showmax
- App Version                         :     2.0.2
- App ID - WAS                        :     3201903018045
- App ID - Tizen                      :     Nm4zJjYmVG.shomwax
-----------------------------------------------------------------------------------------------------
[ 13 - Apple Music]
- App Name                            :     Apple Music
- App Version                         :     13.3.0
- App ID - WAS                        :     3201908019041
- App ID - Tizen                      :     org.tizen.apple.applemusic
-----------------------------------------------------------------------------------------------------
[ 14 - YouTube Kids]
- App Name                            :     YouTube Kids
- App Version                         :     1.0.17
- App ID - WAS                        :     3201611010983
- App ID - Tizen                      :     5SLwh7m3En.TizenYouTubeKids
-----------------------------------------------------------------------------------------------------
[ 15 - Red Bull TV]
- App Name                            :     Red Bull TV
- App Version                         :     15.6.7
- App ID - WAS                        :     3201602007756
- App ID - Tizen                      :     4OAwqypfRT.RedBullTV
-----------------------------------------------------------------------------------------------------
[ 16 - Bloomberg]
- App Name                            :     Bloomberg
- App Version                         :     3.5.3
- App ID - WAS                        :     3201412000690
- App ID - Tizen                      :     Q44TJUVo3Z.Bloomberg
-----------------------------------------------------------------------------------------------------
[ 17 - The Austria Channel]
- App Name                            :     The Austria Channel
- App Version                         :     1.2.000
- App ID - WAS                        :     3202204027037
- App ID - Tizen                      :     iN8cIl8pKD.TheAustriaChannel
-----------------------------------------------------------------------------------------------------

**Comment by tavicu** [comment]
Thank you! I have updated the applications list :)
