### ISSUE TITLE
Problem with disposable token

### ISSUE THREAD

**Issue by marithpl** [tavicu/homebridge-samsung-tizen#63]
On the beginning I would mention that I connected homebridge with TV successfully.
But I observed that after power cut or restart a raspberry I can't use tizen plugin. Each time after restart or power breakdown I have to accept connection on TV.

It looks like I have new token each time or something. @tavicu Did you manage problem like this?

I installed this plugin on my friends TV and it works fine, only at my place there is a problem with conntection after breakdown. So I can do it correctly.

**Comment by marithpl** [comment]
Steps which I made to install
1. Install plugin
2. Fill config.json without token.
3. Run homebridge and try to switch off tv to see token in terminal
(and accept monit on TV)
4. Fill config.json with token
5. Restart homebridge

**Comment by tavicu** [comment]
I am working on a new version that will automatically store the token without needing to add it in config file.

Until the new version is release i will not offer support for things that will change :)
Hope you understand me.

If you will still have problems with the new version (3.0.0) after release, open an issue then and will see what will be able to do

**Comment by marithpl** [comment]
Sure! I'm waiting for new version.
