### ISSUE TITLE
iOS 17: Integration of new Buttons of Remote

### ISSUE THREAD

**Issue by jostrasser** [tavicu/homebridge-samsung-tizen#642]
Hi,
Is the plugin ready to integrate the following new buttons?

MUTE
POWER

Thanks!

![image](https://github.com/tavicu/homebridge-samsung-tizen/assets/14274103/f67918a1-9b61-4bd4-92af-4f34779baa1d)

**Comment by tavicu** [comment]
Hi.

I have installed iOS 17 on one device to check it up and it looks like the buttons are disabled for all custom TVs (just like in your screenshot).

For now they are enabled only for Apple TVs from what I can see.

My guess is they are not implemented by Apple or that they will be removed for custom TVs in a future beta.

I will leave this issue open for now.
