### ISSUE TITLE
Input order since iOS 17 update

### ISSUE THREAD

**Issue by cl4udiu5** [tavicu/homebridge-samsung-tizen#648]
The input order is no longer correct after the update to iOS 17. Had to re-integrate my Samsung TV into HomeKit. That's when I noticed it.
![Bildschirmfoto 2023-09-22 um 14 07 14](https://github.com/tavicu/homebridge-samsung-tizen/assets/74124378/33714d49-a90d-4e5a-8d84-d46022d77adf)
![IMG_7662](https://github.com/tavicu/homebridge-samsung-tizen/assets/74124378/e40189ff-4849-4aed-9a94-c583de6900af)

**Comment by cl4udiu5** [comment]
Home App on macOS Ventura or iPhone with iOS 16.6.2 still showing the right order of the inputs.

**Comment by cl4udiu5** [comment]
For example: Activity order in Harmony switch in Home App is also not correct anymore

**Comment by tavicu** [comment]
Hi.

There is no option for us to select an order beside the order in which the inputs are declared.

Unfortunately there is nothing I can do regarding this. Looks like a problem on Apple side.

**Comment by cgierke** [comment]
I had the same problem in another [homebridge plugin](https://github.com/cgierke/homebridge-musiccast) and finally found a [fix](https://github.com/cgierke/homebridge-musiccast/commit/22bdccdedaebd45b0f52a14598e3e808adc536d8) (inspired by [this](https://github.com/homebridge/HAP-NodeJS/issues/644))

**Comment by tavicu** [comment]
Thank you @cgierke. I have pushed a new version with the fix :)
