### ISSUE TITLE
UE40JU6400 uses PIN authentication

### ISSUE THREAD

**Issue by sderuiter** [tavicu/homebridge-samsung-tizen#65]
Hi, unfortunately my TV uses PIN authentication (the [demo](https://github.com/tdudek/samsung-remote-models-2014-and-newer) version is able to access the TV). 

I've read that you can't test this method yourself (assuming you don't have a TV with this feature), but do you have a thought on which homebridge plugin might work with the PIN method?

Thank you.

**Comment by skop1986** [comment]
> Hi, unfortunately my TV uses PIN authentication (the [demo](https://github.com/tdudek/samsung-remote-models-2014-and-newer) version is able to access the TV).
> 
> I've read that you can't test this method yourself (assuming you don't have a TV with this feature), but do you have a thought on which homebridge plugin might work with the PIN method?
> 
> Thank you.


https://github.com/kkapitan/homebridge-homesung#readme

**Comment by tavicu** [comment]
Hei,
As @skop1986 you can try that plugin :)

I have prepared the code so in the future i will be able to implement the pin method too. What will be difficult will be testing since i don't have a device that use that method.
But who knows, maybe someone will donate one :P

**Comment by skop1986** [comment]
> Hei,
> As @skop1986 you can try that plugin :)
> 
> I have prepared the code so in the future i will be able to implement the pin method too. What will be difficult will be testing since i don't have a device that use that method.
> But who knows, maybe someone will donate one :P

I can test on models samsung 2015 UE40JU7000U

**Comment by tavicu** [comment]
As soon as i will finish the new version and have some spare i will take a look and will see where it goes :)

**Comment by sderuiter** [comment]
Thank you. I can obviously test with a model UE40JU6400. The abovementioned plugin does work, besides some TV Power issues.

**Comment by Luftloch80** [comment]
I can also Beta Test the Pin Method for you. Looking fwd

**Comment by MBarti** [comment]
Early-Tizen TVs (H/J-series from 2014-2015) use slightly different protocols. Luckily, this issue (described in detail here Ape/samsungctl#22 ) has been thoroughly investigated and solved.
There's a full python library for the alternative pairing, encryption and send_command:
https://github.com/eclair4151/SmartCrypto

It'd be amazing to have those TV work with your plugin, especially with the iOS 12.2 enhancements coming soon.

If it helps, here's the output from my TV: http://TV_IP:8001/api/v2/

{
"id": "uuid:b0f374b8-baac-xxxx-xxxx-6b652c78xxxx",
"name": "[TV] UE65JU6500",
"version": "2.0.25",
"device": {
"type": "Samsung SmartTV",
"duid": "uuid:b0f374b8-baac-xxxx-xxxx-6b652c78xxxx",
"model": "15_HAWKM_UHD_2D_SC",
"modelName": "UE65JU6500",
"description": "Samsung DTV RCR",
"networkType": "wireless",
"ssid": "xx:xx:xx:xx:xx:xx",
"ip": "192.168.1.13",
"firmwareVersion": "Unknown",
"name": "[TV] UE65JU6500",
"id": "uuid:b0f374b8-xxxx-xxxx-xxxx-6b652c78xxxx",
"udn": "uuid:b0f374b8-xxxx-xxxx-xxxx-6b652c78xxxx",
"resolution": "1920x1080",
"countryCode": "PL",
"msfVersion": "2.0.25",
"smartHubAgreement": "true",
"wifiMac": "xx:xx:xx:xx:xx:xx",
"developerMode": "0",
"developerIP": ""
},
"type": "Samsung SmartTV",
"uri": "http://TV_IP:8001/api/v2/"
}

**Comment by huglester** [comment]
I see this issue was closed.
So it is unsolvable? 
My model is UE32J6302
So I think it is also "not working"
