### ISSUE TITLE
Not turn off

### ISSUE THREAD

**Issue by colussim** [tavicu/homebridge-samsung-tizen#667]
Hello,
﻿I have a TV type QE55Q85RATXZG and  ﻿I'm having a problem ... the TV turns on in both Apple Home and HomeBridge but it's impossible to turn it off. When I look in the log when I try to turn it off, I get the following error: 
[TV] Failed to open socket {"event": "ms.channel.unauthorized"}
I don't have any authorization problems when I connect to http:://X.X.X.X:8001/api..
Any idea what the problem is ? 

Thanks,

Emmanuel

**Comment by tavicu** [comment]
The plugin cannot reach the TV.

The IP is wrong, the TV is on another network than the server or another subnet, the connection between the two of them is blocked by firewall or something.

**Comment by colussim** [comment]
Thanks ,it was definitely a network problem
