### ISSUE TITLE
Homebridge Samsung Tizen port setup

### ISSUE THREAD

**Issue by GT0mi** [tavicu/homebridge-samsung-tizen#668]
Subject: Issue with Samsung Tizen Plugin Port Configuration

Description:
I am encountering a persistent issue with configuring fixed ports for the Samsung Tizen plugin in Homebridge. Despite specifying the ports in the configuration file, the port number still changes upon restarting. I have tried various configurations, including placing the "ports" array in different sections of the configuration file, but the problem persists.

Configuration Example:

json
Copy code
{
    "devices": [
        {
            "api_key": "xxxxxxxxxxxx",
            "device_id": "xxxxxxxxxxxx",
            "name": "Samsung",
            "ip": "xxxxx",
            "mac": "xxxxxxxx",
            "uuid": "A1",
            "inputs": [],
            "switches": [
                {
                    "power": true
                }
            ]
        }
    ],
    "platform": "SamsungTizen",
    "mdns": true,
    "port": 43400
}
Attempts:

I have tried placing the "ports" array in different locations within the configuration file.
I have ensured that all required parameters are correctly set.
Result:
Despite these efforts, the Samsung Tizen plugin still uses a different port upon restart, leading to connectivity issues.

Request for Assistance:
Could you please provide guidance on how to effectively configure fixed ports for the Samsung Tizen plugin in Homebridge? Are there any additional steps or considerations that might resolve this issue?

Environment:

Homebridge version:  v1.7.0 
Samsung Tizen Plugin version: v5.2.7
Ubuntu Mantic Minotaur (23.10)
Node.js Version | v18.19.0

Thank you for your assistance.

**Comment by tavicu** [comment]
Hi.

The plugin is not responsible for picking which port it would work on.

You should ask on Homebridge repo.
