### ISSUE TITLE
no control centre tv remote since ios17

### ISSUE THREAD

**Issue by crbyxwpzfl** [tavicu/homebridge-samsung-tizen#669]
hi your plugin works great! This is likely an apple issue. 
But is it only me or is the control centre tv remote widget broken since ios17.
I noticed the that since ios17/ipados17 the Samsung tv no longer shows up in the control centre widget.

please just close this if this is only me or if I missed something else.

**Comment by HughesAndrewC** [comment]
I'm running 17.4. I don't see any problems.

![image](https://github.com/tavicu/homebridge-samsung-tizen/assets/15352765/567ff301-1d37-4d16-bed3-f69837ba9e23)

![image](https://github.com/tavicu/homebridge-samsung-tizen/assets/15352765/56cb2981-aa3e-49ea-8625-7c1433e8997c)

**Comment by crbyxwpzfl** [comment]
sorry. than it is an issue on my end. Thank you for your quick reply. Im happy it is not an intentionally by apple.
I apologise and close this.
I will post my solution when i find one.
