### ISSUE TITLE
Regarding the new Apple TV (iOS) Remote Buttons

### ISSUE THREAD

**Issue by audioant** [tavicu/homebridge-samsung-tizen#670]
As 17.4 released and a lot of time passed since the iOS 17 dev beta, has there been any updates regarding the new mute, power, channels and guide buttons?
I noticed that the channel up button just triggers the arrow right button, and the middle channel button just triggers the down button.
Is there a way for us to fetch what the remote sends out? What the remote keys are called?
Really hope we can manipulate these new buttons.
Best regards to everyone.

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/issues/636

**Comment by audioant** [comment]
I know. I was just asking if there are any news.
I also have a question because I really want to fiddle around and figure this out.
Can you please tell me how you got the default name values for the keys in the Apple TV remote? For example ARROW_RIGHT? I can't find documentation online.

**Comment by tavicu** [comment]
Did you even look at my comment :)

There are two links to HAP-NodeJs, the main interface that Homebridge is using to communicate with HomeKit.
One for the Issue where is discussed and ask for implementation and another one for the source code.

> I also have a question because I really want to fiddle around and figure this out.

There is nothing you could figure it out unless you want to help develop in the HAP-NodeJS repo. But I think if it was possible until now, they would have probably implemented by now. But for sure this is just a mistake from Apple and those buttons should not be visible.

**Comment by audioant** [comment]
Well that's a bummer. Thank you so much for your quick reply! Really wish either Apple just removes them from the remote for non-Apple TVs or implements them correctly.

**Comment by tavicu** [comment]
Yeah. I think for now HomeKit it's not the main focus for Apple and it never was.

If you ask me the resources are probably minimal because they cannot remove the Home implementation at this point after they forced users to buy HomeKit compatible devices ..

But hey ... maybe in the future they will be more involved. But something it's telling me they won't, hope I'll be wrong on this one :)
