### ISSUE TITLE
"off" state issue

### ISSUE THREAD

**Issue by pat4020** [tavicu/homebridge-samsung-tizen#69]
Hi, I have just installed the plugin at its latest version and paired my Q9 successfully without any issues. 
However, I do have some problems when switching off the TV. Turning the TV off,  doesn’t matter if I do that via Homekit or the remote control, does toggle the Homekit switch to “off”, but after a short while (approx.. 20 seconds) it comes back “on” again, waiting another minute it goes back “off”, some 20 seconds later back “on” again and so on... This scenario repeats 4 times, before the switch remains “off” eventually.

Homebridge is at its latest version, Node runs at version 9.9.0 due to some other plugins working “best” with that version.

I’ve also tried to enable the real time update option, but that didn’t change anything on the behavior described above.

Anybody an idea how to fix that? I would like to create an automation to switch the lights on/off depending on the TV state, but switching the TV off causing the lights to go into some kind of “party mode” is not quite my intention 😉

Thanks!

**Comment by tavicu** [comment]
Hei! That's very strange. We can try to add some debug and see if the plugin starts the "party mode" or something else :)

You will only have to edit one file following my instructions. But first let me know which version of plugin you use (using this command: `npm -v homebridge-samsung-tizen`) and if you are willing to do it :)

**Comment by pat4020** [comment]
Hey, I would appreciate your help. I ran the command and got `6.8.0` in return …
