### ISSUE TITLE
Tizen App closes when I switch inputs on TV

### ISSUE THREAD

**Issue by pnasonov** [tavicu/homebridge-samsung-tizen#701]
Hi, I am developing my own app, and wanted to ask a question in community familiar with Tizen. 
I'm facing a problem where I need to put event listener on input switch to run my additional logic, but every time I trigger external input switch (ex. HDMI1 => HDMI2) my Tizen App closes and no event listener and logic is triggered. Is it a common case for all Samsung TVs to auto close app in such situation and is there possible ways to make app running on top of all this and let inputs switch underneath?

**Comment by tavicu** [comment]
Hi. This repo is for smart home system and it only use the public api of Tizen.

Unfortunately we don't have anything to do with Tizen itself and we don't know how it works or how it should work :)
