### ISSUE TITLE
Error In Media Player and Dev Tools

### ISSUE THREAD

**Issue by nitewing76** [tavicu/homebridge-samsung-tizen#704]
I receive errors when trying to play a video from the HASS media player and within the actions tab of Developer Tools.
The error for the media player has the same result if I access the media player from the left panel, or select Browse Media within this integration.

The YouTube app is configured in the apps list, along with some others.
In the integration in the Source dropdown, I only see "app_list" not the apps themselves. 

--Log for HASS Media Player:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: 8:57:01 AM (1 occurrences)
Last logged: 8:57:01 AM

Detected that custom integration 'samsungtv_smart' calls media_source.async_resolve_media without passing an entity_id at custom_components/samsungtv_smart/media_player.py, line 1542: play_item = await media_source.async_resolve_media(self.hass, media_id). Please create a bug report at https://github.com/ollo69/ha-samsungtv-smart/issues

--Log for Action tab within Developer Tools:

Logger: custom_components.samsungtv_smart.media_player
Source: custom_components/samsungtv_smart/media_player.py:1496
integration: SamsungTV Smart (documentation, issues)
First occurred: 9:08:32 AM (6 occurrences)
Last logged: 10:24:56 AM

Youtube app ID not available, configure in apps list

[config_entry-samsungtv_smart-01JF4A0W009P5CMHT70DVBVCZK.json](https://github.com/user-attachments/files/18169080/config_entry-samsungtv_smart-01JF4A0W009P5CMHT70DVBVCZK.json)

![ScreenShot_20241217105732](https://github.com/user-attachments/assets/072feeca-614d-41b6-b8b0-130c0843a9d3)
![ScreenShot_20241217111206](https://github.com/user-attachments/assets/191f5a9e-facb-4ee4-9e15-7a0b053d97f4)

![ScreenShot_20241217111151](https://github.com/user-attachments/assets/5d88066e-fc1e-4041-8b51-c69693d95a00)

**Comment by tavicu** [comment]
Hi. Wrong repo. This plugin is for homebridge, not for homeassistant.

**Comment by nitewing76** [comment]
Sorry.
I had both repos open in different tabs and clicked the wrong tab.
