### ISSUE TITLE
v5.3.0 is not marked as HB 2.0 compatible

### ISSUE THREAD

**Issue by jostrasser** [tavicu/homebridge-samsung-tizen#706]
Hi,

Updated today to the newest 5.3.0 release to be HB 2.0 compatible, but it is not marked with a "green check". 

Only to let you know about. 

Thanks!

![image](https://github.com/user-attachments/assets/311836b0-1ae1-41e1-8310-a457d0ebf2c0)

![image](https://github.com/user-attachments/assets/025abd1a-1aea-43a7-a41f-b501e6ff6840)

**Comment by tavicu** [comment]
Hi. I will take a look and see if there is something I should do or Homebridge to mark it as compatible in their list :)

**Comment by tavicu** [comment]
Done. https://github.com/tavicu/homebridge-samsung-tizen/commit/46dcf524ce82a360c49749d7268213015311c259

Can you update to 5.3.1 and see if that's resolved?

**Comment by jostrasser** [comment]
Yes, is fixed! Thank you!
Happy New Year ;)

![image](https://github.com/user-attachments/assets/e0f67997-f471-4d1f-99b7-cfd53e9bde19)

**Comment by tavicu** [comment]
Happy new year :)
