### ISSUE TITLE
Pair failed. Make sure you click Allow on the TV!

### ISSUE THREAD

**Issue by larrydavidow** [tavicu/homebridge-samsung-tizen#74]
I have a KS8000 model TV that's having the same issue reported by kajz3reczka where Homebridge reports an error saying "Pair failed. Make sure you click Allow on the TV!".

I get the prompt on the TV to allow the connection, however a token is not passed back to Homebridge.

Apparently, you mentioned the TV is using the PIN method vs the TOKEN method.  You recommended running a demo that doesn't make any sense as it is not a Homebridge plugin.  Can you elaborate on how to address this issue?

**Comment by ivnDeb11** [comment]
I have the same problem, please if you solve it, comment, thank you!

**Comment by tavicu** [comment]
There is nothing to solve! Right now the plugin is not compatible with PIN method.

That demo i posted it so you can check if your TV works with PIN. If it does, then my plugin is not compatible.

**Comment by ivnDeb11** [comment]
Okay thanks. Some other similar plugin? :(
