### ISSUE TITLE
Inputs to HDM1 and so on

### ISSUE THREAD

**Issue by tgermer** [tavicu/homebridge-samsung-tizen#77]
Hi,
How can I use inputs to got to HDMI1?
How can I use inputs to got to TV-Mode Channel ##?

Only my App-inputs are working.
`"inputs": [
                {
                    "name": "Netflix",
                    "type": "app",
                    "value": "11101200001"
                },
                {
                    "name": "Prime Video",
                    "type": "app",
                    "value": "3201512006785"
                },
                {
                    "name": "Live TV",
                    "type": "command",
                    "value": [
                        "KEY_SOURCE",
                        "KEY_LEFT*3",
                        "KEY_ENTER"
                    ]
                },
                {
                    "name": "FireTV",
                    "type": "command",
                    "value": "KEY_HDMI1"
                },
                {
                    "name": "AppleTV",
                    "type": "command",
                    "value": "KEY_HDMI3"
                }`

Thank you very much.

**Comment by idanyc** [comment]
try something like {"name": "PC","command": ["KEY_SOURCE", "KEY_LEFT", "KEY_ENTER"]},

**Comment by tavicu** [comment]
Unfortunately there is no key to select a hdmi source.

You can find here an example of how i set my inputs.
https://github.com/tavicu/homebridge-samsung-tizen/issues/50#issuecomment-478863884

**Comment by MarkBarbieri** [comment]
Try also 
```
"KEY_LEFT*1.5s"
```
It is quicker, especially if you need to start moving left more than 3 times as it minimizes the delay between multiple presses.  It is the same as holding the key down for 1.5 seconds.    You can fine tune the time a little if you need to but I find it better.  Good also for volume up/down

**Comment by tgermer** [comment]
Thank you.

I did it that way.

`"inputs": [
                {
                    "name": "Netflix",
                    "type": "app",
                    "value": "11101200001"
                },
                {
                    "name": "Prime Video",
                    "type": "app",
                    "value": "3201512006785"
                },
                {
                    "name": "Live TV – ARD",
                    "type": "command",
                    "value": [
                        "KEY_SOURCE",
                        "KEY_LEFT*6",
                        "KEY_RIGHT*1",
                        "KEY_ENTER",
                        "KEY_1",
                        "KEY_5",
                        "KEY_ENTER"
                    ]
                },
                {
                    "name": "Live TV – ZDF",
                    "type": "command",
                    "value": [
                        "KEY_SOURCE",
                        "KEY_LEFT*6",
                        "KEY_RIGHT*1",
                        "KEY_ENTER",
                        "KEY_7",
                        "KEY_4",
                        "KEY_ENTER"
                    ]
                },
                {
                    "name": "Fire TV Stick",
                    "type": "command",
                    "value": [
                        "KEY_SOURCE",
                        "KEY_LEFT*6",
                        "KEY_RIGHT*2",
                        "KEY_ENTER"
                    ]
                },
                {
                    "name": "Chromecast",
                    "type": "command",
                    "value": [
                        "KEY_SOURCE",
                        "KEY_LEFT*6",
                        "KEY_RIGHT*3",
                        "KEY_ENTER"
                    ]
                },
                {
                    "name": "Apple TV",
                    "type": "command",
                    "value": [
                        "KEY_SOURCE",
                        "KEY_LEFT*6",
                        "KEY_RIGHT*4",
                        "KEY_ENTER"
                    ]
                }
            ],`

Is there a maximum of inputs?

**Comment by tavicu** [comment]
There is no limit. But i don’t recommend adding a lot of inputs with the type `app` because for every input a request to tv will be made.
