### ISSUE TITLE
Inputs not added correctly

### ISSUE THREAD

**Issue by idanyc** [tavicu/homebridge-samsung-tizen#78]
Hi,
I'm using iOS 12.2 and the latest homebridge and homebridge-samsung-tizen (just ran npm install -g --unsafe-perm homebridge-samsung-tizen again that's right?)

I copied the inputs part from the example here in the wiki sections

but in the home up the TV input list is empty
and the inputs are added as wierd buttons with home icon  (see attachment)

any clue why?

thanks!

![image](https://user-images.githubusercontent.com/47157828/55513331-1d54d180-566e-11e9-8043-016cba5991d7.png)

**Comment by tavicu** [comment]
Sometimes it takes longer or a few restarts to show the inputs in correct way.

**Comment by monsterciattolo** [comment]
I'm in the same situation.
I see input as button in apple home app but not in input menu of TV.
i'm able to control TV in remote control in iOS and manage the power on/off.

**Comment by tavicu** [comment]
So the same response apply for you too :p

A few restarts should fix the problem!

**Comment by monsterciattolo** [comment]
i've restarted many times samsung TV Q8F, homebridge service and docker.
Same behivour. 
i enabled the debug mode on homebridge but i don't see any errors

**Comment by monsterciattolo** [comment]
finally i restarted my iphone and apple tv 4 HD (homekit hub) and i got the input in list!

Great!

Thanks for the good job!
