### ISSUE TITLE
Can't turn the TV off

### ISSUE THREAD

**Issue by skdelphix** [tavicu/homebridge-samsung-tizen#8]
When the TV is off and Home shows "Off" I'm able to turn the TV on without any issue. However, trying to turn it off shows:

Jul 09 19:44:53 raspberrypi homebridge[8994]: [2018-7-9 19:44:53] [Living Room TV] Power: TV is already OFF

I've tried restarting the TV and Homebridge a few times but am not seeing any ability to turn off the TV. Sometimes tapping the button in the Home App will just keep sending ON commands.

**Comment by tavicu** [comment]
Hi,

Can you run this command and tell me what it returns? Also replace TVIP with your IP:
`ping -t 1 -c 1 -w 1 TVIP`

Then run again this command:
`ping -t 1 -c 1 TVIP`

**Comment by skdelphix** [comment]
Well, that was easy. Looks like the IP had changed.

```
pi@raspberrypi:~ $ ping -t 1 -c 1 -w 1 192.168.7.237
PING 192.168.7.237 (192.168.7.237) 56(84) bytes of data.

--- 192.168.7.237 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

pi@raspberrypi:~ $ ping -t 1 -c 1 192.168.7.237
PING 192.168.7.237 (192.168.7.237) 56(84) bytes of data.
From 192.168.7.236 icmp_seq=1 Destination Host Unreachable

--- 192.168.7.237 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
```

I assumed because it was turning on and not returning error messages that the IP was the same. After fixing the IP in config.json everything is fine. Thanks!
