### ISSUE TITLE
TV in Control Center TV Remote

### ISSUE THREAD

**Issue by MrGh0ST** [tavicu/homebridge-samsung-tizen#80]
I don't have my TV in Control Center TV Remote, but in Homekit App and by Siri all works great :)

My config:
`        {
            "platform": "SamsungTizen",
            "inputs": [
                {
                    "name": "Netflix",
                    "type": "app",
                    "value": "11101200001"
                },
                {
                    "name": "Prime Video",
                    "type": "app",
                    "value": "3201512006785"
                },
                {
                    "name": "Youtube",
                    "type": "app",
                    "value": "111299001912"
                },
                {
                    "name": "DS Video",
                    "type": "app",
                    "value": "111399002250"
                }
            ],
            "devices": [
                {
                    "name": "Bedroom TV",
                    "ip": "192.168.0.23",
                    "mac": "************"
                }
            ]
        }
`
Any idea ?

**Comment by tavicu** [comment]
Most of the time it will work after a restart of the phone. Or just if you leave it some time.

It's showing now? Are you sure you are looking where you should?
The TV will not appear in Remote app, but in Remote from Control Center. There are two different things. Make sure you are not mistaken them :)

**Comment by MrGh0ST** [comment]
Thanks for this idea, after a lot of restart it's all good.
Remote from Control Center it's allow to control only one TV ?

**Comment by tavicu** [comment]
Right now, yes! Apple expects only one TV per bridge!

I have started working on a version where every tv will be an external accessory :)

**Comment by MrGh0ST** [comment]
Oh great idea, I hope to see it quickly :)

**Comment by jelvs** [comment]
> Right now, yes! Apple expects only one TV per bridge!
> 
> I have started working on a version where every tv will be an external accessory :)

Hey, do you know a way to prioritise a tv over another in the meanwhile? because I'm using another plugin for the same affect but for a an older tv using IR, but when I launch the control center it shows that one, instead of this plugin, and I would like to prioritise this one . Thanks

**Comment by tavicu** [comment]
The only thing that comes to my mind is order you add it in config.json. Other than that, there is no other option.

**Comment by jelvs** [comment]
Curiously I have this plugin first on my config

Best Regards,

Tiago Sousa

**Comment by jelvs** [comment]
> Right now, yes! Apple expects only one TV per bridge!
> 
> I have started working on a version where every tv will be an external accessory :)

you are implementing based on the KhaosT API for the external accessory ?

**Comment by tavicu** [comment]
> you are implementing based on the KhaosT API for the external accessory ?

Yup! I'm not a fan ... but it's the only method right now!

**Comment by jelvs** [comment]
yhe, I've seen...  I'm still not sure if it was intended by apple, or simply a "bug" (forgotten)

**Comment by tavicu** [comment]
Intended :) it makes sense to be that way!

I have made a new branch for testing https://github.com/tavicu/homebridge-samsung-tizen/pull/94

**Comment by josephcomisi** [comment]
Hi, not sure where to put this: is there a way to add the buttons Skip+-10 on the Remote from Control Center ? Not sure if these buttons are still available, but if they do, would be 2 more buttons to configure
