### ISSUE TITLE
Volume down/up

### ISSUE THREAD

**Issue by Maxwell70** [tavicu/homebridge-samsung-tizen#81]
Hi! Can you do volume down/up in the form of dimming?

**Comment by tavicu** [comment]
Nope. HomeKit does not support this. You can control volume from Control Center.

Select the TV then the volume buttons from your device will control the TV

**Comment by Maxwell70** [comment]
"HomeKit does not support this." - Can be made in the form of a bulb with dimming
"Select the TV then the volume buttons from your device will control the TV" - I didn't understand. Where is it?

**Comment by Maxwell70** [comment]
"Select the TV" - This is a homekit icon from your plugin?

**Comment by tavicu** [comment]
> "HomeKit does not support this." - Can be made in the form of a bulb with dimming

Nope. And even if i did, as i wrote in the previous comment, we don't know the current volume of tv so we can populate the bar and having a working feature.

> "Select the TV then the volume buttons from your device will control the TV" - I didn't understand. Where is it?

Just search "ios remote control center" on Google and you will find a lot of examples :)

**Comment by Gordon-Newell** [comment]
The upnp plugin does work controlling their volume, but the plugin as woefully out of date and throws errors
