### ISSUE TITLE
Configure status real time

### ISSUE THREAD

**Issue by oigroigm** [tavicu/homebridge-samsung-tizen#82]
I have not found any information to configure Update switch status in real time

**Comment by tavicu** [comment]
Status is updated every 30 seconds for both main accessory and switches.
You can change the interval but the minimum is 1 second.

The time is in ms, so 1000 it's 1 second.

Here is an example how you can update both (main and switches) every 1 second.
```
{
    "platform": "SamsungTizen",
    "refresh": 1000,
    "devices": [

    ]
}
```

And here is an example how you can set individual settings
```
{
    "platform": "SamsungTizen",
    "refresh": {
        "main": 1000,
        "switch": 5000
    },
    "devices": [

    ]
}
```

Setting one of them to false it will disable refreshing that type of accessory. I don't recommend refreshing at a low interval except you have automations based on the accessories. Also, if you have automations only on the main accessory, change only that. Don't refresh switches at a lower interval if you don't need it.

**Comment by oigroigm** [comment]
Thanks, I tried but it seems to be not working well, it takes more than the time set to update the status in homekit, version 2.1.2 worked better

**Comment by tavicu** [comment]
Tested right now and it's working at it should. With 1000 for `main` it's refreshing every second.

```
Update value in the background 1554492991
Update value in the background 1554492992
Update value in the background 1554492993
Update value in the background 1554492994
Update value in the background 1554492995
Update value in the background 1554492996
Update value in the background 1554492997
Update value in the background 1554492998
Update value in the background 1554492999
Update value in the background 1554493000
Update value in the background 1554493001
Update value in the background 1554493002
Update value in the background 1554493003
Update value in the background 1554493004
Update value in the background 1554493005
Update value in the background 1554493006
Update value in the background 1554493007
```
