### ISSUE TITLE
Plugin doesn't appear in homekit

### ISSUE THREAD

**Issue by bodenchristian** [tavicu/homebridge-samsung-tizen#84]
iOS 12.0.1 - can't update since I'm using a jailbreak

I enter the correct info for my Samsung TV and when homebridge is started, no accessory is listed for the TV

**Comment by tavicu** [comment]
v3 is compatible only with iOS 12.2+

**Comment by bodenchristian** [comment]
Sorry - how do I get an older version of this plugin. I have downloaded the v.2.1.2 source code and replaced the config file with this, but do I have to downgrade anything?

**Comment by tavicu** [comment]
i think you can try like this: `sudo npm install -g --unsafe-perm homebridge-samsung-tizen@2.1.2`

You can find more informations here: https://docs.npmjs.com/cli/install
