### ISSUE TITLE
Are Tizen JU Models supported?

### ISSUE THREAD

**Issue by Moskvitch** [tavicu/homebridge-samsung-tizen#85]
All switches show no response (correct IP/MAC addresses double-checked)

Another developer (for Athom Homey hub) says a different approach is to be coded for this JU series because it needs encrypted tokens (not sure about this - ??)

https://github.com/balmli/com.samsung.smart

The specific TV model number is UE40JU6510

Also, I could not find that setting in the TV menu that is mentioned.

Thanks a lot

**Comment by Moskvitch** [comment]
The TV does respond to the url:
{
  "id": "uuid:25958b1c-2e89-411e-b968-0ba7a62f1270",
  "name": "[TV] Master Bathroom",
  "version": "2.0.25",
  "device": {
    "type": "Samsung SmartTV",
    "duid": "uuid:25958b1c-2e89-411e-b968-0ba7a62f1270",
    "model": "15_HAWKM_UHD_2D_SC",
    "modelName": "UE40JU6510",
    "description": "Samsung DTV RCR",
    "networkType": "wired",
    "ssid": "",
    "ip": "192.168.1.20",
    "firmwareVersion": "Unknown",
    "name": "[TV] Master Bathroom",
    "id": "uuid:25958b1c-2e89-411e-b968-0ba7a62f1270",
    "udn": "uuid:25958b1c-2e89-411e-b968-0ba7a62f1270",
    "resolution": "1920x1080",
    "countryCode": "RU",
    "msfVersion": "2.0.25",
    "smartHubAgreement": "true",
    "wifiMac": "24:4b:03:6f:63:d9",
    "developerMode": "0",
    "developerIP": ""
  },
  "type": "Samsung SmartTV",
  "uri": "http://192.168.1.20:8001/api/v2/"
}

**Comment by Moskvitch** [comment]
If turned off, the debug mode does throw an error:

[2019-4-7 10:37:03] [Bathroom TV] [DEBUG] connect EHOSTUNREACH 192.168.1.20:8002
[2019-4-7 10:37:03] [Bathroom TV] Failed to pair! Make sure TV is online and you click "Allow" on the popup
[2019-4-7 10:37:03] [Bathroom TV] [DEBUG] PairFailedError: Failed to pair! Make sure TV is online and you click "Allow" on the popup
    at WebSocketSecure.pair (/usr/local/lib/node_modules/homebridge-samsung-tizen/lib/methods/wss.js:28:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)

**Comment by Moskvitch** [comment]
However, if the TV is turned ON while starting homebridge (in debug mode), no error message appear, yet all accessories in Homebridge display "No response"

**Comment by Moskvitch** [comment]
The alpha version of the Athom Homey plugin mentioned above does work (turn off and volume up/down only at the moment) and did require a pin, which apparently is not supported by this homebridge plugin.  Weill keep waiting.  Thanks

**Comment by tavicu** [comment]
Hei. Yup, the plugin is not compatible with TV's that require a pin for pairing.
