### ISSUE TITLE
Wrong choose input when alredy use some input tv.

### ISSUE THREAD

**Issue by erokoder** [tavicu/homebridge-samsung-tizen#86]
Hello All,

I have update ios and also homebridge and node to the newest version. 
So,
I have a problem when chose some of the input if is already chosen.
In Default :
Live TV -> Source Key -> Enter Key
HDMI -> Source Key -> Right key -> Enter Key.
But when I watching HDMI I can't choose input Live TV because of initial state  HDMI and I must go to Source Key and Left to Live TV.

How I can fix it?

Also How I can find number of some aplication from local ISP like Netflix which install on TV?

Thanks

**Comment by tavicu** [comment]
> Hello All,
> 
> I have update ios and also homebridge and node to the newest version.
> So,
> I have a problem when chose some of the input if is already chosen.
> In Default :
> Live TV -> Source Key -> Enter Key
> HDMI -> Source Key -> Right key -> Enter Key.
> But when I watching HDMI I can't choose input Live TV because of initial state HDMI and I must go to Source Key and Left to Live TV.

Just use KEY_LEFT*1s


> Also How I can find number of some aplication from local ISP like Netflix which install on TV?

You can find your answer in Readme. https://github.com/tavicu/homebridge-samsung-tizen#applications

**Comment by erokoder** [comment]
@tavicu 
Don't work, I don't know, maybe I have a problem with version TV.

My Config:

`       {
        "platform": "SamsungTizen",
                "inputs": [
                        {"name": "Eon TV", "type": "command", "value": ["KEY_HOME", "KEY_LEFT*1s", "KEY_ENTER"]},
                        {"name": "Home TV", "type": "command", "value": ["KEY_SOURCE", "KEY_RIGHT*1s", "KEY_ENTER"]},
                        {"name": "Kamere", "type": "command", "value": ["KEY_SOURCE", "KEY_RIGHT*2s", "KEY_ENTER"]},
                        {"name": "Live TV", "type": "command", "value": ["KEY_SOURCE","KEY_ENTER"]},
                        {"name": "Youtube", "type": "app", "value": "111299001912"}
                ],
                "devices": [{
                        "name": "Living Room TV",
                        "ip": "192.168.2.9",
                        "mac": "5c:49:7d:52:c8:0c"
                }]
        },`

**Comment by tavicu** [comment]
Look at the example. The key is to go left to the first option, then right on the hdmi.

So if you want to go on the second source for example use key_source, key_left*1s, key_right, key_enter.

https://github.com/tavicu/homebridge-samsung-tizen/issues/50#issuecomment-478863884

**Comment by erokoder** [comment]
@tavicu 

Thanks, working excellent.
Can I choose directly HDMI1 key, not universal KEY_HDMI?
So, does it exist KEY_HDMI1 and KEY_HDMI2... key like KEY_AV1.

Also, Do you have a problem when you quickly change the condition on/off that accessories got to out of service some time. Also when somebody turn off on remote, information is slow on home app.

**Comment by tavicu** [comment]
> @tavicu
> 
> Thanks, working excellent.
> Can I choose directly HDMI1 key, not universal KEY_HDMI?
> So, does it exist KEY_HDMI1 and KEY_HDMI2... key like KEY_AV1.

Unfortunately there are no keys to select a specific HDMI source :(

> Also, Do you have a problem when you quickly change the condition on/off that accessories got to out of service some time. Also when somebody turn off on remote, information is slow on home app.

The on/off functionality has a 5 seconds wait state. So if you turn on the tv and then press turn off in the 5 seconds frame it will return an error that the TV is in powering off state and get the "No response" message because you have no other option in Homekit to display errors.

**Comment by erokoder** [comment]
I use automation, why problematic 1s?

**Comment by tavicu** [comment]
> I use automation, why problematic 1s?

Every second will check the TV state. It's ok for main accessory but if you don't have automations based on the switches i will let them to the 30s default because they used more resources (sending a request to TV to check if app is active).

```
{
    "platform": "SamsungTizen",
    "refresh": {
        "main": 1000
    },
    "devices": [

    ]
}
```

**Comment by erokoder** [comment]
@tavicu  I set and working thanks.

**Comment by tavicu** [comment]
Hei @erokoder ,

Pushed a new version where the minimum interval for `main` can be set to 500ms. For switch it remains at 1000ms
