### ISSUE TITLE
[Feature] PIN for Pairing

### ISSUE THREAD

**Issue by benfysh** [tavicu/homebridge-samsung-tizen#87]
Just wanted to formally request the capability to support models (J & U Series) that require a PIN code during the pairing process. As mentioned in https://github.com/tavicu/homebridge-samsung-tizen/issues/85#issuecomment-480612239 this is not currently compatible.

There is another [Samsung TV Homebridge Plugin](https://github.com/kkapitan/homebridge-homesung) that does support the PIN pairing process however this is not being actively developed so may not gain the iOS 12.2 TV functionality that this plugin has.

I would be happy to help test etc if required.

**Comment by tavicu** [comment]
Thank you for your support but right now the PIN method it's not a priority for me.

I will start an Issue where we can talk and help me test it as soon as i will begin development for it :)

**Comment by DeutscheMark** [comment]
I second this feature.
The other plugin seems a bit dated and abandoned and most importantly does not supply the new TV Accessory that is available since iOS 12.2.
I would be very happy too if you'd add it, thanks. :)
