### ISSUE TITLE
[Question] iOS 12.2 TV Remote - Home Button?

### ISSUE THREAD

**Issue by xtai** [tavicu/homebridge-samsung-tizen#88]
**What is the problem and how we can help you?**

Thanks for the great project!

I am curious if there is a way to add the TV home button (KEY_HOME) in the iOS remote. Currently, it only showing me 3 buttons: play/pause, back, and info.

![IMG_1600](https://user-images.githubusercontent.com/3366724/55931425-34e60a00-5bda-11e9-940f-c90146c8184a.PNG)

**Comment by greensouth** [comment]
Yeah, would be interesting, instead of reassigning buttons for navigation (can't show channel list with so few options)

**Comment by apexad** [comment]
@tavicu Even if we cannot add buttons to this remote (which I suspect may be the case), perhaps you could make them customizable? I for one would make the 'I' (info) button into KEY_HDMI

**Comment by tavicu** [comment]
Hi. Unfortunately we cannot change the buttons that are shown. But as @apexad suggested we can make them customizable so you can map one button to a custom key.

It's on my to-do list :)

**Comment by xtai** [comment]
Ah thanks guys! Looks like this is a homebridge or Apple issue. Hope they open up more options to customize TV remote.

As suggested, I cloned the repo locally and changed L15 on https://github.com/tavicu/homebridge-samsung-tizen/blob/master/lib/options/remote.js#L15 to 'KEY_HOME', and now the info button is working as home button! Yay

**Comment by tavicu** [comment]
I will make the changes this week so you can change the keys mapping :)

Keep you posted

**Comment by monsterciattolo** [comment]
Is it possible to add additional buttons as Apple TV?

**Comment by tavicu** [comment]
Hei,

I have pushed a new version where you can change the mapping of remote keys.
Default keys:
```
    REWIND         : 'KEY_REWIND',
    FAST_FORWARD   : 'KEY_FF',
    NEXT_TRACK     : '',
    PREVIOUS_TRACK : '',
    ARROW_UP       : 'KEY_UP',
    ARROW_DOWN     : 'KEY_DOWN',
    ARROW_LEFT     : 'KEY_LEFT',
    ARROW_RIGHT    : 'KEY_RIGHT',
    SELECT         : 'KEY_ENTER',
    BACK           : 'KEY_RETURN',
    EXIT           : 'KEY_HOME',
    PLAY_PAUSE     : 'KEY_PLAY_BACK',
    INFORMATION    : 'KEY_INFO'
```

How config file should look to change mapping. It can also have an array as value to execute more commands:
```
{
    "platform": "SamsungTizen",
    "keys": {
        "INFORMATION": "KEY_ENTER",
        "REWIND": ["KEY_ENTER", "KEY_ENTER"]
    },
    ...
}
```

@xtai

**Comment by JonoHaysom** [comment]
I just updated and mapped the info button to :"home" works perfectly and will be pervasive after updates. thanks mate!

**Comment by xtai** [comment]
Hey, @tavicu, thanks for the great work! Really appreciate it.
