### ISSUE TITLE
Ambient Mode Q8 Series

### ISSUE THREAD

**Issue by steinejo** [tavicu/homebridge-samsung-tizen#89]
Hi, i am running your plugin on iobroker ham Adapter successfully - thanks for your effort!

I was wondering if there is a command key to switch to ambient mode functionality on q8 series TVs.

Regards

**Comment by tavicu** [comment]
Hei!

I am not aware of such a command :)

**Comment by coreh** [comment]
Hey @steinejo, the `KEY_AMBIENT` key code can be used to trigger ambient mode (found it here on [this reference](https://github.com/balmli/com.samsung.smart/blob/7b373d06623cc0e1495f246d39bdf8e973ad5f6a/keys.md))

Here's my setup:

```json
"inputs": [
    {
        "name": "Ambient",
        "type": "command",
        "value": [
            "KEY_AMBIENT"
        ]
    }
]
```
