### ISSUE TITLE
Scenes

### ISSUE THREAD

**Issue by yclai1229** [tavicu/homebridge-samsung-tizen#90]
Hi tavicu,

I updated the latest version of tizen 12.2.  I set a scene in the homekit.  
The content is to turn off the TV and lights.  But when I originally turned off the TV, I executed this scene.  The closed TV is turned on!  Can you help me? 

Thank you.

**Comment by tavicu** [comment]
Hei,

Make sure you set the scene correctly! The problem you are facing has nothing to do with how the plugin works.
