### ISSUE TITLE
[BUG] Can't control over cellular

### ISSUE THREAD

**Issue by WendelFelius** [tavicu/homebridge-samsung-tizen#93]
**The problem**
I'm unable to control my tv over cellular. I'm using two homekit hubs, so that can't be the problem. When connected to my home network it works just fine from the Home.app. Also, controlling the tv using Siri on my iPhone works, but not when using Siri on HomePod. 

Every device is connected with the same Apple ID and same local network. Since homebridge-samsung-tizen is my only homebridge device, I'm not sure whether it's a homebridge or a plugin issue.

**Screenshots**
![IMG_0010](https://user-images.githubusercontent.com/8288091/56811317-be334880-6838-11e9-913a-a67c1283d973.JPG)
![IMG_0011](https://user-images.githubusercontent.com/8288091/56811322-c095a280-6838-11e9-8cd3-47dd9f172a2f.JPG)

**Versions**
 - iOS: 12.2
 - Node.js: 8.16.0
 - Homebridge: 6.4.1
 - Plugin: 3.1.0

**Comment by tavicu** [comment]
Hi. Unfortunately the plugin has nothing to do with remote access. But i will try to help you, maybe will find a solution :)

The fail is when you try to make an action?

I had the same problem when i changed my routers to a Mesh system. If you are having multiple routers the problem may come if you have the homebridge on a router and the hub to another router.

**Comment by WendelFelius** [comment]
I’m sorry, it has been fixed already! Thanks anyway! 👌🏻
