### ISSUE TITLE
Choose HDMI source without cycling through

### ISSUE THREAD

**Issue by KevinAPearson** [tavicu/homebridge-samsung-tizen#96]
Hi,
Is there a way to choose which HDMI source to open?
At the moment I can Key_HDMI which cycles through all the currently connected HDMI sources.
It would be handy to say Key_HDMI_2 instead.
I suppose it depends on if Tizen allows it?
I've got a UE55MU7000 Samsung TV if that helps.

**Comment by tavicu** [comment]
Hi. There is no option! You can find a solution here: https://github.com/tavicu/homebridge-samsung-tizen/issues/77
