### ISSUE TITLE
Use the already-done JS code to add H/J-series TVs

### ISSUE THREAD

**Issue by MBarti** [tavicu/homebridge-samsung-tizen#98]
You've done amazing work on the plugin! However thousands of users with early-Tizen H/J series TVs are being left out.

Good news: now the JS code for H/J-series Samsung TV is ready - so it should be easy to take it and incorporate those TVs with your plugin.

Check out the Homesung plugin https://github.com/kkapitan/homebridge-homesung
(it works well, but is not updated for the new iOS 12.2 remote capabilities)

**Comment by tavicu** [comment]
As i told in previous issues, this will not be a priority for me and probably it will not be implemented! It's more complicate to pair an old version of TV. Plus the fact that i don't have a TV to develop and make the tests.

Plus my time is very limited and this is not a fast thing to implement. The plugin is prepared to change the method it uses to communicate with the TV but i cannot implement something that i can't even test.

If someone with the right knowledge want's to do it, i can offer support :)
