### ISSUE TITLE
Getting App Code with no Command Line

### ISSUE THREAD

**Issue by JordanPatterson** [tavicu/homebridge-samsung-tizen#99]
I am running the Homebridge Config-UI-X plugin and cant figure out how to run “homebridge Tizen-apps” to get the app code for the new Apple TV app. Is there another way to get it?

**Comment by JordanPatterson** [comment]
I think maybe the more direct question is how I can sun the homebridge tizen-apps command since i am running a systemd version of homebridge.

**Comment by tavicu** [comment]
Can't you stop the instance? :)

Right now i've seen there is a problem with Node 8 and how the apps are shown with `tizen-apps`. So you will need to start with debug mode also.

I will push a new version with a fix soon.

**Comment by JordanPatterson** [comment]
Ok so I guess if I stop the instance I can launch homebridge with the tizen-apps parameter and the -U /var/lib/homebridge to point homebridge at my config file.

How should i structure that command?

**Comment by tavicu** [comment]
The command you should run is `DEBUG=* homebridge -D tizen-apps`

**Comment by JordanPatterson** [comment]
I finally got it.

Samsung TV App IDs

│ (index) │              name              │        appId        │
├─────────┼────────────────────────────────┼─────────────────────┤
│    0    │           'Netflix'            │    '11101200001'    │
│    1    │             'ESPN'             │   '3201708014618'   │
│    2    │       'Universal Guide'        │   '3201710015067'   │
│    3    │           'Apple TV'           │   '3201807016597'   │
│    4    │           'YouTube'            │   '111299001912'    │
│    5    │         'Prime Video'          │   '3201512006785'   │
│    6    │           'Internet'           │ 'org.tizen.browser' │
│    7    │         'FandangoNOW'          │   '111399000031'    │
│    8    │          'Watch TNT'           │   '3201710014956'   │
│    9    │           'e-Manual'           │    '20182100009'    │
│   10    │         'Discovery GO'         │   '3201801015541'   │
│   11    │ 'CBS News: Live Breaking News' │   '3201711015155'   │
│   12    │             'HGTV'             │   '3201608010450'   │
│   13    │             'VUDU'             │   '111012010001'    │
│   14    │           'Gallery'            │   '3201710015037'   │
│   15    │   'Google Play Movies ＆ TV'    │   '3201601007250'   │
│   16    │       'Cooking Channel'        │   '3201812017516'   │
│   17    │         'DIY Network'          │   '3201812017511'   │
│   18    │             'ABC'              │   '3201806016508'   │
│   19    │            'TLC GO'            │   '3201803015977'   │
│   20    │         'SmartThings'          │   '3201710015016'   │
│   21    │         'DIRECTV NOW'          │   '3201611011040'   │
│   22    │             'NBC'              │   '3201606009840'   │
│   23    │            'CNNgo'             │   '3201704012161'   │
│   24    │             'Hulu'             │   '3201601007625'   │
│   25    │    'McAfee Security for TV'    │   '3201612011418'   │
│   26    │           'Spotify'            │   '3201606009684'   │
│   27    │          'DisneyNOW'           │   '3201902017822'   │
│   28    │          'YouTube TV'          │   '3201707014489'   │

**Comment by dansturm** [comment]
I just went through this to add an "open Apple TV app" button to my homebridge TV remote but it doesn't appear to be working. The command is being sent, but the TV isn't responding. Is yours working?

**Comment by JordanPatterson** [comment]
No it is not. I just created Issue #100 for that exact reason.

**Comment by mazafra1** [comment]
> The command you should run is `DEBUG=* homebridge -D tizen-apps`

Is there a way to pass these parameters through when running homebridge on a docker container?
